### ISSUE TITLE
Support Frontmatter

### ISSUE THREAD

**Issue by klorenz** [shd101wyy/markdown-preview-enhanced#100]
Can you please support [frontmatter](https://jekyllrb.com/docs/frontmatter/)

Maybe rendered as table or definition list on top of the document.

Cheers!

**Comment by shd101wyy** [comment]
Hi @klorenz ,

I will have a look.

Thanks

**Comment by klorenz** [comment]
Maybe replace
```
---
foo: bar
---
```

with 
{{{
```yaml
foo: bar
```
}}}

**Comment by shd101wyy** [comment]
Is that okay if I render the yaml as a table?

**Comment by shd101wyy** [comment]
like this  
![screen shot 2016-08-12 at 3 29 29 pm](https://cloud.githubusercontent.com/assets/1908863/17615553/9915f4d6-60a1-11e6-826d-44d0524ebfc1.png)

ps: Anything else I need to add? Sorry I have never used front-matter before ;)

**Comment by shd101wyy** [comment]
If you don't like table, I can also do (which is much easier) 
<pre>
```yaml 
blablabla
```</pre>

From my point of view, I think table is not a good idea when there are too many entries. But it seems that gfm is using table to render yaml.

**Comment by shd101wyy** [comment]
Anyway, both will be supported. I will release a new version that supports front matter this weekend.

**Comment by klorenz** [comment]
Great, ty :)

if a table, I'd prefer

| name | value |
|--------|--------|
| foo    | bar |

BUT:  I think the syntax is even better

**Comment by shd101wyy** [comment]
Done.  

![screen shot 2016-08-12 at 11 48 40 pm](https://cloud.githubusercontent.com/assets/1908863/17628313/67b293f4-60e7-11e6-9512-37ae31f8ffdc.png)

You can disable rendering as table from the settings.  
![screen shot 2016-08-12 at 11 48 59 pm](https://cloud.githubusercontent.com/assets/1908863/17628322/6cd22f34-60e7-11e6-883a-e7c508b25c2e.png)  

Then it will be rendered as yaml  

![screen shot 2016-08-12 at 11 49 14 pm](https://cloud.githubusercontent.com/assets/1908863/17628327/753bdca6-60e7-11e6-9f1c-e91e8df842dc.png)  

Cheers!

**Comment by shd101wyy** [comment]
I changed the options so that now you can hide front matter if you want.  
![screen shot 2016-08-26 at 12 45 48 am](https://cloud.githubusercontent.com/assets/1908863/17995335/7aa6c428-6b26-11e6-88a0-aecae7b95c1e.png)
