### ISSUE TITLE
VScode更新后无法使用

### ISSUE THREAD

**Issue by AdexoMing** [shd101wyy/markdown-preview-enhanced#1000]
点击预览之后报错：无法打开“MPE Preview”: Cannot read property 'filter' of undefined。
VScode版本
版本: 1.28.2 (system setup)
提交: 7f3ce96ff4729c91352ae6def877e59c561f4850
日期: 2018-10-17T00:23:12.403Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: ia32

**Comment by MoBenw** [comment]
我也是 ：无法打开“MPE Preview”: Cannot read property 'filter' of undefined。

**Comment by shd101wyy** [comment]
应该修好了，非常抱歉。
