### ISSUE TITLE
VSCode: Cannot renew TOC at version 0.3.10

### ISSUE THREAD

**Issue by datasciesotist** [shd101wyy/markdown-preview-enhanced#1002]
I updated MPE for VSCode 0.3.8 to 0.3.10.
Then the command "markdown-preview-enhanced.createTOC" does not renew TOC structure automatically. On other machine with MPE 0.3.8, TOC is automatically renewed when I add some contents with section header at the same file.

regards,

**Comment by shd101wyy** [comment]
I just tried TOC myself and it worked well.  
The TOC should only be renewed when you save the file.
Could you please send me your markdown file to my email `shd101wyy@gmail.com` so I can try it?
Thank you.

**Comment by datasciesotist** [comment]
Hi,

The file is really simple. Please see below.
And I made a screencast. You can see what is happen.
https://youtu.be/FHRfEO6XyvQ

----
# TOC test on MPE 0.3.10

<div style = "text-align:right">
2018-10-30<br>
</div>

## begin
aaaa

## next
eeee

## third
iiii

## last
oooo
----

I'm using VSCode on Windows 10 and my environment is below (in Japanese).
-----
バージョン: 1.28.2 (user setup)
コミット: 7f3ce96ff4729c91352ae6def877e59c561f4850
日付: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
-----

regards,

**Comment by shd101wyy** [comment]
Hi @datasciesotist ,

Thanks, it is a bug in this [line](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/blob/master/src/preview-content-provider.ts#L147). I will fix it tonight.

Thanks for reporting the bug!

**Comment by datasciesotist** [comment]
Hi, 

Thanks for your effort!
The problem is solved on 0.3.11.

**Comment by sdellenb** [comment]
I'm sorry to post on an old issue, but today's VSCode Update to 1.31 broke this feature again on 0.3.11. 😢
