### ISSUE TITLE
幻灯片如何设置向下翻页？ 如果对不同slice设置不同设置？

### ISSUE THREAD

**Issue by AbeGeMS** [shd101wyy/markdown-preview-enhanced#1007]
1. 幻灯片的html有向下的按钮，但是如果在md文件里标识是向下翻页
2. 文档中说可以通过less文件对不同的slice采用不同的style，但是less文件写在哪儿？怎么和md文件绑定？

**Comment by AbeGeMS** [comment]
好吧，找到答案了。自问自答：
#1 
#2 在vscode里 按 ctr+shift+p，选择Markdown Preview enhanced：customize css
然后写你该写的东西：）

**Comment by AbeGeMS** [comment]
#1 是《!-- slide vertical=true --》

**Comment by drrui** [comment]
@AbeGeMS   你好，找了半天该怎么写垂直页面，谢谢。不过我想请问你这个回答是从哪里找到的呢？reveal.js的一些设置好像比MPE里面的多一些，但是MPE的说明文件里似乎没有写全，有些功能不知道怎么设置。另外MPE里面的revealjs的版本是最新的吗？
