### ISSUE TITLE
Feature Request: Add hooks

### ISSUE THREAD

**Issue by klorenz** [shd101wyy/markdown-preview-enhanced#101]
If there would be a preprocessing hook, you could add other graphics and other stuff:

Assume following atom init script for managing frontmatter

`````` coffee
atom.packages.onDidActivatePackage (pkg) ->
  if pkg.name is 'markdown-preview-enhanced'
    debugger
    console.log pkg

    pkg.mainModule.onDidWantPreview (markdown) ->
      markdown.replace /^---\n([\s\S]*?\n)---\n/, "```yaml\n$1\n```"
``````

And you can add a [service consumer](http://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/), to enable other packages to provide hooks:

`````` coffee
module.exports =
  ...
  provideMarkdownPreviewEnhancedHooks (mpe) ->
     mpe.onDidWantPreview (markdown) ->
      markdown.replace /^---\n([\s\S]*?\n)---\n/, "```yaml\n$1```\n"
``````

Hooks for:
- before passing markdown to parser
- maybe provide AST to manipulate
- maybe provide parser to extend
- before injecting HTML

**Comment by shd101wyy** [comment]
Partially done
[extension.md](https://github.com/shd101wyy/markdown-preview-enhanced/blob/0.8.1/docs/extension.md)

**Comment by klorenz** [comment]
Wow, great thanks :)

**Comment by dpo** [comment]
Is this still the right strategy to specify hooks, or are we supposed to use the [extend parser](https://shd101wyy.github.io/markdown-preview-enhanced/#/extend-parser?id=extend-markdown-parser) feature now?
