### ISSUE TITLE
Soft tabs in VS Code

### ISSUE THREAD

**Issue by mundodisco8** [shd101wyy/markdown-preview-enhanced#1010]
Hi!
I use your extension in VS Code. Thanks for such a great piece of software, I really appreciate your work.

I use [markdownlint](https://github.com/DavidAnson/markdownlint) as my MD linter, and it complains that the TOC has tabs instead of spaces (it's [rule 10](https://github.com/DavidAnson/markdownlint/blob/v0.11.0/doc/Rules.md#md010). I've seen that you added a fix for Atom a while ago ( #187). My VS Code is set to use spaces as tabs (and 2 spaces for each tab), but the TOC is generated with tabs, instead of spaces. Would it be possible to get a similar fix?

Thanks!

**Comment by shd101wyy** [comment]
Hi @mundodisco8 , 

Yes it is possible to use soft tab in toc.
Just add `tab="  "` in the TOC configuration. Like below:

```
<!-- @import "[TOC]" {cmd="toc" depthFrom=1 depthTo=6 orderedList=false tab="  "} -->
```

Thanks.
