### ISSUE TITLE
表格扩展语法无效？望能加入思维导图功能

### ISSUE THREAD

**Issue by AdexoMing** [shd101wyy/markdown-preview-enhanced#1011]
表格扩展语法无效？望能加入思维导图功能，类似于幕布的那种功能

**Comment by shd101wyy** [comment]
拓展表格得先在插件设置里开启 enableExtendedTableSyntax 这个选项

**Comment by shd101wyy** [comment]
思维导图现在可通过 plantuml 实现，如下

![Capture](https://user-images.githubusercontent.com/1908863/54895500-d131c080-4efa-11e9-8236-4930b057d368.PNG)

**Comment by AdexoMing** [comment]
多谢大佬
