### ISSUE TITLE
ebook export not have chapter content 

### ISSUE THREAD

**Issue by Guojicheng** [shd101wyy/markdown-preview-enhanced#1031]
ebook-convert (calibre 3.34.0)
markdown-preview-enhanced  0.15.8
ebook-example (clone from https://github.com/shd101wyy/ebook-example.git)

when I convert to ebook , on ebook  not  have chapter's content ,

**Comment by shd101wyy** [comment]
Sorry I am a bit busy recently. Will investigate when I get time.
Thanks.

**Comment by siriuscc** [comment]
I speculate that the author may have forgotten this bug. So bad.

**Comment by Periter** [comment]
I run into this question, using mouse clicks or  ```export_on_save:``` for auto-generate the file, but these methods did not work.

**Comment by shd101wyy** [comment]
The ebook bug should be fixed in the commit: https://github.com/shd101wyy/mume/commit/7763b77256ff4bd2643076310027e9df423dad42 .
I will publish soon.

**Comment by shd101wyy** [comment]
Should be fixed now. Thanks.
