### ISSUE TITLE
Please support some extentions

### ISSUE THREAD

**Issue by Camypaper** [shd101wyy/markdown-preview-enhanced#104]
In my impression, this plugin only support *.md files.
I often use *.mmark extention file which was used to support MathJax and Katex in Hugo.

Is it possible to support some extensions or extension free preview?

**Comment by shd101wyy** [comment]
Hi @Camypaper , what extensions do you want me to add? Only `.mmark`?

**Comment by Camypaper** [comment]
That(`.mmark`) is all for now.

**Comment by Vatscy** [comment]
Excuse me for cutting in.
I want you to add `.markdown` if possible.

**Comment by shd101wyy** [comment]
no problem

**Comment by shd101wyy** [comment]
@Camypaper @vatscy , Done!

<img width="469" alt="screen shot 2016-08-20 at 4 27 13 pm" src="https://cloud.githubusercontent.com/assets/1908863/17833965/fef27dc2-66f2-11e6-823e-a8f819f12a72.png">  

You can add more extension in settings.

Cheers!

**Comment by Camypaper** [comment]
Great update!
Thanks @shd101wyy!
