### ISSUE TITLE
hexo support

### ISSUE THREAD

**Issue by alfredtofu** [shd101wyy/markdown-preview-enhanced#105]
Can it support [hexo](https://hexo.io/) rendering?

**Comment by maplewizard** [comment]
@alfredtofu  I think maybe you should put this issue to hexo?

**Comment by shd101wyy** [comment]
Hi @alfredtofu , 

Can you please be more specific? What specific features do you want me to add? 

Thanks

**Comment by alfredtofu** [comment]
Here is an example: [this markdown source](https://raw.githubusercontent.com/alfredtofu/blog_data/master/source/_posts/action-still-image-cnn2.md) will be rendered as [this page](http://blog.cvmarcher.com/posts/2015/05/29/action-still-image-cnn2/).

Main features are inner sources reference:
- page ref: `[论文笔记](/2015/05/13/action-still-image-cnn)`
- image ref: `{% asset_img xiaoou_fuse_deep_channels_confusion.png %}`
