### ISSUE TITLE
预览实时更新不起作用

### ISSUE THREAD

**Issue by Wuqiqi123** [shd101wyy/markdown-preview-enhanced#1078]
我是用的是ubuntu18.04上的vscode，版本1.32.1
**markdown-preview-enhanced**是在插件页搜索安装的，显示版本为0.3.11

MPE Preview页面在一点开是可以的显示，但是将makedown的源文件修改后并不能刷新MPE Preview中的内容，保存之后也不行，但是**Markdown Preview Enhanced: Toggle Live Update** 切换后就可以刷新。

**Comment by shd101wyy** [comment]
是的这可能因为 vscode 的 api 变了，这个插件还没有跟上更新。
我这个周末会发一个新的版本修复这个问题。
谢谢

**Comment by hide-on-bush-lalala** [comment]
我刚刚下载了最新版的VS code又不起作用了，是api又变了吗
