### ISSUE TITLE
FR: Possibility to make this default preview

### ISSUE THREAD

**Issue by parthi2929** [shd101wyy/markdown-preview-enhanced#1081]
Hi

Currently I have to explicitly open the markdown enhanced preview after markdown file is opened. There is a preview icon on top right corner of VS code. Clicking that opens only default markdown preview. Is there a way to configure that to open your preview?

**Comment by shd101wyy** [comment]
Weird. I just tried `cmd+k v` in vscode and it did open mpe by default. 
Restart vscode and try again?
Thanks

**Comment by parthi2929** [comment]
No not control k v, I am talking about this.. 
![image](https://user-images.githubusercontent.com/11896263/54101737-26de7700-43eb-11e9-9629-95ca39a6ae7e.png)

Nevertheless, just discovered, the left most in that opens your preview. Its very similar to vscode's default preview icon.. if possible can you change that? 

But this issue could be closed, as we have that option already.

**Comment by shd101wyy** [comment]
We will need someone to help create a unique icon for that task...

**Comment by parthi2929** [comment]
I tried a quick icon in adobe (i am not a designer..) can use if its ok..

white:  

![a_icon_for_vscode_ext](https://user-images.githubusercontent.com/11896263/54108570-492fbf00-4402-11e9-873e-ed9a14314a94.png)  

black:   
![a_icon_for_vscode_ext_black](https://user-images.githubusercontent.com/11896263/54108582-5187fa00-4402-11e9-8351-521efd645011.png)

**Comment by parthi2929** [comment]
here is zip with source file (.ai file)

[a_icon_for_vscode_ext.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/2951204/a_icon_for_vscode_ext.zip)
