### ISSUE TITLE
导出epub问题

### ISSUE THREAD

**Issue by blackredscarf** [shd101wyy/markdown-preview-enhanced#1096]
我 git clone 了这个项目 [ebook-example](https://github.com/shd101wyy/ebook-example)，然后尝试导出epub，导出后发现电子书只有主文件的内容，点击目录无法跳转。

![](https://i.loli.net/2019/03/30/5c9f3a6484787.png)

**Comment by Periter** [comment]
SAME AS YOU

**Comment by shd101wyy** [comment]
我这个周末应该有时间，到时候会修一下

**Comment by Periter** [comment]
谢谢，不知能否可以再看下这个phantomjs的issue呢[#1093](https://github.com/shd101wyy/markdown-preview-enhanced/issues/1093)，ebook导出的公式错乱很多。

**Comment by shd101wyy** [comment]
建议使用 puppeteer，因为 phantomjs 已经不再继续被维护了。

**Comment by Periter** [comment]
> 建议使用 puppeteer，因为 phantomjs 已经不再继续被维护了。

好的，thx

**Comment by shd101wyy** [comment]
应该修好了。谢谢
