### ISSUE TITLE
怎么生成和预览图一样的pdf

### ISSUE THREAD

**Issue by markwinds** [shd101wyy/markdown-preview-enhanced#1099]
我在我的markdown文件中用import引入了一个css文件，在预览图中成功看到了结果，但是在打印pdf时还是白纸黑字的，不知道能不能生成和预览图一样的pdf

**Comment by shd101wyy** [comment]
加入一个 front matter 

````
```
print_background: true
```
````

或者在插件设置里面把 `printBackground` 设置为 true
