### ISSUE TITLE
the preview window not closed when view a js file after preview a file of md

### ISSUE THREAD

**Issue by kiyota77** [shd101wyy/markdown-preview-enhanced#111]
the preview window not closed when view a js file after preview a file of md

**Comment by shd101wyy** [comment]
Hello, 

Well, it's designed like that.  
You can close the preview panel by yourself or toggle the preview by command 'Markdown Preview Enhanced: Toggle Preview'

Thanks

**Comment by zhiquan-yu** [comment]
@shd101wyy I think when I close .md tab, the preview pane should close automatically.

**Comment by shd101wyy** [comment]
@zhiquan-yu yea make sense, might be changed in next release.
thanks :)

**Comment by zhiquan-yu** [comment]
@shd101wyy Now I think when I close .md tab, the preview pane should not close automatically. It should show the preview of the .md file, rather than empty.
![issue-md-preview](http://ww2.sinaimg.cn/large/801b780agw1f7yxyirxbzj20ec04wdg0.jpg)

Please see **markdown-preview**'s behavior.
