### ISSUE TITLE
No Night Mode Support

### ISSUE THREAD

**Issue by PannenetsF** [shd101wyy/markdown-preview-enhanced#1112]
- VScode 
- Markdown Preview Enhanced 0.15.10
# The preview tab is always white-background, whatever vscode theme is, which makes usr  uncomfortable.
![image](https://user-images.githubusercontent.com/45866836/56337014-880d1d80-61d5-11e9-82e2-cc6fe1e50bfc.png)

**Comment by shd101wyy** [comment]
@PannenetsF you can go to the extension settings, search for `previewTheme` then change it....

**Comment by PannenetsF** [comment]
Okay now. Thank you!
Best wishes to you and your project!




------------------ 原始邮件 ------------------
发件人: "Yiyi Wang"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 中午12:50
收件人: "shd101wyy/markdown-preview-enhanced"<markdown-preview-enhanced@noreply.github.com>;
抄送: "Nirvana."<3111812673@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [shd101wyy/markdown-preview-enhanced] No Night Mode Support(#1112)




@PannenetsF you can go to the extension settings, search for previewTheme then change it....
