### ISSUE TITLE
Documentation - Extended (Table) Syntax

### ISSUE THREAD

**Issue by aplatypus** [shd101wyy/markdown-preview-enhanced#1124]
I believe the documentation page on Extended Syntax needs to tell people that they need to turn-on **`enableExtendedTableSyntax`** for the examples to work.

    // Enable extended table syntax to support merging table cells.
       enableExtendedTableSyntax: false

Once changed ot **`True`** his example works:

   | A | B |
   |---|---|
   | > | 1 |
   | 2 ||

show as:

![image](https://user-images.githubusercontent.com/67028/57205839-aca22b80-7004-11e9-9ae4-2ebdd7d92fed.png)

The descriptions should probably go under the Extended Syntax heding:

- [Extended Syntax](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics?id=table)

I spent a lot of time wondering why by markdown wasn't working.  There are related posts as well for other who have faced the same challenge:

 - #907 -- [Table: support grid tables](https://github.com/shd101wyy/markdown-preview-enhanced/issues/907)
 - #133 -- [Feature Request: Extended table notation to express merged cell](https://github.com/shd101wyy/markdown-preview-enhanced/issues/133)
 - #866 -- [Enhanced Tables](https://github.com/shd101wyy/markdown-preview-enhanced/issues/866)

The place I looked to uncover why it wasn't working was actually [Mume](https://github.com/shd101wyy/mume) ... I found these other issues later, once I knew what to look for.

**Comment by shd101wyy** [comment]
Sure will do. Thanks!

**Comment by shd101wyy** [comment]
Done. Thanks!
