### ISSUE TITLE
text and picture layout in presentation

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#113]
Not sure this question should be asked here or reveal.. 

How to add picture and text to one page and fine turn the layout? 
1) Setting the size of the picture
2) Setting the location of the picture and text.  for example, text on the left and picture on the left
3) Adding several pictures one by one from left to right on the page.

BTW. it's a great feature to support reveal.js. I can finally making slides in plain text and version control them.

**Comment by shd101wyy** [comment]
Hi,  

> Setting the size of the picture    

You may need to write html in this case, e.g.
```markdown
# This is markdown 
<img src="/path/tp/image" width="200" height="150">   
```      
or 
```markdown
<img src="/path/tp/image" style="width:200px; height: 150px;">   
```
 <br>
> Setting the location of the picture and text. for example, text on the left and picture on the left  

```markdown
<img src="/path/tp/image" style="float: left; width:48%; margin-right: 2%;">   
```  
here `float: left;` will align image to the left side, similarly `float: right;` will align image to right.  
  
>  Adding several pictures one by one from left to right on the page.  
This is a bit hard, but I am pretty sure that this can be achieved by `html`.  

Thanks

**Comment by xu4wang** [comment]
Thanks @shd101wyy . I tried your suggestion,, it works.

```
# Tittle
<img src="http://i.imgur.com/TPHIEH8.png" style="float: left; margin-right: 8%; margin-top: 0%;" width="350" height="350" >
 * line1
    1. kkk
    1. experience
 * line2
```

For the a bit hard HTML, I workaround it using markdown table. ;-).
