### ISSUE TITLE
Additional unnecessary code in HTML code block when I use HTML comment

### ISSUE THREAD

**Issue by linkchen1982** [shd101wyy/markdown-preview-enhanced#1132]
The original HTML is:
```html
<!-- add _includes/analytics.html -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ site.google_analytics }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ site.google_analytics }}');
</script>
```

But the preview will show like:
![螢幕快照 2019-05-14 上午11 55 27](https://user-images.githubusercontent.com/48361013/57669834-42f6d280-763f-11e9-8c1a-ec7b770e42f3.png)

There comes a \<p\> tag which I don't expect. How do I fix it?

**Comment by shd101wyy** [comment]
Please write <code>```html</code> instead of <code>~~~html</code>?

**Comment by linkchen1982** [comment]
Yes, it works! 
Thank you!!!
![螢幕快照 2019-05-14 下午12 39 22](https://user-images.githubusercontent.com/48361013/57671214-615fcc80-7645-11e9-80df-2632cd10141d.png)

**Comment by shd101wyy** [comment]
I would recommend to always use <code>```</code> instead of <code>~~~</code> for all code blocks. Thank you.
