### ISSUE TITLE
mermaid 图的loop 和opt 标签 显示不正常,变成黑底的了，请问是为啥么？如何恢复一下？

### ISSUE THREAD

**Issue by alcarl** [shd101wyy/markdown-preview-enhanced#1135]
mermaid 图的loop 和opt 标签 显示不正常,变成黑底的了，请问是为啥么？如何恢复一下？
![image](https://user-images.githubusercontent.com/2275135/57827834-956cf600-77db-11e9-9ad0-f9f38daefd16.png)

**Comment by sanchips** [comment]
@alcarl  我也遇到这个问题，翻看了之前已解决的issue之后找到了作者给出的解决方案#983，在vscode的设置里面将`Mermaid Theme`修改为`default`。如果已经是`default`，修改到别的选项之后再改回来，去项目里面预览的话就恢复正常了。
![image](https://user-images.githubusercontent.com/8832855/57906621-2d86e000-78ad-11e9-838d-8994f3b8a2e6.png)

**Comment by alcarl** [comment]
搞定了，在设置里搜mermaid然后照你说的切换一下就好了。感谢！

**Comment by tucaoxingren** [comment]
> @alcarl 我用的是vscode，也遇到这个问题，翻看了之前已解决的issue之后找到了作者给出的解决方案#983，在设置里面将`Mermaid Theme`修改为`default`。如果已经是`default`，修改到别的选项之后再改回来，去项目里面预览的话就恢复正常了。Atom同理。
> ![image](https://user-images.githubusercontent.com/8832855/57906621-2d86e000-78ad-11e9-838d-8994f3b8a2e6.png)

谢谢已解决
