### ISSUE TITLE
No "pandoc document export" menu in preview

### ISSUE THREAD

**Issue by chjz1024** [shd101wyy/markdown-preview-enhanced#1136]
I followed the instruction in [https://shd101wyy.github.io/markdown-preview-enhanced/#/pandoc](https://shd101wyy.github.io/markdown-preview-enhanced/#/pandoc) to export my .md file to pdf with pandoc, but there is no `pandoc document export` on the context menu. Any advice on how to get this work? My vscode version is 1.33.1 user setup.
<img width="617" alt="Annotation 2019-05-16 212400" src="https://user-images.githubusercontent.com/29775388/57857164-24503180-7821-11e9-975c-fa10b968e83d.png">

**Comment by shd101wyy** [comment]
Yes that `Pandoc` is what you want to use.

**Comment by chjz1024** [comment]
@shd101wyy Thank you very much, seems like I wrote a wrong front-matter so nothing happened then.

**Comment by StevenTang1994** [comment]
I had a problem.
![image](https://user-images.githubusercontent.com/24404599/63840324-6f96e600-c9b3-11e9-9574-13286e368567.png)
