### ISSUE TITLE
Markdown导出为HTML时目录功能不见了

### ISSUE THREAD

**Issue by Aparesse** [shd101wyy/markdown-preview-enhanced#1138]
在之前的版本中，Markdown文件导出为HTML时，左侧默认有目录的，但在新版本中，目录功能似乎被取消了，或者说，由左侧隐藏式改为了顶部的目录。还是说在其他地方需要做配置，而我没有发现？我用的是vscode，目前一直在用0.3.1的版本。

**Comment by shd101wyy** [comment]
把插件中的 enableScriptExecution 设置打开就好了。

**Comment by Aparesse** [comment]
> 把插件中的enableScriptExecution设置打开就好了。

试了一下，果然可以，谢谢
