### ISSUE TITLE
Local style has been not working in latest version

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/markdown-preview-enhanced#1141]
https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css

https://shd101wyy.github.io/markdown-preview-enhanced/#/file-imports?id=supported-file-types

Local style has been not working in latest version.

I think it was working last week before udate.

Probably because of mume@0.4.0.

**Comment by shd101wyy** [comment]
I will investigate the issue this weekend. Thanks.

**Comment by shd101wyy** [comment]
Weird. I just tried it on my ubuntu 18.04 vscode 1.34.0 mpe 0.4.0 and it worked well. 
Are you using atom or vscode? On which platform? Thank you

**Comment by mickelti** [comment]
I also have a same issue maybe from 2 weeks ago.
I'm using vscode 1.34.0

**Comment by mickelti** [comment]
I'm sorry. I made a mistake. 
I noticed it last week.

**Comment by shd101wyy** [comment]
Which operating system are you using?

**Comment by mickelti** [comment]
windows10

**Comment by DavidCDreher** [comment]
I also cannot get the example for local styling as described in https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css?id=styleless to work on Windows 10 with Atom.

**Comment by shd101wyy** [comment]
Thank you for your reports. I will try to fix the problem as soon as possible (ideally tomorrow evening). Thank you!

**Comment by shd101wyy** [comment]
Hmmm that is awkward, I just tried a fresh installation of atom editor on my windows 10, and I didn't encountered the problem like you guys. Since many people have the same problem, I am pretty sure something is wrong in MPE code. Could you guys please try to remove `~/.mume` directory (On windows it is located at `C:\Users\$username\.mume`) then restart your editor to see if it helps? Thank you.

**Comment by mickelti** [comment]
I tried to delete the .mume directory, but the situation was not changed.

**Comment by DavidCDreher** [comment]
> 
> 
> I tried to delete the .mume directory, but the situation was not changed.

Same for me, no changes

**Comment by shd101wyy** [comment]
Gerrrr. 
Which operating system and which editor + version are you guys using?
Besides, did you modify the `style.less` opened from `Markdown Preview Enhanced: Customize Css` command? May I see your `style.less` code? 
Thank you.

**Comment by shd101wyy** [comment]
Oh, besides all above, which preview theme are you using?

**Comment by mickelti** [comment]
I do not modify style.less but use local style, because I want to switch the format according to the kind of document. 
The .less file is as follows.
-----------------------
#my-id {
  font-size: 0.8em;
  font-family: "Lucida Grande", Meiryo, sans-serif;
  h1 {
    counter-reset: h2counter;
    text-align: center;
    font-size: 1.4em;
    background: #c2edff;/*背景色*/
    padding: 0.5em;/*文字まわり（上下左右）の余白*/

  }
  h2 {
    counter-increment: h2counter;
    counter-reset: h3counter;
    font-size: 1.2em;
    border-bottom: solid 2px black;
}
  h3 {
    counter-increment: h3counter;
    counter-reset: h4counter;
    font-size: 1.2em;
  }
  h4 {
    counter-increment: h4counter;
    font-size: 1.2em;
  }
  h2:before {
    content: counter(h2counter) ". ";
  }
  h3:before {
    content: counter(h2counter) ". " counter(h3counter) ". ";
  }
  h4:before {
    content: counter(h2counter) ". " counter(h3counter) ". " counter(h4counter)
      ". ";
  }
  table {
    width: 90%;
  }
  th,
  td {
    word-break: break-all;
  }

  @media print {
    font-family: "Lucida Grande", Meiryo, sans-serif;
  }
  // custom prince pdf export style
  &.prince {
  }
  // custom phantomjs png/jpeg export style
  &.phantomjs-image {
  }
  //custom phantomjs pdf export style
  &.phantomjs-pdf {
  }
  // custom presentation style
  .reveal .slides {
  }
  .slides > section:nth-child(1) {
    // this will modify `the first slide`
  }
}

.md-sidebar-toc.md-sidebar-toc {
  // sidebar TOC style
}

**Comment by DavidCDreher** [comment]
I'm trying the local style from the documentation.
Atom 1.37.0
MPE 0.16.1
Win 10 1809 17763.503

Example from the documentation (slightly changed)

Test.md
```markdown
---
id: "my-id"
class: "my-class1 my-class2"
# HEADING 2
---

@import "my-style.less"

# Heading1

Test paragraph
## Heading 2
```

```less
#my-id {
    background-color: #222;
    color: #f48342;

    h1, h2, h3, h4, h5, h6 {
        color: #53f442;

    }
}
```

Output:
![2019-06-06 13_27_13-Window](https://user-images.githubusercontent.com/47252106/59029569-e1510f00-885e-11e9-9040-2f08b35c210a.png)

**Comment by shd101wyy** [comment]
Ah I see. I misunderstood the issues you guys mentioned. I might know where the problem comes from. Let me take a shower first then I will go fix it.

**Comment by shd101wyy** [comment]
![Screenshot from 2019-06-06 23-19-00](https://user-images.githubusercontent.com/1908863/59044848-809ef200-88b1-11e9-81ca-a051a54e66a9.png)

A temporary solution is to change the `End of Line Sequence` from `CRLF` to `LF`.

**Comment by DavidCDreher** [comment]
That's already super helpful. Thanks a lot!

**Comment by shd101wyy** [comment]
Actually, I don't plan to publish a new release so soon, because I just published one yesterday.
Please wait till [this pr](https://github.com/shd101wyy/mume/pull/128) gets merged.
Please just use the temporary solution that I post above for now.
Thank you!

**Comment by DavidCDreher** [comment]
No problem. A quick a bit related question: is it possible to overwrite individual style elements from sub blocks like a mermaid diagram somehow using a local style? Say I want to overwrite the #line.today color of a gantt plot.
Thank you for being so super responsive!!! 😄

**Comment by tmori3y2** [comment]
```
<!-- start -->
@import "style.less"
```

This tips now working. Thanks a lot !

**Comment by mickelti** [comment]
Oh, its working by `<!-- start -->`!
Thanks a lot !!

**Comment by parthi2929** [comment]
Its still not working for me.

**Comment by michaelschufi** [comment]
On my machine it's working in the preview but not when exporting to PDF with puppeteer. Both features work on 0.3.13.

**Comment by tmori3y2** [comment]
It has already been solved in my environment. Can I close it?
