### ISSUE TITLE
Presentation with data-background-image can not use the local relative path? #575 (reopen)

### ISSUE THREAD

**Issue by miskovics** [shd101wyy/markdown-preview-enhanced#1142]
@shd101wyy I can not get background image with relative file path, e.g. `<!-- slide data-background-image="test.jpg" -->`, working; a URL path, e.g. `<!-- slide data-background-image="https://i.loli.net/2017/07/12/5965b7edd3a2a.jpeg" -->`, does work. How can I confirm if the fix still works in the latest version and find out the right way to use relative path?

_Originally posted by @miskovics in https://github.com/shd101wyy/markdown-preview-enhanced/issues/575#issuecomment-448218115_

**Comment by shd101wyy** [comment]
It's weird. I just tried on my ubuntu 18.04 vscode 0.4.0 mpe 0.4.0 and the the background image with relative file path worked well.
Are you using atom or vscode? Which operating system are you using? Thank you.

**Comment by miskovics** [comment]
I saw the problem on Ubuntu in December. I retested it now on Mac OS X, and (after closing and reopening the preview pane) I can see the picture, so probably I did something wrong on Ubuntu. I am closing the ticket, sorry for the trouble.
