### ISSUE TITLE
ATOM 无法预览，一直在加载，升级到最新版本也一样

### ISSUE THREAD

**Issue by isuwei** [shd101wyy/markdown-preview-enhanced#1144]
操作系统：win10 1809
Atom插件版本：V0.16.0
问题：旧版本可以加载预览，用了一段时间后，就无法加载了，升级到新版本也无法加载。
已尝试：重新安装新版本，也不行。

![未命名1559623361](https://user-images.githubusercontent.com/47851043/58851672-445b6e00-86c6-11e9-9193-abdc105c94c0.png)

![未命名1559623586](https://user-images.githubusercontent.com/47851043/58852070-9d77d180-86c7-11e9-9796-7673c3f2b51a.png)

**Comment by isuwei** [comment]
每次打开一个文档，用「ctrl+shift+m」调出预览，就显示一直加载，但是如果继续打开另一个文档，就会正常加载出来。如果现在再去点击第一个文档，预览会切换到第一个文档的预览。感觉像是一个BUG。

**Comment by isuwei** [comment]
如果设置成，打开一个文档，自动打开预览。

左键点击文件，就会一直加载，不能预览。
如果左键双击一个文件，就可以正常加载。

**Comment by shd101wyy** [comment]
你好。你用的是 atom beta 还是 atom stable 呢？谢谢

**Comment by shd101wyy** [comment]
我发现了很多人都有这个问题，可能是因为我用 ubuntu 没问题的缘故而忽视了。
我有时间的话会着重看下。谢谢

**Comment by airystar** [comment]
atom 1.37.0 x64版本， arch系统， 之前的0.15.0版本，和更新后的0.16.0版本，有一样的问题
打开很小的markdown文档会一直加载状态，切换到另一个另一个随便什么文件，再切换回来就可以加载成功

**Comment by shd101wyy** [comment]
很奇怪，我刚刚 fresh install 了一个 atom 到 windows 平台，然后安装了 mpe 试了试发现依旧没有出现你们所说的问题。试试删除 ~/.mume 文件夹，然后重启编辑器？

**Comment by isuwei** [comment]
" 删除 ~/.mume 文件夹，然后重启编辑器？"

我试了下，不行。

**Comment by shd101wyy** [comment]
@isuwei 我昨晚刚发了个新版本 0.16.1 不知道修复了没？

**Comment by isuwei** [comment]
@shd101wyy 新本版完美解决，谢谢大佬~
