### ISSUE TITLE
PDF creation time of puppeteer

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/markdown-preview-enhanced#1147]
The PDF creation time of puppeteer is extremely slow from about 10-15 pages over. (Normally about 10 seconds will suddenly take 5 to 30 minutes)

Can you improve by increasing the buffer etc?

**Comment by tmori3y2** [comment]
Some headless chrome processes have been launched, but each process only uses about 20 MB of memory and CPU usage is very high.

**Comment by tmori3y2** [comment]
The sample is not immediately available as it is a confidential document.

The document has many Katex formulas, some UML / WaveDrom / Vega-lite diagrams, and page number footers.

Replacing the diagram with PNG does not improve it.

Although I tried to make PDF from the file which imported the .md files of MPE docs folder, the performance is not bad even if it exceeds 60 pages.

KaTex may be suspicious, but I will check it a little more.

**Comment by tmori3y2** [comment]
Maybe the cause is my custom css.

[A4_Slide_Numbering.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/3265361/A4_Slide_Numbering.zip)


Dramatic slowdown with increasing number of child-doc.md imports.

**Comment by tmori3y2** [comment]
* There is a way to use pandoc paser with --number-sections option, but the Japanese latex engine is difficult to set up and it is difficult to use in our projects in my company.
* phantomjs was good but dead.
* puppeteer requires custom css. By the way, css is not effective at the time of PDF creation when using front-matter of id / class, it is not used

**Comment by shd101wyy** [comment]
すみません、今日は中国端午の節句です、私は休みています。週末に帰ります！^_^

Haha I am learning Japanese now. Don’t know if I write it correctly. 

I will be back this weekend, likely Sunday. Thank you!

**Comment by tmori3y2** [comment]
Almost correct. Fix only one sentence;

私は休みています。-> 私は休んでいます。

日本の端午の節句は、5/5なので、1か月違いますね。:smile:

By the way, I suspected that the cause was the numbering of the header, but it was the reason that the div for the page break was made the closed empty element.

I used \<div style = "page-break-before: always" /\> for page break which can be used by other parsers instead of \<!--pagebreak--\> of MPE.

terrible slow when Chrome (Puppeteer)/PDF or Open in Browser (Chrome)/Print preview

* \<div style = "page-break-before: always" /\>
* \<div class="pagebreak" /\>
* 13 breaks (p14): 20 sec, 14 breaks (p15): 50sec, 15 breaks (p16): 95sec, 16 breaks (p17): 178sec ...
* Open in Browser (Edge)/Print preview: 2sec

fast (<2sec)

* \<div style = "page-break-before: always"\> \</div\>
* \<div class="pagebreak"\> \</div\>
* \<!--pagebreak--\>
* \<div class="abc" /\> // not page break

Chronium seems to be slow if div for page break is a closed empty element, so I will not use it.

Thanks a lot.

**Comment by tmori3y2** [comment]
I reported this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=990319
