### ISSUE TITLE
Small changes required for an upcoming Atom release

### ISSUE THREAD

**Issue by maxbrunsfeld** [shd101wyy/markdown-preview-enhanced#115]
Hi! Atom will soon be upgrading to a new version of Electron, which will cause some APIs to change.

You'll need to change [this usage](https://github.com/shd101wyy/markdown-preview-enhanced/blob/88c1aa993910c7bed3adce79140a63cf09051a5f/lib/markdown-preview-enhanced-view.coffee#L740) of `BrowserWindow.prototype.loadUrl` to `win.webContents.loadURL`.

There may be other similar small changes required. See [this post](http://electron.atom.io/blog/2015/11/17/electron-api-changes) on the electron blog for more information. And let me know if you need any additional help. Thanks!

**Comment by shd101wyy** [comment]
Hi @maxbrunsfeld , 

Thank you very much for this important information 👍 . 
I will upgrade APIs this weekend.  

Cheers!

**Comment by shd101wyy** [comment]
Done! Thanks!
