### ISSUE TITLE
请问怎么只import文件的前几行？

### ISSUE THREAD

**Issue by zhiyiZeng** [shd101wyy/markdown-preview-enhanced#1164]
比如@import "xx.md", 怎么指定只显示xx.md的前N行或者指定第N行到第N+M行？

**Comment by shd101wyy** [comment]
现在支持 `line_begin` 和 `line_end` 了。

https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/file-imports?id=%e5%af%bc%e5%85%a5%e7%89%b9%e5%ae%9a%e8%a1%8c%e6%95%b0

谢谢

**Comment by zhiyiZeng** [comment]
谢谢，升级了下可以了。
