### ISSUE TITLE
puml not work

### ISSUE THREAD

**Issue by hilision** [shd101wyy/markdown-preview-enhanced#1167]
this is my code
![image](https://user-images.githubusercontent.com/23415986/60697447-ea480580-9f1c-11e9-9096-839790aeea3a.png)

but the preview show this error
Error: write EPIPE

i'm use vscode,the version is 1.36.0.
OS is windows 7

**Comment by shd101wyy** [comment]
Do you have Java installed and set java executable in your system path?

**Comment by hilision** [comment]
> Do you have Java installed and set java executable in your system path?

yes ,i had installed java.
![image](https://user-images.githubusercontent.com/23415986/60700489-a956ed80-9f2a-11e9-9376-9e8e937537e3.png)

**Comment by hilision** [comment]
i restart my pc and it works.

**Comment by dsouzasavio** [comment]
Adding Java to the path worked for me (y)
