### ISSUE TITLE
数学公式多行预览问题

### ISSUE THREAD

**Issue by at2008** [shd101wyy/markdown-preview-enhanced#1171]
行内正常，多行预览似乎不正常，不知道是不是我环境的问题？

MD代码:
$f(x) =  sin(x) + 12$

$$
f(x) = sin(x) + 12
f(x) = sin(x) + 12
$$

下面多加了双引号“避免Github解释
“```math {.line-numbers}
f(x) = sin(x) + 12

f(x) = sin(x) + 12
”```

预览结果：
![2019-07-09_235952](https://user-images.githubusercontent.com/25857125/60905234-355c7280-a2a7-11e9-8ad2-8642ffc75e64.png)

**Comment by shd101wyy** [comment]
应该这么写：

```
$$f(x) = sin(x) + 12$$  
$$f(x) = sin(x) + 12$$
```

或者 

```
$$f(x) = sin(x) + 12 \\ f(x) = sin(x) + 12 $$
```

**Comment by at2008** [comment]
多谢大神！👍
