### ISSUE TITLE
Preview Theme setting has no effect

### ISSUE THREAD

**Issue by will-e-yams** [shd101wyy/markdown-preview-enhanced#1178]
macOS Mojave Version 10.14.5
VS Code Version 1.36.1

Changing the `Preview Theme` setting has no effect. Theme is always from selected VS Code theme.

All other markdown extensions are uninstalled or disabled.

Same behavior with multiple VS themes.

![image](https://user-images.githubusercontent.com/5280307/61805768-48b12700-adeb-11e9-9ce4-9b0946a4e04e.png)

**Comment by shd101wyy** [comment]
Hi. Please send me a screenshot here. Thank you.

**Comment by will-e-yams** [comment]
> Hi. Please send me a screenshot here. Thank you.

Original updated with screenshot.

**Comment by shd101wyy** [comment]
It seems to me that the preview you opened was still the default markdown preview, not the one from MPE.  
 
Please try to right click at the panel of your markdown file, then click `Markdown Preview Enhanced: Open Preview To The Side` or just `cmd-shift-p` then run `Markdown Preview Enhanced: Open Preview To The Side` command. 

Thank you

**Comment by will-e-yams** [comment]
Thanks @shd101wyy, this resolved my issue. I would like to use something like `Auto-Open Markdown Preview` [link to marketplace](https://marketplace.visualstudio.com/items?itemName=hnw.vscode-auto-open-markdown-preview), but that's using the built-in VS version also. Is this a feature you see on your roadmap?
