### ISSUE TITLE
为什么不并入atom的内置插件呢

### ISSUE THREAD

**Issue by crper** [shd101wyy/markdown-preview-enhanced#119]
相当的实用的插件，我感觉应当内置到atom中，取代那个鸡肋的markdown内置插件；

**Comment by shd101wyy** [comment]
Hello @crper 感谢你的回复  

这个插件只是作为扩展功能用的，目前来说还有很多的不足，仍需完善和改进。

谢谢你的赞～

**Comment by shd101wyy** [comment]
这个 issue 我先关闭了哈
