### ISSUE TITLE
add an empty cell in Extended Table

### ISSUE THREAD

**Issue by Vincendovich** [shd101wyy/markdown-preview-enhanced#1190]
Hi, shd101wyy,

the ExtendedTableSyntax is a very handy feature that I'm very fond of.

one thing I just wonder is that  if I do need a empty cell in a row in my table when the ExtendedTableSyntax is ture, what shall I do? I think the default syntax for the extended table should be more stringent, as the ^ and > has been already defined as merged cells. Why would empty cells be previewed as merged rows as well? 

leaving the empty cell to be previewed as an empty cell probably is a better Syntax in the extended table.

thank you for your consideration.

**Comment by TimoHocker** [comment]
Pretty old post, but it's still an issue.
As a workaround you could put &nbsp; into the cell to prevent it from being merged

**Comment by Vincendovich** [comment]
> Pretty old post, but it's still an issue.
> As a workaround you could put `&nbsp;` into the cell to prevent it from being merged

many thanks, TimoHocker, it works perfectly!
