### ISSUE TITLE
Any plans to add support for the new features in mermaid 8.2?

### ISSUE THREAD

**Issue by sratsamy** [shd101wyy/markdown-preview-enhanced#1199]
Are there any plans to add support for the new mermaid 8.2 features? Namely the background highlighting?

https://mermaidjs.github.io/#/sequenceDiagram?id=background-highlighting

Love the plugin. Thank you for your work!

**Comment by shd101wyy** [comment]
Upgraded to 8.4. Sorry for the delay. Thank you.
