### ISSUE TITLE
Feature request: Set default path for exported files

### ISSUE THREAD

**Issue by sorenmortensen** [shd101wyy/markdown-preview-enhanced#120]
It would be great if it were possible to set the default folder, relative to the file being exported, in which to save the exported file - like the "Image save folder path" setting.

For example, if I have a file saved as `/Project/Documents/File.md`, I'd like to set the default export path to `../Exports/` in Settings, so that when I export the file, the default value in the "Save as" field is `/Project/Exports/File.pdf`, rather than its current default value, which is just in the same folder as the current file - e.g. `/Project/Documents/File.pdf`.

**Comment by shd101wyy** [comment]
Hi @sorenmortensen , Thanks for your suggestion.  

I will release a new version that supports the feature you request this weekend.  

Cheers

**Comment by sorenmortensen** [comment]
Thanks very much!

**Comment by shd101wyy** [comment]
I will close this issue after I publish the new version

**Comment by shd101wyy** [comment]
@sorenmortensen feature added, please help me test it out. 

Cheers
