### ISSUE TITLE
Forgets location when switching tabs between documents

### ISSUE THREAD

**Issue by taoeffect** [shd101wyy/markdown-preview-enhanced#121]
Sometimes I have two markdown documents open and like two switch between them. However, Markdown-preview-enhanced seems to forget where it was in a document after I switch tabs away from it. When I switch back, I'm taken to the top of the document, and this can be kinda annoying when switching back and forth between very long documents.

**Comment by shd101wyy** [comment]
@taoeffect should be fixed now.

Cheers

**Comment by taoeffect** [comment]
Excellent! You're amazing @shd101wyy! Thanks much! 😄 

One thing I noticed: it wasn't enough to update the plugin to get this to work. I had to quit Atom and relaunch it before the new changes propagated. But closing this issue since I verified the fix.
