### ISSUE TITLE
0.4.3版本侧边栏不显示

### ISSUE THREAD

**Issue by LexHsu** [shd101wyy/markdown-preview-enhanced#1211]
请问0.4.3侧边栏取消了吗，我已经勾选了enableScriptExecution。md转换为html还是不能显示侧边栏。fontmatter也设置了toc为true
---
html:
embed_local_images: true
embed_svg: true
offline: false
toc: true
---

**Comment by shd101wyy** [comment]
侧边栏应该还有的。。我找时间看下，最近很忙。抱歉

**Comment by LexHsu** [comment]
@shd101wyy 多谢

**Comment by LexHsu** [comment]
今天自己找到了原因，忘了设置toc的缩进，因此不生效：
---
html:
embed_local_images: true
embed_svg: true
offline: false
toc: true
export_on_save:
  html: true
---
多谢。
