### ISSUE TITLE
中文输入下部分字符会导致Atom 卡顿

### ISSUE THREAD

**Issue by YoYo-YY-YoYo** [shd101wyy/markdown-preview-enhanced#122]
如输入 `（）` `《》`等符号会导致卡顿.

补充:准确 说是在 编辑 流程图的 时候

**Comment by shd101wyy** [comment]
Hello @willcrybest , 感谢你的回复

我个人感觉这个可能是 atom  的问题，当然如果我找到了解决方案会通知你。 

谢谢 ;)

**Comment by willcrybest** [comment]
再次补充一下。只有在开预览的时候才会出现卡顿。不开预览不会卡顿

**Comment by willcrybest** [comment]
用了一段时间。整体还是挺赞的~

**Comment by gabyx** [comment]
reopen in english if problem persists...
