### ISSUE TITLE
markdow 侧边栏目录选项没有用？

### ISSUE THREAD

**Issue by AllenLeic** [shd101wyy/markdown-preview-enhanced#1221]
> 如果 toc 被设置为 false，那么边栏目录将会被隐藏。如果 toc 被设置为 true，那么边栏目录将会被缺省启动并显示。如果 toc 没有被设置，那么缺省边栏目录将会被启动，但是并不显示。

这个是导出html时候的配置，但是我是用之后无法生效。
![image](https://user-images.githubusercontent.com/35724223/66726397-bcebeb80-ee6b-11e9-8f06-116e7285557c.png)

**Comment by shd101wyy** [comment]
得去插件设置把 `enableScriptExecution` 打开
