### ISSUE TITLE
Presentation Writer  Nesting

### ISSUE THREAD

**Issue by BaronTommy** [shd101wyy/markdown-preview-enhanced#123]
atom preview nesting difficult?

```html
<!-- slide -->
  <section>
    text_a_1
  </section>
  <section>
    text_a_2
  </section>
```  
preview mode
![screencapture at sun sep 4 15 31 25 jst 2016](https://cloud.githubusercontent.com/assets/16768208/18229449/cc234fb6-72b4-11e6-9dec-4dc0967f5c72.png)

Browser
![a6f40dbd-209b-4e19-914e-26ddcba78a01-604-0000ef6370bf25d5](https://cloud.githubusercontent.com/assets/16768208/18229465/6528ee82-72b5-11e6-8ebd-3847736eeb8a.gif)

**Comment by shd101wyy** [comment]
Hi @BaronTommy , thanks for your reply

Vertical slides will be supported in next version.  

Thanks

**Comment by shd101wyy** [comment]
@BaronTommy , vertical slides is now supported. 
You can define vertical slides like this:  
```markdown
<!-- slide -->  
this is horizontal 

<!-- slide vertical:true -->
text_a_1

<!-- slide vertical:true -->
text_a_2
```

Just add `vertical:true` to your slide meta.  

I also updated [presentation_doc](https://rawgit.com/shd101wyy/markdown-preview-enhanced/master/docs/presentation-intro.html), you can have a look if you want.

Cheers!

**Comment by shd101wyy** [comment]
By the way, what software are you using to capture the gif? It was fancy.
Thanks

**Comment by BaronTommy** [comment]
*Thank you very much*

nglish weak
sorry

gif


This is also great
Mouse operation
[screen capture](http://www.alfredforum.com/topic/902-take-quick-screenshots-using-the-screencapture-workflow/)

**Comment by BaronTommy** [comment]
bug ?

[gif](https://dl.dropboxusercontent.com/s/f3npgazr5dju8kk/39D42168-0167-466D-8823-4F2C0EF4B6E4-604-000115261F76C997.gif?dl=0)
