### ISSUE TITLE
mermaid无法正常显示

### ISSUE THREAD

**Issue by PolarisRisingWar** [shd101wyy/markdown-preview-enhanced#1245]
VSCode。
mermaid代码片里的几何块是黑色的，可以用鼠标选到里面的字，可能是我没有正确配置mermaid的样式。我之前下过其他markdown mermaid插件可以显示，但是那一插件只能用于vscode内置Markdown预览器，不能用在MPE的预览里。
仅下载了markdown preview enhanced这一个插件。
mermaid_config.js是初始状态：
// config mermaid init call
// http://knsv.github.io/mermaid/#configuration
//
// You can edit the 'MERMAID_CONFIG' variable below.
MERMAID_CONFIG = {
  startOnLoad: false
}
js文件中的GitHub网址无法登录（不知道是因为墙还是网址真的没了），所以也还是没找到在哪去做这个配置……
本人是小白，没学过js，所以不太懂。如果有人能看一下问题的话真是感激不尽！

**Comment by VVangYZ** [comment]
切换一下主题再切换回来似乎就好了。

**Comment by PolarisRisingWar** [comment]
> 切换一下主题再切换回来似乎就好了。

谢谢，还真是这样的，我改了mpe插件里面mermaid的主题，然后现在3个主题这几种配色居然都能用了……虽然没搞懂是为什么，但是感觉很神奇。
