### ISSUE TITLE
Can't export PDF with PanDoc

### ISSUE THREAD

**Issue by David-Else** [shd101wyy/markdown-preview-enhanced#1249]
I have this as front matter
```
---
output: pdf_document
---
```
```
$ pandoc -v
pandoc 2.7.3
```
In VS Code I select `pandoc` to try and export PDF and get
```
Error: Command failed: pandoc -f markdown+tex_math_single_backslash -o /location/title.pdf --pdf-engine=pdflatex pdflatex not found. Please select a different --pdf-engine or install pdflatex
```
I don't want another PDF engine, PanDoc should just export my file, please help!

**Comment by fuhrmanator** [comment]
It's not clear - is `pdflatex` found in your path?

**Comment by David-Else** [comment]
@fuhrmanator No, I don't have that installed, and no way to get it on Centos 8 I am afraid. Maybe I need to go to ODT as an intermediate format.
