### ISSUE TITLE
ImageMagick conversion fails when spaces are in Windows directory

### ISSUE THREAD

**Issue by fuhrmanator** [shd101wyy/markdown-preview-enhanced#1262]
I'm working on a Google Drive with Windows 10, and so my path of documents is always `G:\My Drive\...` (there's a space between My and Drive).

When I try to **Save as Markdown** for the following:

    ```puml {filename="sequence.svg"}
    @startuml
    scale 5
    A -> B : hello
    @enduml
    ```

inside the generated file is this error:

> Error: imagemagick-cli failure
Error: Failed to call 'convert C:\Users\me\AppData\Local\Temp\mume-svg2019114-17424-18rxvt6.derp.svg G:\My Drive\MarkdownTests\assets\sequence.svg', which was mapped to '"C:\Windows\System32\convert.exe" C:\Users\me\AppData\Local\Temp\mume-svg2019114-17424-18rxvt6.derp.svg G:\My Drive\MarkdownTests\assets\sequence.svg'. Error is 'Command failed: "C:\Windows\System32\convert.exe" C:\Users\me\AppData\Local\Temp\mume-svg2019114-17424-18rxvt6.derp.svg G:\My Drive\MarkdownTests\assets\sequence.svg
Invalid Parameter - G:\My

The call to `"C:\Windows\System32\convert.exe"` looks good, but maybe there should be quotes around the path of the files, e.g., `"C:\Users\me\AppData\Local\Temp\mume-svg2019114-17424-18rxvt6.derp.svg" "G:\My Drive\MarkdownTests\assets\sequence.svg"`

Also, I'm assuming I can use `plantuml {filename="sequence.svg"}` to say I want the markdown to have an SVG file (rather than PNG)?

**Comment by tmori3y2** [comment]
"C:\Windows\System32\convert.exe" is not ImageMagick's "convert" command.

ImageMagick's "convert" command conflicts the system command in Windows system.

https://stackoverflow.com/questions/4481573/how-to-override-windows-convert-command-by-imagemagicks-one

You need to set the ImageMagick's  path before the system command path in PATH variable.

**Comment by fuhrmanator** [comment]
@tmori3y2 That is correct. However, the bug with the space is not related to that problem. 

For proof: I opened a project in the path "C:\Users\me\Documents\Test" for example, and the error I got was one related to not finding convert/magick (as opposed to the "Invalid Parameter" caused by the space in "My Drive".
