### ISSUE TITLE
markdown-preview-enhanced 0.17 无法打开预览

### ISSUE THREAD

**Issue by bluehysteric** [shd101wyy/markdown-preview-enhanced#1265]
mac atom 1.41 x64 markdown-preview-enhanced 0.17无法打开预览,修改快捷键后也无法打开.atom没有报错,请检查一下.谢谢

**Comment by Katherinaxxx** [comment]
我也遇到了同样的问题 解决了吗

**Comment by bluehysteric** [comment]
> 我也遇到了同样的问题解决了吗

没有.我已经放弃了,转头别的markdown软件了.

**Comment by shd101wyy** [comment]
虽然你们说的可能不是一回事，如果是 atom 1.47.0 的话看这个

https://github.com/shd101wyy/markdown-preview-enhanced/issues/1380#issuecomment-631341305

**Comment by Katherinaxxx** [comment]
> 虽然你们说的可能不是一回事，如果是 atom 1.47.0 的话看这个
> 
> [#1380 (comment)](https://github.com/shd101wyy/markdown-preview-enhanced/issues/1380#issuecomment-631341305)

应该是了 我的是atom 1.47.0 thx～
