### ISSUE TITLE
erd

### ISSUE THREAD

**Issue by baronTommy** [shd101wyy/markdown-preview-enhanced#128]
Function addition

https://github.com/BurntSushi/erd
Haskell &  GraphViz.
\`\`\`erd

...

\`\`\`

**Comment by shd101wyy** [comment]
I will try to add support in next version.
thanks ;)

**Comment by shd101wyy** [comment]
I failed to install `erd`, any idea how to solve the problem?  
![screen shot 2016-09-08 at 8 51 55 pm](https://cloud.githubusercontent.com/assets/1908863/18373007/35343e12-7606-11e6-97d3-5940a85dd21b.png)

**Comment by BaronTommy** [comment]
```shell
brew cask install haskell-platform
git clone git@github.com:BurntSushi/erd.git
cd erd
cabal install graphviz
cabal configure
cabal build
```
[参考](http://qiita.com/nori3tsu/items/c36591b8091e9ff89ce5)
please try it

**Comment by BaronTommy** [comment]
好运
感谢您的各种附加
文本 - 加工（markdown-preview-enhanced） - >图
良好的管理方便

很难理解
日本< - 翻译 - >英语

易于理解
日本< - 翻译 - >中国

**Comment by BaronTommy** [comment]
cabal install erd
看来老版

**Comment by shd101wyy** [comment]
谢谢你的回复，

我最近两周会很忙。有空闲的话我会添加这个功能。

谢谢 :)

**Comment by BaronTommy** [comment]
它是在业余时间不错
这是不着急

**Comment by shd101wyy** [comment]
早速のご返信ありがとうございます。

ここ二週間は忙しくて手が回らないので、時間ができ次第フィーチャーを足していきます。

引き続きよろしくお願いいたします。

（我的朋友帮忙翻译的）

**Comment by shd101wyy** [comment]
erd 图像 [code chunk](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/code-chunk.md#demo) 实现。

1, 安装 [erd](https://github.com/BurntSushi/erd)
2, 写  
<pre>
```{erd output:"html", args:["-i", "{input_file}", "-f", "svg"]}

内容

```
</pre>

3, 按 按钮  
<img src="https://camo.githubusercontent.com/018dd5f3c6fda726b22dcf767f601fe49e12ae26/687474703a2f2f692e696d6775722e636f6d2f61374c6b4a59442e676966" alt="code_chunk" data-canonical-src="http://i.imgur.com/a7LkJYD.gif" style="max-width:100%;">

**Comment by baronTommy** [comment]
感谢您的发展

谢谢
![23aee345](https://cloud.githubusercontent.com/assets/16768208/18812246/11d845d4-8309-11e6-881a-48c4582d70f5.gif)

**Comment by shd101wyy** [comment]
いいえ、どういたしまして ;)

![tumblr_lyf4yguthy1qcrs5uo1_500](https://cloud.githubusercontent.com/assets/1908863/18812383/41c52828-8298-11e6-81d2-fbadb998ebd3.gif)

何でも自由に聞いてください。できる限り助けますよ。
