### ISSUE TITLE
How to Use in "untitled"

### ISSUE THREAD

**Issue by SeaPants** [shd101wyy/markdown-preview-enhanced#1280]
When I examined why MPE cannot use in "untitled", I found it was caused in `isMarkdownFile()`.

Then, I did change
https://github.com/shd101wyy/markdown-preview-enhanced/blob/1830481bc0f01475d512ff2143f3ffc3e88a4985/out/src/extension.js#L112
to
`if (!editor || !editor["getPath"]){`.

At first glance, it seems to work, but I know this is not an essential solution. (Because included some yellow errors. :/ )

So, please teach me how to make MPE work in `untitled`.

**Comment by shd101wyy** [comment]
Sorry you have to save the markdown file first. 
Because for example, when you import an image `![]()` with a relative path, I will need to know the base file path of your markdown file first.
Thanks
