### ISSUE TITLE
导出成电子书equb无法显示图片

### ISSUE THREAD

**Issue by CraneJen** [shd101wyy/markdown-preview-enhanced#129]
导出成电子书equb无法显示图片，pdf的可以，这是equb的问题吗？

**Comment by shd101wyy** [comment]
嗯？能让我看看你的图片路径是怎么写的吗？

**Comment by CraneJen** [comment]
@shd101wyy 
<img src="https://upload.wikimedia.org/wikipedia/commons/9/94/Model_S_driving.jpg" >

**Comment by shd101wyy** [comment]
哦貌似得用 markdown 的 image 写法
![caption](./img.png).

**Comment by shd101wyy** [comment]
<code>![caption](./your_inage.png)</code>

**Comment by shd101wyy** [comment]
啊啊啊发现手机打不出来，得用 markdown 的图片写法

**Comment by CraneJen** [comment]
@shd101wyy 

。。。 这就尴尬了，得该好多，都是网络图片，但是pdf没问题啊

**Comment by shd101wyy** [comment]
我回家后试试，貌似是个 bug

**Comment by shd101wyy** [comment]
您先不用改，我觉得是我的 bug

**Comment by CraneJen** [comment]
@shd101wyy 
我真不想改的，麻烦

**Comment by shd101wyy** [comment]
我研究了一下，貌似是因为你用的是网络图片，所以生成的epub文档里面的图片是需要网络来加载的。  
![screen shot 2016-09-08 at 9 01 09 pm](https://cloud.githubusercontent.com/assets/1908863/18373143/6029782a-7607-11e6-85a6-24b854a550b5.png)
所以只要网络正常就应该会显示出来。

**Comment by CraneJen** [comment]
我试了Google play books，多看，iBook，都加载不进来啊😯，网络没问题

**Comment by shd101wyy** [comment]
你把其中一个图片换成本地图片试试？

**Comment by CraneJen** [comment]
本地可以😂

**Comment by shd101wyy** [comment]
那我加个功能把网络图片自动下载到本地？

**Comment by CraneJen** [comment]
可以可以

**Comment by shd101wyy** [comment]
我争取这周发一个新的版本吧😂

**Comment by shd101wyy** [comment]
@CraneJen 哦了，请升级到最新的版本，然后重启 atom。
现在会自动下载网络图片。但是下载时间可能会很长，所以我推荐还是事先把图片存在本地然后引用本地图片。   

ebook 的文档我也更新了，现在可以更加好的定制了。 [doc](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/ebook.md)。  

遇到问题或者需要添加功能请告知我。
谢谢

**Comment by CraneJen** [comment]
Good Job!!!完美！！！

**Comment by shd101wyy** [comment]
那这个 issue 我就给关闭了 :)
