### ISSUE TITLE
macOS MPE mermaid 渲染问题

### ISSUE THREAD

**Issue by chptx** [shd101wyy/markdown-preview-enhanced#1298]
VS Code版本：
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

文本：
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

渲染结果：

![1581394384758](https://user-images.githubusercontent.com/5226504/74210747-ef95db80-4cc7-11ea-8fae-bde5513f3ad6.jpg)

**Comment by shd101wyy** [comment]
可以去插件设置里面调整下 mermaidTheme 就好了。以前有人遇到过相同的问题可以搜下
