### ISSUE TITLE
不能预览连续的多个空格吗？

### ISSUE THREAD

**Issue by hjzCy** [shd101wyy/markdown-preview-enhanced#1309]
![Y0_QS9 ZK58XRXKKR93$VMJ](https://user-images.githubusercontent.com/39392770/75310039-c3648800-588d-11ea-9624-15e55baf8b4a.png)

例如想在文字之间可以有多个空格的时候应该怎么办呢？

**Comment by hjzCy** [comment]
好像图片看不了，例如下面文字，预览时只它忽略了多余的空格：

- `$`            根对象；
- `@`           当前对象；
- `.` 、`[]` 子对          象；
- `..`  后代          对象；

**Comment by justinchuby** [comment]
根据Markdown的语法规则这些空格会被忽略掉。可以加一个`&nbsp;`表示空&nbsp;格

参见 https://stackoverflow.com/questions/44810511/how-to-add-empty-spaces-into-md-markdown-readme-on-github

**Comment by hjzCy** [comment]
@justinchuby 好的，谢谢。
