### ISSUE TITLE
请问如何在 mermaid 的流程图/时序图中实现换行？

### ISSUE THREAD

**Issue by luoxiaohei** [shd101wyy/markdown-preview-enhanced#1310]
官方的 mermaid 库支持通过 `<br>` 将长文本转成多行展示，但是在 MEP 里该操作没有生效。
请问如何在 mermaid 的流程图/时序图中实现换行？
![image](https://user-images.githubusercontent.com/7138906/75312496-0a09b080-5895-11ea-8181-9db3f5fa04f3.png)

**Comment by luoxiaohei** [comment]
在文档和 issues 里没有找到相关信息， @shd101wyy 请帮忙看一下哈，谢谢！

**Comment by shd101wyy** [comment]
😂我也不知道原因。我有时间了研究下👀

**Comment by ZHULOO** [comment]
我在atom的MPE中也碰到了这个问题，使用<br/>节点内的文字不会换行，mermaid官网的编辑器是可以的。

**Comment by shd101wyy** [comment]
@luoxiaohei @ZHULOO 久等了，应该是修复了现在 😂但也有可能引入了其它的 bugs。。。

**Comment by luoxiaohei** [comment]
确认 VSCode 更新插件到 0.5.3 版本后可以正常使用 `<br/>` 换行了，赞！！！

**Comment by ZHULOO** [comment]
> @luoxiaohei @ZHULOO 久等了，应该是修复了现在 😂但也有可能引入了其它的 bugs。。。

辛苦了
