### ISSUE TITLE
Bug: Table of contents doesn't update when the heading level is changed

### ISSUE THREAD

**Issue by sorenmortensen** [shd101wyy/markdown-preview-enhanced#134]
# Bug

If a table of contents has been generated, like so:

``` markdown
<!-- toc orderedlist:0 -->

- [Introduction](#introduction)
- [Main Section](#main-section)
    - [Subsection 1](#subsection-1)
        - [Subsection 2](#subsection-2)

<!-- tocstop -->

# Introduction
# Main Section
## Subsection 1
### Subsection 2
```

and the user realises the `Subsection 2` heading is wrong, and should be a heading 2 (`##`) rather than heading 3 (`###`), and they change it, like so:

``` markdown
# Introduction
# Main Section
## Subsection 1
## Subsection 2
```

then the table of contents doesn't change, remaining like so:

``` markdown
<!-- toc orderedlist:0 -->

- [Introduction](#introduction)
- [Main Section](#main-section)
    - [Subsection 1](#subsection-1)
        - [Subsection 2](#subsection-2)

<!-- tocstop -->
```

This means that the rendered table of contents now has a bullet point at the wrong indentation level, like this:
- [Introduction](#introduction)
- [Main Section](#main-section)
  - [Subsection 1](#subsection-1)
    - [Subsection 2](#subsection-2)

It's not until the user changes the name of the heading, like this:

``` markdown
# Introduction
# Main Section
## Subsection 1
## Sub-Section 2
```

that the table of contents updates to look like this, correctly:

``` markdown
<!-- toc orderedlist:0 -->

- [Introduction](#introduction)
- [Main Section](#main-section)
    - [Subsection 1](#subsection-1)
    - [Sub-Section 2](#sub-section-2)

<!-- tocstop -->
```

This then renders the correct table of contents, like so:
- [Introduction](#introduction)
- [Main Section](#main-section)
  - [Subsection 1](#subsection-1)
  - [Sub-Section 2](#sub-section-2)
# Workaround

A workaround is to, when changing the indentation level of a heading, briefly change the text of the heading as well (e.g. add an extra letter), save (to ensure the TOC updates), and then remove it again.

**Comment by shd101wyy** [comment]
Hi @sorenmortensen , thanks for your reply

This issue will be fixed in next version.

Thanks

**Comment by shd101wyy** [comment]
Hi @sorenmortensen , this issue should be fixed now.

Cheers ;)
