### ISSUE TITLE
Empty exports

### ISSUE THREAD

**Issue by frankieliu** [shd101wyy/markdown-preview-enhanced#1341]
Using:

VS Code
Version: 1.43.1
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:17:38.324Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-91-generic

Markdown Preview Enhanced: 0.5.2

Simple file:

# hello 
some text

Right click on preview window:
Chrome/png
or
Chrome/pdf

Both blank pages
Pages are generated, they just happen to be blank.

**Comment by shd101wyy** [comment]
Did you save your file? You will need to save your file first then export.

**Comment by frankieliu** [comment]
Yes you are correct, I wanted to remove my post, but didn't get to it.
Thanks so much for this wonderful plugin.
