### ISSUE TITLE
Cant use configurations

### ISSUE THREAD

**Issue by Stephan-MDD** [shd101wyy/markdown-preview-enhanced#1350]
I want to export my markdown file as html with the TOC as a sidebar, but I can get it to work. Can any one provide a simple example on how to do this? :)

**Comment by shd101wyy** [comment]
Check this: https://shd101wyy.github.io/markdown-preview-enhanced/#/html

You will need to set “toc” to true under “html” section in front matter

**Comment by Stephan-MDD** [comment]
I read that, it was where i saw the feature :)
If I place the code at the top of my markdown and exports to html nothing happens, I only get the regular format

**Comment by Stephan-MDD** [comment]
If I export this to html I wont get a sidebar, only the regular TOC
```md
---
html:
  embed_local_images: false
  embed_svg: true
  offline: false
  toc: true

print_background: false
---

# Markdown Title {ignore=true}

[TOC]

## Header 1
### Header 1.1
### Header 1.2

## Header 2
### Header 2.1
### Header 2.2
```

**Comment by shd101wyy** [comment]
You probably also need to enable this in settings:

```
    "markdown-preview-enhanced.enableScriptExecution": true,
```

**Comment by Stephan-MDD** [comment]
It works, thanks! This tool is so awesome, and should be the standard for all markdowns out there - just love it <3
