### ISSUE TITLE
New mathInlineDelimiters not taken in account

### ISSUE THREAD

**Issue by deadbird99** [shd101wyy/markdown-preview-enhanced#1361]
I use MPE as a notebook in complement with VSCode. All my notes are stored in a Git repo, hosted at Gitlab.com.

I have a little issue with inline math expressions. By default, MPE uses "$" as delimiters for inline math expression. But according to [this page](https://docs.gitlab.com/ee/user/markdown.html#math), Gitlab uses "$\`" and "\`$". Si I edited `settings.json` and modified `markdown-preview-enhanced.mathInlineDelimiters` like so:

```json
"markdown-preview-enhanced.mathInlineDelimiters": [
		[
			"$",
			"$"
		],
		[
			"$`",
			"`$"
		],
		[
			"\\(",
			"\\)"
		]
	]
```

However, when I type, for example, "$\`LiFePO_4\`$", it's rendered correctly in Gitlab but MPE renders it as:
![image](https://user-images.githubusercontent.com/4655239/80283166-fc966880-8715-11ea-9978-dfcecd7250b2.png)

Is this a bug or am I missing something?

**Comment by shd101wyy** [comment]
Put “$’” ahead “$”? Not sure if it works though

**Comment by deadbird99** [comment]
It works! It's kind of weird though ^^'
