### ISSUE TITLE
Question: What is the theme used for syntax highlighting in the first screenshot of the readme?

### ISSUE THREAD

**Issue by lewallen** [shd101wyy/markdown-preview-enhanced#1362]
Hello, thanks so much for an amazing package. I had a small question: how can I get syntax highlighting in Atom to match the first screenshot in the readme ([here](https://user-images.githubusercontent.com/1908863/28227953-eb6eefa4-68a1-11e7-8769-96ea83facf3b.png) or [here](https://shd101wyy.github.io/markdown-preview-enhanced/#/))? 

I'm specifically curious how to get distinct colors for so many different elements of markdown and latex syntax, but I also like the particular theme being used and wonder what it is (and to be clear, I'm referring to the source highlighting on the lefthand side). I'm using the language-gfm-enhanced grammar, but haven't found a theme which matches this one.

I hope it's alright to post this as a question; previously there was a similar question, it was about matching the preview CSS from the same screenshot. Thanks again!

**Comment by RobertAguilera712** [comment]
Did you realize how to get the same syntax highlighting?
