### ISSUE TITLE
Salt wireframe support for plantuml

### ISSUE THREAD

**Issue by cbuteau** [shd101wyy/markdown-preview-enhanced#1374]
I am okay with installing another package if it is necessary but I would like to start using SALT to show basic layout.

Heavy user of your plugin at home and at work.

Thanks for your hard work.

**Comment by tmori3y2** [comment]
Please read the manual and ask questions.

PlantUML is supported.

https://shd101wyy.github.io/markdown-preview-enhanced/#/diagrams?id=plantuml

Of course, SALT too.

> If @start... is not found, then @startuml ... @enduml will automatically be inserted.

This means ...

~~~puml
@startalt



@endsalt
~~~
