### ISSUE TITLE
style.less 无效  styles.css 有效

### ISSUE THREAD

**Issue by Royleeother** [shd101wyy/markdown-preview-enhanced#1385]
创建 **_style.css_** , 设置css, 无效
在同目录下发现了一个自带的 **_styles.css_**, 设置css, 有效
这难道是文档写错了？

**Comment by shd101wyy** [comment]
@Royleeother 可能是出 bug 了。你用的是 atom 还是 vscode？

**Comment by Royleeother** [comment]
> @Royleeother 可能是出 bug 了。你用的是 atom 还是 vscode？

Vscode

**Comment by shd101wyy** [comment]
`0.5.9` 应该修好了，谢谢～
