### ISSUE TITLE
Mathjax Rendering Issues

### ISSUE THREAD

**Issue by Ficklee** [shd101wyy/markdown-preview-enhanced#139]
Mathjax rendering functions seems to fail to render basic math equation in my running environment. 
Detailed Example:
$x+y=z$ fails to render in Mathjax option, but runs well in KaTex option.

Atom Version:1.10.2
Plug-in Version: 0.8.5

**Comment by shd101wyy** [comment]
Hi @Ficklee , thanks for your reply,

I just tried mathjax and I didn't meet the problem you mentioned. could you please try again or type something else after you insert mathjax expression?

Thanks

**Comment by Ficklee** [comment]
Hi, @shd101wyy thanks for your reply. 
When I typed in this block below.
> Reference frames with respect to which Law I has the analytical form: $$\frac{d^2\vec r}{d^2t}=0$$ are called inertial frames.

The result of KaTex is shown:
![2016-09-24 13 06 20](https://cloud.githubusercontent.com/assets/10938785/18806253/156843e4-8259-11e6-9079-1612a98cd35c.png)

However, the Mathjax result is below:
![image](https://cloud.githubusercontent.com/assets/10938785/18806266/5f75c97a-8259-11e6-9f63-955968ea72f6.png)

Since you don't meet with such an issue I assumed my system lacks some plug-ins or rendering environment. Should I install the Mathjax in local?

Thanks again for your reply

**Comment by shd101wyy** [comment]
No, you don't need to install anything local.  
Could you please try restart atom and then try again?

**Comment by Ficklee** [comment]
@shd101wyy Yes, it worked. Simple and fast solution, thanks.
