### ISSUE TITLE
预览界面什么都不显示

### ISSUE THREAD

**Issue by 914191848** [shd101wyy/markdown-preview-enhanced#1393]
win10 系统，安装后没有任何报错，但是什么也不显示

![2020-05-27_2-32-33](https://user-images.githubusercontent.com/30688308/82937440-be18f580-9fc2-11ea-8cdd-2fbf9cd5be61.jpg)

**Comment by shd101wyy** [comment]
看这个解释

https://github.com/shd101wyy/markdown-preview-enhanced/issues/1380#issuecomment-631341305
