### ISSUE TITLE
Mac OS. With 0.18.2 update preview stopped working

### ISSUE THREAD

**Issue by hsa1970** [shd101wyy/markdown-preview-enhanced#1394]
Reinstalled all from scratch including Atom. 
Using light-theme, looks like something wrong with CSS or other parts with the new update

**Comment by shd101wyy** [comment]
Please see the explanation here

https://github.com/shd101wyy/markdown-preview-enhanced/issues/1380#issuecomment-631341305

**Comment by hsa1970** [comment]
Thanks!
