### ISSUE TITLE
Stopped working since Atom v1.47.0

### ISSUE THREAD

**Issue by johannheyne** [shd101wyy/markdown-preview-enhanced#1398]
My copy stopped working since Atom v1.47.0
- Mac mini 2018
- macOS Mojave
- Atom v1.47.0

When I roll back to Atom v1.46.0 "markdown-preview-enhanced" works again.

**Comment by shd101wyy** [comment]
Yeah please check this upstreaming issue:

https://github.com/shd101wyy/markdown-preview-enhanced/issues/1380#issuecomment-631341305
