### ISSUE TITLE
Hash character get misinterpreted inside code

### ISSUE THREAD

**Issue by mgoldshteyn** [shd101wyy/markdown-preview-enhanced#1409]
~~~ c++
    #include <iostream.h>
    ~~~

Previews as

    <p data-line="133" class="sync-line" style="margin:0;"></p>

    # include <iostream>
    <p class="mume-header " id="include-iostream"></p>

**Comment by shd101wyy** [comment]
Hi @mgoldshteyn , please write your markdown as below

````
```c++
#include <iostream.h>
```
````

Unfortunately `~~~` code block is not well supported. Thanks
