### ISSUE TITLE
plantuml只能使用http渲染吗？

### ISSUE THREAD

**Issue by ponyp** [shd101wyy/markdown-preview-enhanced#1410]
您好，
我在visual studio code中只使用markdown-preview enhanced扩展，不单独装plantuml扩展时，无法渲染plantuml（显示为plantuml源码）。
如果安装了plantuml扩展，在使用markdown-preview enchanced扩展时，必须在plantuml的扩展配置中指定服务器渲染才行（也就是说必须指定服务器的url，否则会报错(No PlantUML server, specify one with "plantuml.server")
![image](https://user-images.githubusercontent.com/45324426/84151232-a303b680-aa95-11ea-80b5-1817ee024089.png)
），若指定了服务器的渲染服务器的url，可以正常渲染
但是plantuml扩展是支持本地渲染（ALT+D）的，不需要服务器渲染
我看到咱们的扩展包里面也引用了plantuml.jar这个文件（~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.5.12/node_modules/@shd101wyy/mume/dependencies/plantuml/plantuml.jar 
），markdown-preview-enhanced支持使用plantuml.jar进行本地渲染吗？

**Comment by shd101wyy** [comment]
MPE 插件和 PlantUML 完全没有任何关系。MPE 的 PlantUML 本身就是本地的。

**Comment by ponyp** [comment]
> MPE 插件和 PlantUML 完全没有任何关系。MPE 的 PlantUML 本身就是本地的。

谢谢大神这么晚了还回复，我想知道我需要启动什么配置才能使用吗？

**Comment by shd101wyy** [comment]
给我看下你的 Markdown 源码我试试？

**Comment by ponyp** [comment]
这一段代码
机器：ubuntu 18.10
vs code：version 1.45
java version 1.8.0_221

下面是文档正文

## 测试MPE PLANTUML
```plantuml
(a)->(b)
```

这段文字在单独（无plantuml扩展）使用MPE的时候，plantuml文字显示为文字

**Comment by shd101wyy** [comment]
![Screenshot from 2020-06-09 21-31-43](https://user-images.githubusercontent.com/1908863/84153560-a2b8ea80-aa98-11ea-99f8-22bf555be329.png)
我的没问题呀，我啥其它插件也没安装。

**Comment by shd101wyy** [comment]
我猜测是不是你打开的预览不是 MPE 的预览呀，你试试右键 MD 文件，然后选择 `Markdown Preview Enhanced: Open Preview to the Side` 命令

**Comment by ponyp** [comment]
单独使用MPE时
![image](https://user-images.githubusercontent.com/45324426/84153788-e57ac280-aa98-11ea-9d4c-5c75518f5b13.png)

**Comment by ponyp** [comment]
你说的对，右键是可以的

**Comment by ponyp** [comment]
我记得装了MPE之后，右上角有两个预览，第一个是VS自带的，第二个是MPE，之前的操作，我都是点的第二个

**Comment by ponyp** [comment]
不好意思，我错了，谢谢您，他两个位置颠倒了，现在第一个是MPE的预览，太感谢您了，这么晚:-)

**Comment by shd101wyy** [comment]
诶客气啦
