### ISSUE TITLE
可以添加对汇编语言代码块的高亮显示吗？

### ISSUE THREAD

**Issue by cliuyang** [shd101wyy/markdown-preview-enhanced#1423]
如图，对汇编语言没有高亮支持。
![image](https://user-images.githubusercontent.com/39078310/85913512-15cbaa80-b868-11ea-98f9-e12d0255e207.png)

**Comment by shd101wyy** [comment]
https://prismjs.com/#supported-languages 这里面的语言是支持的。

**Comment by cliuyang** [comment]
好的

**Comment by gabyx** [comment]
reopen in english please
