### ISSUE TITLE
可以增加一个暗色主题吗

### ISSUE THREAD

**Issue by ocian** [shd101wyy/markdown-preview-enhanced#1426]
黑色配色打开预览之后，觉得眼睛很不适应

我看到有 自定义 css 的选项，这个选项可用的配置位置可以多一点吗，`background-color` 和 `color` 改了之后，代码块没变化，标题和背景色一样，不知道怎么改比较好

**Comment by shd101wyy** [comment]
@ocian 再插件设置里面搜索 `previewTheme` 可以改变预览主题的。
