### ISSUE TITLE
使用ditaa画流程图预览乱码

### ISSUE THREAD

**Issue by izzio** [shd101wyy/markdown-preview-enhanced#1431]
在使用ditaa画流程图时，发现如果内容出现日文会乱码，在寻找问题时发现插件使用的ditaa.jar还是很老的版本，不支持更换渲染出来的svg的字体，希望能够更换新的jar包，满足更多的需要

**Comment by gabyx** [comment]
Please reopen in english.

**Comment by shd101wyy** [comment]
@izzio 抱歉，你也可以自己手动替换下 ditaa 的 jar，但是我不确定能不能用

地点位于 vscode `~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.5.12/node_modules/@shd101wyy/mume/dependencies/ditaa/` 以及 atom `~/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/dependencies/ditaa/`.

---

If you think the ditaa.jar is out of date, then you could replace it yourself, but not guaranteed to work correctly though.

The jar file is located at vscode `~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.5.12/node_modules/@shd101wyy/mume/dependencies/ditaa/` and atom `~/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/dependencies/ditaa/`.
