### ISSUE TITLE
Cannot use more than one '$' in table cell without enabling typesetting.

### ISSUE THREAD

**Issue by withviz** [shd101wyy/markdown-preview-enhanced#1433]
Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

e.g 
```
| A | B |
|--|--|
| $ 10 | Between $10 and $100|
```
Typesetting becomes enabled in Column B

**Comment by tmori3y2** [comment]
Use \$ instead of $.

In MPE, $ is reserved for math expressions, so it needs to be escaped.

**Comment by withviz** [comment]
@tmori3y2 I think I follow but cannot get it to work Your example looks like you are using identical symbols and identical syntax, which I am sure you are not.

**Comment by tmori3y2** [comment]
> Use $ instead of $.
> 
> In MPE, $ is reserved for math expressions, so it needs to be escaped.

Sorry,  I forgot to escape the markdown escape character (\\).

~~~markdown
Use \$ instead of $.
~~~
