### ISSUE TITLE
怎么改高亮颜色

### ISSUE THREAD

**Issue by auroralzone** [shd101wyy/markdown-preview-enhanced#1441]
Atom
可以把黄色改为其他颜色吗?
语法：==文字==
![Snipaste_2020-08-04_16-25-54](https://user-images.githubusercontent.com/42070770/89271394-3957f100-d66f-11ea-8888-52f331402f97.png)

**Comment by shd101wyy** [comment]
自己运行 Markdown Preview Enhanced: Customize Css 命令然后修改 style.less 文件如下

```
.markdown-preview.markdown-preview {

  // modify your style here
  // eg: background-color: blue;
  mark {
    background-color: red !important;
    color: white !important;
  }
}
```

**Comment by auroralzone** [comment]
完美！大佬可否在文档上写详细点，小白真的难搞懂相对应的标签
