### ISSUE TITLE
yarn instead of npm?

### ISSUE THREAD

**Issue by kachkaev** [shd101wyy/markdown-preview-enhanced#1447]
👋 @shd101wyy!

WDYT of using `yarn` instead of `npm` in this repo? I’ve noticed you’ve already switched to `yarn` in [mume](https://github.com/shd101wyy/mume) and [vscode-markdown-preview-enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced), so wonder if there are any blockers to do so in the remaining third repo.

Using `yarn` everywhere should help local dev (use of `yarn link`). Happy to submit a PR if it has a chance of being accepted 🙂

**Comment by shd101wyy** [comment]
Hi @kachkaev Yeah that would be great if we also switch to `yarn` in markdown-preview-enhanced repo.
I don't think there is any blockers.  
Feel free to submit a PR. Thank you! :)
