### ISSUE TITLE
md预览背景色

### ISSUE THREAD

**Issue by everhopingandwaiting** [shd101wyy/markdown-preview-enhanced#146]
可不可以自适应 atom主题的 对应背景色，现在预览是白色的，不是很协调

**Comment by shd101wyy** [comment]
Hi @everhopingandwaiting ,

请查看 [#89](https://github.com/shd101wyy/markdown-preview-enhanced/issues/89)，在 settings 里面可以设置的。

谢谢

**Comment by everhopingandwaiting** [comment]
very  nice!

**Comment by everhopingandwaiting** [comment]
![Uploading image.png…]()



这个插件很赞，就是可不可以 code区域的 代码可以高亮呢 ?

**Comment by shd101wyy** [comment]
closing this issue out

**Comment by everhopingandwaiting** [comment]
这个插件很赞，不过 可不可以 让code区域的 代码 高亮呢？

**Comment by shd101wyy** [comment]
代码本来就有高亮啊？你截张图

**Comment by everhopingandwaiting** [comment]
![ff](https://cloud.githubusercontent.com/assets/6021724/18963904/5a3853ac-86a9-11e6-90f2-84ca6db1e219.png)

**Comment by everhopingandwaiting** [comment]
哎 直接 传图还不行，非得我 出墙才能传图

**Comment by shd101wyy** [comment]
哦哦这个问题，貌似我现在还真解决不了。  
这个是和 [language-gfm`](https://github.com/atom/language-gfm) 挂钩的，以后我找到解决方案了再告诉你吧。

抱歉

**Comment by everhopingandwaiting** [comment]
恩 ，谢谢啦， 最近也想做个atom插件的，在学习呢

**Comment by everhopingandwaiting** [comment]
```
	writePng: (assetsDir, filename, buffer, callback)->
		fs = require('fs')
		fs.writeFile assetsDir+filename, buffer, 'binary',() =>
			console.log('finish clip image')
			callback()

	insertUrl: (url,editor) ->
		editor.insertText('![' + url + '](' + url + ')')
		## 这样可以一键复制 不用再 写 img 标签啦
	deactivate: ->

```
不知道你考不考虑 把这个粘贴图片功能集成到你的插件里，就是 直接把粘贴板的图片直接复制到 当前根目录，然后 再插入 img标签，这样复制图片方便点， 我看你的 内置的那个  功能 有点步骤多

**Comment by shd101wyy** [comment]
这个原来我也考虑过，但是有 API 限制。请查看 [#71](https://github.com/shd101wyy/markdown-preview-enhanced/issues/71)

**Comment by everhopingandwaiting** [comment]
这么晚 还不睡呀，大神

**Comment by shd101wyy** [comment]
没，我这里刚下午。。。晚安啦

**Comment by shd101wyy** [comment]
@everhopingandwaiting 现在可以用 [language-markdown-enhanced](https://atom.io/packages/language-markdown-enhanced) 来显示 code chunk 了。  
顺便 [code chunk doc](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/code-chunk.md) 也更新了，使用了快捷键替代按钮。

**Comment by shd101wyy** [comment]
这个问题我关闭了 :)

**Comment by ChanmoX** [comment]
在VScode中如何改变MPE预览的背景色呢？ 原因如图所示。
![1](https://i.imgur.com/x4UbykS.jpg)

**Comment by shd101wyy** [comment]
@ChanmoX 这个得去插件设置里面把 mermaidTheme 更改下就好了。

**Comment by ChanmoX** [comment]
用这款插件没多久，但是觉得非常好用。但也有一些问题需要请教作者
MPE预览的背景色如何改变  
(PS:我没有任何前段的知识储备，主要是学习嵌入式)

**Comment by shd101wyy** [comment]
@ChanmoX 插件设置里面修改 `previewTheme` 就好了。

**Comment by ChanmoX** [comment]
- PDF(prince) 中文出现乱码，如何解决？
- 可否发一份你已经写好的`style.css` 的模板，有时间我想尝试学习自定义
