### ISSUE TITLE
Wrongly generated html for latex equations

### ISSUE THREAD

**Issue by snippins** [shd101wyy/markdown-preview-enhanced#147]
The below code render correctly in review, but when using "Open with Browser" or export to pdf, some unwanted characters appears. Looking at the generated html, it is likely that a closing tag is generated wrongly.

```
$$
1 + \frac{q^2}{(1-q)}+\frac{q^6}{(1-q)(1-q^2)}+\cdots =
\prod_{j=0}^{\infty}\frac{1}{(1-q^{5j+2})(1-q^{5j+3})},
\quad\quad \text{for $|q|<1$}.
$$
```

Correctly shown in preview:
![test](https://cloud.githubusercontent.com/assets/6032077/18946514/c85fa864-8661-11e6-8c3c-5df2c00a624f.png)

Wrongly shown in chrome:
![test2](https://cloud.githubusercontent.com/assets/6032077/18946673/7a69e15a-8662-11e6-8feb-c87008150c97.png)

Generated html code have an extra `< p="">:`
```
<body class="markdown-preview-enhanced " data-use-github-style  > <p class="sync-line" data-line="2">$$1 + \frac{q^2}{(1-q)}+\frac{q^6}{(1-q)(1-q^2)}+\cdots =
\prod_{j=0}^{\infty}\frac{1}{(1-q^{5j+2})(1-q^{5j+3})},
\quad\quad \text{for $|q|<1$}.$$< p="">
</1$}.$$<></p> </body>  </html>
```

**Comment by shd101wyy** [comment]
Hi @snippins , 

This issue will be fixed in next release.

Thanks

**Comment by shd101wyy** [comment]
@snippins fixed now

Cheers ;)

**Comment by snippins** [comment]
@shd101wyy Thanks you so much! <3
