### ISSUE TITLE
这个什么xxx怎么用啊。我淦，英文打字不麻烦吗？做个中国人，写点中文吧

### ISSUE THREAD

**Issue by JKwarn** [shd101wyy/markdown-preview-enhanced#1510]
找一个用法都这么难吗

**Comment by shd101wyy** [comment]
README 主页上那么大的[简体中文](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/)您是看不懂还是眼睛失明了？？？

**Comment by shd101wyy** [comment]
哦，应该是眼睛失明了，中文也不大好。可惜，祝您早日康复。
