### ISSUE TITLE
plantuml绘图报错

### ISSUE THREAD

**Issue by hjianhao** [shd101wyy/markdown-preview-enhanced#1512]
插件中带的platuml.jar的版本是plantuml.1.2020.26.jar

这个版本在渲染图时直接报错

我替换官方的Latest version就OK了。

错误如下：
An error has occured : java.lang.IllegalArgumentException: source is null
Sometimes if you received an answer, the question might be taken away.
Diagram size: 114 lines / 2328 characters.
PlantUML (1.2020.26) cannot parse result from dot/GraphViz.
Please go to https://plantuml.com/graphviz-dot to check your GraphViz version.
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Default Encoding: UTF-8
Language: zh
Country: CN
PLANTUML_LIMIT_SIZE: 4096
This may be caused by :
- a bug in PlantUML
- a problem in GraphViz
You should send this diagram and this image to
plantuml@gmail.com
or
post to
https://plantuml.com/qa
to solve this issue.
You can try to turn arround this issue by simplifing your diagram.
java.lang.IllegalArgumentException: source is null
net.sourceforge.plantuml.brotli.BrotliInputStream.<init>(BrotliInputStream.java:112)
net.sourceforge.plantuml.brotli.BrotliInputStream.<init>(BrotliInputStream.java:92)
net.sourceforge.plantuml.windowsdot.WindowsDotArchive.extract(WindowsDotArchive.java:76)
net.sourceforge.plantuml.windowsdot.WindowsDotArchive.getWindowsExeLite(WindowsDotArchive.java:95)
net.sourceforge.plantuml.cucadiagram.dot.GraphvizWindowsLite.specificDotExe(GraphvizWindowsLite.java:62)
net.sourceforge.plantuml.cucadiagram.dot.GraphvizWindowsLite.searchDotExe(GraphvizWindowsLite.java:54)
net.sourceforge.plantuml.cucadiagram.dot.AbstractGraphviz.<init>(AbstractGraphviz.java:80)
net.sourceforge.plantuml.cucadiagram.dot.GraphvizWindowsLite.<init>(GraphvizWindowsLite.java:76)
net.sourceforge.plantuml.cucadiagram.dot.GraphvizUtils.create(GraphvizUtils.java:103)
net.sourceforge.plantuml.svek.DotStringFactory.getGraphvizVersionInternal(DotStringFactory.java:291)
net.sourceforge.plantuml.svek.DotStringFactory.getGraphvizVersion(DotStringFactory.java:285)
net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntityInternal(GeneralImageBuilder.java:566)
net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntity(GeneralImageBuilder.java:548)
net.sourceforge.plantuml.svek.GeneralImageBuilder.printEntities(GeneralImageBuilder.java:540)
net.sourceforge.plantuml.svek.GeneralImageBuilder.printGroup(GeneralImageBuilder.java:649)
net.sourceforge.plantuml.svek.GeneralImageBuilder.printGroups(GeneralImageBuilder.java:610)
net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:412)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:118)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:83)
net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:659)
net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:180)
net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:144)
net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:164)
net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:117)
net.sourceforge.plantuml.Run.managePipe(Run.java:379)
net.sourceforge.plantuml.Run.main(Run.java:180)

**Comment by ttw199402** [comment]
遇到了和你一样的问题， 想问一下你是怎么替换官方的Latest version的？下载好官网最新plantuml.jar 后具体怎么操作？

**Comment by hjianhao** [comment]
> 遇到了和你一样的问题， 想问一下你是怎么替换官方的Latest version的？下载好官网最新plantuml.jar 后具体怎么操作？

如果是windows，一般vscode安装在c盘，你搜一下plantuml.jar文件，就可以搜到包含在插件目录下的plantuml.jar，你替换markdown preview enhanced插件目录下的那个plantuml.jar即可。

**Comment by shirayner** [comment]
> > 遇到了和你一样的问题， 想问一下你是怎么替换官方的Latest version的？下载好官网最新plantuml.jar 后具体怎么操作？
> 
> 如果是windows，一般vscode安装在c盘，你搜一下plantuml.jar文件，就可以搜到包含在插件目录下的plantuml.jar，你替换markdown preview enhanced插件目录下的那个plantuml.jar即可。

Thanks! I solved this problem in your way.

**Comment by shd101wyy** [comment]
hmm 我应该就是用的官方最新的 plantuml.jar。
我现在再修复一下试试

**Comment by shd101wyy** [comment]
刚刚从 plantuml.jar 的 MIT Licensed 版本切换到默认的版本了。大家可以再试试。

**Comment by ardorleo** [comment]
谢谢。更新的版已经好用了

**Comment by ttw199402** [comment]
> > 遇到了和你一样的问题， 想问一下你是怎么替换官方的Latest version的？下载好官网最新plantuml.jar 后具体怎么操作？
> 
> 如果是windows，一般vscode安装在c盘，你搜一下plantuml.jar文件，就可以搜到包含在插件目录下的plantuml.jar，你替换markdown preview enhanced插件目录下的那个plantuml.jar即可。

谢谢， 问题已经修复。（tip：下载官网的plantuml.jar不管用的话，请下载tagged version plantuml.1.2020.26.jar）
