### ISSUE TITLE
Add KaTeX "mhchem" extension

### ISSUE THREAD

**Issue by Sushant-Padha** [shd101wyy/markdown-preview-enhanced#1514]
[mhchem](https://mhchem.github.io/MathJax-mhchem/) is a KaTeX extension that adds support for rendering chemical equations and formulae, and physical units using `\ce` and `\pu` tags.

I was able to use it with the ["Markdown All In One"](https://github.com/yzhang-gh/vscode-markdown) VS Code extension, but when I enable the "Markdown Preview Enhanced" extension, it does not work with the enhanced preview.

Markdown Preview screenshot with only "Markdown All In One" enabled
![1](https://user-images.githubusercontent.com/69337374/104016636-b8cc8c00-51dc-11eb-9744-d73a0a9a5674.png)
---
Markdown Enhanced Preview screenshot with "Markdown All In One" and "Markdown Preview Enhanced" extensions enabled
![2](https://user-images.githubusercontent.com/69337374/104016601-ab170680-51dc-11eb-8da0-349f2f1b85a0.png)

---
I get the same result with only "Markdown Preview Enhanced" extension enabled.

I found [this](https://chemistry.meta.stackexchange.com/questions/4029/editor-to-use-on-pc-with-windows-to-format-answers/4031#4031) on how to enable MhChem for MathJax and that does work, but I want to use KaTeX because MathJax is quite slow, and I can't find a way enable MhChem for KaTeX.

This [issue](https://github.com/yzhang-gh/vscode-markdown/issues/520) and [pull request](https://github.com/yzhang-gh/vscode-markdown/pull/521) may be useful.

**Comment by shd101wyy** [comment]
Hi @Sushant-Padha the latest version should support mhchem in katex now. Thanks!
