### ISSUE TITLE
Preview fails with Pandoc error

### ISSUE THREAD

**Issue by davidbenque** [shd101wyy/markdown-preview-enhanced#1519]
Previewing Pandoc Markdown documents has stopped working for me. The preview pane only shows this error: 

```
Error: Command failed: pandoc --from=markdown-raw_tex+tex_math_single_backslash --to=html --katex --citeproc
Unknown option --citeproc.
Try pandoc --help for more information.
```
I have added the following setting
```json
"markdown-preview-enhanced.pandocArguments": "--filter=pandoc-citeproc"
```
but then it just fails with this instead

```
Error: Command failed: pandoc --from=markdown-raw_tex+tex_math_single_backslash --to=html --katex --filter=pandoc-citeproc --citeproc
Unknown option --citeproc.
Try pandoc --help for more information.
````

It could be due to another component, Pandoc or citeproc, but the problem started a few days ago, I think nearly after the last release of this extension. 

Would appreciate any pointers to resolve this.

EDIT: I should add that using Pandoc with citeproc outside of the VSCODE extension works fine.

**Comment by shd101wyy** [comment]
Please upgrade your pandoc to be 2.11

Thank you!

**Comment by davidbenque** [comment]
That did it thank you! (that version is not in the Ubuntu repos yet so didn't see it when I checked for an update)
