### ISSUE TITLE
supporting markdown as output type for codetrunk

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#153]
Right now, the code trunk supports following output format:
- html 
- text 
- png
- none

Suggest to add another option to support markdown format. The markdown-preview-enhanced plugin then parse the markdown into HTML and render in the preview window.

Using markdown instead of HTML will make the code (in code trunk) easier.

**Comment by shd101wyy** [comment]
This is supported now. [#271](https://github.com/shd101wyy/markdown-preview-enhanced/issues/271)
