### ISSUE TITLE
本地图片无法在code-server+浏览器环境显示

### ISSUE THREAD

**Issue by zhsvector** [shd101wyy/markdown-preview-enhanced#1544]
## 测试环境：

- ubuntu 20.04
- [code-server v3.9.1](https://github.com/cdr/code-server)
- firefox

## 问题

本地图片在自带的预览窗口中能显示，图片的HTML

```html
<img src="%E5%A6%82%E6%9E%9C%E8%83%BD%E6%98%BE%E7%A4%BA%E5%87%BA%E6%9D%A5%E5%B0%B1%E5%A4%AA%E5%A5%BD%E4%BA%86.jpeg" alt="" class="" id="image-hash--1876658901">
```

---

在MPE0.5.3插件预览窗口不能显示，图片的HTML

```html
<img src="vscode-resource:///home/osepp/文档/测试/%E5%A6%82%E6%9E%9C%E8%83%BD%E6%98%BE%E7%A4%BA%E5%87%BA%E6%9D%A5%E5%B0%B1%E5%A4%AA%E5%A5%BD%E4%BA%86.jpeg" alt="">
```

## 期待

**非常期待**在MPE预览窗口中能正常显示

![Ubuntu20 04-2021-03-20-16-47-57](https://user-images.githubusercontent.com/28133600/111864556-8ee1d380-899c-11eb-9d4d-9cd82084f67f.png)

**Comment by shd101wyy** [comment]
我猜测可能是中文路径的问题？我找个时间修复下。谢谢！

**Comment by shd101wyy** [comment]
喔喔那是因为你的路径是全局路径，这个是不支持的。 `/path/to/image` 在 MPE 里面表示的是相对于项目根目录的路径。推荐将那个图片拷贝到你的项目路经下再引用。谢谢！
