### ISSUE TITLE
LaTeX formulae can not be rendered when Jupyter extension enabled after the last update.

### ISSUE THREAD

**Issue by integzz** [shd101wyy/markdown-preview-enhanced#1550]
LaTeX formulae can not be rendered when the Jupyter extension enabled after the last update. How can I solve this problem?

![WeChat Screenshot_20210330174342](https://user-images.githubusercontent.com/46377665/112969191-9a44b400-917f-11eb-9e52-bc907e8739b2.png)

**Comment by majiang** [comment]
I'm experiencing the same issue, and:

* I'm not sure it relates to update or Jupyter extension,
* It's only happening with KaTeX, so I'm workarounding with MathJax,
* When exporting as HTML, the only KaTeX-related stuff included is `katex.min.css`.

I hope this additional information helps!

**Comment by integzz** [comment]
I switched to MacOS, it works well.
