### ISSUE TITLE
Two deprecated selectors 

### ISSUE THREAD

**Issue by JonSn0w** [shd101wyy/markdown-preview-enhanced#156]
**Use the `atom-text-editor` tag instead of the `editor-colors` class.**
- In styles/markdown-preview-enhanced.less: Use the `atom-text-editor` tag instead of the `editor-colors` class.  

**Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.**  
- In styles/markdown-preview-enhanced.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
  If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by shd101wyy** [comment]
Hi @JonSn0w , sorry for my late reply.

I am busy these two weeks, so I will fix this issue like 2 weeks later.

Thanks
