### ISSUE TITLE
MathJax not rendered in preview mode

### ISSUE THREAD

**Issue by youqad** [shd101wyy/markdown-preview-enhanced#157]
Hi, 
First of all, thank you so much for this absolutely amazing package ! :-)
It would be - by far - my favorite, if there wasn't a annoying glitch that prevents me from using it : for me, Mathjax isn't rendered in preview mode (whereas KaTex is, but I can't use it, since I heavily resort to unicode characters in math mode) :-( 
I've been tinkering with the source code for hours, trying to figure out why : but nothing worked (I'm a total newbie), that's why I'm turning to you : would you mind working out the issue ? 

Thanks a lot in advance ! 

<img width="1280" alt="capture d ecran 2016-10-08 a 21 29 16" src="https://cloud.githubusercontent.com/assets/8027127/19215441/513fb0e6-8d9e-11e6-8577-1defe50195b0.png">

**Comment by shd101wyy** [comment]
Hey can you please send me your markdown file. My email is shd101wyy@gmail.com.   

Also could you please type something after you open preview and see if the Mathjax renders? Thanks

**Comment by youqad** [comment]
Thanks a lot for helping me! :-)

I have sent you the file (but it's not the only on which Mathjax isn't rendered : for me, it doens't work on any of my .md). 
I've tried what you suggested, but no result :-( 

Thank you again!

**Comment by shd101wyy** [comment]
I will be busy these two weeks as I need to study for the two coming midterms
I will probably fix this issue like two weeks later. 
Sorry for the trouble :(

**Comment by shd101wyy** [comment]
Huh this's wierd. It works fine on my Mac.  
 
![screen shot 2016-10-08 at 10 42 51 pm](https://cloud.githubusercontent.com/assets/1908863/19217757/9cab238a-8da8-11e6-8466-1dc82ae49cf5.png)   

Could show please show me your developer console?  `View -> Developer -> Toggle Developer View`. The `Console` panel on the right bottom corner.  
<img width="1440" alt="screen shot 2016-10-08 at 10 42 25 pm" src="https://cloud.githubusercontent.com/assets/1908863/19217761/afb0f432-8da8-11e6-90c3-804b15476b29.png">  

Thanks

**Comment by youqad** [comment]
Here it is : 

<img width="1280" alt="capture d ecran 2016-10-09 a 05 48 34" src="https://cloud.githubusercontent.com/assets/8027127/19217787/1c4bbd44-8de4-11e6-9690-13f5ea48dc6d.png">

**Comment by shd101wyy** [comment]
<img width="593" alt="screen shot 2016-10-08 at 10 52 11 pm" src="https://cloud.githubusercontent.com/assets/1908863/19217798/dd4c8e3c-8da9-11e6-89ed-561400fd1afe.png">

Click `console` and then give me screenshot :)

**Comment by shd101wyy** [comment]
Apparently right now there are `3` errors

**Comment by youqad** [comment]
<img width="1280" alt="capture d ecran 2016-10-09 a 05 54 21" src="https://cloud.githubusercontent.com/assets/8027127/19217808/ec8b869c-8de4-11e6-9c23-705471805877.png">

**Comment by shd101wyy** [comment]
😔 Sorry I can't find the solution right now. I will let you know once I solve this problem.

**Comment by youqad** [comment]
Fine, I understand :-) 

Don't apologize, I can wait :-) 
Good luck for your exams !

**Comment by youqad** [comment]
It's because of an incompatible package! I've disabled all my packages but yours and the core ones, and it works! It remains for me to discover which one is incompatible (I have to hurry, I've a huge essay to write for tomorrow!) :-)

**Comment by youqad** [comment]
I've found the culprit! Of course, it was this package : https://atom.io/packages/preview-inline !
(I had totally forgotten that I had installed it : that's what happens when you have too many packages, that'll teach me a lesson!)
