### ISSUE TITLE
电子书的作者无法显示

### ISSUE THREAD

**Issue by CraneJen** [shd101wyy/markdown-preview-enhanced#158]
|---
|ebook:
|  title: Title
|  author: Author
|---  

*去掉(|)
按照这样格式写生成的电子书作者是unknown！但是title是没问题的，是格式错误吗？

**Comment by shd101wyy** [comment]
抱歉我文档写错了。应该是  
```
ebook:
    title: Title
    authors: Author
```

是 `authors` 不是 `author` 囧😳

**Comment by CraneJen** [comment]
我也想过，但是就是没试，囧
