### ISSUE TITLE
KaTeX does not render

### ISSUE THREAD

**Issue by mathiasweidinger** [shd101wyy/markdown-preview-enhanced#1589]
Hi,

I am trying to render KaTeX maths expressions in a markdown file.
When opening MPE, the github-icon on the lower left of the preview suggests that it is loading but it never stops and the maths is not typeset correctly. I am running VSCodium on Windows 10, with the Pandoc parser enabled.

![image](https://user-images.githubusercontent.com/56146131/122766231-95386200-d2a1-11eb-8309-1c3a9472b5e5.png)

Can you point me to a solution? Thanks.

**Comment by mathiasweidinger** [comment]
I have enabled Mathjax as a work around for the time being...it works.

**Comment by thstyl2000** [comment]
Problem still exists. Using katex instead of mathjax is a lot faster, especially when editing a document with many math environments. Please reopen!
