### ISSUE TITLE
GitHub style inconsistencies

### ISSUE THREAD

**Issue by danielbayley** [shd101wyy/markdown-preview-enhanced#160]
* [ ] Headings are much bolder on GitHub
* [ ] Inline \`code\` blocks don't match the GitHib `code` blocks

For example:
![preview](https://cloud.githubusercontent.com/assets/7797479/19417411/3247279e-93a4-11e6-8d1f-3c4f79e84bc3.gif)

**Comment by shd101wyy** [comment]
Hi @danielbayley ,

>  Headings are much bolder on GitHub   

Right now you customize css yourself by `Markdown Preview Enhanced: Customize Css` command. 

>  Inline `code` blocks don't match the GitHib code blocks  

I think this issue might be caused by package conflicts. Try to disable other packages to see if the issue still happens.  

Thanks :)

**Comment by danielbayley** [comment]
@shd101wyy Nope, the latter is definitely an issue with this package; I tried disabling _all_ other markdown packages, but the inline \`code\` blocks remain different to GitHub.

Why not use something like _[github-markdown-css](https://github.com/sindresorhus/github-markdown-css)_ instead of trying to manually replicate the styles?

There's also [gfm.css](https://github.com/ungoldman/gfm.css) and probably others…

**Comment by shd101wyy** [comment]
Hi @danielbayley ,

The style inconsistency should be fixed now.

Cheers!

**Comment by danielbayley** [comment]
@shd101wyy Nice one, so headings seem to be fixed (although now slightly larger than **atom/markdown-preview** headings for some reason…) but inline `code` blocks still differ.

![markdown-preview](https://cloud.githubusercontent.com/assets/7797479/19781686/57f6cf4e-9c82-11e6-8966-4aa673b6902e.png)
![enhanced](https://cloud.githubusercontent.com/assets/7797479/19781688/5a5dedb2-9c82-11e6-8d40-8442eb672fee.png)

**Comment by shd101wyy** [comment]
Huhh this is actually very wierd. the `<code>` shows like this on my laptop:  
![screen shot 2016-10-27 at 4 04 08 pm](https://cloud.githubusercontent.com/assets/1908863/19785910/111401f8-9c61-11e6-9779-c429957c353a.png)    
May I have a look of the css style of your code element?   
1. open your file under developer mode.  `View -> Developer -> Open in Dev Mode...`
2. right click at the `<code>` element.  Then click `Inspect Element` from the context menu
3. send me the `Styles` section screenshot here.  

Mine is like this:  
![screen shot 2016-10-27 at 4 04 13 pm](https://cloud.githubusercontent.com/assets/1908863/19786037/981ffc74-9c61-11e6-9d7a-357800fb2712.png)  

Thanks

**Comment by danielbayley** [comment]
Sure, so I'm getting this:
![csstack](https://cloud.githubusercontent.com/assets/7797479/19787406/73ac6cd6-9c9a-11e6-9a51-a3723e14e0ac.png)

**Comment by shd101wyy** [comment]
Seems that you have a section:  
```css
code {
    background: inherit !important;  
}
```
This section overrides the github style (I don't know where it is from).    

Can you try change the atom UI theme and Syntax Theme to see if that helps?

**Comment by shd101wyy** [comment]
Hi @danielbayley , I am pretty sure (100%) that this time the heading and inline code style is correct 😳

**Comment by danielbayley** [comment]
@shd101wyy Ah sorry it _was_ my `styles.less` after all! I tried temporarily removing it, but for some reason changes didn't take effect until I reloaded Atom, which is what threw me off. Cheers!
