### ISSUE TITLE
Any plans to support Obsidian ?

### ISSUE THREAD

**Issue by huzion** [shd101wyy/markdown-preview-enhanced#1607]
I like to use MPE in vscode, and i use [Obsidian](https://obsidian.md/) offen.
the knowledge link feature of Obsidian is easy to use, but Obsidian support for markdown is not as good as MPE, will you plan to support it ?

**Comment by shd101wyy** [comment]
Yes I am planning to migrate https://github.com/0xGG/crossnote to vscode.
