### ISSUE TITLE
Not support wolfram language

### ISSUE THREAD

**Issue by pilgrimlyieu** [shd101wyy/markdown-preview-enhanced#1609]
Hope to support wolfram mathematica language.

[This plugin support wolfram language code block highlight.](https://github.com/weihongliang233/vscode-fenced-code-block-grammar-injection-example)

**Comment by pilgrimlyieu** [comment]
![2021-08-15_13-35-18](https://user-images.githubusercontent.com/80107081/129468322-2ef0419f-3669-4c6c-9c7a-e7c0131ae7eb.png)

Markdown Preview Enhanced plugin ( not support Mathematica commands. Error: spawn mathematica ENOENT)

![2021-08-15_13-35-57](https://user-images.githubusercontent.com/80107081/129468321-be61ae6d-7261-4623-bf34-e6bc4ee5861b.png)

Original Markdown Preview ( Markdown-All-In-One plugin)

**Comment by shd101wyy** [comment]
The syntax highlighting for wolfram family languages will be supported in https://github.com/shd101wyy/mume/pull/237
