### ISSUE TITLE
Feature request: 增添Typora上![](<path_to_image>/<image.jpg>)引用图片方法

### ISSUE THREAD

**Issue by Firestar-Reimu** [shd101wyy/markdown-preview-enhanced#1628]
希望能支持markdown引用本地图片方法：

```
![](<path_to_image>/<image.jpg>)
```
![Screenshot_20211109_103622](https://user-images.githubusercontent.com/65082432/140853200-c5a38670-f223-49d2-b5c6-5b6f5368412e.png)

例如在typora上面是支持的，但是在vscode上面就会显示一片空白（且原有的import貌似不支持在别的路径下插入图片）

![Screenshot_20211109_105337](https://user-images.githubusercontent.com/65082432/140853327-8fd7ae91-e47a-4863-91ee-f1e10c3ca7b4.png)

**Comment by shd101wyy** [comment]
hmmm 插入图片肯定是支持的。是路径错误的问题吗？

**Comment by Firestar-Reimu** [comment]
我没有改过源代码，在typora上显示的出来图片，在vscode上只能显示一行空白

**Comment by shd101wyy** [comment]
你的项目的结构是什么样子的，例如你的这个 markdown 文件相对的 "../images/hello_world_reimu.jpg" 这个图片文件存在吗？

**Comment by Firestar-Reimu** [comment]
存在啊，就是你看到的第一张图里面的博丽灵梦的图啊

```
(base) [firestar@ThinkPad source]$ ls -r ./*
./CNAME

./tools:
index.md

./_posts:
tools  Manjaro-KDE-Installation.md  Hello-World.md

./js:
time-calculator.js

./images:
hello_world_reimu.jpg

./about:
index.md
```

**Comment by shd101wyy** [comment]
![Screenshot from 2021-11-09 19-29-11](https://user-images.githubusercontent.com/1908863/140916286-87189070-0769-448b-888f-610d052ae33a.png)

没问题。我的猜测是你是直接用 vscode 打开了 markdown 文件，而不是整个项目目录。你这么做图片显示不了是因为 vscode 没有读取 workspace 外的文件夹的权限。你只要用 vscode 打开整个项目文件夹就好了。

**Comment by Firestar-Reimu** [comment]
解决了，谢谢！
