### ISSUE TITLE
Feature request: 自动覆盖vscode的预览

### ISSUE THREAD

**Issue by Firestar-Reimu** [shd101wyy/markdown-preview-enhanced#1629]
下载本插件会显示两个预览，左边是本插件的预览，右边是vscode自带预览，比较冗余，希望能自动覆盖vscode的预览

**Comment by Lemmingh** [comment]
Ref: <https://github.com/microsoft/vscode/pull/136273>

**Comment by shd101wyy** [comment]
最新的版本支持了。默认 `markdown-preview-enhanced.hideDefaultVSCodeMarkdownPreviewButtons` 为 `true`。

**Comment by shd101wyy** [comment]
谢谢！
