### ISSUE TITLE
哪些文件后缀在 @import 时支持高亮？

### ISSUE THREAD

**Issue by freshchild** [shd101wyy/markdown-preview-enhanced#1631]
起因是输入 `@import "example.ps1"` 的预览并无高亮，而使用 \`\`\`powershell \`\`\` 的预览高亮正常显示，由于不熟悉前端且 markdown-preview-enhanced 文档似乎并无相关说明而发此 issue。如果这并非正常行为，仅仅是我配置有误的话，烦请指正。

**Comment by JardinHotel** [comment]
[As（作为）代码块](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/file-imports?id=as%ef%bc%88%e4%bd%9c%e4%b8%ba%ef%bc%89%e4%bb%a3%e7%a0%81%e5%9d%97)
`@import "example.ps1" {as="powershell"}`

**Comment by freshchild** [comment]
> [As（作为）代码块](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/file-imports?id=as%ef%bc%88%e4%bd%9c%e4%b8%ba%ef%bc%89%e4%bb%a3%e7%a0%81%e5%9d%97) `@import "example.ps1" {as="powershell"}`

As 原来是这个意思，谢谢
