### ISSUE TITLE
使能 "Print Background", puppeteer 生成的PDF只有背景, 没有内容

### ISSUE THREAD

**Issue by chaojizhang** [shd101wyy/markdown-preview-enhanced#1635]
![image](https://user-images.githubusercontent.com/13182564/145660700-7b79a3e9-84f3-493d-88c9-7b8aac03cd7a.png)

**Comment by lokiodin** [comment]
As a workaround, you click on Open in Browser (Chrome) and print the page (Ctrl+p) and select the option "Background Graphics" in "More settings".

I think it's because the option is not selected when we do the right click on preview mode.

**Comment by chaojizhang** [comment]
@

> As a workaround, you click on Open in Browser (Chrome) and print the page (Ctrl+p) and select the option "Background Graphics" in "More settings".
> 
> I think it's because the option is not selected when we do the right click on preview mode.

I tried and in chrome it print the background. But the theme is not same as the setting. I have changed the "Preview Theme" to "Vue.css", and the theme is working on preview. But in chrome, it didn't work.

**Comment by chaojizhang** [comment]
It worked now. I don't know why.
In extension settings, set preview theme and code block theme. Then, in preview tab, right click to select theme. And then right click "Chrome(puppeteer)" print the pdf as same as preview.

**Comment by weixiaolv** [comment]
"vue theme" need download some resource from internet, such as:

```less
@import url("https://fonts.googleapis.com/css?family=Roboto+Mono|Source+Sans+Pro:300,400,600");
```

as you know, sometimes the network block, and something strange happened:

1. "vue theme" render a view version , after few seconds change to another version view
2. Export pdf missing text as you described

Maybe MPE improve change link to global cdn, or store locally while install
