### ISSUE TITLE
Translation in Korean.

### ISSUE THREAD

**Issue by hwan-ajou** [shd101wyy/markdown-preview-enhanced#1636]
Hi I am a prof. of Ajou university in Korea. 
I want to contribute to translation of the doucment with my students. (https://shd101wyy.github.io/markdown-preview-enhanced/#/)
Please let me know how to. 

Hwan

**Comment by shd101wyy** [comment]
Hello professor @hwan-ajou . I am very glad to hear from you! 
All the docs are currently located at the [docs](https://github.com/shd101wyy/markdown-preview-enhanced/tree/master/docs) directory.  
You could see there are directories for specific languages like `ja-jp`, `zh-cn`, `zh-tw` there.  
Basically you could create a simliar directory like `ko-kr` for Korean language and put the translationed docs there.  
Welcome to submit pull request!
Thank you! Very much appreciated :)

**Comment by hwan-ajou** [comment]
I made first version of translation in forked repository - https://github.com/hwan-ajou/markdown-preview-enhanced/blob/master/docs/ko-kr/.  Please merge it into your project.
