### ISSUE TITLE
大神求教

### ISSUE THREAD

**Issue by wlccgp3** [shd101wyy/markdown-preview-enhanced#166]
## 打开窗口预览问题
*系统设置我打开了临时预览*
### 开启自动预览
1.关闭代码窗口，只留预览窗口，在打开文件预览失效，且单击文件一直打开新窗口
2.第一次打开软件后关闭所有窗口，重复单击同一个文件，一直打开新窗口
### 关闭自动预览后
打开一个文件，然后按快捷键预览，在另外打开一个文件，它直接在预览窗口的右侧打开窗口，而不是在代码窗口的右边

**Comment by shd101wyy** [comment]
不太清楚啊，可能是插件冲突？把其他的插件禁掉试试？

**Comment by shd101wyy** [comment]
最近考试很忙，我有时间了再看看这个 issue。抱歉

**Comment by wlccgp3** [comment]
好的大神

**Comment by shd101wyy** [comment]
这个问题我先关闭了哈 :)
