### ISSUE TITLE
中文文档翻译问题

### ISSUE THREAD

**Issue by pilgrimlyieu** [shd101wyy/markdown-preview-enhanced#1661]
在[缩略](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/markdown-basics?id=缩略)教程处是
```md
_[HTML]: Hyper Text Markup Language
_[W3C]: World Wide Web Consortium
The HTML specification
is maintained by the W3C.
```

这不起作用，实际上应该是`*[HTML]`，在英文文档里这是正确的。（翻了一下其他语言，除了韩语都错了）

**Comment by shd101wyy** [comment]
能不能提个 PR？谢谢
