### ISSUE TITLE
processEnvironment in MathJax doesn't work reliably

### ISSUE THREAD

**Issue by Aetf** [shd101wyy/markdown-preview-enhanced#167]
I use math environments (e.g. `\begin{align} ... \end{align}`) heavily in my course notes to typeset multi-line equations. However the environments are not always correctly rendered and the behavior is quite weird.

Using the following minimal document, here's what I've found
```
Some text

\begin{align}
1 + 1 &= 2 \\\\
1 + 2 &= 3
\end{align}

Other text
$$
a = b \\\\
e = f
$$
```

Situations when the environments are rendered:
- type into another normal math block (like `$$ ... $$` or `$ ... $`) without saving the document
- switch away from the document and switch back (with at least one `$$ ... $$` block in the document)
- first open the document
- switch math engine (with at least one `$ ... $` or `$$ ... $$` block)

Situations when the environments are __not__ rendered:
- after saving the document
- type into normal text area (outside of any math block)

Related system information:
Atom: 1.10.2
markdown-preview-enhanced: 0.8.7
OS: Archlinux with kernel 4.7.6

**Comment by shd101wyy** [comment]
Hi @Aetf ,

you have to type your math expressions inside `$$...$$` or `$...$`.     

So the following is not supported.  
```
Some text

\begin{align}
1 + 1 &= 2 \\\\
1 + 2 &= 3
\end{align}

Other text
```

So you should write `begin{align}` and `end{align}` inside `$...$` or `$$...$$`  
For example:  
```
$$
\begin{align}
1 + 1 &= 2 \\\\
1 + 2 &= 3
\end{align}
$$
```

Thanks

**Comment by Aetf** [comment]
That's odd. From the MathJax [documentation](http://docs.mathjax.org/en/latest/options/tex2jax.html): 

> `processEnvironment: true`
> When true, tex2jax looks not only for the in-line and display math delimiters, but also for LaTeX environments (`\begin{something}...\end{something}`) and marks them for processing by MathJax. When false, LaTeX environments will not be processed outside of math mode.

Also, in the [code](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/mathjax-wrapper.coffee#L27), MathJax is configured to enable `processEnvironment`.

Actually that's why I find this package promising for my note taking. I checked the code and was glad to find that this is the only package that has process environment is enabled.

**Comment by shd101wyy** [comment]
No I only parse the code within `$...$` and `$$...$$`.

**Comment by shd101wyy** [comment]
I see what you mean.  
seems [this line](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/markdown-preview-enhanced-view.coffee#L745) will processEnviroment but [this line](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/markdown-preview-enhanced-view.coffee#L747) won't. That's the cause of the issue that you mentioned.   
However, I intend to support math only within `$...$` and `$$...$$`.  I might change it in next release.

**Comment by Aetf** [comment]
I see. For now I have to turn to other solutions since otherwise there are too many changes to my notes.

But I do love your package, looking forward to using it in the future. Thank you for prompt reply!
