### ISSUE TITLE
Uncaught exception caused by - [ref]: target syntax

### ISSUE THREAD

**Issue by DanielMahu** [shd101wyy/markdown-preview-enhanced#168]
The following snippet causes an instant exception in the preview pane:

```
- [l1]: l1ref
```
![screenshot 2016-10-20 17 40 12](https://cloud.githubusercontent.com/assets/11088419/19564514/7e5f3f90-96ec-11e6-9d31-5eb8385b005a.png)

**Comment by shd101wyy** [comment]
huhh it's a bug. I will fix it in next release. Sorry for the trouble.

**Comment by shd101wyy** [comment]
seems you shouldn't nest reference inside a list item

**Comment by shd101wyy** [comment]
Hi @DanielMahu , 

This issue should be fixed now :)

Cheers!

**Comment by shd101wyy** [comment]
closing this issue :)

**Comment by DanielMahu** [comment]
Thanks a lot, @shd101wyy ! sorry for the late reply
