### ISSUE TITLE
KaTex的下标语法显示不一致

### ISSUE THREAD

**Issue by UPIMMUNITY** [shd101wyy/markdown-preview-enhanced#1680]
**例如官方示例 $\sum_{\substack{0<i<m\\0<j<n}}$，预览时下标会显示在右下侧而非正下方**

 实际显示
![image](https://user-images.githubusercontent.com/77432836/162557724-900b600d-eace-4289-abb1-75fbeca88e86.png)

示例
![image](https://user-images.githubusercontent.com/77432836/162557662-080a618a-ca71-4a50-b375-c1abc6bde309.png)

**Comment by pilgrimlyieu** [comment]
应该是 **displaystyle** 与 **textstyle** 的区别，试试 `$\displaystyle\sum_{\substack{0<i<m\0<j<n}}$`

详情可见 [KaTeX 文档](https://katex.org/docs/supported.html#style-color-size-and-font)

**Comment by UPIMMUNITY** [comment]
已解决，感谢👍
