### ISSUE TITLE
Unsupport equationNumbers in MathJax

### ISSUE THREAD

**Issue by zhuangbo** [shd101wyy/markdown-preview-enhanced#169]
Is there any way to support 'equationNumbers'?

**Comment by shd101wyy** [comment]
Hi @zhuangbo ,

Sorry auto numbering is not supported in preview. But you can number equation manually by using `\tag{number}`   
For example:  
![screen shot 2016-10-25 at 4 59 58 pm](https://cloud.githubusercontent.com/assets/1908863/19705876/9c57bb94-9ad4-11e6-80cb-2771a84cc1ca.png)  
Hope this helps :)

Thanks

**Comment by zhuangbo** [comment]
Get it! Thank you so much!
