### ISSUE TITLE
Invalid Markdown file error with new documents

### ISSUE THREAD

**Issue by tomyun** [shd101wyy/markdown-preview-enhanced#17]
When document was not saved to a file yet, "Invalid Markdown file" error would appear. You could simply reproduce it by triggering preview on any new blank document tabs.

If previewing non-existing file was tricky, it'd be still less confusing to have a message like "Markdown file should be saved first.".

**Comment by shd101wyy** [comment]
@tomyun yea make sense. I will change it in the next version.

Thanks ;)

**Comment by shd101wyy** [comment]
Did you find anything else that is bad and do you have any request for new features?

**Comment by shd101wyy** [comment]
Hi @tomyun , I have changed the error message. Thanks for your advice ;)

**Comment by tomyun** [comment]
Sounds great!

I found `markdown-katex` very useful especially with advanced features like 2-way scrolling. It'd be very nice if it could support syntax highlighting for math equations.

**Comment by shd101wyy** [comment]
closing this old issue now
