### ISSUE TITLE
MathJax can not render inline equations properly with delimiter [["\\(", "\\)"]]

### ISSUE THREAD

**Issue by Daniel-UCAS** [shd101wyy/markdown-preview-enhanced#170]
I change Katex to MathJax to render equations, at the same time replace the default [["$", "$"]] with [["\\(", "\\)"]] as delimiter. However, part of the equations can not be rendered as expected.
Original code:
`\\( T_n(t)=e^{-a^2\lambda_n t} \\) , \\( u(x,t)=\Sigma_{n=1}^\infty B_n sin(\sqrt{\lambda x})e^{-a^2\lambda t} \\)，\\( u(x,0)=\phi(x) \\)`
Rendered results
\( T_n(t)=e{-a2\lambda_n t} \) ,  \( u(x,t)=\Sigma_{n=1}^\infty B_n sin(\sqrt{\lambda x})e{-a2\lambda t} \)，u(x,0)=ϕ(x)
I am not sure where the problem locates. It seems MathJax works for simple equations, but fails with complicated ones.  Katex will not identify this delimiter, even for the last equation.
BTW, thank you for this nice tool.

**Comment by shd101wyy** [comment]
Works for me...   
<img width="439" alt="screen shot 2016-10-24 at 12 29 37 pm" src="https://cloud.githubusercontent.com/assets/1908863/19656430/95a01aca-99e5-11e6-8464-d361eebcb336.png">   
<img width="767" alt="screen shot 2016-10-24 at 12 29 44 pm" src="https://cloud.githubusercontent.com/assets/1908863/19656433/983ec40c-99e5-11e6-91d1-75cced4522ea.png">   

You need to restart atom after you change the delimiters...

Thanks

**Comment by Daniel-UCAS** [comment]
Yes, you are right, I have used wrong "\\(" and "\\)" in the editor instead of "\(" and "\)" , the delimiter [["\\(", "\\)"]] works fine. Thank you for the quick response.
