### ISSUE TITLE
www.jsdelivr.com又被墙了，插件文档看不了了。

### ISSUE THREAD

**Issue by quchunguang** [shd101wyy/markdown-preview-enhanced#1704]
不是一次了，换了这个不靠谱的CDN吧

**Comment by drrui** [comment]
是的。。。生成的网页ppt，打不开。。。本地的文档都显示空白，需要翻墙才行。。。呜呜呜呜呜，咋办

**Comment by shd101wyy** [comment]
有啥可用的替代推荐不。。。:joy:

**Comment by Oldog** [comment]
> 是的。。。生成的网页ppt，打不开。。。本地的文档都显示空白，需要翻墙才行。。。呜呜呜呜呜，咋办

有离线版应该比较好，直接把需要的库打包，依赖改成本地。

**Comment by shd101wyy** [comment]
先在可以设置：

```
"markdown-preview-enhanced.jsdelivrCdnHost": "fastly.jsdelivr.net",
```

这个貌似没有被墙。这个 issue 我先关闭了哈。
