### ISSUE TITLE
TOC function is useful ,but can we add a 'scope' or 'untoc'?(可以有一个toc的范围选择,或者类似于untoc的标签来排除那些不希望加入toc的标题码)

### ISSUE THREAD

**Issue by xionchen** [shd101wyy/markdown-preview-enhanced#171]
厉害了我的哥,这个东西确实是我用过最好用的markdown 插件!
TOC function is useful ,but can we add a 'scope' or 'untoc' to  to remove those titile which User may not want add to toc?
TOC的功能很实用,但是有的标题不希望它出现在toc中,可以有一个toc的范围选择,或者类似于untoc的标签来实现这个功能吗?

**Comment by shd101wyy** [comment]
@xionchen 好的 word ge。下个版本就支持。:)

**Comment by shd101wyy** [comment]
@xionchen 好了，现在可以在标题上方插入 `<!-- untoc -->` 来排除标题。我还添加了 `depthTo` 和 `depthFrom`。具体查看 [toc 文档](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/toc.md)

**Comment by shd101wyy** [comment]
closing this issue
