### ISSUE TITLE
Project Development Discussion & Advice

### ISSUE THREAD

**Issue by shd101wyy** [shd101wyy/markdown-preview-enhanced#172]
Hi guys,  

I am planning to remove the `run` and `all` button for code chunks and use keyboard shortcut  instead.    
![screen shot 2016-10-26 at 12 00 47 am](https://cloud.githubusercontent.com/assets/1908863/19713878/480741c8-9b0f-11e6-881e-5f9eb95582fa.png).   

I am planning to use <kbd>shift-enter</kbd> to run one selected (where your cursor is at) code chunk and <kbd>ctrl-shift-enter</kbd> to run all code chunk.   

Do you guys agree with this proposal or you have any other ideas?  

Thanks.

**Comment by shd101wyy** [comment]
There are several reasons why I want to remove these two buttons.  

1. When I am trying to hide the code chunk like   
<pre>
\`\`\`{node hide:true}
console.log('hello world')
\`\`\`
</pre>
currently the code chunk will still be displayed in the preview because I have to show `run` and `all` buttons; otherwise there is no way to execute the code.   
2. keyboard shortcut is more intuitive and fast compare to clicking button from my point of view.

**Comment by shd101wyy** [comment]
I will remove `run` and `all` buttons if nobody disagrees with me by the end of this weekend.  
Hopefully a new version will be released this weekend. (finally finished all my midterms)
Thanks :)

**Comment by shd101wyy** [comment]
NVM I DECIDE TO REMOVE `run` and `all` buttons

**Comment by StefanoCecere** [comment]
hi @shd101wyy i just checked 0.8.8 but i can't run the chunks anymore!
the shortcuts don't work.. the readme doen'st say well how to run them... uhmmm

**Comment by shd101wyy** [comment]
@StefanoCecere sorry for the change and trouble.  
If you want I can put those buttons back in next version...

**Comment by StefanoCecere** [comment]
Well I guess I had good reasons to remove the buttons!!

Anyway when the shortcuts wors and you know them, it's faster!

Maybe novice users would prefer buttons. I'll use shortcuts from now on. 

code chunks are one of the more powerful functions seen in Text editor.

**Comment by shd101wyy** [comment]
In the end, I put those two buttons back 😳 , but they won't show up unless hovered. (Won't be displayed for hidden code chunk).  
I also added `stdin` option.        
Anyway closing this issue out.

**Comment by StefanoCecere** [comment]
huge improvement 0.8.9! mighty @shd101wyy

**Comment by shd101wyy** [comment]
closing this issue :)
