### ISSUE TITLE
导入文件无法显示

### ISSUE THREAD

**Issue by auroralzone** [shd101wyy/markdown-preview-enhanced#1736]
@import "test.js"导入文件无法显示，`py、csv、png`可以正常
<img width="530" alt="image" src="https://user-images.githubusercontent.com/42070770/187625046-83146b1c-d8e9-47d4-9e9a-ef5c8ff8f7a0.png">

**Comment by shd101wyy** [comment]
这样才行，

```
@import "test.js" {code_block=true}
```

要不然默认会插入为 `<script>..</script>`

**Comment by shd101wyy** [comment]
https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/file-imports?id=%e6%94%af%e6%8c%81%e7%9a%84%e6%96%87%e4%bb%b6%e7%b1%bb%e5%9e%8b

**Comment by auroralzone** [comment]
OK，可以了，感谢巨佬
