### ISSUE TITLE
不支持emoji？

### ISSUE THREAD

**Issue by foregather** [shd101wyy/markdown-preview-enhanced#176]
:tada:

**Comment by shd101wyy** [comment]
Hi @foregather ,

问题重复 [#98](https://github.com/shd101wyy/markdown-preview-enhanced/issues/98)。
请使用 [autocomplete-emojis](https://atom.io/packages/autocomplete-emojis) 插件。

谢谢

**Comment by shd101wyy** [comment]
@foregather `:smile` 这种写法现在也支持了，可以在插件设置中禁用。
