### ISSUE TITLE
plantuml图片导出

### ISSUE THREAD

**Issue by leexusky** [shd101wyy/markdown-preview-enhanced#177]
![image](https://cloud.githubusercontent.com/assets/16282049/19795034/54acc298-9d0a-11e6-8b59-922911f8095a.png)
当到处成HTML或者PDF时，plantuml生成的图片就提示please wait till preview finishes rendering graph
应该是没有等图片生成完就导出结束了吧。这个bug还挺影响使用的

**Comment by leexusky** [comment]
补充一下，如果对uml图片进行修改，那么第一次导出或者直接用浏览器浏览是没有问题的，但是第二次就不行了，应该是第二次导出时没有重新生成图片

**Comment by shd101wyy** [comment]
得等它运行完才可以。

**Comment by shd101wyy** [comment]
你每次修改代码，preview 应该都会重新生成图像，得等到图像生成完了才可以

**Comment by leexusky** [comment]
图像生成完了，导出会有这个问题
比如这个场景：
我编写plantuml，完成后右侧生成预览图片，能够正常显示。
这时候我导出HTML，也没有问题。
这是不做任何修改，再次导出HTML，就没有图片了，提示的就是图片那句话

**Comment by shd101wyy** [comment]
嗯我也觉得 plantuml 不太好因为运行太慢了（我觉得我不应该做成实时的），我以后可能会删掉这个功能，或者直接移到 code chunk。很抱歉造成现在这个问题。

**Comment by leexusky** [comment]
不要删除啦~~~~(>_<)~~~~，我就冲着Markdown里能直接写plantuml用的。实时预览还真没觉得慢，就是导出的时候遇到些问题。
还是会继续支持你~~加油~

**Comment by shd101wyy** [comment]
你稍等啊，我看看一个小时里能不能 fix。不能的话我就睡觉了先。。。

**Comment by leexusky** [comment]
不忙不忙~给你点赞

**Comment by shd101wyy** [comment]
我突然发现不止 plantuml，其他的 graph 也有问题了😳 。。。
多谢你及时发现了这个问题，我赶紧去查查。。。

**Comment by leexusky** [comment]
哈哈

**Comment by shd101wyy** [comment]
@leexusky 修好了。顺便你也可以用 code chunk 来画 plantuml 的图，这样的话就不是实时的了。   
（code chunk 就是运行自定义的程序和代码）
<pre>
```{puml cmd:"java", args: ["-Djava.awt.headless=true", "-jar", "~/Desktop/plantuml.jar", "-pipe", "-tsvg", "-charset", "UTF-8"], output:"html", stdin:true, id:"iutaxxtf", hide:true}
@startuml
A --> B
@enduml
```
</pre>  

把 `-jar` 后面的路径改为你的 `plantuml.jar` 的路径，`A --> B` 改为你想要的内容，然后鼠标移动到 code chunk, <kbd>shift-enter</kbd> 就可以运行了。  
如果你不想隐藏 code clock，可以把 `hide:true` 给删掉。具体信息请查看 [code chunk](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/code-chunk.md)

**Comment by shd101wyy** [comment]
才发现这个 issue 其实已经已经存在了一个多月了也没有人发现过。这次多谢你啦～  
  
晚安😴

**Comment by leexusky** [comment]
![1197b6fcde1ff569dff2770d4c2c2e65](https://cloud.githubusercontent.com/assets/16282049/19796720/e7e6c4b0-9d18-11e6-8536-67bffc7bda79.jpg)

**Comment by shd101wyy** [comment]
closing this issue out

**Comment by shd101wyy** [comment]
@leexusky `0.12.4` 大幅度提升了 PlantUML 渲染速度
