### ISSUE TITLE
导出pdf后，表格标题文字的颜色跟背景一样

### ISSUE THREAD

**Issue by CraneJen** [shd101wyy/markdown-preview-enhanced#18]
[md.pdf](https://github.com/shd101wyy/atom-markdown-katex/files/240036/md.pdf)

**Comment by shd101wyy** [comment]
Hi @CraneJen ， 非常感谢发现这个 bug。

应该已经修好了。 `~(*_*)~`

谢谢

**Comment by CraneJen** [comment]
@shd101wyy 很快啊！ 请问代码块有方法高亮显示吗？

**Comment by shd101wyy** [comment]
@CraneJen 应该用 markdown 自带的 ``` 就可以。
例如 
![snip20160428_1](https://cloud.githubusercontent.com/assets/1908863/14901147/9caad242-0d59-11e6-94cf-bbda189355a1.png)
