### ISSUE TITLE
Add ability to preview unsaved buffers

### ISSUE THREAD

**Issue by danielbayley** [shd101wyy/markdown-preview-enhanced#180]
Is there a particular reason why it can't preview unsaved markdown?

**Comment by shd101wyy** [comment]
Hi @danielbayley ,

There are several reasons why the markdown file is required to be saved first:

1. PDF and HTML file generation requires the file path in order to be generated under the same directory.
2. image relative path requires file path.  
for example  
```markdown
![test](../images/test.png)
```
etc  

Thanks

**Comment by danielbayley** [comment]
@shd101wyy 

1. PDF and HTML file generation is, I would say, a much less frequent use case than just wanting a quick markdown preview, and so not sure if that alone should completely prevent it from working for unsaved files… The regular _markdown-preview_ does preview unsaved files also.

2.  Why not just fall back to something like `atom.project.getPaths()[0]`?
