### ISSUE TITLE
Feature Request: Set the preview theme sync to the system color theme or match the editor color theme.

### ISSUE THREAD

**Issue by ThymeNK** [shd101wyy/markdown-preview-enhanced#1804]
You may know another similar extension called **Markdown Preview Github Styling**. It has the options to change the preview theme sync to the system color theme. It's really convenient to help change the theme automatically when the system turns to dark mode every night. This way, there's no need to manually switch every day. Wish you can improve that experience. Love your extension. d(^_^o)
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/79644707/230817086-1ed76485-fe65-4b84-831d-d792e6cc35f9.png">

**Comment by shd101wyy** [comment]
Supported now. You can now set:

```
  "markdown-preview-enhanced.previewColorScheme": "systemColorScheme",
```

or

```
  "markdown-preview-enhanced.previewColorScheme": "editorColorScheme",
```

or

```
  "markdown-preview-enhanced.previewColorScheme": "selectedPreviewTheme",
```

**Comment by ThymeNK** [comment]
Really appreciate. ~\(≧▽≦)/~
