### ISSUE TITLE
修改 导出html (cdn host) 时, html文件的cdn path 

### ISSUE THREAD

**Issue by Offsaying** [shd101wyy/markdown-preview-enhanced#1819]
请问 导出html (cdn host) 此时,该html文件的
cdn path (默认认:https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css) 
要如何更改此路径?通过json改该怎么写呢,谢谢!

**Comment by shd101wyy** [comment]
先在支持了，可以在插件中设置:

```
  "markdown-preview-enhanced.jsdelivrCdnHost": "fastly.jsdelivr.net",
```
