### ISSUE TITLE
生成TOC带有Katex时出现问题

### ISSUE THREAD

**Issue by zhwuyuhehe** [shd101wyy/markdown-preview-enhanced#1823]
![image](https://github.com/shd101wyy/markdown-preview-enhanced/assets/47172382/281cc607-0c87-416a-8b02-e6e1d6267261)
### 他会一直尝试更新目录，反复out of data与up to data

**Comment by zhwuyuhehe** [comment]
大概排查了一下问题。应该是因为VScode在自动保存时，会把`\`保存成`\\`，但是目录内只有一个反斜杠，导致了目录内容不一致，插件就会再次更新目录。因此陷入了死循环。

**Comment by shd101wyy** [comment]
谢谢。我这周修一下。

**Comment by shd101wyy** [comment]
> 应该是因为VScode在自动保存时，会把\保存成\\

hmm 我尝试了下我的 vscode，发现保存是没有把 `\` 保存成 `\\`。我猜测是不是你用了什么 formatter 的插件导致了这种问题？
