### ISSUE TITLE
About the font 可以切换字体吗？

### ISSUE THREAD

**Issue by MagShadow** [shd101wyy/markdown-preview-enhanced#183]
Can I change the font I want to use when generating the PDF files?
我可以换字体吗？中文英文都可以。

**Comment by shd101wyy** [comment]
Hi @MagShadow , yes it is possible. 
`cmd-shift-p` then choose `Markdown Preview Enhanced: Customize Css`. It will open `style.less` for you.  
Inside `.markdown-preview-enhanced-custom` section, add the following code:   
```less  
@font-face {
  font-family: "{font_name}";
  src: url("{font_path}");
}
font-family: "{font_name}", sans-serif;
```
for exampe:  

![screen shot 2016-11-03 at 1 45 01 pm](https://cloud.githubusercontent.com/assets/1908863/19980443/0637acc4-a1cc-11e6-809b-2a03b97b1db2.png)

谢谢

**Comment by shd101wyy** [comment]
或者直接 `font-family: blablabla;` 如果你想用系统自带的字体。

**Comment by MagShadow** [comment]
OK I have successfully change the Fonts.
And what's more I want to ask is **Can I Use the different fonts and different place?**For example the Header and the Passage I hope them to be different.
I know this may disturb you but I still want to know about that.
Or you can tell me where could i learn about such knowledge. I'm quite a freshman in such area.THANKS A LOT!

**Comment by shd101wyy** [comment]
这个你得写 less(css）了，例如你想要只改变 headings，就只把 `font-family: blabla;` 加入 `h1, h2, h3, h4, h5, h6`。例如:
```less
h1, h2, h3, h4, h5, h6 {
    font-family: 'Anton';
}
```

**Comment by shd101wyy** [comment]
paragraph 的话就是 
```less
p {
    font-family: 'Anton';
}
```
