### ISSUE TITLE
列表的自动补全有问题

### ISSUE THREAD

**Issue by MagShadow** [shd101wyy/markdown-preview-enhanced#184]
当我写下
```markdown
+ 这是一行示例
```
在行尾按下空格，它会自动补全出现两个+ +，即成为二级列表
如这样：
```markdown
+ 这是一行示例
+ +
```
检查了一下，和md相关的，只有系统的markdown语法支持和本插件开了

**Comment by shd101wyy** [comment]
@MagShadow 我没有遇到过这个问题。我试了下 Atom 没有发生你所说的问题。试试用 `*` 代替 `+`？

**Comment by shd101wyy** [comment]
\newpage
# Introduction
The intermediate report includes the algorithm solving travelling salesman problem, using `Gurobi` doing the linear optimize work and the parallel branch and bound algorithm.   

## TSP
We target at Traveling Salesman (TSP) Problem as start point.  The traveling salesman problem is a problem in graph theory requiring the most efficient (i.e., least total distance) Hamiltonian cycle a salesman can take through each of n cities. The problem then consists of finding the shortest tour which visits every city on the itinerary.  

The notations of TSP are as follows:  
<img src="http://api.gmath.guru/cgi-bin/gmath?G%20%3D%20%5Clangle%20V%2C%20E%5Crangle"/> is a positive weight complete graph, where
<img src="http://api.gmath.guru/cgi-bin/gmath?V%3D%5C%7Bv_i%5C%7D%20%281%20%5Cle%20i%20%5Cle%20n%29"/> is a vertex set.  
<img src="http://api.gmath.guru/cgi-bin/gmath?E%3D%5C%7B%28v_i%2C%20v_j%29%20%7C%20v_i%2C%20v_j%20%5Cin%20V%20%5Ctext%7B%20and%20%7D%20i%20%5Cneq%20j%20%5C%7D"/> is a set of undirected edges.   
<img src="http://api.gmath.guru/cgi-bin/gmath?d_%7Bij%7D%3D%28v_i%2C%20v_j%29"/> is positive weight of edges.    

<img src="http://api.gmath.guru/cgi-bin/gmath?%5Cint_%7B0%7D%5E%7B100%7D%20sin%28x%29%20dx%20+%20%5C%24%20123"/> is cool

<img src="http://api.gmath.guru/cgi-bin/gmath?A%20%3D%20%5Cbegin%7Bbmatrix%7Dd_%7B11%7D%20%26%20%5Cdots%20%26%20d_%7B1n%7D%20%5C%5C%5Cvdots%20%26%20%5Cddots%20%26%20%5Cvdots%20%5C%5Cd_%7Bn1%7D%20%26%20%5Cdots%20%26%20d_%7Bnn%7D%5Cend%7Bbmatrix%7D"/> is an adjacency matrix of graph <img src="http://api.gmath.guru/cgi-bin/gmath?G"/>. Among them,
<div align="center" style="margin-bottom: 16px;"><img src="http://api.gmath.guru/cgi-bin/gmath?d_%7Bij%7D%20%3D%20%5Cbegin%7Bcases%7D%20%3E%200%20%5Ctext%7B%20and%20%7D%20d_%7Bij%7D%20%3D%20d_%7Bji%7D%20%26%20i%20%5Cneq%20j%20%5C%5C+%5Cinfty%20%26%20i%20%3D%20j%5Cend%7Bcases%7D"/></div>    
<div align="center" style="margin-bottom: 16px;"><img src="http://api.gmath.guru/cgi-bin/gmath?A_%7Bij%7D%20%3D%20%5Cbegin%7Bcases%7D%20d_%7Bji%7D%20%26%20%28v_i%2C%20v_j%29%20%5Cin%20E%28G%29%20%5C%5C%20%20+%5Cinfty%20%26%20%5Ctext%7Bothers%7D%20%5Cend%7Bcases%7D"/></div>    

We also define <img src="http://api.gmath.guru/cgi-bin/gmath?x_%7Bij%7D"/> as logic variable that identifies whether the edge <img src="http://api.gmath.guru/cgi-bin/gmath?%28v_i%2C%20v_j%29"/> belongs to search path or not.
<div align="center" style="margin-bottom: 16px;"><img src="http://api.gmath.guru/cgi-bin/gmath?x_%7Bij%7D%20%3D%20%5Cbegin%7Bcases%7D1%20%26%20%28v_i%2C%20v_j%29%20%5Ctext%7B%20belongs%20to%20search%20path%7D%20%5C%5C0%20%26%20%5Ctext%7Bothers%7D%5Cend%7Bcases%7D"/></div>  

Then our solution to calculate the minimum cost cyclic route (<img src="http://api.gmath.guru/cgi-bin/gmath?MinCR"/>) in graph <img src="http://api.gmath.guru/cgi-bin/gmath?G"/> would become:  
<div align="center" style="margin-bottom: 16px;"><img src="http://api.gmath.guru/cgi-bin/gmath?MinCR%20%3D%20min%20%5Csum_%7Bi%3D1%7D%5E%7Bn%7D%5Csum_%7Bj%3D1%7D%5E%7Bn%7D%20d_%7Bij%7Dx_%7Bij%7D%20%5Ctag%7B1%7D"/></div>

In order not to generate sub loop by using the formula <img src="http://api.gmath.guru/cgi-bin/gmath?%281%29"/>, it needs to add the following constraints:  
<div align="center" style="margin-bottom: 16px;"><img src="http://api.gmath.guru/cgi-bin/gmath?%5Cbegin%7Bcases%7D%20%20%5Csum_%7Bj%20%5Cneq%20i%7D%20x_%7Bij%7D%20%3D%202%20%26%20i%2C%20j%5Cin%20%5C%7B1%2C%202%2C%20...%2C%20n%5C%7D%20%5C%5C%5Csum_%7Bi%2C%20j%20%5Cin%20S%7D%20x_%7Bij%7D%20%5Cle%20%7CS%7C%20-%201%20%26%202%20%5Cle%20S%20%5Cle%20n-2%2C%20S%20%5Csubset%20%5C%7B1%2C%202%2C%20...%20n%5C%7D%5Cend%7Bcases%7D%20%5Ctag%7B2%7D"/></div>  

The first condition ensures that each vertex in search path just has two and only two edges; the second condition makes sure the graph <img src="http://api.gmath.guru/cgi-bin/gmath?G"/> has no sub loop. If the graph <img src="http://api.gmath.guru/cgi-bin/gmath?G"/> has some sub loops, then the number of edges in all sub loops equals to the number of vertices[2].

**Comment by MagShadow** [comment]
@shd101wyy 很抱歉这么急地提问，昨天我用的时候可能由于刚刚更新 加载项不太对，今日再测试已经可以了，谢谢！很感谢你这么热心的解答！

**Comment by shd101wyy** [comment]
那这个 issue 我就给关闭了哈😄
