### ISSUE TITLE
How to remove the horizontal rules under H1 and H2?

### ISSUE THREAD

**Issue by abhayghatpande** [shd101wyy/markdown-preview-enhanced#185]
Is there any way to remove the horizontal rules for "#" and "##"? I prefer to have the "clean" look.

Thanks.

**Comment by abhayghatpande** [comment]
ok. solved it by adding `border-bottom: none` in the `styles.less`. thanks.

**Comment by wooden-utensil** [comment]
Cool, is there a way to do this in GitHub markdown, README.md etc. This thing is really annoying me: 
![annoying line](https://user-images.githubusercontent.com/48314599/56858800-d1265400-69c3-11e9-8af6-4bda31d29d7c.PNG)
In fact I can make my own line:

________

See?

By doing this:
```markdown

-------

```
or
```markdown

_______

```

**Comment by Ayush-Suman** [comment]
+1

**Comment by KronosTheLate** [comment]
+1

**Comment by stepanjakl** [comment]
@mekb-turtle +1

**Comment by krishna2803** [comment]
+1

**Comment by mekb-turtle** [comment]
wait what?

**Comment by basicfeatures** [comment]
+1

**Comment by mekb-turtle** [comment]
hello me from 3 years ago

**Comment by matthewelmer** [comment]
bro why are these ugly lines still a thing they look like doodoo

**Comment by mekb-turtle** [comment]
---

these lines are way more solid than h1/h2

#

##

**Comment by kikoooooooo** [comment]
+1

**Comment by kikoooooooo** [comment]
I found a compromise that uses `<summary>`
![image](https://user-images.githubusercontent.com/69651056/178627360-0b885641-ffb3-4799-8eb1-7131a4d89f42.png)
![image](https://user-images.githubusercontent.com/69651056/178627391-21b1948f-02ad-47b3-9723-126f36e164bc.png)
^h1 tag no underline

**Comment by AradhanaChhabra** [comment]
but then there's a bullet point added to the heading

> I found a compromise that uses `<summary>` ![image](https://user-images.githubusercontent.com/69651056/178627360-0b885641-ffb3-4799-8eb1-7131a4d89f42.png) ![image](https://user-images.githubusercontent.com/69651056/178627391-21b1948f-02ad-47b3-9723-126f36e164bc.png) ^h1 tag no underline

**Comment by kikoooooooo** [comment]
You can use `list-style-type: none;` but [apparently](https://stackoverflow.com/a/29275390/18055567) it does not work on chrome.
