### ISSUE TITLE
mermaid preview stops working

### ISSUE THREAD

**Issue by chyuan530** [shd101wyy/markdown-preview-enhanced#195]
I'm on Mac Atom 1.12.3. Believe it last worked on 1.11.2.

**Comment by shd101wyy** [comment]
Hi @chyuan530 ,

Could you please try to restart atom and see if this issue still happen?  
Also, can you paste your mermaid code here?  

Thanks

**Comment by chyuan530** [comment]
Just tried restart, no changed. Also uninstalled and reinstalled package and shows no difference.

Any mermaid would do, here's a simple example:

```mermaid
sequenceDiagram
  participant User
  participant Wizard
  participant Actions
  participant Reducer
  User->>Wizard: Enters a wizard
  alt creates new wizard
    Wizard->>Actions: initialize(stepCount)
    Actions->>Reducer: WIZARD_INITIALIZE
  else
    note over Wizard,Reducer: to be completed as part of Wizard re-entry
  end
  Wizard->>Wizard: render()
```

**Comment by shd101wyy** [comment]
Are you writing <code>\`\`\`{mermaid}</code>  or  <code>\`\`\`mermaid</code>?

**Comment by chyuan530** [comment]
```mermaid without the curly braces, and in fact, adding ```{mermaid} does work. It used to work without the curly braces though?

and again thanks for staying on top of the issues!
