### ISSUE TITLE
上传图片至imgur超时

### ISSUE THREAD

**Issue by leexusky** [shd101wyy/markdown-preview-enhanced#197]
我在家里使用插件上传是没有问题的，但是在公司就会提示网络超时。又用MarkdownPad2上传到imgur试了下可以。
公司的Atom我是设置了网络代理的，是不是这个插件还不支持代理?好多公司都需要设置代理上网，这个功能还是很有必要的

**Comment by shd101wyy** [comment]
你可以换用 sm.ms，这个支持国内，不用翻墙的。
![screen shot 2016-11-16 at 2 29 15 am](https://cloud.githubusercontent.com/assets/1908863/20339915/805e2fe6-aba4-11e6-8d1a-9c2841a1cf9e.png)

**Comment by leexusky** [comment]
![qq 20161116163202](https://cloud.githubusercontent.com/assets/16282049/20339982/392fe3c8-ac1a-11e6-8264-15f2c4b18751.png)
用sm.ms的话就报错了

**Comment by shd101wyy** [comment]
我得睡觉了。你重启下试试。如果还不行就把 sm.ms 的 bug 完整的发过来我早上看看。多谢啦

**Comment by shd101wyy** [comment]
也有可能是插件冲突

**Comment by leexusky** [comment]
好的，待会发，晚安

**Comment by leexusky** [comment]
bug日志
file:///C:/Users/Leexus/AppData/Local/atom/app-1.12.3/resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CDesktop%22%2C%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CDesktop%5C%5Cmarkdown%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CDesktop%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%2C%7B%22pathToOpen%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CDesktop%5C%5Cmarkdown%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.12.3%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cinitialize-application-window.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.12.3%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22ALLUSERSPROFILE%22%3A%22C%3A%5C%5CProgramData%22%2C%22APPDATA%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CAppData%5C%5CRoaming%22%2C%22ATOM_HOME%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5C.atom%22%2C%22CommonProgramFiles%22%3A%22C%3A%5C%5CProgram%20Files%20(x86)%5C%5CCommon%20Files%22%2C%22CommonProgramFiles(x86)%22%3A%22C%3A%5C%5CProgram%20Files%20(x86)%5C%5CCommon%20Files%22%2C%22CommonProgramW6432%22%3A%22C%3A%5C%5CProgram%20Files%5C%5CCommon%20Files%22%2C%22COMPUTERNAME%22%3A%22LEEXUS-PC%22%2C%22ComSpec%22%3A%22C%3A%5C%5CWindows%5C%5Csystem32%5C%5Ccmd.exe%22%2C%22FP_NO_HOST_CHECK%22%3A%22NO%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22GRADLE_HOME%22%3A%22D%3A%5C%5CProgram%20Files%20(x86)%5C%5Cgradle-2.14.1%22%2C%22GRAPHVIZ_DOT%22%3A%22D%3A%5C%5CProgram%20Files%20(x86)%5C%5CGraphviz2.38%5C%5Cbin%5C%5Cdot.exe%22%2C%22HOMEDRIVE%22%3A%22C%3A%22%2C%22HOMEPATH%22%3A%22%5C%5CUsers%5C%5CLeexus%22%2C%22JAVA_HOME%22%3A%22C%3A%5C%5CProgram%20Files%5C%5CJava%5C%5Cjdk1.8.0_77%22%2C%22LOCALAPPDATA%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CAppData%5C%5CLocal%22%2C%22LOGONSERVER%22%3A%22%5C%5C%5C%5CLEEXUS-PC%22%2C%22MAVEN_HOME%22%3A%22D%3A%5C%5CFDC%5C%5Capache-maven-3.2.5%22%2C%22NUMBER_OF_PROCESSORS%22%3A%224%22%2C%22OS%22%3A%22Windows_NT%22%2C%22Path%22%3A%22C%3A%5C%5CProgram%20Files%20(x86)%5C%5CPerl64%5C%5Csite%5C%5Cbin%3BC%3A%5C%5CProgram%20Files%20(x86)%5C%5CPerl64%5C%5Cbin%3BC%3A%5C%5CProgram%20Files%5C%5CJava%5C%5Cjdk1.8.0_77%5C%5Cbin%3BC%3A%5C%5CWindows%5C%5Csystem32%3BC%3A%5C%5CWindows%3BC%3A%5C%5CWindows%5C%5CSystem32%5C%5CWbem%3BC%3A%5C%5CWindows%5C%5CSystem32%5C%5CWindowsPowerShell%5C%5Cv1.0%5C%5C%3BC%3A%5C%5CProgram%20Files%5C%5CIntel%5C%5CWiFi%5C%5Cbin%5C%5C%3BC%3A%5C%5CProgram%20Files%5C%5CCommon%20Files%5C%5CIntel%5C%5CWirelessCommon%5C%5C%3BC%3A%5C%5CProgram%20Files%5C%5CWIDCOMM%5C%5CBluetooth%20Software%5C%5C%3BC%3A%5C%5CProgram%20Files%5C%5CWIDCOMM%5C%5CBluetooth%20Software%5C%5Csyswow64%3BC%3A%5C%5CProgram%20Files%5C%5CSlikSvn%5C%5Cbin%3BD%3A%5C%5CProgram%20Files%20(x86)%5C%5Cdoxygen%5C%5Cbin%3BD%3A%5C%5CProgram%20Files%20(x86)%5C%5CGraphviz2.38%5C%5Cbin%3BD%3A%5C%5CProgram%20Files%20(x86)%5C%5Cgradle-2.14.1%5C%5Cbin%3BD%3A%5C%5CProgram%20Files%20(x86)%5C%5CGit%5C%5Ccmd%3BD%3A%5C%5CFDC%5C%5Capache-maven-3.2.5%5C%5Cbin%3BC%3A%5C%5CProgram%20Files%5C%5C7-Zip%3BC%3A%5C%5CProgram%20Files%5C%5CIntel%5C%5CWiFi%5C%5Cbin%5C%5C%3BC%3A%5C%5CProgram%20Files%5C%5CCommon%20Files%5C%5CIntel%5C%5CWirelessCommon%5C%5C%3BC%3A%5C%5CUsers%5C%5CLeexus%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Cbin%22%2C%22PATHEXT%22%3A%22.COM%3B.EXE%3B.BAT%3B.CMD%3B.VBS%3B.VBE%3B.JS%3B.JSE%3B.WSF%3B.WSH%3B.MSC%22%2C%22PROCESSOR_ARCHITECTURE%22%3A%22x86%22%2C%22PROCESSOR_ARCHITEW6432%22%3A%22AMD64%22%2C%22PROCESSOR_IDENTIFIER%22%3A%22Intel64%20Family%206%20Model%2058%20Stepping%209%2C%20GenuineIntel%22%2C%22PROCESSOR_LEVEL%22%3A%226%22%2C%22PROCESSOR_REVISION%22%3A%223a09%22%2C%22ProgramData%22%3A%22C%3A%5C%5CProgramData%22%2C%22ProgramFiles%22%3A%22C%3A%5C%5CProgram%20Files%20(x86)%22%2C%22ProgramFiles(x86)%22%3A%22C%3A%5C%5CProgram%20Files%20(x86)%22%2C%22ProgramW6432%22%3A%22C%3A%5C%5CProgram%20Files%22%2C%22PROMPT%22%3A%22%24P%24G%22%2C%22PSModulePath%22%3A%22C%3A%5C%5CWindows%5C%5Csystem32%5C%5CWindowsPowerShell%5C%5Cv1.0%5C%5CModules%5C%5C%3BC%3A%5C%5CProgram%20Files%5C%5CIntel%5C%5C%22%2C%22PUBLIC%22%3A%22C%3A%5C%5CUsers%5C%5CPublic%22%2C%22SESSIONNAME%22%3A%22Console%22%2C%22SystemDrive%22%3A%22C%3A%22%2C%22SystemRoot%22%3A%22C%3A%5C%5CWindows%22%2C%22TEMP%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CAppData%5C%5CLocal%5C%5CTemp%22%2C%22TMP%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5CAppData%5C%5CLocal%5C%5CTemp%22%2C%22USERDOMAIN%22%3A%22Leexus-PC%22%2C%22USERNAME%22%3A%22Leexus%22%2C%22USERPROFILE%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%22%2C%22windir%22%3A%22C%3A%5C%5CWindows%22%2C%22windows_tracing_flags%22%3A%223%22%2C%22windows_tracing_logfile%22%3A%22C%3A%5C%5CBVTBin%5C%5CTests%5C%5Cinstallpackage%5C%5Ccsilogfile.log%22%7D%2C%22appVersion%22%3A%221.12.3%22%2C%22atomHome%22%3A%22C%3A%5C%5CUsers%5C%5CLeexus%5C%5C.atom%22%2C%22shellLoadTime%22%3A419%7D:1
Hide Stack Trace
SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Request._callback (file:///C:/Users/Leexus/.atom/packages/markdown-preview-enhanced/lib/sm.coffee:10:17)
    at self.callback (C:\Users\Leexus\.atom\packages\markdown-preview-enhanced\node_modules\request\request.js:186:22)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\Leexus\.atom\packages\markdown-preview-enhanced\node_modules\request\request.js:824:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by leexusky** [comment]
哦对了，我说的需要挂代理，是因为公司内网的缘故，不需要翻墙也可以用imigur。所以imigur不能用应该是因为没有使用ATOM的代理设置连接网络

**Comment by shd101wyy** [comment]
貌似是 sm.ms 返回的结果 parse 成 JSON 出了问题。插件和代理没关系吧，只要你连的网翻墙了，你的电脑也就翻墙了啊。

**Comment by leexusky** [comment]
那sm.ms还有救么

**Comment by shd101wyy** [comment]
我试了下用 sm.ms 没有问题。所以我觉得可能还是你的网络问题。
你试试直接 [sm.ms](https://sm.ms/) 网站上传图片试试？

**Comment by leexusky** [comment]
sm.ms网站是可以的。
是这样的，我公司的网络设有网关，只有设置了公司的代理后才能连接外网。浏览器我设置了代理，所以可以访问sm.ms网站。Atom也需要在配置文件里设置代理，否则插件都无法安装。
我之前使用Intellij IDEA的一个翻译插件时，就出现过插件无法联网的情况。后来和开发者沟通，确认是我虽然在Intellij IDEA里设置了代理，但是他的插件里没有使用这个代理，所以无法上网。
所以我怀疑是否是因为我虽然在Atom里设置代理，但是插件没有使用代理连接网络。
我不懂哈，只是猜测

**Comment by shd101wyy** [comment]
不太清楚了，我也不大清楚 atom 怎么弄代理。。。

**Comment by leexusky** [comment]
我google下，看看代理设置是不是有问题
