### ISSUE TITLE
Speaker notes in reveal presentations

### ISSUE THREAD

**Issue by Rikorose** [shd101wyy/markdown-preview-enhanced#199]
Is this feature available? I did not find documentation on this.

**Comment by shd101wyy** [comment]
You mean you want to put audio into presentation?

**Comment by Rikorose** [comment]
No I mean this: https://github.com/hakimel/reveal.js#speaker-notes

**Comment by shd101wyy** [comment]
Sorry I am in class 😂. 
I will go have a look after class.

**Comment by shd101wyy** [comment]
I don't think it's supported now.
I might implement this feature in next release then.

**Comment by shd101wyy** [comment]
@Rikorose it seems that speaker note requires setting up a local server.  
I can add `data-notes="..."` to `section`, but you may need to run a local server by yourself.  
Is that okay?

**Comment by Rikorose** [comment]
yes that would be fine

**Comment by shd101wyy** [comment]
Hi @Rikorose , sorry for my late reply.  
**Speaker notes** is now supported.  
To enable speaker notes, set front-matter as:  
```yaml  
---
presentation:
  enableSpeakerNotes: true
---
```  
To add notes, simply set `data-notes` property:
```html
<!-- slide data-notes:"Write your note here" -->
```
or write 
```
<aside class="notes">
Your notes here
</aside>
```
under `<!-- slide -->`

**Comment by schlichtanders** [comment]
If I try to open Speaker Notes by pressing ``s``, I just a get an empty speaker view. Nothing at all is shown. I also tested the default https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/presentation-intro.md file, same unfortunate result.

any ideas what goes wrong here?


Operating System: Windows
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
markdown-preview-enhance : 0.10.8

**Comment by shd101wyy** [comment]
Hi @schlichtanders ,

Try using Chrome?

Thanks

**Comment by shd101wyy** [comment]
Hi @schlichtanders ,

This is weird. I will test it on Windows when I have time.  

Thanks

**Comment by shd101wyy** [comment]
@schlichtanders  Also please post that as a new issue. Thanks
