### ISSUE TITLE
Atom安装插件问题

### ISSUE THREAD

**Issue by zhchen-Git** [shd101wyy/markdown-preview-enhanced#203]
# Atom客户端安装插件问题
我用的是MacBook Air，安装了Atom Release1.12.4，由于自带的MarkDown Preview功能较弱，想要安装Enhanced 版本，然而在Atom客户端找到之后却安装不了，永远显示正在安装的界面
![Atom-intalling-package](/Users/altman/Desktop/Atom.png)

**Comment by zhchen-Git** [comment]
发现是权限问题，Atom的package的安装需要管理员权限

**Comment by shd101wyy** [comment]
其实不应该需要管理员权限。
