### ISSUE TITLE
mermaid的today line无法改变颜色，默认为黑色

### ISSUE THREAD

**Issue by coolboy0961** [shd101wyy/markdown-preview-enhanced#204]
##### 问题
- today line的颜色默认为黑，但是mermaid.css中定义为红色`stroke: red;`，且无法改变。
改变`stroke-width: 2px;`可以改变today line的粗细。

##### 环境信息
- MacOS:10.11.6
- atom:1.11.2
- markdown-preview-enhanced:0.8.9

##### 图像
![2016-11-20 12 07 04](https://cloud.githubusercontent.com/assets/12973893/20460066/e5e302fa-af1a-11e6-8091-ed70da2d5510.png)
![2016-11-20 11 59 44](https://cloud.githubusercontent.com/assets/12973893/20460069/f1ea443c-af1a-11e6-9fb0-03a4cd47e1b6.png)
![2016-11-20 12 07 23](https://cloud.githubusercontent.com/assets/12973893/20460071/fb64c442-af1a-11e6-838d-33f958dec089.png)

**Comment by shd101wyy** [comment]
加个 !important 试试？然后每次修改完 js 文件得重启 atom

**Comment by coolboy0961** [comment]
如你所说，`.atom/packages/markdown-preview-enhanced/dependencies/mermaid/mermaid.css`的Today line的定义改成如下就能改变颜色了。
~~~
/* Today line */
.mermaid .today {
  fill: none;
  stroke: red !important;
  stroke-width: 2px;
}
~~~

非常感谢！！

**Comment by coolboy0961** [comment]
markdown-preview-enhanced的preview中today line变成红色了，但是保存成html或者PDF后又变成了黑色，还有什么可以试试的吗？

**Comment by shd101wyy** [comment]
`cmd+shift+p` then choose `Markdown Preview Enhanced: Customize Css`.  
在 `.markdown-preview-enhanced-custom` 下面添加 
```
.mermaid .today {
  fill: none;
  stroke: red !important;
  stroke-width: 2px;
}
```
后保存。

**Comment by coolboy0961** [comment]
非常感谢你的回答。
我试了一下还是没能解决，出现如下结果。

##### 修改style.css,不修改mermaid.css
markdown-preview-enhanced的preview中today line是黑色，输出的PDF和HTML也是黑色

##### 修改mermaid.css,不修改style.css
markdown-preview-enhanced的preview中today line是红色，输出的PDF和HTML是黑色

##### 修改style.css,不修改mermaid.css情况的截图如下：(我确定重启过atom)
![2016-11-21 13 22 02](https://cloud.githubusercontent.com/assets/12973893/20470681/1f8778c8-afee-11e6-8e29-7d7f23bf00b6.png)
![2016-11-21 13 22 57](https://cloud.githubusercontent.com/assets/12973893/20470701/494de5f2-afee-11e6-9a5d-cf4ebb4db5ee.png)
![2016-11-21 13 23 48](https://cloud.githubusercontent.com/assets/12973893/20470705/50e1e4d0-afee-11e6-8c7d-32a6376bfadc.png)

如果你那里确实是按你说的可以用style.css改变颜色的话，我重新安装markdown-preview-enhanced一次试试。

**Comment by coolboy0961** [comment]
解决方法发现了，但是也不正规。
你可以考虑一下实现在style.less修改的内容能够反映出来吗？

`.atom/packages/markdown-preview-enhanced/styles/markdown-preview-enhanced.less`中进行了如下修改以后就可以都变成红色了。

![2016-11-21 15 51 03](https://cloud.githubusercontent.com/assets/12973893/20473296/feff5840-b002-11e6-8081-b471ed377add.png)
![2016-11-21 15 51 29](https://cloud.githubusercontent.com/assets/12973893/20473298/01303a6c-b003-11e6-98c8-9c7120408feb.png)

**Comment by shd101wyy** [comment]
修改 style.less 和修改 markdown-preview-enhanced.less 效果是一样的。不要建议直接修改源码。修改 style.less 文件

**Comment by shd101wyy** [comment]
我明天研究下为什么 style.less 不好用😳。

**Comment by shd101wyy** [comment]
@coolboy0961 抱歉，

我尝试了下，不用在 `style.less` 里面加上 `!important`。  

![screen shot 2016-11-21 at 2 25 08 am](https://cloud.githubusercontent.com/assets/1908863/20475502/d89a0450-af91-11e6-8ee8-a5d97c19394a.png)  

这样就可以了 :)

**Comment by coolboy0961** [comment]
确实可以了。
非常感谢！！
