### ISSUE TITLE
The release of version 0.9.0 will be postponed.  

### ISSUE THREAD

**Issue by shd101wyy** [shd101wyy/markdown-preview-enhanced#207]
Hey guys,  

It's now Thanksgiving break. I thought I would be very free during this break, but the fact turned out to be that I have a lot of school projects and homework left to do. 
Therefore I decide to focus on my school work first. 
I will focus on this project after the final exams (probably after December 15th).          

My plan for `0.9.0` is as follows:   
* [ ] fix existing bugs and issues.  
* [ ] allow one markdown file to include other markdown files. But I haven't thought a good way to write it: `<!-- include:"/path" -->` or `{% include "/path" %}` or some other ways. So I need some advice.  
* [x] support compiling markdown to markdown. So that the compiled version of markdown will include graphs, math typesettings, and all markdown files that it included. The compiled version can be used on Github. I have implemented part of this feature in branch `0.9.0` but the final result doesn't seem very good.  
* [ ] add `html`, `pdf`, `phantomjs`, `markdown` front-matter.  
* [ ] modify `pandoc` front-matter. Put original front-matter content under `pandoc: ` section.  
* [ ] export file on save.  
* [ ] execute code chunk on save.   
* [ ] `html` file  left-side`TOC`. Tell me if you know any good library that can do this job. 
* [x] upgrade all dependencies.   

Feel free to modify the TODO list. 

Pull request is welcomed :)  preferably submitted to branch `0.9.0`

Thank you

**Comment by StefanoCecere** [comment]
hi shd

for the inclusion of external files.. sine it' an hot topic (iA writer 4 makes this feature a "major" eature: https://ia.net/writer/updates/ia-writer-4 ) and Brett Terpstra replies with http://brettterpstra.com/2016/11/22/marked-2-dot-5-8/

i would use one of their solutions:
the iA 4 one is really simple and nice:

/nameofthefile.md

while Marked uses <<[sections/section1.md]

**Comment by shd101wyy** [comment]
Thanks for your advice,  I will go have a look:)

**Comment by codevinsky** [comment]
As I haven't looked at the code, I'm just going to assume you're parsing the markdown AST... If that's true, you can -literally- do anything you want. Why not stick to the es6 style we're all used to and do something like:

<sup><sub>_`partials/header.md`</sub></sup>

## ♡ notes <sup><sup><sub><sub> by Ada Lovecraft</sub></sub></sup></sup>


<sup><sub>`partials/footer.md`</sub></sup>
<sub><sub>made with ♡ by [shd101wyy](https://github.com/shd101wyy)</sub></sub>



```markdown
import 'partials/header'

My New Post
===========

Some Content Here:
* Foo
* Bar
* Baz

import '../partials/footer'
```

**Comment by shd101wyy** [comment]
Hi @StefanoCecere @8-uh ,

Including external files is now supported. Plz check [this doc](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/doc-imports.md).   

Cheers

**Comment by 8-uh** [comment]
Fantastic.

You've -almost- built a full-featured literate programming environment... Really, the only thing left is to implement tangling and weaving
