### ISSUE TITLE
关于 0.9.0 版本的延期

### ISSUE THREAD

**Issue by shd101wyy** [shd101wyy/markdown-preview-enhanced#208]
大家好，

我现在正在感恩节假期，本来以为自己会有很多空闲时间，但事实却是我非常的忙，有很多学校的作业和课程项目要做。  
所以我决定先专心学校的功课。  
我会在我的期末考试结束后 (差不多 12 月 15 日) 再开始做这个项目。  

下个版本 `0.9.0` 的计划如下：  
* [ ] 修复现存的 bug 和问题。
* [ ] 支持 markdown 引用其他的 markdown。现在我想了几个写法: `<!-- include:"/path" -->` or `{% include "/path" %}`。或者你有什么想法可以在下面留言。
* [x] 支持编译 markdown 到 markdown. 这样所有的图，数学表达式都会放在编译好的 markdown 文件里并且可以直接在 Github 上预览。我已经在分支 `0.9.0` 里面写了一部分了，但是效果不太好。
* [ ] 增加 `html`, `pdf`, `phantomjs`, `markdown` front-matter.  
* [ ] 修改 `pandoc` front-matter. 把原来的 front-matter 内容放到 `pandoc: ` 下面.  
* [ ] 保存时导出文件 (pdf, html...).  
* [ ] 保存时运行 code chunk.   
* [ ] `html` 文件左侧`TOC`。如果你知道什么好的 render TOC 的库请告诉我。
* [x] 升级所有的依赖。

请随意修改此计划列表。

很欢迎 pull request。最好是提交到 `0.9.0` 这个分支上。    

非常感谢！

**Comment by zhchen-Git** [comment]
还不太熟悉github的pull request，写在这里希望你也能看到。
我是这两周需要写一份报告才开始接触到markdown，非常感谢你分享的这个插件，它为我的工作提供了很多便利。不过在我写到12000字左右的时候，插件的反应开始变慢，到大概15000字之后电脑开始发热，输入也出现了明显的延迟。（我的文章中含有一些图片，一些类图用的是plantuml，还有一些java代码。）
希望我的反馈能为你改进这个插件提供一点帮助，markdown-preview-enhanced是一个很棒的插件，希望它越来越好！

**Comment by shd101wyy** [comment]
Hi @zhchen-Git ,

是的我准备编写 include 的功能，这样就可以把一个 markdown 可以 include 几个小的 markdown。然后就不会卡了。现在单独编写大的 markdown 文件是会很卡的。
我发布 0.9.0 版本的时候会通知你 :)

谢谢
