### ISSUE TITLE
WaveJSON parsing issue

### ISSUE THREAD

**Issue by rexrainbow** [shd101wyy/markdown-preview-enhanced#212]
Test this WaveJSON
```
{ signal : [
  { name: "clk",  wave: "p......" },
  { name: "bus",  wave: "x.34.5x",   data: "head body tail" },
  { name: "wire", wave: "0.1..0." },
]}
```
shown at [home page of wavedrom](https://github.com/drom/wavedrom), is not worked -- `failed to parse JSON`.

The WaveJSON should be fixed to 
```
{ signal: [
  { name: "clk",  wave: "p......" },
  { name: "bus",  wave: "x.34.5x",   data: "head body tail" },
  { name: "wire", wave: "0.1..0." }
]}
```
, removing the space after "signal" key, and the last "," character.

Is it possible to have more flexible format of WaveJSON?

**Comment by shd101wyy** [comment]
Hi,

No, right now you have to write in valid JSON format. The WaveDrom uses eval function in their code, which is not allowed in atom extension due to safety reasons. So only valid JSON works.

Thanks

**Comment by shd101wyy** [comment]
Hi @rexrainbow ,   

I have changed the code, so now it doesn't have to a JSON format to work.   
I will close this issue now.  

Cheers
