### ISSUE TITLE
how to support puml 

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#213]
Hello, my puml is not working. It was working before but for unknown reason not working any more, maybe after I made some upgrading.

I'm wondering how to debug this issue? I tried below with no luck:
```
git pull wyy master
npm install
sudo apm install
apm link
```

Thanks.

**Comment by shd101wyy** [comment]
write 
    
    ```{puml}
    ...
    ```

instead of   
   
    ```puml
    ...
    ```

**Comment by xu4wang** [comment]
Thanks. it works. 

Grammar changed? but for language hightlighting, both below code blocks work..

   ```python
   print "hello"
   ```

   ```{python}
   print "hello"
   ```

**Comment by shd101wyy** [comment]
the one with `{...}` implies code chunk, while the normal one (without `{}`) is only code block.

**Comment by xu4wang** [comment]
OK make sense
