### ISSUE TITLE
support ```language (in addition to ```{language}

### ISSUE THREAD

**Issue by StefanoCecere** [shd101wyy/markdown-preview-enhanced#214]
since other markdown interpreters are starting to use the syntax
\`\`\`language (like \`\`\`mermaid ) to render content blocks
to enhance portability of our .md documents i ask:

couldn't markdown-preview-enhanced automatically interpret \`\`\`mermaid like it was \`\`\`{mermaid} if it's just a single word?

the {} are good if we have to pass parameters (and here only markdown-preview-enhanced can interpret them)

what do you think?

**Comment by shd101wyy** [comment]
Hi @StefanoCecere  @okwolf @8-uh @Michael-Thibault , sorry for my late reply.    

Now both <code>\`\`\`mermaid </code> and <code>\'\'\'@mermaid</code> will render mermaid graphs. (Same for `plantuml`, `viz`, and `wavedrom`)   
If you only want <code>\'\'\'@mermaid</code> to work, disable `Use standard code fencing for graphs` in settings of this package.  

Cheers

**Comment by okwolf** [comment]
Thanks @shd101wyy! I was using this syntax for compatibility with the mermaid plugin for GitBook FYI:

    ```mermaid
    graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
    ```
