### ISSUE TITLE
configuration: open each preview in a separate tab

### ISSUE THREAD

**Issue by abhayghatpande** [shd101wyy/markdown-preview-enhanced#218]
Hi @shd101wyy 

Any way to open preview of each .md file in separate tabs in the right pane? Sometimes I want to compare the outputs of two different files, at other times I want to refer to something in a different document. Currently the only way to switch different previews is to switch to the .md files in the left pane.

It will be great if we could independently toggle the previews of .md files in the left pane. Sometimes I have multiple .md files open, but I don't want to see the preview on the right.

So these seem to be different features:
(1) Toggle previews independently
(2) Open each preview in independent tab on the right

**Comment by shd101wyy** [comment]
Hi @abhayghatpande , 

The newest version now supports multiple previews. You can change it from the package settings.

![](http://i.imgur.com/gNEh6aK.png)  

Thanks

**Comment by abhayghatpande** [comment]
@shd101wyy thank you! works like a charm!

**Comment by abhayghatpande** [comment]
@shd101wyy one suggestion: when I have a number of previews open, and I switch to one of the markdown files, can the corresponding preview be made "active"? Currently, the preview does not switch when I switch the markdown file.

**Comment by shd101wyy** [comment]
Some people prefer to editing one markdown file while reading the preview of another markdown file. But I can add one option in the settings. Please post it as a `Feature Request` in case I forget. Thanks :)

**Comment by abhayghatpande** [comment]
@shd101wyy I posted the feature request.

I think logically it follows that the preview should match the file being edited. It is always possible to manually select another preview pane if one wishes to view another preview. Thanks!
