### ISSUE TITLE
安装之后[TOC]似乎没用,求解..

### ISSUE THREAD

**Issue by Arthur244** [shd101wyy/markdown-preview-enhanced#220]

**Comment by shd101wyy** [comment]
请具体一点

**Comment by Arthur244** [comment]
我安装了插件之后禁用了atom自带的mrakdown插件..然后在之前打开写的md文件,预览状态下[TOC]会直接显示[TOC]而不是生成一个目录.是不是我有哪里设置没有操作

**Comment by Arthur244** [comment]
好吧..试了一下命令确实可以有用..但是能否像其他md编辑器一样写[TOC]就直接自己生成目录呢..

**Comment by shd101wyy** [comment]
不，我并不打算 `[TOC]`，因为我是在 markdown 文本中生成 `TOC`，而不是仅仅在 preview 中。
这个问题我先关闭了，谢谢～

**Comment by shd101wyy** [comment]
@Arthur244 现在支持 `[TOC]` 了

谢谢
