### ISSUE TITLE
I can not download this plugins from atom?

### ISSUE THREAD

**Issue by arondl** [shd101wyy/markdown-preview-enhanced#221]
I can not download this plugins from atom?

**Comment by shd101wyy** [comment]
Hi @arondl , it might be caused by network error? Try to use `apm` command to install. Thanks

**Comment by cdcdec** [comment]
I can not find   this plugins from atom?

**Comment by shd101wyy** [comment]
check [#228](https://github.com/shd101wyy/markdown-preview-enhanced/issues/228)
