### ISSUE TITLE
Deprecated selector in `markdown-preview-enhanced/styles/zen.less`

### ISSUE THREAD

**Issue by Foreigner-JA** [shd101wyy/markdown-preview-enhanced#223]
In `markdown-preview-enhanced/styles/zen.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[data-markdown-zen]::shadow .gutter` => `atom-text-editor[data-markdown-zen].editor .gutter`

* `atom-text-editor[data-markdown-zen]::shadow atom-text-editor-minimap` => `atom-text-editor[data-markdown-zen].editor atom-text-editor-minimap`

* `atom-text-editor[data-markdown-zen]::shadow .vertical-scrollbar` => `atom-text-editor[data-markdown-zen].editor .vertical-scrollbar`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by kevwil** [comment]
This is an issue for me as well.

**Comment by shd101wyy** [comment]
@Foreigner-JA , @kevwil should be fixed now, thanks :)
