### ISSUE TITLE
Function request: Chart.js  support

### ISSUE THREAD

**Issue by xxtxx** [shd101wyy/markdown-preview-enhanced#224]
It would be nice to add the function of rendering Chart.js .
> http://www.chartjs.org/docs/

**Comment by shd101wyy** [comment]
Hi @xxtxx ,

我试了一下，结果只能在 preview 中显示，但是导出的 html 或者 pdf 就显示不了了。  
如果能生成 svg 就没问题，但是我不知道该怎么做。  

谢谢

**Comment by shd101wyy** [comment]
@xxtxx 我找到解决方案了。将在下一个版本支持 chart.js。  
发布后我会通知你，谢谢。

**Comment by shd101wyy** [comment]
@xxtxx 请查看 [该文档](https://cdn.rawgit.com/shd101wyy/markdown-preview-enhanced/f83acb43/test/code-chunks-test.html)
