### ISSUE TITLE
I can not find this plugins from atom?

### ISSUE THREAD

**Issue by cdcdec** [shd101wyy/markdown-preview-enhanced#228]
I can not find this plugins from atom?
![qq 20161229145716](https://cloud.githubusercontent.com/assets/8176067/21538353/2e27fb08-cdd7-11e6-9c36-73dbea3ed193.png)

**Comment by shd101wyy** [comment]
Hi @cdcdec , you need to install it first.  
![screen shot 2016-12-29 at 6 45 50 pm](https://cloud.githubusercontent.com/assets/1908863/21557798/0e01023c-cdf7-11e6-924d-82d5e4ebad65.png)
Thanks :)
