### ISSUE TITLE
\text{}貌似不支持中文

### ISSUE THREAD

**Issue by Ahoge1993** [shd101wyy/markdown-preview-enhanced#23]
希望能加入中文支持

**Comment by shd101wyy** [comment]
Hi @Ahoge1993 , 在 version 0.5.9 中我添加了 MathJax 的支持。
MathJax 比 KaTeX 更好的支持数学符号的渲染，我刚刚测试过了中文也可以。
但是 MathJax 比 KaTeX 的渲染速度会慢一点。
如果你想切换到 MathJax，你可以在 Settings 里面设定。
![screen shot 2016-05-13 at 4 14 38 pm](https://cloud.githubusercontent.com/assets/1908863/15262089/d0fb97d4-1925-11e6-9467-4bf55bde5f3c.png)

然后我研究了下 **公式部分希望能加入语法高亮**  貌似是不能完成的。。抱歉。


谢谢。

**Comment by shd101wyy** [comment]
哈罗 @Ahoge1993 ，现在 `\text{}` 支持中文了。
