### ISSUE TITLE
emoji support

### ISSUE THREAD

**Issue by davidro** [shd101wyy/markdown-preview-enhanced#230]
Support emoji :sunglasses: like in github markdown https://help.github.com/articles/basic-writing-and-formatting-syntax/#using-emoji

**Comment by davidro** [comment]
It works nicely. Thx for recommendation.

**Comment by shd101wyy** [comment]
@davidro  Both emoji and font-awesome are supported now.  

You can disable it from the package settings.   
![screen shot 2017-09-30 at 9 32 11 pm](https://user-images.githubusercontent.com/1908863/31051176-d87e648e-a626-11e7-8e50-694bee25ff70.png)

Cheers :)
