### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by AungVillage** [shd101wyy/markdown-preview-enhanced#231]
![失败截图](https://cloud.githubusercontent.com/assets/11907472/21772252/702ba198-d6c5-11e6-8e13-ab74117a375b.png)

我python和vs都装了的。他给的here那个链接地址其实已经没有了。
`apm install --check` 我也 `gyp ERR!`

这是第一次遇到装插件出问题- -

**Comment by shd101wyy** [comment]
应该是网络问题，翻个墙再试试。。

**Comment by shd101wyy** [comment]
因为 phantomjs 这个依赖国内安装可能会出现问题。或者你可以本地先把 phantomjs 给安装好。

**Comment by Niefee** [comment]
@shd101wyy 试了很多方式，国内只有用 `git clone`克隆下来放在package目录，然后用淘宝的`cnpm install`安装才行。其他方式太慢或者不行，代理也开了全局也卡了两个小时没反应。

**Comment by shd101wyy** [comment]
@Niefee 我对如何设置 cnpm 不太了解。你知道有什么方式可是让 npm 不可以的时候 自动切换为 cnpm 吗？

谢谢

**Comment by shd101wyy** [comment]
@Niefee , 因为我不在国内，所以能不能帮我试验一下这个方法？
[phantom-prebuilt 设置 Where to get PhantomJs](https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs)  

创建 `.npmrc` 然后添加 
```
phantomjs_cdnurl=https://bitbucket.org/ariya/phantomjs/downloads
```

如果可行的话，请发给我一个 pull request。

非常感谢

**Comment by Niefee** [comment]
@shd101wyy 
用`npm install cnpm -g`安装`cnpm`的，然后操作`npm`相关命令的时候换成`cnpm`效果是一样的。
我在`.npmrc`里面添加了一行内容
`registry=http://r.cnpmjs.org/`。
基本安装都不太会有影响力额。
安装后也会从淘宝那里下载`phantomjs`，全程五分钟就可以，速度挺快的。其他方法我试过都感觉不太好，在atom客户端安装两个小时挂着不动。
关键还是国内的VPN最近都封得太死的，atom安装插件是一定要翻墙的。

**Comment by shd101wyy** [comment]
@Niefee 抱歉我没太搞懂。所以我还需要修改 `.npmrc` 文件吗？  
我觉得我可以把  `cnpm` 的这个方法写进 `疑难解答 FAQ` 这个环节里。
非常感谢啦

**Comment by Niefee** [comment]
@shd101wyy 
这里是使用指南 [cnpm安装](http://npm.taobao.org/)
全局安装`cnpm`，之后的命令都用`cnpm`代替`npm`就能快速安装各种npm上的程序了。

**Comment by Niefee** [comment]
@shd101wyy  最近测试了一下VPN，全局挂代理，浏览器可以照常访问谷歌，但Atom还是无法安装插件，非常低几率试过一两次成功。

**Comment by Niefee** [comment]
@shd101wyy 
国内如果不能通过Atom安装，可参考这个方法：

```
//安装淘宝的cnpm
1. npm install -g cnpm --registry=https://registry.npm.taobao.org

//设置代理
2.npm config set registry https://registry.npm.taobao.org

//克隆项目到 .atom/packages 目录
3.git clone https://github.com/shd101wyy/markdown-preview-enhanced.git

//安装
4.cnpm install
```
