### ISSUE TITLE
在选择Save as Markdown后PlantUml无法生成图片

### ISSUE THREAD

**Issue by coolboy0961** [shd101wyy/markdown-preview-enhanced#235]
## 环境信息
- OS: macOS 10.12.1
- Software:
  - Atom Version: 1.13.0 X64
  -  markdown-preview-enhanced v0.9.2
  - gnuplot 5.0.5
  - java 1.8.0_25

## 选择save as markdown之前的test.md
![screen shot 2017-01-14 at 17 41 39](https://cloud.githubusercontent.com/assets/12973893/21953661/e874a910-da80-11e6-844d-e429e993bd14.png)

## 选择save as markdown之后的test_.md
![screen shot 2017-01-14 at 17 41 21](https://cloud.githubusercontent.com/assets/12973893/21953664/fdea68ca-da80-11e6-88ef-507660058e6e.png)

**Comment by shd101wyy** [comment]
Hi @coolboy0961 , 谢谢你的回复，

请写成 <code>```{puml ...}</code> 而不是 <code>\~\~\~{puml ...}</code>
现在 <code>\~\~\~</code> 这种写法尚不支持，我将在下个 release 中修复该问题。
你也可以直接写成 
<pre>
```{puml}
class abs {
    + init();
```
</pre>

谢谢 :)

**Comment by coolboy0961** [comment]
原来如此。问题解决了！
这个机能很赞，总算不用一个图片一个图片手动收成，然后再一个一个插入了。

非常感谢。
