### ISSUE TITLE
当md的文件名不是英文的时候，save as markdown后生成的md文件无法正确显示插入的图片

### ISSUE THREAD

**Issue by coolboy0961** [shd101wyy/markdown-preview-enhanced#236]
## 环境信息
- OS: macOS 10.12.1
- Software:
  - Atom Version: 1.13.0 X64
  - markdown-preview-enhanced v0.9.2
  - gnuplot 5.0.5
  - java 1.8.0_25

## 中文文件名的情况
![screen shot 2017-01-14 at 20 42 53](https://cloud.githubusercontent.com/assets/12973893/21954664/3dd939e2-da9b-11e6-9426-1be1a1577a35.png)

## 日文文件名的情况
![screen shot 2017-01-14 at 20 45 56](https://cloud.githubusercontent.com/assets/12973893/21954666/422a765a-da9b-11e6-91c4-da173f715a48.png)

**Comment by shd101wyy** [comment]
我会尽快修复

**Comment by shd101wyy** [comment]
Hi @coolboy0961 已修复，谢谢 :)

**Comment by coolboy0961** [comment]
问题解决了。谢谢！
