### ISSUE TITLE
Bold character highlighting editor

### ISSUE THREAD

**Issue by kpstolk** [shd101wyy/markdown-preview-enhanced#239]
When I want to make a single character bold like this:

`A bold **c**haracter of a single word messes with the highlighting?`

The color highlighting in the editor marks everything orange, but the preview works correctly.
![image](https://cloud.githubusercontent.com/assets/538170/21993914/82e3dc3a-dc1d-11e6-99b5-34fea91af6fb.png)

Is this a bug or can't I just make a single character bold?
Running version: 0.9.3

**Comment by shd101wyy** [comment]
Hi @kpstolk ,
This plugin only deal with the preview part.  
For the highlighting, I think it is [language-gfm](https://github.com/atom/language-gfm) bug?  
Thanks

**Comment by kpstolk** [comment]
@shd101wyy  I thought package did both, sorry about that!
Will check if it can be reported in language-gfm repo.

**Comment by kpstolk** [comment]
FYI I think this is already reported but still open [#117](https://github.com/atom/language-gfm/issues/117)
