### ISSUE TITLE
希望修改快捷键定义方式

### ISSUE THREAD

**Issue by johnnychen94** [shd101wyy/markdown-preview-enhanced#240]
在Mac系统下需要重新定义快捷键，原来的快捷键为：

```
'.editor:not(.mini)':
    'ctrl-shift-M': 'markdown-preview-enhanced:toggle'
```

若修改成

```
'.editor:not(.mini)':
    'cmd-b': 'markdown-preview-enhanced:toggle'
```

之后，由于这是全局快捷键，会与其他的快捷键设置冲突。希望能够增加selector属性，使得多种语言下快捷键使用能够不冲突，例如设置为：

```
"atom-text-editor[data-grammar='markdown']":
    'cmd-b': 'markdown-preview-enhanced:toggle'
'atom-text-editor[data-grammar="latex"]':
    'cmd-b': 'latex:build'
```
之后在.tex文件下cmd-b调用latex build，在.md文件下cmd-b调用markdown preview :)

(这只是一个设想，由于不懂具体可能的实现方式，所以想法可能有点naive =.=)

**Comment by shd101wyy** [comment]
我感觉 `cmd-b` 有钦定 build 的意思，所以我用的是 `M`，是打开 markdown 的意思。  
我个人感觉改为 `cmd-b` 不太好。  
我再思考下哈 :)
