### ISSUE TITLE
Presentations: several groups of vertical slides following each other

### ISSUE THREAD

**Issue by Flauschbaellchen** [shd101wyy/markdown-preview-enhanced#241]
I want to create a presentation in which several vertical slides follow another group of vertical slides.
It is currently not possible to archive this as `vertical:true` needs to be specified on the first slide.

This syntax will generate all 4 slides as one vertical group:
```
<!-- slide vertical:true -->
Vertical 1 (top) Group 1
<!-- slide vertical:true -->
Vertical 2 (below) Group 1
<!-- slide vertical:true -->
Vertical 1 (top) Group 2
<!-- slide vertical:true -->
Vertical 2 (below) Group 2
```

If you want to "break free" you got the first group right but the second group is generated as normal horizontal slides.
```
<!-- slide vertical:true -->
Vertical 1 (top) Group 1
<!-- slide vertical:true -->
Vertical 2 (below) Group 1
<!-- slide -->
Vertical 1 (top) Group 2
<!-- slide vertical:true -->
Vertical 2 (below) Group 2
```

In my humble opinion, the parsing should be changed to make the following syntax work and to make "vertical:true" a bit more logical on slides which are truly vertical per definition:
```
<!-- slide -->
Vertical 1 (top) Group 1
<!-- slide vertical:true -->
Vertical 2 (below) Group 1
<!-- slide -->
Vertical 1 (top) Group 2
<!-- slide vertical:true -->
Vertical 2 (below) Group 2
```

Sadly, current presentations will need to adopt the change :(

**Comment by shd101wyy** [comment]
Oh I see. I will make change in next release. Thanks

**Comment by shd101wyy** [comment]
Hi @Flauschbaellchen , thanks for your advice and sorry for my late reply,

I have changed the code according to your description and get it fixed in version `0.9.4`

Cheers :)

**Comment by Flauschbaellchen** [comment]
Thanks @shd101wyy for the quick fix. I updated the package on my machine and can confirm that it is working now.

**Comment by xldrkp** [comment]
Thank you @shd101wyy for the fix! I ran in the same problem recently.
