### ISSUE TITLE
Missing syntax color in code chunk

### ISSUE THREAD

**Issue by kenpuluma** [shd101wyy/markdown-preview-enhanced#243]
In recent updates syntax colors won't show up when not using github.com syntax theme. I tried changing UI theme & Syntax theme and also reinstall packages but nothing works.

Please see the screenshot below:

![default](https://cloud.githubusercontent.com/assets/18385602/22168223/3007e532-df39-11e6-9ffc-9182fa2670e4.PNG)

So I just overrode the markdown-preview-enhanced.less file and temporary add atom-material style syntax to it, see #242. Most of the codes are referenced from atom-material-syntax package. Please tell me if you have anything in mind. Thank you in advance!

**Comment by shd101wyy** [comment]
Okay I see, I will try to fix this issue in the future :)

**Comment by kenpuluma** [comment]
Thanks for the quick reply.
This happens only after Atom 1.13, I think they probably treat the whole .markdown file as plain text now, so that whatever the syntax theme you choose the color will remain the same.

**Comment by shd101wyy** [comment]
Hi @kenpuluma , sorry for my late reply.

This issue should be fixed now.  

Cheers :)

**Comment by shd101wyy** [comment]
PS: Seems atom does changed how it define syntax class. It now prepend `syntax--` to all css classes.

**Comment by kenpuluma** [comment]
@shd101wyy Problem solved, Thank you!
