### ISSUE TITLE
請問 plantuml diagram

### ISSUE THREAD

**Issue by KaichunChangVIA** [shd101wyy/markdown-preview-enhanced#244]
win7環境有裝 java
atom 新裝好的
把內建的 markdown-preview 關掉後
到 atom setting install packages 裝上大大的 markdown-preview-enhanced

跑下面的 code 後
訊息看似少裝了Graphviz，請問是去 atom setting install packages 找哪個一個裝?還是要從哪裡裝?

![intro](https://i.imgsafe.org/45c601e688.png)

**Comment by shd101wyy** [comment]
Hi @KaichunChangVIA ,  

![screen shot 2017-01-22 at 1 23 22 pm](https://cloud.githubusercontent.com/assets/1908863/22185151/fa6d1de8-e0a5-11e6-843b-8f930e48951d.png)  

你需要到 [Graphiz](http://www.graphviz.org/) [下載頁](http://www.graphviz.org/Download..php) 的網站下載並安裝 `graphviz`，然後就可以使用了。

謝謝 :)

**Comment by shd101wyy** [comment]
Hi @KaichunChangVIA ,  

![screen shot 2017-01-22 at 1 23 22 pm](https://cloud.githubusercontent.com/assets/1908863/22185151/fa6d1de8-e0a5-11e6-843b-8f930e48951d.png)  

你需要到 [Graphiz](http://www.graphviz.org/) [下載頁](http://www.graphviz.org/Download..php) 的網站下載並安裝 `graphviz`，然後就可以使用了。

謝謝 :)
