### ISSUE TITLE
Cache无法清除

### ISSUE THREAD

**Issue by coolboy0961** [shd101wyy/markdown-preview-enhanced#249]
用plantuml画图并插入md的时候，经常需要修改然后覆盖图片。
现在的情况是尽管我覆盖了图片，但还是无法在preview中显示出修改后的样子。
我觉得应该是cache一直没有清除，不改名字就不能更新导致的。

希望能够增加图片是否改变的检查并更新功能。或者添加一个clear cache的按钮也可以。

**Comment by shd101wyy** [comment]
Hi @coolboy0961 ,

请参考 [#144](https://github.com/shd101wyy/markdown-preview-enhanced/issues/144)
我记得我原来支持过不缓存的图片，但是效果非常不好，preview 会发生闪动。所以我就决定不支持了。  
你可以在 image url 后面加上 `?1` ，然后手动改变数字就好了。

谢谢

**Comment by coolboy0961** [comment]
谢谢，OK了👌
