### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by Niefee** [shd101wyy/markdown-preview-enhanced#250]
我在setting那里的update想更新这个插件，总是无法完成更新。其他插件都可以的，就这个插件不行。

**Comment by shd101wyy** [comment]
Hi @Niefee ,

不太清楚，可能是网络问题。试试从 command line 更新？`apm upgrade markdown-preview-enhanced`。最好贴一下错误的信息，要不然我也无法知道为啥会这样。

谢谢
