### ISSUE TITLE
Use of wrong syntax theme

### ISSUE THREAD

**Issue by rolandg** [shd101wyy/markdown-preview-enhanced#254]
I set the preview option to GitHub syntax but it uses the Syntax theme of the editor.

![image](https://cloud.githubusercontent.com/assets/1443267/22507783/6d9d222a-e887-11e6-953e-5897c6618de7.png)

**Comment by shd101wyy** [comment]
Hi @rolandg 

This is weird. Does restarting atom help?

Thanks

**Comment by shd101wyy** [comment]
And what syntax theme are you using?

**Comment by rolandg** [comment]
No doesn't help. 
I tried Atom Dark and Onedark Theme. 
It is readable with bright themes but does always use syntax theme and not Github syntax.

**Comment by shd101wyy** [comment]
Which version of atom are you using?

**Comment by rolandg** [comment]
v 1.13.1

**Comment by shd101wyy** [comment]
I think I will need to see your css.  
Please do the following steps:

1. Open atom, then click `View` -> `Developer` -> `Open in Dev Mode` and open a markdown file.  
2. Change the content of the markdown file to the following:  
<pre>
```java 
function add(x, y) {
    return x + y
}
```
</pre>  
  
![screen shot 2017-02-05 at 1 22 49 pm](https://cloud.githubusercontent.com/assets/1908863/22629145/42cf21ca-eba6-11e6-9854-5ecdc11e95e3.png)


3. right click at `public` in the **preview**, from the context menu, choose `Inspect Element`  
![screen shot 2017-02-05 at 1 24 11 pm](https://cloud.githubusercontent.com/assets/1908863/22629154/6807ca8c-eba6-11e6-8409-6fc423adb919.png). If you do it correctly, `public` should be highlighted in blue and a developer panel will be open.   
![screen shot 2017-02-05 at 1 26 25 pm](https://cloud.githubusercontent.com/assets/1908863/22629178/b7edd0d2-eba6-11e6-964a-ede872ea470e.png)

4. Give me a screenshot of `Styles` section like this:  
![screen shot 2017-02-05 at 1 26 12 pm](https://cloud.githubusercontent.com/assets/1908863/22629182/ccabae9a-eba6-11e6-8b11-3dcb9befa584.png)  

Thanks

**Comment by rolandg** [comment]
![screenshot_20170205_230044](https://cloud.githubusercontent.com/assets/1443267/22630266/2fe23ee8-ebf7-11e6-8af7-23d0793b007e.png)
![screenshot_20170205_230107](https://cloud.githubusercontent.com/assets/1443267/22630267/357e78da-ebf7-11e6-947f-9ebc8c61afcc.png)
![screenshot_20170205_230129](https://cloud.githubusercontent.com/assets/1443267/22630270/3ae09286-ebf7-11e6-8501-3abd80678bd5.png)
![screenshot_20170205_230158](https://cloud.githubusercontent.com/assets/1443267/22630271/3ec4d4d4-ebf7-11e6-945b-326a81916aae.png)

**Comment by shd101wyy** [comment]
Could you please also post a screenshot like this? Thanks  
![screen shot 2017-02-05 at 1 21 31 pm](https://cloud.githubusercontent.com/assets/1908863/22630419/7d0ead56-ebbf-11e6-9627-cad946614917.png)

**Comment by shd101wyy** [comment]
Sorry, please make sure this is selected (the `<span>public</span>` in blue), and then take a screenshot of `styles`.  
Seems you sent me a wrong one.  
![screen shot 2017-02-05 at 4 30 11 pm](https://cloud.githubusercontent.com/assets/1908863/22630481/72527716-ebc0-11e6-98ac-6ea69ff57729.png)

**Comment by rolandg** [comment]
Ok now it should be right. Also c, js are wrong..
![screenshot_20170206_120429](https://cloud.githubusercontent.com/assets/1443267/22644993/2e7eb55e-ec65-11e6-8d82-4faf391c3efb.png)
![screenshot_20170206_120509](https://cloud.githubusercontent.com/assets/1443267/22645008/3d83574e-ec65-11e6-8f6d-8c7b0e343293.png)
![screenshot_20170206_120616](https://cloud.githubusercontent.com/assets/1443267/22645012/415f3c48-ec65-11e6-948d-72ff1baa68ec.png)
![screenshot_20170206_120653](https://cloud.githubusercontent.com/assets/1443267/22645016/43d3901e-ec65-11e6-8814-aeb347b8d1a5.png)

**Comment by shd101wyy** [comment]
This is very weird. Could you please try reinstalling this package? Sorry for the trouble.

**Comment by shd101wyy** [comment]
Mine (`Atom Material`) looks like this:    

![screen shot 2017-02-06 at 1 16 45 pm](https://cloud.githubusercontent.com/assets/1908863/22662436/a39b094c-ec6e-11e6-892b-b1873175e866.png)

Seems yours is `.syntax--storage` but mine is `.storage` directly, that is the reason.   
I think this issue should have been fixed in newest version.  
Try upgrading this package or reinstalling it.   

Thanks

**Comment by rolandg** [comment]
I am already on 0.9.5 and reinstalling did not help.
I also had no luck with updating atom-beta to 1.13.1 (from about text) 1.14 (AUR).

Thaks

**Comment by shd101wyy** [comment]
Ok i see, I will try to find a way to fix it when I have time.  
Sorry for the trouble though :(

**Comment by shd101wyy** [comment]
Sorry, one more question.  
What operating system are you using?

**Comment by rolandg** [comment]
I'm on Arch Linux

**Comment by shd101wyy** [comment]
I think we need to wait for atom `1.14` to be released.  
I just did an experiment, and it seems that atom `1.13` and `1.14` beta use different versions of `highlights` library.   
I am not sure whether or not `Arch Linux` is the reason that caused this issue. So let's just wait for atom `1.14`.  
Thanks

**Comment by shd101wyy** [comment]
Hi @rolandg , should be fixed now.  
Cheers

**Comment by rolandg** [comment]
Hi,
yes it works since 1.14.1.

**Thank You**
