### ISSUE TITLE
Object.extname is deprecated.

### ISSUE THREAD

**Issue by orgwem** [shd101wyy/markdown-preview-enhanced#255]
Argument to `path.extname` must be a string
```
Object.extname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:20:10)
<unknown> (/Users/Michael/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:150:58)
Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:616:7)
Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
Object.activate (/Users/Michael/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:143:49)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:191:19)
```

**Comment by nedpark** [comment]
Object.extname - /Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:20:10
<unknown> - /Users/nedpark/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:149:58
Config.observeKeyPath - /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:616:7
Config.observe - /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21
Object.activate - /Users/nedpark/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:143:49
Package.activateNow - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:19

**Comment by shd101wyy** [comment]
Hi all,  
I never met this issue. What operating system are you using?  
Thanks

**Comment by laris** [comment]
Windows10

**Comment by shd101wyy** [comment]
Hi @laris , is that a warning or an error? Does it affect the use of this package?

**Comment by Flauschbaellchen** [comment]
Hi @shd101wyy,
I have the same issue.
It is listed within the "Deprecation Cop" under "Deprecated calls".
I'm currently using Atom 1.14.0-beta3 with version 0.9.11 of your package.
As far as I can see this dows not affect the funtionality.

**Comment by shd101wyy** [comment]
Should be fixed now.  
Cheers.
