### ISSUE TITLE
Feature request: include other markdown files within document

### ISSUE THREAD

**Issue by docsteveharris** [shd101wyy/markdown-preview-enhanced#256]
Amazing package 👍 Thank you!
Is something like this possible too?

https://www.npmjs.com/package/markdown-include

**Comment by shd101wyy** [comment]
Hi @docsteveharris ,

Yes I am planning to support importing other docs in the future. [#207](https://github.com/shd101wyy/markdown-preview-enhanced/issues/207).  

Thanks

**Comment by shd101wyy** [comment]
Hi @docsteveharris , including external files is now supported. Plz check [this doc](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/doc-imports.md)
