### ISSUE TITLE
support ditaa 

### ISSUE THREAD

**Issue by jzhang** [shd101wyy/markdown-preview-enhanced#258]
the plantuml of latest version has support ditaa, http://plantuml.com/ditaa, but the ditaa only outputs png format. in your program, it first generates svg first and then convert svg to png. 
so ditaa text such as below cannot show properly:

@startditaa
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |diagram|
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
    :                         ^
    |       Lots of work      |
    +-------------------------+
@endditaa

please submmit a patch for it. Thanks!

zczxyz@126.com

**Comment by shd101wyy** [comment]
Hi @jzhang 

Will do.

Thanks

**Comment by shd101wyy** [comment]
Hi @jzhang ,

我刚刚做了下实验，貌似效果不好。
所以还是等 plantuml 支持 svg 吧。

谢谢

**Comment by jzhang** [comment]
谢谢

**Comment by roipoussiere** [comment]
I am concerned by this issue, can you explains the status in english please?

**Comment by shd101wyy** [comment]
So right now I can only render plantuml `svg` graph but not `png` graph. 
`ditta` can only export `png`, so I am not able to display `ditta` graph in preview.  
I think we need to wait until plantuml supports exporting `svg` for `ditta`.
