### ISSUE TITLE
Attension: Big Change coming soon! Version 0.9.6 will abandon how you used to draw graphs.  

### ISSUE THREAD

**Issue by shd101wyy** [shd101wyy/markdown-preview-enhanced#261]
I am planning to release version `0.9.6` this week or next week. (Maybe I will wait till atom `1.14` is released) 
The major new feature for this version is the support of including external files. You can check the  [introduction doc here](https://github.com/shd101wyy/markdown-preview-enhanced/blob/0.9.6/docs/doc-imports.md).    
While implementing this feature, I realized I have to distinguish code chunk with graphs.    

Therefore, <code>\`\`\`{mermaid}</code> will not be supported anymore. Please write <code>\`\`\`@mermaid</code> instead in the future. Same for `@viz`, `@wavedrom`, `@puml` and `@plantuml`.     

![mermaid](https://cloud.githubusercontent.com/assets/1908863/22728790/6a990c9c-eda5-11e6-8f3b-5fed8c798a91.gif)

Feel free to post suggestions here :)
Thanks

**Comment by shd101wyy** [comment]
![doc-imports](https://cloud.githubusercontent.com/assets/1908863/22716507/f352a4b6-ed5b-11e6-9bac-88837f111de0.gif)

**Comment by shd101wyy** [comment]
What do you guys think about changing to <code>\`\`\`@mermaid</code> instead?

**Comment by jalexander8717** [comment]
I think it's an awesome new feature! Since I will probably make my mermaid, plantuml, and graphviz diagrams in their own file now, would it be possible to use markdown-preview-enhanced to view those stand-alone file types while they are being edited?

**Comment by shd101wyy** [comment]
Hi @jalexander8717 ,

No, the update won't be realtime. But you can use the refresh button to refresh the preview.    

![screen shot 2017-02-07 at 5 48 52 pm](https://cloud.githubusercontent.com/assets/1908863/22716917/c7088ae0-ed5d-11e6-8db9-e1ab035a3a2b.png)

**Comment by StefanoCecere** [comment]
no problem at converting all ```{mermaid} to ```@mermaid

**Comment by Cphoenix** [comment]
This file import feature is the best thing since sliced bread.
