### ISSUE TITLE
注意：大更改将至。版本 0.9.6 会弃用原先的画图方式。

### ISSUE THREAD

**Issue by shd101wyy** [shd101wyy/markdown-preview-enhanced#262]
我准备这周或者下周发布版本 `0.9.6`。（也可能等 atom `1.14` 发布了再说）  
这个版本的主要新特征是支持外部文件的调用。详细的可以查看这个[文档](https://github.com/shd101wyy/markdown-preview-enhanced/blob/0.9.6/docs/doc-imports.md)。  
在编写这个功能的时候，我发现必须得把 code chunk 和 graphs 的写法分开，否则会出现问题。 

所以 <code>\`\`\`{mermaid}</code> 这种写法将不会再被支持。请在以后写成 <code>\`\`\`@mermaid</code> 。 `@viz`, `@wavedrom`, `@puml` 和 `@plantuml` 也一样。    

![mermaid](https://cloud.githubusercontent.com/assets/1908863/22728790/6a990c9c-eda5-11e6-8f3b-5fed8c798a91.gif)

有什么想法的话请在下面留言，谢谢～

**Comment by shd101wyy** [comment]
![doc-imports](https://cloud.githubusercontent.com/assets/1908863/22716507/f352a4b6-ed5b-11e6-9bac-88837f111de0.gif)

**Comment by shd101wyy** [comment]
你们对于 <code>\`\`\`@mermaid</code> 的更改有什么看法吗？

**Comment by coolboy0961** [comment]
虽然以前的文档需要改，不过置换一下就行也不是大问题。

对新版本十分期待！

**Comment by xu4wang** [comment]
新版本很赞 👍
