### ISSUE TITLE
Regarding Export to HTML

### ISSUE THREAD

**Issue by thiner** [shd101wyy/markdown-preview-enhanced#264]
I wrote a slides show with MPE, and tried to export to HTML. It looks good when I open it in local browser. However, when I share with someone else, it is broken. The root cause is that extra resources (e.g. images) are referenced as absolute path in HTML code. 
I wonder is it possible change it to relative path and copy the resources to the same folder automatically when exports to HTML?

**Comment by shd101wyy** [comment]
Hi @thiner , 

Please make sure you have `CDN` option checked when exporting html.    
[#259](https://github.com/shd101wyy/markdown-preview-enhanced/issues/259)  
I am planning to rename the label to make it more clear.  
Any suggestions?  

Thanks

**Comment by thiner** [comment]
@shd101wyy I checked the option, and it do help to change the JS library path to CDN URL. However, there are some extra local images referenced in slides as well. The images can't be exposed to public network due to company policy. So after export to HTML, the absolute file path impact the resource loading when open it in someone else's computer.

**Comment by shd101wyy** [comment]
Okay I see. I will add one more option tomorrow that uses relative path.

Thank

**Comment by thiner** [comment]
Thanks a lot for your quick response! :smile: 

Regarding the label name, would it be better if change to "Use CDN Hosted Resources"?

**Comment by shd101wyy** [comment]
Hi @thiner , should be fixed now.  
Cheers.

**Comment by thiner** [comment]
Verified, you did a great work! @shd101wyy
