### ISSUE TITLE
preview主题

### ISSUE THREAD

**Issue by tybleo** [shd101wyy/markdown-preview-enhanced#268]
想问下右侧同步预览的pane只能是白色的吗，不能改主题吗，要怎么改呢

**Comment by shd101wyy** [comment]
Hi @tybleo 

<img width="708" alt="screen shot 2017-02-09 at 10 35 39 pm" src="https://cloud.githubusercontent.com/assets/1908863/22814312/215d63ba-ef18-11e6-806b-2ccac383cda0.png">  

可以在设置里面设置。 把 `Use Github.com style` 和 `Use Github.com syntax theme` 给关掉就可以了。

谢谢～

**Comment by shd101wyy** [comment]
Packages 中搜 `markdown-preview-enhanced` 然后可以看待 settings 的按钮。

**Comment by showbye** [comment]
代码没有高亮啊 都是白色的

**Comment by shd101wyy** [comment]
现在这个只能和最新版的 atom 工作，请把 atom 升级到最新版。如果还不行就发我张截图吧。

**Comment by showbye** [comment]
1.4.1确实可以工作了

**Comment by shd101wyy** [comment]
那这个 issue 我就关闭了哦~
