### ISSUE TITLE
cant search this package in atom, why?

### ISSUE THREAD

**Issue by ijnmklpo** [shd101wyy/markdown-preview-enhanced#269]
一开始用synchronize-settings同步了之后这个插件没有安装，然后在atom里搜了一下，直接搜不到这个插件了，是下架了？

**Comment by shd101wyy** [comment]
搜全称，只搜 markdown 的话会搜不到

**Comment by ijnmklpo** [comment]
还真得搜全称才能搜到，我搜Markdown Preview Enhanced这样都搜不到，谢谢啦，插件超棒的

**Comment by blankxiv** [comment]
![image](https://user-images.githubusercontent.com/65127570/83958440-51480a00-a8a4-11ea-8f67-869bf1405b20.png)
显示不出来怎么办啊
