### ISSUE TITLE
Suggestion: code chunks markdown output

### ISSUE THREAD

**Issue by cdsousa** [shd101wyy/markdown-preview-enhanced#271]
In addition to `html`, `text`, `png` and `none`, it would be nice if code chunks supported `markdown` output.

**Comment by shd101wyy** [comment]
Hi @cdsousa,

Thanks for your suggestion. I will try to add the support in the future when I have time.

Thanks

**Comment by shd101wyy** [comment]
Hi @cdsousa , it is now supported.  
Cheers :)
