### ISSUE TITLE
在Presentation中如何定义字体颜色？

### ISSUE THREAD

**Issue by rainmisty** [shd101wyy/markdown-preview-enhanced#272]
了解到可以定义幻灯的尺寸、背景颜色，如何定义字体和字体颜色呢？谢谢！

**Comment by shd101wyy** [comment]
Hi @rainmisty ,

你需要 `cmd+shift+p` 然后 `Markdown Preview Enhanced: Customize Css`，接着编辑 `style.less` 文件。

谢谢

**Comment by shd101wyy** [comment]
可以编辑这个部分 
```less
// custom presentation style
.preview-slides .slide,
&[data-presentation-mode] {
  // eg
  // background-color: #000;
}
```

**Comment by simoxi** [comment]
你好 @shd101wyy 请问怎么定义字体呢？比如想换成微软雅黑或者google的那个开源字体~
