### ISSUE TITLE
scroll bug

### ISSUE THREAD

**Issue by cuyl** [shd101wyy/markdown-preview-enhanced#273]
在 Settings-Editor-Scroll Past End 打上勾的时候，md滑到底的时侯preview会跳到前面。

**Comment by shd101wyy** [comment]
Hi @cuyl ，谢谢你的回复

这个我还真没注意过，我争取在下个版本修复这个问题。  

谢谢

**Comment by cuyl** [comment]
还有就是往回滚到顶部的时候也回不到起点

**Comment by shd101wyy** [comment]
嗯，话到顶点就是那么设计的。这时候是根据 cursor 的位置来判断的

**Comment by shd101wyy** [comment]
merge 之后的新版本发布了。非常感谢你的 pull request :)

**Comment by cuyl** [comment]
没啥啦，也就改了一行代码
