### ISSUE TITLE
Code block wasn't highlighted.

### ISSUE THREAD

**Issue by wafer-li** [shd101wyy/markdown-preview-enhanced#274]
![image](https://cloud.githubusercontent.com/assets/12459199/22856623/2874bd3a-f0d8-11e6-8471-eb096022bb0d.png)

Syntax theme: One Dark 1.6.0
Language Pack: language-markdown 0.19.1

How can I fix it?

**Comment by shd101wyy** [comment]
Hi @wafer-li , 

请更新 atom 到最新版。

谢谢

**Comment by wafer-li** [comment]
@shd101wyy 
:sweat_smile:

乡下网络太慢了，不好意思。
到时候我自己关了吧。

**Comment by shd101wyy** [comment]
😄哈哈没关系，如果升级完了还有问题的话就再把这个 issue 打开吧。
