### ISSUE TITLE
Deploying Presentation on GitHub Pages?

### ISSUE THREAD

**Issue by thancock20** [shd101wyy/markdown-preview-enhanced#276]
I made a presentation and exported it as an HTML file. When I open the file directly in the browser, everything works perfectly.

However, when I put the HTML file on GitHub and tried to open it on GitHub pages, all I get is a blank page with the background color of the first slide.

Is there some step I'm missing to make the HTML file work on GitHub pages, or is not possible?

**Comment by shd101wyy** [comment]
Hi @thancock20 ,

Please make sure that you have  `Use CDN hosted resources` checked.  

![screen shot 2017-02-15 at 11 30 06 am](https://cloud.githubusercontent.com/assets/1908863/22986757/2b643eac-f372-11e6-9c62-fb3310345749.png)   

Here are some related issues.  [#264](https://github.com/shd101wyy/markdown-preview-enhanced/issues/264) [#259](https://github.com/shd101wyy/markdown-preview-enhanced/issues/259)  

Thanks

**Comment by thancock20** [comment]
That worked. Thank you. Seems like a good candidate for an FAQ.

**Comment by shd101wyy** [comment]
Good idea. I will add `FAQ` section in readme.
