### ISSUE TITLE
Syntax Highlighting not working

### ISSUE THREAD

**Issue by PaulBrownMagic** [shd101wyy/markdown-preview-enhanced#279]
I've installed this today and spent a couple of hours trying to figure out why I can't get syntax highlighting to work properly.

![screenshot from 2017-02-17 01 58 02](https://cloud.githubusercontent.com/assets/10325887/23049596/16a493ba-f4b5-11e6-8d49-01b6cbda048b.png)

If I don't use the Code Chunks syntax it will highlight only in the editor. Otherwise it doesn't highlight in the editor, preview, browser or pdf. In the browser the tags have appropriate classes for syntax highlighting but the css for the colours isn't present. Changing Atom theme and the GitHub options makes no difference, even with restarting Atom. I'm running this on Debian GNU/Linux.

**Comment by shd101wyy** [comment]
Hi,  

If you want syntax highlighting of code chunk and graphs in editor, try installing [language-gfm-enhanced](https://atom.io/packages/language-gfm-enhanced) and disable `language-gfm`. Also install `language-dot`, `language-mermaid`, and `language-plantuml` if you want syntax highlighting for graph code.  

As for why the syntax highlighting doesn't work in the preview, I am also very confused. What atom syntax theme are you using?  Make sure you installed atom from the official website but not from the Debian repo. Furthermore, make sure you are using the newest version of atom (right now it's `1.14.2`).   

Thanks

**Comment by PaulBrownMagic** [comment]
Thanks shd101wyy,

I followed all the steps, had to do a complete build of atom from source for Debian, but it is now working:
![screenshot from 2017-02-17 17 39 43](https://cloud.githubusercontent.com/assets/10325887/23076381/1d2df73e-f538-11e6-9e57-f8098997f567.png)
That is a thing a beauty. Great work on this package!

Now I just have to fix my tool-bar that broke in the rebuild...
