### ISSUE TITLE
atom-markdown-katex does not work 'out of the box' upon manual installation.

### ISSUE THREAD

**Issue by dbusbridge** [shd101wyy/markdown-preview-enhanced#28]
Situation: I am using Ubuntu behind a proxy that prevents me from using atom package management.

When opening using atom-markdown-katex manually
> by downloading the .zip from github, placing it in the ~/.atom/packages folder and then running
```
$ apm link
```

I get the following three issues when loading atom:

1. Error compiling Less stylesheet: /home/user/.atom/packages/atom-markdown-katex/styles/atom-markdown-katex.less
Line number: 4
'../node_modules/mermaid/dist/mermaid.css' wasn't found

2. Failed to load the atom-markdown-katex package
'../node_modules/mermaid/dist/mermaid.css' wasn't found in /home/user/.atom/packages/atom-markdown-katex/styles/atom-markdown-katex.less:4:2
The error was thrown from the atom-markdown-katex package. atom-markdown-katex is out of date: 0.5.8 installed; 0.5.9 latest. Upgrading to the latest version may fix this issue.

3. Failed to activate the atom-markdown-katex package
Cannot find module 'katex'
The error was thrown from the atom-markdown-katex package. atom-markdown-katex is out of date: 0.5.8 installed; 0.5.9 latest. Upgrading to the latest version may fix this issue.

If I run
```
$ npm install /home/user/.atom/packages/atom-markdown-katex
```
then npm downloads all of the dependencies for atom-markdown-katex.

I appreciate this is not a bug of atom-markdown-katex, however, since atom-markdown-katex does not work 'out of the box' during a manual installation, I thought it would be worth adding a line to the package documentation on git as this took me a while to figure out.

Awesome package by the way!

Thanks, Dan

**Comment by shd101wyy** [comment]
Hi @dbusbridge , thanks for your reply.
I will add documentation for developer in next release. 
I am planning to change the package name, so all doc will be updated soon.

**Comment by shd101wyy** [comment]
Hi @dbusbridge , the manual installation instruction has been added to the doc. Thanks for your advice ;)
