### ISSUE TITLE
How do I get my Markdown Preview to be a dark theme?

### ISSUE THREAD

**Issue by parlays** [shd101wyy/markdown-preview-enhanced#281]
My markdown preview window is a white theme like Github, but on the Markdown Preview Enhanced documentation, the first image shows the preview in dark theme.  How do I get it to look like the first image preview with a dark theme on the markdown view?  thanks!

**Comment by shd101wyy** [comment]
Hi @parlays ,

Open `Settings` -> `Packages` -> `markdown-preview-enhanced` -> `Settings`.  
Disable the following checkbox.   

![screen shot 2017-02-17 at 12 17 53 am](https://cloud.githubusercontent.com/assets/1908863/23054618/ac6b83ae-f4a6-11e6-8053-fbafd93bcb19.png)   

This will make the style be consistent with your atom theme.  

Thanks.

**Comment by parlays** [comment]
Thank so much!  I'm new to Atom.  I had tried clicking on configure but I didn't see all the new options when scrolling down.  Appreciate the help :)
