### ISSUE TITLE
Nesting not supported in numbered lists

### ISSUE THREAD

**Issue by BenLatham** [shd101wyy/markdown-preview-enhanced#283]
In markdown-preview-enhanced it is not possible to nest ordered lists as you can with unordered lists.
It would be very helpful if this ability were present.

While github also does not seem to support multi-level ordered lists, they are available in markdown-preview.

**Comment by shd101wyy** [comment]
Hi @BenLatham,

Could you please paste an example here?

Thanks

**Comment by shd101wyy** [comment]
Because I think it should be already supported.

**Comment by shd101wyy** [comment]
I think it might be caused by identation.  
1. haha
2. yoo
    1. gg
    2. gugu

you need 4 spaces:  
```
1. haha
2. yoo
    1. gg
    2. gugu
```

**Comment by BenLatham** [comment]
Ah, thank you!
It works fine using 4 spaces. I had been using 2 spaces, which explains why my markdown did not convert properly. I'd picked up bad habits as the preview I was using let me. Sorry for wasting your time when there wasn't a real problem.

**Comment by shd101wyy** [comment]
It's fine. I also don't know that before.  
Learnt something new today haha.
