### ISSUE TITLE
Markdown doesn't work in own HTML tags.

### ISSUE THREAD

**Issue by AndreWin** [shd101wyy/markdown-preview-enhanced#284]
Hello!

Markdwon-preview-enhanced ver. 0.9.8.

When I type

```
$\Sigma_{n=0)^\infty$
```

all works fine. But when I use formula in own tags it doesn't parsed. For example the following willn't work:

```
<p>$\Sigma_{n=0)^\infty$</p>
```

Best regards, Andrey.

**Comment by shd101wyy** [comment]
Hi @AndreWin ,

I don't think it is supported to write formula in your own tags. You can only write it outside HTML tags.

Thanks

**Comment by AndreWin** [comment]
@shd101wyy , but formula always will be in any tag. At least `html` and `body`. I used Mathjax in `.html` files and it worked inside of any tags... It seems to me there is just some setting that prevent Mathjax to parse formulas inside of any tags...

**Comment by shd101wyy** [comment]
@AndreWin , I think that is because the markdown parser [remarkable](https://github.com/jonschlinkert/remarkable) that I am using doesn't support parsing inside html tags.  
Please check this [issue #216](https://github.com/jonschlinkert/remarkable/issues/216)    
Sorry about this.

**Comment by AndreWin** [comment]
Hm... It seems to me, parsing markdown and parsing formula aren't the same. I think Mathjax can search formulas, not remarkable.

I will check tomorrow if marked not parse markdown in tags. As far as I remember it doesn't has such problem...

**Comment by shd101wyy** [comment]
For my implementation, I only parse formulas inside `$...$` and `$$...$$`, therefore I need to use a markdown parser to find all the math blocks first, then render them by MathJax.  
So I didn't apply MathJax to the whole preview html.

**Comment by shd101wyy** [comment]
If I remember correctly, `marked` doesn't have this problem.  
But I need `remarkable` to implement scroll sync.

**Comment by AndreWin** [comment]
Maybe code just need to search `$...$` and `$$...$$` after parsing it but before rendering? But to be honest I don't sure if this will work... My idea is that preview pane is just html page (if I understand correctly) and Mathjax should be work as on static site.

**Comment by shd101wyy** [comment]
But I think your way will affect performance a lot.  
Sorry, may I ask why you want to write formulas inside html tags?

**Comment by AndreWin** [comment]
Yes, of course. But I'd like to answer tomorrow. I'm busy now, sorry.

**Comment by AndreWin** [comment]
Hello! I write notes for technical book that describes how to calculate a precision of metallworking or any other machine. There are some images in this book and in my notes and they should be numbered and have caption. I created the following:

```
<div class="numbered img">
  <img src="imgs/img_04.png">
  <div class="caption">Соединение двух деталей как совмещение координатных систем $\Sigma_0$ и $\Sigma_в$, построенных на основных и вспомогательных базах</div>
</div>
```

My CSS for this block:

```
body {
    counter-reset: img_num;
  }
  .numbered.img .caption {
    counter-increment: img_num;
  }
  .numbered.img .caption::before {
    content: "Рис. " counter(img_num) ". "
  }
```
Russian рис. is shorten of рисунок (figure in English).

Best regards, Andrey.

**Comment by shd101wyy** [comment]
Hi @AndreWin , you can now enable `MathJax processEnvironments` options.    

![screen shot 2017-02-20 at 1 03 37 am](https://cloud.githubusercontent.com/assets/1908863/23115132/8588bd88-f708-11e6-847b-e47426563cba.png)    

However, it will be very slow as MathJax function will be called everytime you make changes in your markdown file.  

Therefore, it is recommended to disable `Live Update` if you enable `MathJax processEnvironments`.  
You can disable `Live Update` by running `Markdown Preview Enhanced: Toggle Live Update`.  

Cheers

**Comment by AndreWin** [comment]
Thank you very much!) I'll test it today.

**Comment by AndreWin** [comment]
Hello! The new feature works like a sharm! :-)
I even didn't turn off live update!
Thank you very much!)
