### ISSUE TITLE
Gitlab PlantUML compatibility

### ISSUE THREAD

**Issue by jmatsushita** [shd101wyy/markdown-preview-enhanced#286]
Hi there,

It would be great to allow more standard markdown code fencing (i.e. without the `@`) to support for instance [Gitlab PlantUML integration](https://github.com/gitlabhq/gitlabhq/blob/master/doc/administration/integration/plantuml.md#creating-diagrams)

**Comment by shd101wyy** [comment]
Hi @jmatsushita ,

I will add a configuration button that allows you to render graphs by standard code fencing directly in settings page.

Thanks

**Comment by shd101wyy** [comment]
@jmatsushita , done.  
Now both <code>\`\`\`plantuml</code> or <code>\`\`\`@plantuml</code> are supported by default.  
If you only want <code>\`\`\`@plantuml</code> to work, disable `Use standard code fencing for graphs`.

**Comment by shd101wyy** [comment]
closing this issue.
