### ISSUE TITLE
关于python代码的解析问题

### ISSUE THREAD

**Issue by orgliny** [shd101wyy/markdown-preview-enhanced#287]
代码示例：
``` python
def func(x->int,y->int)->int:
  pass
print(func.__annotations__)
```
在定义函数的时候不能识别这种方式，会导致后续写的代码，在编辑中没有高亮显示，全部为灰色。

**Comment by shd101wyy** [comment]
Hi @orgliny ,

 我没有遇到这个问题，能否发我下完整的 code snippet

谢谢

**Comment by shd101wyy** [comment]
这个插只做 preview。关于代码高亮，可能是 [language-gfm](https://github.com/atom/language-gfm) 的问题。

**Comment by orgliny** [comment]
好的，非常感谢~

**Comment by shd101wyy** [comment]
如果发现问题请继续留言哈～
