### ISSUE TITLE
local image/picture file rendering

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#29]
Is it possible to preview local image file? like:

```
![some Picture](picture_file_name.jpg)

```

**Comment by xu4wang** [comment]
OK. I realized it is supported already.. amazing.
What I need now is to define the size of embedded picture.  :-)

**Comment by shd101wyy** [comment]
Hi @xu4wang , you can define the size of image by using `img` tag instead of using `![]()`.
for example 

```html
<img src="picture_file_name.jpg" width="300" height="300">
```

**Comment by xu4wang** [comment]
Thanks. I confirm the `img` tag works. :-)
