### ISSUE TITLE
Scrolling sync is off

### ISSUE THREAD

**Issue by rlam3** [shd101wyy/markdown-preview-enhanced#292]
Scrolling sync is off
Starting off scrolling is in sync but when you scroll up again to the top. It will be off.

**Comment by shd101wyy** [comment]
Hi @rlam3 ,

Try restarting atom? Or send me a gif of how this issue happens.   

Thanks

**Comment by rlam3** [comment]
Should i disable the markdown-preview too? Still seems a bit off. Even after restart. Where do you see live update disabled?

**Comment by shd101wyy** [comment]
Can you send me a gif or video of your case.

**Comment by rlam3** [comment]
![mar-02-2017 12-07-32](https://cloud.githubusercontent.com/assets/1154044/23520511/f55ecb94-ff40-11e6-951b-e3160bdb7ff6.gif)

Scrolling downward is okay. 
But scrolling to the top of the markdown file. It doesn't go all the way back up until I scroll it myself.

**Comment by shd101wyy** [comment]
Yes it is intentionally designed like that.  
If you scroll the preview, then the middle of preview will match the middle of editor.  
So after you scroll your editor to the most top, you need to use your mouse to do sync.  
Try just click at the first line.

**Comment by shd101wyy** [comment]
Try move your cursor

**Comment by rlam3** [comment]
@shd101wyy Oh. it syncs to the cursor? Not to the scroll of the mouse? Felt so odd... no wonder. Is there a way to sync with mouse as well?

**Comment by shd101wyy** [comment]
I think it makes more sense to make preview match your cursor position.  
So the line at your current cursor in editor will match the corresponding line in the preview.  
I would suggest you to click the first line if you want your preview scroll to the most top.

**Comment by shd101wyy** [comment]
But I will consider your way.

**Comment by shd101wyy** [comment]
So you want 
> when editor is scrolled to the most top, scroll preview back to top.    

 But not 
> when preview is scrolled to the most top, scroll editor back to top.   

Or both?

**Comment by rlam3** [comment]
I think i prefer both. Cursor to control the scrolling.
And scrolling with mouse to control the .md file and sync the preview with the scrolling of the mouse. 

It allows the user to choose between the two when working. :)

Thanks!

**Comment by shd101wyy** [comment]
Hey @rlam3 ,  

Done

Cheers

**Comment by rlam3** [comment]
@shd101wyy Thanks!
