### ISSUE TITLE
image problem

### ISSUE THREAD

**Issue by weigq** [shd101wyy/markdown-preview-enhanced#293]
hi, 
when I insert an image into the markdown file with following:
```![alt text](/path/to/img.jpg "Title")```
why it does not show the "Title" of the image, which is a grammar of markdown language.
thanks！

**Comment by weigq** [comment]
@shd101wyy

**Comment by shd101wyy** [comment]
Hi @weigp ,

What do you mean it doesn't show title? You mean title is not displayed in preview?

Thanks

**Comment by weigq** [comment]
oh! I mean:
now the image inserted to the file is like:
`![alt text](https://raw.githubusercontent.com/weigq/image-raw/master/1.PNG)`
![image](https://raw.githubusercontent.com/weigq/image-raw/master/1.PNG)

and when I click the image and zoom it, the title of the image `alt text `will show below the image:
![1](https://raw.githubusercontent.com/weigq/image-raw/master/2.PNG)

what can I do to let the title show below the image just without not clicking it, like this:
![2](https://raw.githubusercontent.com/weigq/image-raw/master/3.PNG)

oh! it`s not a big problem, I can just enter the title as text below the image. 
thanks!

**Comment by shd101wyy** [comment]
I don't think showing title below image is a feature of markdown.  
No markdown preview does that, so I suggest you adding title manually.  
Thanks :-)

**Comment by vjagodnik** [comment]
Still, even I have an issue with image preview if code is written this way:
![alt text](/user/example/image-raw/master/1.PNG)
