### ISSUE TITLE
Customized math expression block indictor cannot use ```math ... ``` 

### ISSUE THREAD

**Issue by alan-lee** [shd101wyy/markdown-preview-enhanced#295]
Cannot define math expression block indictor as follow

\```math
 \\some math expression
 \``` 

many other markdown editors use this indictor, cloud you please help to fix it? many thanks

**Comment by shd101wyy** [comment]
Hi @alan-lee ,  

Why not just use `$...$` and `$$...$$`?  

Thanks

**Comment by alan-lee** [comment]
Hi, shd101wyy

Thanks for your reply.

Since I will share my document with others, but not all the people use Atom as md editor, some other editors are using  ```math as math block indictor. This is more reasonable, we consider it as a code block and the language is "math" 

I think this is a bug not a feature request. Customized math expression block indictor can be set with any words, but  ```math  does not work.

Regards

**Comment by shd101wyy** [comment]
@alan-lee done.
Cheers :)

**Comment by alan-lee** [comment]
many thanks, shd101wyy!  I really like this plugin！
谢谢！
