### ISSUE TITLE
Code block highlighting does not work when exported to pdf:

### ISSUE THREAD

**Issue by BenLatham** [shd101wyy/markdown-preview-enhanced#297]
My code blocks are appropriately highlighted in the preview window, but in the pdf export the code blocks are un-highlighted.

My code:
```
'''java
public void example(){
  int myInt = 23;
  //do stuff
}
'''
```
(I have replaced `` ` ``with `` ' ``in this example as I could not work out how to escape tripple backticks!)

How it appears in preview:
![code_in_md_p_e](https://cloud.githubusercontent.com/assets/17005190/23409044/16ccdb7a-fdc2-11e6-8d48-762163381235.jpg)

How it appears in the exported pdf
![code_in_pdf](https://cloud.githubusercontent.com/assets/17005190/23409027/018d3570-fdc2-11e6-9dcf-d4ac48cae21c.jpg)

Settings in the export dialogue:
Tab: PDF; Format: Letter; Orientation: portrait; Margin: default margin; print background: ticked; Github style: ticked; Open pdf: ticked.

**Comment by shd101wyy** [comment]
Hi @BenLatham ,  

Which version of atom are you using?

Thanks

**Comment by shd101wyy** [comment]
Hi @BenLatham , could you please try upgrading your atom to the newest version `1.14.4` and then check if this issue still happens. Thanks.

**Comment by BenLatham** [comment]
Thanks @shd101wyy !
It is working on ```1.14.4```.

Just to note though ```1.13.1``` is the latest version of Atom available through Ubuntu store, so I expect quite a few people still use it.

I know I can chose my atom theme or github theme for the code block highlighting; is there a way to use a different installed theme?  For example I like to use ```One Dark``` in atom as I find it easy on the eye, however ```One Light``` would look better in my PDF which may need to be printed. If not I can use the work around of switching themes in atom before I export.

**Comment by shd101wyy** [comment]
Ok I see. I will try to find way to let you pick theme.

**Comment by shd101wyy** [comment]
@BenLatham done.  
I have removed `Use Github.com style` and `Use Github.com syntax theme` options.  
To use Github.com theme, install [octocat-syntax](https://atom.io/themes/octocat-syntax). 

Cheers :)

**Comment by BenLatham** [comment]
Thanks!
I've just upgraded to 0.10.5, but I can't seem to get the new way of changing highlighting to work - the preview theme drop-down box is empty. May be a slight bug there.

**Comment by shd101wyy** [comment]
@BenLatham try installing [octocat-syntax](https://atom.io/themes/octocat-syntax) then restart atom.

**Comment by BenLatham** [comment]
Ah, I had just not yet done the restart after installing octocat. It's now working great!
Thank you!

**Comment by shd101wyy** [comment]
Oops that is my fault. This issue should be fixed now :)
