### ISSUE TITLE
AntiVirus: HTML/ExpKit.Gen2 Warning after update

### ISSUE THREAD

**Issue by Semertl** [shd101wyy/markdown-preview-enhanced#299]
Hey There, 

i get a warning of avira antivir while updating:

![grafik](https://cloud.githubusercontent.com/assets/6665519/23500683/29ebc854-ff31-11e6-96f6-48462286c900.png)

... or for english see: https://www.avira.com/en/support-threats-summary-product?tid=5424&threat=HTML%252FExpKit.Gen2&track=1

What happend? Is this truly a security issue?

Thanks for reply,
Fabian

**Comment by shd101wyy** [comment]
Hi @Semertl , 

I think this issue might be related to `request` library, which uses `unsafe eval`. [#303](https://github.com/shd101wyy/markdown-preview-enhanced/issues/303) .   
I have just published a new version to fix this issue.   
Please help check if this issue still happens after  upgrading.  

Cheers
