### ISSUE TITLE
Mermaid support for <div class="mermaid"> Graph</div>

### ISSUE THREAD

**Issue by ankitp94** [shd101wyy/markdown-preview-enhanced#300]
Hi,
I have recently started using mermaid and your extension for writing posts in jekyll on github pages. For that purpose, I have to use mermaid.js to render the graph on client side browser.

I use markdown to write posts and frankly, your support of mathjax environment has been a great help.

Currently, The preview uses

 ``` @mermaid  graph Definition```

 while I have to use `<div class="mermaid"> Graph </div>` for the website.

Can you provide any option to choose between the two for the live preview?

**Comment by shd101wyy** [comment]
Hi @ankitp94 , I am not very familiar with jekyll.  
But here is a way to hack.   
You can check [developer doc](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/extension.md).  

The following steps should solve your problem:   
1. `cmd-shift-p` then run `Application: Open your init script`. This should open `init.coffee` file for your.  
2. copy the following code to `init.coffee`  
```coffeescript  

atom.packages.onDidActivatePackage (pkg)->
  if pkg.name is 'markdown-preview-enhanced'
    #debugger
    #console.log pkg

    pkg.mainModule.onWillParseMarkdown (markdown)->
      markdown = markdown.replace /\<div\s*class\=\"mermaid\"\>([\w\W]+?)\<\/div\>/g, (whole, content)=>
        """
\`\`\`mermaid
#{content}
\`\`\`
        """
      markdown
```

This code will replace  `<div class="mermaid">content</div>` by  
<pre>
```mermaid 
content
```
</prev>

3. **restart atom** to take effect.  

Thanks

**Comment by shd101wyy** [comment]
![screen shot 2017-03-02 at 2 21 07 pm](https://cloud.githubusercontent.com/assets/1908863/23525277/7f0c0e58-ff53-11e6-8634-750e1a02efd5.png)

**Comment by ankitp94** [comment]
It worked perfectly.
Thanks a lot!
