### ISSUE TITLE
Cannot display pipe inside table cells

### ISSUE THREAD

**Issue by baijiangliang** [shd101wyy/markdown-preview-enhanced#301]
I have a markdown table row as follows: 
```
|位运算|`&` `^` `|`|
```
I expect two cells to be displayed, and the latter one has an inline code block `|`. But I got three cells instead.

I tried several ways to escape the pipe char in markdown cells: `\|`, `&#124`, none of them worked.

Please take a look. Thanks.

**Comment by shd101wyy** [comment]
Hi @baijiangliang ,  

This seems to be a [remarkable](https://github.com/jonschlinkert/remarkable) issue.  
I am not able to fix it.  

:(

**Comment by BenLatham** [comment]
```&#124;``` produces a pipe and works in a table -
to use a pipe in a code block in a table you could use ```<code>&#124;</code>```
In your question you write ```&#124```, missing the ```;``` could that be your problem?
Hope you find a suitable solution!

**Comment by baijiangliang** [comment]
You are right, Ben. I missed `;`, `<code>&#124;</code>` will work. Thanks!
