### ISSUE TITLE
Preview Theme is empty in v0.10.5

### ISSUE THREAD

**Issue by uframer** [shd101wyy/markdown-preview-enhanced#309]
After upgraded to v0.10.5, preview theme is missing and the "Preview Theme" drop-down list in Settings is empty.

**Comment by shd101wyy** [comment]
Try restarting Atom?

**Comment by uframer** [comment]
@shd101wyy Just tried. I can see a loading page with GitHub logo and then no GitHub theme is applied. Now I suspect the firewall policy of my working network is the killer. I'll try it at home this evening and keep you in sync.

**Comment by shd101wyy** [comment]
@uframer you can also try installing [octocat-syntax](https://atom.io/themes/octocat-syntax) then restart atom.

**Comment by uframer** [comment]
@shd101wyy Brilliant! *octocat-syntax* solved my problem. Thank you for your responses and great work.

**Comment by shd101wyy** [comment]
I actually think it might be my code bug.  
If you meet this issue again, please notify me.  
Thanks

**Comment by uframer** [comment]
@shd101wyy I will verify this issue at home tonight. Hope this can help.

**Comment by uframer** [comment]
@shd101wyy I can confirm this issue on my Mac at home.

**Comment by shd101wyy** [comment]
@uframer should be fixed now. Thanks a lot :)

**Comment by uframer** [comment]
@shd101wyy I upgraded to v0.10.6 and I can see a theme list in *Settings* which resembles the theme list of Atom's *UI Theme*. So I believe this issue is resolved. Thank you.

**Comment by shd101wyy** [comment]
You mean Atom Syntax theme right?

**Comment by uframer** [comment]
The theme list **IS** identical to Atom's *Syntax Theme*, **NOT** *UI Theme*. I mistakenly thought it is *UI Theme" because the contents looks similar. You are right.
