### ISSUE TITLE
wiki style link support

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#31]
Suggest Katex process `[[some_page]]` same as ` [some_page](some_page.md)` in the preview window.

Reason:
`[[page_name]]` syntax is used by some wiki system to link wiki page together, if Katex understand the syntax, Katex can be used as a even better tool for personal wiki, knowledge management ...

PS.
I am currently use nvAtom and Katex together, use nvAtom for wiki page linking and Katex for markdown preview.

**Comment by xu4wang** [comment]
I made a quick hack, the result is in the PR #43

**Comment by xu4wang** [comment]
![wikilink](https://cloud.githubusercontent.com/assets/311397/15804586/af10270c-2b40-11e6-8558-71ac9c84d383.gif)

**Comment by shd101wyy** [comment]
Hi @xu4wang , 

thanks for your pull request. 
It is merged to main branch and I just published a new version.

Thank you

**Comment by xu4wang** [comment]
thanks..
