### ISSUE TITLE
the equation alignment

### ISSUE THREAD

**Issue by weigq** [shd101wyy/markdown-preview-enhanced#310]
hi,
i want to align the equation following the instruction of mathjax: but the the equation cannot align:

![1](https://raw.githubusercontent.com/weigq/image-raw/master/raw/2.PNG)

but  my hexo blog shows this:
![2](https://raw.githubusercontent.com/weigq/image-raw/master/raw/1.PNG)

is this an error?

**Comment by shd101wyy** [comment]
Hi @weigq ,

You are now using KaTeX not MathJax
Try changing the math rendering engine from the package settings.

Thanks

**Comment by weigq** [comment]
oh, thank you ,it`s OK!
