### ISSUE TITLE
use only one window for markdown preview

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#32]
it's peferable to have one and only one window opened for markdown preview, each time a new markdown file is chosen in the edit area, the preview window will be re-freshed and preview the active buffer.

PS.
At the moment, whenever a .md file is clicked, a new window for markdown preview is open. After a while, there will be many preview window.

**Comment by shd101wyy** [comment]
Hi @xu4wang , sorry for my late reply.

Thanks for this idea. I will add this feature support in next release.

**Comment by shd101wyy** [comment]
Hi @xu4wang , now only one window will be open.

Please report any further bugs ;)

Cheers

**Comment by xu4wang** [comment]
Great. I will try it.

**Comment by xu4wang** [comment]
Should I install the github master branch to try?  How to do that? 

PS. I have the package atom-markdown-katex ver 0.5.9 installed from ATOM settings..

**Comment by shd101wyy** [comment]
As I have renamed the package to `markdown-preview-enhanced`, you would have to **uninstall** old `atom-markdown-preview` package, then install `markdown-preview-enhanced`. After the installation is done, you need to restart the package.

**Comment by xu4wang** [comment]
Thanks for the help..it works. and I like the new feature. Thanks!
