### ISSUE TITLE
Used Theme for Screenshots and Gifs?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [shd101wyy/markdown-preview-enhanced#322]
It would be great to mention in the readme which theme was used for creating the screenshots and animations of the readme.

When using a vanilla Atom editor and installing this package, the texts on rendered mermaid diagrams are very much unreadable, because they are dark on dark background. Maybe a recommendation for a theme of the preview pane can be added in the readme? : )

**Comment by shd101wyy** [comment]
Hi,

You can change the preview theme from the package settings. Currently mermaid doesn't work well with dark preview theme, so I recommend you to try a light preview theme. As for the readme gif, I modified the CSS so that the edge of mermaid graph becomes white, but it was originally dark.
