### ISSUE TITLE
language indicator of the code block is case sensitive

### ISSUE THREAD

**Issue by hhysj** [shd101wyy/markdown-preview-enhanced#325]
In the preview page, it can not recognize `Java` of the code block. 

\```Java
public class MyThread extends Thread {
...
}
\```

you must keep it lower case. that is not cool.

Other languages have the same problem.

**Comment by shd101wyy** [comment]
@hhysj 

Done!

Cheers :)

**Comment by hhysj** [comment]
@shd101wyy good job! thank you!
