### ISSUE TITLE
Feature request: TikZ support 

### ISSUE THREAD

**Issue by schlichtanders** [shd101wyy/markdown-preview-enhanced#329]
it would awesome to have a code-fence option for ``TikZ``
this would also solve to #132 

Resources I found so far:

* tikz markdown parser build upon python-markdon https://github.com/neapel/tikz-markdown **This might be the preferrable resource**

* how to compile standalone latex into: http://tex.stackexchange.com/questions/51757/how-can-i-use-tikz-to-make-standalone-svg-graphics
* example implementation for ipython notebook: https://github.com/mkrphys/ipython-tikzmagic/blob/master/tikzmagic_test.ipynb

**Comment by shd101wyy** [comment]
Hi @schlichtanders ,

This is a bit hard. I will have a look when I am free.

Thanks

**Comment by shd101wyy** [comment]
@schlichtanders TikZ is now finally supported. Please check [this doc](https://shd101wyy.github.io/markdown-preview-enhanced/#/code-chunk?id=latex).  
Cheers :)

**Comment by schlichtanders** [comment]
that is awesome!
=)

**Comment by lborg019** [comment]
Perfect timing for my Theory of Algorithms class!
Thanks a bunch! 👍
