### ISSUE TITLE
Unable to close the preview panel with the predefined keystroke

### ISSUE THREAD

**Issue by Khaos** [shd101wyy/markdown-preview-enhanced#33]
It seems impossible to close the preview via `ctrl-alt-o`. 

Version: v0.6.4
ATOM: v1.7.4

**Comment by shd101wyy** [comment]
Hi, @Khaos 

Should be fixed now.

I have changed the keymap to `ctrl+shift+m` . 
Please disable the native `markdown-preview` package to resolve keymap conflict.

Cheers

**Comment by Khaos** [comment]
It works. Ths
