### ISSUE TITLE
Preview does not scroll

### ISSUE THREAD

**Issue by rroopreddy** [shd101wyy/markdown-preview-enhanced#330]
Preview pane does not scroll manually or does not sync to the editor pane scrolling. It is stuck in first page. It used to work, stopped with one of the updates recently.

**Comment by shd101wyy** [comment]
Hi @rroopreddy ,

Can you send me a gif? Or your markdown file.  

Thanks

**Comment by rroopreddy** [comment]
![atom markdown preview enhanced](https://cloud.githubusercontent.com/assets/523806/24077364/3abb9d74-0c08-11e7-91d0-1e5083d400da.gif)

I used test file in this project "code-chunks-test.md". Same behavior with any file. I am using latest version 10.8.0 that is available

**Comment by shd101wyy** [comment]
Restart atom?

**Comment by jyboudreau** [comment]
I have the same issue, this is after updating some other packages and Atom itself.

**Comment by Emphere** [comment]
I am having the same issue as well, along with the rendering looking different. Moreover, trying to open/preview it in browser just results in  a text block stating "undefined".

**Comment by jyboudreau** [comment]
Seems like something was broken between 0.10.2 and 0.10.3. Going back to 0.10.2 fixes the isssue for me. For others who want to want to revert, from the command line:
```
apm install markdown-preview-enhanced@0.10.2
```

**Comment by shd101wyy** [comment]
I will get it fixed as soon as possible.
Thanks

**Comment by shd101wyy** [comment]
Hi @jyboudreau , after upgrading to `0.10.8`, could you please send me a screenshot of package settings?  
![screen shot 2017-03-19 at 1 30 40 pm](https://cloud.githubusercontent.com/assets/1908863/24083619/55283974-0ca8-11e7-98ee-b2dc15eb0418.png)
Is the `Preview Theme` field empty?

Thanks

**Comment by jyboudreau** [comment]
![image](https://cloud.githubusercontent.com/assets/62624/24084038/1c727520-0cb9-11e7-9b03-be78b219c29f.png)

It's not empty, and switching it changes nothing.

**Comment by jyboudreau** [comment]
Here is a screenshot from the config.cson:
![image](https://cloud.githubusercontent.com/assets/62624/24084046/6fe7d8da-0cb9-11e7-820b-5980fceea1f4.png)

As you can see appart from the theme, I have everything else set as default.

**Comment by shd101wyy** [comment]
@jyboudreau which version of atom are you using?

**Comment by jyboudreau** [comment]
1.15.0

**Comment by shd101wyy** [comment]
This is weird, I didnt get this issue. 
What operating system are you using?

**Comment by shd101wyy** [comment]
@jyboudreau it seems that `earthsung-by-jackson-syntax` doesn't work properly with `mpe`.  
I think that theme is outdated as it doesn't use `syntax--` prefix in its `.less` files.  
Does `atom-dark-syntax` work for you?

**Comment by shd101wyy** [comment]
@rroopreddy , @Emphere 
Try changing the `Preview Theme` to `mpe-github-syntax` and restarting atom afterwards?

**Comment by jyboudreau** [comment]
@shd101wyy That does seem to fix the issue. Thanks!

**Comment by Emphere** [comment]
@shd101wyy Yep, that fixes the issue

**Comment by shd101wyy** [comment]
So I think I can close this issue now.
