### ISSUE TITLE
no settings

### ISSUE THREAD

**Issue by Bonjew** [shd101wyy/markdown-preview-enhanced#332]
I download the package from github and used npm to install. The package has no "settings" button. And both Markdown Preview Enhanced and Language GFM Enhanced could not swith the button of enable/disable.

**Comment by shd101wyy** [comment]
Hi @Bonjew ,

Why not just install from atom?
Please check [this instruction](https://github.com/shd101wyy/markdown-preview-enhanced/wiki/Installation)

Thanks

**Comment by Bonjew** [comment]
For I used the Atom material UI theme, the highlight of code did not work in markdown files(I did not know that it is the problem of UI theme).

So I installed the [language-gfm-enhanced] and disabled the [language-gfm]. But the code in the markdown files and the output of the preview did not highlight the code. (The [markdwon-preview] had been disabled either.)

I wanna set the packages, but the packages has no "settings" button. So I deleted the [markdown-preview-enhanced], the [language-gfm-enhanced] and the [language-gfm].

I installed them all again. But I could not enable them, the color of the three packages had been dimmed.

I installed and deleted the three packages several times through different ways, such as npm, apm and click install button in Atom, but the enable/disable button still did not work.

I downloaded the and the [language-gfm2], and they worked. But it was not what I want. 

I installed the [markdown-preview-enhanced] again right now through apm method and it worked. I disabled the [markdown-preview-plus].

Now I'm using the [markdown-preview-enhanced] and the [language-gfm2]. They all get settings button.

But the [language-gfm-enhanced] and the [language-gfm] are still dimmed and no use.

<img width="821" alt="2017-03-21 10 56 45" src="https://cloud.githubusercontent.com/assets/22942317/24155217/2a300390-0e8e-11e7-9056-55727c7abc60.png">

**Comment by Bonjew** [comment]
After I updated the Atom material UI theme, the problem of UI theme that the highlight of code did not work had been solved.

**Comment by shd101wyy** [comment]
You can change preview theme from `markdown-preview-enhanced` package settings.  
I don't understand what you mean by `dimmed`. If you enable the package, then it shouldn't be dimmed.  
My suggestion is to just install from atom.

**Comment by Bonjew** [comment]
I meant the enable/disable button was no use by `dimmed`. I can not switch the package by the button.
