### ISSUE TITLE
Feature Request: Syncronized Scrolling with Slides

### ISSUE THREAD

**Issue by schlichtanders** [shd101wyy/markdown-preview-enhanced#333]
when using slides there seems to be no syncronized scrolling yet. Would be great to have.

thank you so much for this awesome markdown-previewer!!

**Comment by shd101wyy** [comment]
@schlichtanders 

Partially done.    

Now scrolling preview will sync the editor.  
Nevertheless, scrolling editor won't sync preview. I tried to support that, but the effect is bad. So I will not implement it.  

Cheers

**Comment by schlichtanders** [comment]
in fact the preview->editor sync was most important

When I scroll in the editor a simple click enables me to sync the preview to the right spot. That is more than enough as it does the job, is very flexible, and not reduces noise.

thank you very much for implementing this so fast! it works for me after updating to 0.10.10

**Comment by shd101wyy** [comment]
Ok, so I will close this issue :)
