### ISSUE TITLE
希望支持`[TOC]`在预览中显示为内容目录

### ISSUE THREAD

**Issue by deathrush** [shd101wyy/markdown-preview-enhanced#338]
Typora、为知笔记等都支持，希望可以支持这种目录语法。

**Comment by shd101wyy** [comment]
Hi @deathrush , 

请查看 [#220](https://github.com/shd101wyy/markdown-preview-enhanced/issues/220)

谢谢

**Comment by shd101wyy** [comment]
我看这么多人都要求这个 feature，那我有时间的话写下支持吧。

**Comment by shd101wyy** [comment]
@deathrush 搞定了。

谢谢 :)

**Comment by deathrush** [comment]
谢谢S大
