### ISSUE TITLE
!include in plantuml error

### ISSUE THREAD

**Issue by szacchino** [shd101wyy/markdown-preview-enhanced#342]
Hi,
in the same folder of a plantuml script I put a file that contains header and style defintion for a plantuml diagram. Tipically I can include this file in a plantuml script using 
```
...
!include header.puml
...
```
and everything is compiled correctly. Now I put the above script in a plantuml code chunk of a markdown file and copied `header.puml` in the same folder containing the markdown file. The result is the following
![image](https://cloud.githubusercontent.com/assets/1788337/24213218/fc620928-0f31-11e7-9574-77481e0e53c4.png)
caused by plantuml running the code bytes in the home folder and not in the markdown file folder.
Unfortunately I'm not expert in atom plugins so I'm not able to update the build command by myself.

**Comment by shd101wyy** [comment]
Hi @szacchino ,

Could  you please send me your puml files and markdown file as a zip?

Thanks

**Comment by szacchino** [comment]
Sure, here it is. If you run plantuml from this folder it will generate an activity diagram with blue activities. Previewing in atom it will show the error. If you comment the !include statement in test.plantuml the preview will work as expected but header.plantuml is, obviously, not taken into account.

[test.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/865135/test.zip)

Thank you!

**Comment by shd101wyy** [comment]
Oh I see. I am very busy recently, so I will fix this issue when I am free. 
Thanks

**Comment by shd101wyy** [comment]
@szacchino fixed now.  
The refresh button on the right top corner of the preview can help you refresh the graph after you make changes in your plantuml file.
![screen shot 2017-03-26 at 9 07 17 pm](https://cloud.githubusercontent.com/assets/1908863/24338084/45aacda2-1268-11e7-9fe7-70030754c0cd.png)

Cheers
