### ISSUE TITLE
Markdown Parsing Suggestion

### ISSUE THREAD

**Issue by mikegittester** [shd101wyy/markdown-preview-enhanced#344]
Hi 
    Currently, the generated html will add `<p></p>` pairs to list items, like:
```
- this is a line
- next line
```
will get:
```
<ul>
<li><p>this is a line</p></li>
<li><p>next line</p></li>
</ul>
```
shouldn't it be:
```
<ul>
<li>this is a line</li>
<li>next line</li>
</ul>
```
I checked other people's parsers, they don't add <p> to list in this case, so maybe this is an over-head?

thank you

**Comment by shd101wyy** [comment]
Hi @mikegittester ,

HTML is generated by markdown parser called remarkable.
I am not able to modify it.

Thanks
