### ISSUE TITLE
Embed images using Data URI scheme in html export

### ISSUE THREAD

**Issue by kpstolk** [shd101wyy/markdown-preview-enhanced#345]
Would it be possible to add support for embedding images in html using [Data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme#Examples_of_Usage) when exporting to an html file?

Then the html file would be portable and doesn't depend on external sources 🙂

**Comment by shd101wyy** [comment]
Nice idea, I will add the support when I am free. Thanks

**Comment by shd101wyy** [comment]
@kpstolk done.  

![screen shot 2017-03-26 at 9 09 05 pm](https://cloud.githubusercontent.com/assets/1908863/24338110/7d229ac6-1268-11e7-82a2-794d76aecaac.png)

`Embed local images`

Cheers :)

**Comment by kpstolk** [comment]
Thanks, that was quick! 😄 
I've updated to version 0.10.11 but when I click export -> check `Embed local images` it still embeds the files?

I've an image inserted like this:
`![my fancy img.jpg](<my fancy img.jpg>)`

**Comment by kpstolk** [comment]
I figured out what the difference is, it does work but only when the `assets` folder is used like this:
`![my fancy img.jpg](<assets/my fancy img.jpg>)`

Is it also possible to let it work with images directly, so not placed in the `assets` folder?

**Comment by shd101wyy** [comment]
It should be working with all images.  
I will get it fixed when I have time.
Thanks

**Comment by shd101wyy** [comment]
@kpstolk should be fixed now.

Cheers :)

**Comment by kpstolk** [comment]
@shd101wyy Works like a charm now, thanks! 😃
