### ISSUE TITLE
Change default file type in preview from from .md to .markdown?

### ISSUE THREAD

**Issue by clickbrain** [shd101wyy/markdown-preview-enhanced#346]
I am using an app called TrunkNotes for iOS and editing files via Atom on desktop via DropBox. The default markdown extension for files created by TurnkNotes is .markdown, but when I click a link in Markdown Preview in Atom, it creates a new file for the file I want with the extension .md. Ideally, clicking the link to another note will navigate to the note with a .markdown extension that already exists in the directory or create a new file with the .markdown extension. 

I tried reordering the markdown file extensions allowed to have .markdown as the first entry in the config settings and that did not work. How do I default links in preview to seek files with .markdown extension instead of .md? 

Thanks,
Brad

**Comment by shd101wyy** [comment]
Hi, can I see how you wrote the link?
<code>[path](file.markdown)</code>

**Comment by clickbrain** [comment]
[[This is the link]]

Links to another markdown file in same directory. The previewer seems to default to .md. I also have the markdown-writer package installed, but these are links I create without the file name itself.

**Comment by shd101wyy** [comment]
I see. You are using [wiki link](https://help.github.com/articles/adding-links-to-wikis/).    
Why not just use standard markdown link like `[name](path_to_file)`?

**Comment by shd101wyy** [comment]
https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/md.coffee#L319

**Comment by clickbrain** [comment]
These are files created in TrunkNotes which is an organizer of sorts. I've actually told the author to consider making a package like yours for desktop for Atom that carries that across. A big part of the app is creating links between wiki files, without having to create the manual path to them. 

[Trunk Notes website link](http://www.trunknotes.com/)

**Comment by clickbrain** [comment]
Thanks

**Comment by shd101wyy** [comment]
How about I add wikilink default file extension option for you?

**Comment by clickbrain** [comment]
That would be phenomenal! Thanks.

**Comment by clickbrain** [comment]
Let me know if I can contribute in any way.

**Comment by clickbrain** [comment]
Works great!! Thank you.

**Comment by clickbrain** [comment]
Spoke a little too soon. Wiki Links with a space between the words don't have a link in preview that condenses the spaces. I can change wiki links in brackets to no spaces, but would have to revamp a lot of links. 

Example:
[[This Link To New]] creates - This Link To New.markdown
Ideally would truncate and create the preview link of ThisLinkToNew.markdown

**Comment by shd101wyy** [comment]
So you mean I just replace space with empty word?
For example `a b c d` becomes `abcd`?

**Comment by clickbrain** [comment]
Yes.

**Comment by shd101wyy** [comment]
@clickbrain 

Done. You can change it from the package settings.  

![screen shot 2017-03-26 at 9 10 24 pm](https://cloud.githubusercontent.com/assets/1908863/24338147/b9946502-1268-11e7-8804-b298928013e4.png)  

Cheers :)

**Comment by clickbrain** [comment]
Wow man, I really appreciate what you've done for me tonight. Thank you so much. If I can be of any help to you, please let me know. I did point the developer of the app I use - Trunk Notes to your Package, so he may reach out.
