### ISSUE TITLE
Footnote Features Support

### ISSUE THREAD

**Issue by ckdanny** [shd101wyy/markdown-preview-enhanced#35]
For example:
Content [^1]

[^1]: abc: XXXX

**Comment by shd101wyy** [comment]
Hi @ckdanny , the footnote is now supported.

Cheers ;)

**Comment by ckdanny** [comment]
Hi @shd101wyy,
Thanks, this plugin is awesome ;)

**Comment by LfqGithub** [comment]
awesome

**Comment by cossio** [comment]
The footnotes do not work for me on VS Code.

**Comment by mundodisco8** [comment]
@cossio Works for me, did you make sure that you typed the ":" in the footnote, after the "]"?
