### ISSUE TITLE
安装完之后使用插件，一直是“Loading Markdown”

### ISSUE THREAD

**Issue by cyh41** [shd101wyy/markdown-preview-enhanced#350]
Toogle后，一个空的preview出现，然后github的猫一直在转和下面一行“Loading Markdown”....
原版的markdown-preview不会可以正常浏览

**Comment by shd101wyy** [comment]
重启 atom 试试？

**Comment by cyh41** [comment]
还是会诶，但是你的0.8版本是没问题可以正常显示的

**Comment by shd101wyy** [comment]
你用的什么版本的 atom？

**Comment by cyh41** [comment]
1.15.0  x64

**Comment by shd101wyy** [comment]
感觉不应该啊，重装下这个插件试试？

**Comment by cyh41** [comment]
也重装过了...是在github下的，然后复制粘贴到packages，在用npm安装相应需要的插件。
其他插件也是用这种安装方式可以正常安装。实在不行我就用原生或者其他版本好了

**Comment by shd101wyy** [comment]
不太清楚了，试试更改下 package settings 下面的 preview theme?
推荐直接通过 atom 安装，而不是手动安装。

**Comment by cyh41** [comment]
国内安装不了...用vpn也是装不上去..就直接下了

**Comment by shd101wyy** [comment]
😂  

![screen shot 2017-03-29 at 8 33 14 pm](https://cloud.githubusercontent.com/assets/1908863/24483614/f7a64ec0-14be-11e7-92df-5e1abaccf87b.png)

试试更改下这个 `Preview Theme`，然后重启 atom。

**Comment by cyh41** [comment]
为什么我的atom packages 项下面打开你的插件，下面只有readme没有 Settings啊。而且我插件后面多个master

**Comment by shd101wyy** [comment]
我猜想是 local installation 的安装问题。
你运行 `apm link` 命令了吗？

**Comment by cyh41** [comment]
执行之后可以进了settings了，请问一下这句命令是什么意思啊

**Comment by shd101wyy** [comment]
这个命令就是 link package 到 `~/.atom/packages` 路径的意思。
> Create a symlink for the package in ~/.atom/packages. The package in the
current working directory is linked if no path is given.

我猜想是因为没有 link，所以导致了 packages load 的时候路径发生了错误。

**Comment by shd101wyy** [comment]
那么这个 issue 我就关闭了哈～ 😀
