### ISSUE TITLE
Feature Request: local style file for pdf generation

### ISSUE THREAD

**Issue by szacchino** [shd101wyy/markdown-preview-enhanced#351]
Hi,

first of all, thanks again for your amazing project.

Pdf/html generation from markdown (above all prince) should allow users to define a local .less/.css file containing styles definition. Current version allows the user to put those definitions in ~/.atom/styles.less: unfortunately, doing so makes the document folder not portable and does not allow the user to have different styles for different documents.
If this result can be obtained in some other way, please let me know.

**Comment by shd101wyy** [comment]
I think you can write `<style>` directly in your markdown file. But only `css` is supported.  
For example:  
```markdown
<style>
.markdown-preview-enhanced.markdown-preview-enhanced {
    background-color: red;
}
</style>

# Above is the style
```

I might allow you to import 'less' file in the future
For example:
```markdown
@import "my_style.less"

# Heading 1
```

Thanks

**Comment by shd101wyy** [comment]
@szacchino done, you can just `@import "your-style.less"` directly in your markdown file.  
Check [this doc](https://github.com/shd101wyy/markdown-preview-enhanced/wiki/Customize-CSS#local-style).
