### ISSUE TITLE
BUG: the extra cell of the last line is not necessary when importing .csv file.

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/markdown-preview-enhanced#352]
Hi, @shd101wyy.

There is a bug when importing .csv file.

# test.csv

```
a,b,c
1,2,3
```

# test.md

```
@import "test.csv"
```

# test_.md

```
|a|b|c|  
|---|---|---|  
|1|2|3|  
||  <-- the extra cell
```

Best regards.

**Comment by shd101wyy** [comment]
Hi @tmori3y2 

I just tried it and I didn't get that issue.  
Can you send me your files as a zip.

Thanks

**Comment by tmori3y2** [comment]
[TestCsv.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/889923/TestCsv.zip)

Hi, @shd101wyy.

I had created .csv file by Atom Editor.
Atom Editor automatically appended CRLF on saving .CSV file, then markdown-preview-enhanced generated the extra cell.

**Comment by shd101wyy** [comment]
I see, that is because the last line in your `.csv` file is blank. You can remove it.  
I will fix it in the future so that the content will be trimmed.

**Comment by shd101wyy** [comment]
@tmori3y2 should be fixed now.

Cheers :)

**Comment by tmori3y2** [comment]
Thanks a lot !
