### ISSUE TITLE
References in presentations

### ISSUE THREAD

**Issue by adamaltmejd** [shd101wyy/markdown-preview-enhanced#354]
As discussed in https://github.com/shd101wyy/markdown-preview-enhanced/issues/315, it would be great if the pandoc-citeproc filter could be used for presentations as well. One solution could be to instead of having the option to parse the preview using Pandoc, the option would be to run the markdown through Pandoc (and pandoc-citeproc), outputting a new markdown file, before applying the regular parser to produce html. What do you think?

**Comment by shd101wyy** [comment]
@adamaltmejd It's now supported.

Cheers :)

**Comment by adamaltmejd** [comment]
Thanks a bunch :). 

How did you implement this? Using your package with the pandoc parser i frequently find myself turning it on and off because of it lacking some of the nice features (like live update and check lists). If you would you consider implementing pandoc as a filter instead of a parser, and still use Remarkable for the parsing, would that it be possible to keep all the features then? In that case, I think that would be a much better implementation, albeit perhaps being slower.

With a filter i mean that the pandoc process outputs a markdown file instead of html, that you can then feed to Remarkable.

In that case, you could consider automatically turning that filter on if someone specifies a "bibliography" in the frontmatter.

**Comment by shd101wyy** [comment]
I tried to make pandoc as a filter just like what you mentioned, but it doesn't work very well.   
So it will take me a while to find a proper solution to it.  
Thanks

**Comment by adamaltmejd** [comment]
Hmm, do you have any idea why? Maybe I could help look into it. 

Anyways, maybe one thing you could do meanwhile is automatically load the pandoc parser whenever bibliography is defined in the YAML frontmatter. I use references in some documents, not in others. The previewer works so much smoother without pandoc so I tend to turn it on and off. Making this automatic would be nice :)
