### ISSUE TITLE
Numbered TOC badly indented

### ISSUE THREAD

**Issue by YannBrrd** [shd101wyy/markdown-preview-enhanced#355]
When generating numbered TOC, indentation is bad. 

Linter says missing spaces and preview shows a flat TOC instead of subnumbered lists.
![toc](https://cloud.githubusercontent.com/assets/2820034/24698637/b3f91bde-19f1-11e7-880f-b0042824ff29.png)

**Comment by shd101wyy** [comment]
@YannBrrd Oh I see. I will get it fixed in next version.  
Thanks

**Comment by shd101wyy** [comment]
@YannBrrd should be fixed now.

Cheers :)

**Comment by YannBrrd** [comment]
:+1:  Waiting for release then :smile:
