### ISSUE TITLE
cnpm使用的问题

### ISSUE THREAD

**Issue by Neofly1992** [shd101wyy/markdown-preview-enhanced#359]
关于文档中说的 cnpm 安装是使用 git clone 到本地之后 npm install 吗？
这样在需要更新的时候应该怎么办呢？应该卸载插件之后再安装吗？
另外 git clone 之后使用 apm 与 npm 命令有什么区别吗？

**Comment by shd101wyy** [comment]
Hi @Neofly1992 

你如果是 git clone 的话，每次更新就 git pull 然后重新运行 `npm install` 然后 `apm link` 就好了。
如果你 `apm` 没有被墙，就直接 `apm install markdown-preview-enhanced` 就好了。

谢谢

**Comment by shd101wyy** [comment]
更新了下文档，请查看 [这个](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/installation)
