### ISSUE TITLE
Export to html doesn't embed scripts

### ISSUE THREAD

**Issue by kpstolk** [shd101wyy/markdown-preview-enhanced#362]
I've created an export to an html file which I believe should be portable, so no Atom required?

I shared an exported html file with someone and doesn't work because it tries to load:
`file:///C:\Users\<mylocaluser>\.atom\packages\markdown-preview-enhanced\dependencies\reveal\js\reveal.js`
The same is true for these files: `katex.min.css` and `head.min.js`

It would be nice to have an option to embed these kind of files as well just like the css is also embedded.
Or at least make the paths relative when this new option is not checked.
What do you think?

Thanks!

**Comment by shd101wyy** [comment]
You need to have `Use CDN` checked.

**Comment by kpstolk** [comment]
Thanks, that works!
But still, when `Use CDN` is not checked shouldn't it use a relative path instead?

CDN works fine for me so will close this issue.
