### ISSUE TITLE
Feature request: command to switch focus between editor and preview

### ISSUE THREAD

**Issue by baijiangliang** [shd101wyy/markdown-preview-enhanced#363]
Currently the only way to switch focus between editor and preview is moving cursor into the tab and click(am I right?)，which is rather inconvenient since I'm switching focus between editor and preview frequently(e.g. I'm writing at the bottom line of the editor, but the preview hasn't reached the bottom). It would be nice to have a command to switch focus between them, then I can bind a keyboard shortcut to the command.

So what do you say, Yiyi? Is it a feature worth to add? And do you have time to do it?

Thanks.

**Comment by shd101wyy** [comment]
Hi @baijiangliang , Check [this](http://stackoverflow.com/questions/33276971/switch-panes-in-atom-without-cmd-ctrl-k)

**Comment by baijiangliang** [comment]
Oh, I didn't realize preview tab and editor tab are in different panes. Thanks.
