### ISSUE TITLE
No code highlighting for the exported html

### ISSUE THREAD

**Issue by AStupidBear** [shd101wyy/markdown-preview-enhanced#366]
Preview is OK
![2017-04-16_134101](https://cloud.githubusercontent.com/assets/16422976/25069118/7f987918-22aa-11e7-9717-bc342efeb0f2.jpg)
But the exported html is
![2017-04-16_134124](https://cloud.githubusercontent.com/assets/16422976/25069117/7ba3275e-22aa-11e7-9cb2-544e24b2871b.jpg)

**Comment by shd101wyy** [comment]
Hi @AStupidBear ,

Which version of atom and this package are you using?

Thanks

**Comment by AStupidBear** [comment]
Sorry, I forgot to close this issue. After upgrading atom from 1.12.5 to 1.15.0, there's no problem with highlighting. I think that's the problem of Atom, not mpe.
