### ISSUE TITLE
BUG: Cannot link to local files with spaces in filename

### ISSUE THREAD

**Issue by tucknology** [shd101wyy/markdown-preview-enhanced#368]
Hi. I use markdown extensively to keep notes on my local machine. I like to view these notes using markdown-preview-enhanced in Atom. I find it useful to cross reference notes sometimes. For example, I might have a local markdown file about a particular subject, and I want to insert a hyperlink to another local markdown file on a related subject matter. I'd like to be able to click on the hyperlink to quickly open up the related note.

Generally this works fine for simple file names, but sometimes my notes have spaces in the filename. For example, I want to create a link to the related markdown file following this syntax
```
See related [note](</path/to/note with spaces in title.md>)
```

I've used the angle brackets `< >` to tell markdown that the link contains spaces (because without the angle brackets the parser is confused by the spaces), but when I click on the link it tries to open a local file called `/path/to/note%20with%20spaces%20in%20title.md`. It seems the `%20` need to be converted to spaces when opening local files. Any ideas how this can be resolved (I know I could just create files without spaces in the filename, but I am stuck with a lot of old files that I don't want to rename).

Any ideas?

**Comment by shd101wyy** [comment]
Hi @tucknology ,

I see, this is a bug. 
I will get it fixed in next version when I am free.

Thanks

**Comment by shd101wyy** [comment]
@tucknology should be fixed now.

Cheers :)

**Comment by tucknology** [comment]
Thanks for fixing the issue!

**Comment by Kailasa** [comment]
I tried linking files with spaces in the file name, but failed. I guess it should be the same issue here, can anyone have a look at my code and let me know how to fix it? 

`note is [here](</summaries/John et al., 2019, ACE.md>)`

**Comment by acalpixca** [comment]
I have the same issue. 

This markdown:

[Human friendly text - this works well](./prueba.md)
[Human friendly text - this doesn't work](<./202003042247 Cincuate serpiente mexicana.md>)

renders as this:

![image](https://user-images.githubusercontent.com/483802/76038019-26998e80-5f0e-11ea-8579-5e13d866532c.png)

Atom version 1.44.0 for Windows.
Package version: I cloned the github repo just 5 minutes ago.

Any help will be very much appreciated.
