### ISSUE TITLE
Change picture size?

### ISSUE THREAD

**Issue by timedreamer** [shd101wyy/markdown-preview-enhanced#374]
Hi, is there a way to control the picture size using this package? Thanks!

**Comment by shd101wyy** [comment]
@timedreamer you can write html directly. For example
```html
<img src="your_image.png" width="300" height="400">
```
Check [this](http://stackoverflow.com/questions/14675913/how-to-change-image-size-markdown)

**Comment by openshmem** [comment]
@shd101wyy 请问能否考虑一下支持高票答案中的此种语法呢？
```
![](./pic/pic1_50.png =100x20)
```

**Comment by intijk** [comment]
请问能否考虑支持高票答案中的此种语法呢
```
![](./pic/pic1_50.png =100x20)
```
