### ISSUE TITLE
More than one preview pane...?

### ISSUE THREAD

**Issue by ShadowRylander** [shd101wyy/markdown-preview-enhanced#375]
Hello!
My sincerest apologies, as this has *most likely* already been addressed; however, I am having a *very* difficult time finding a way to have `more than one preview pane` at any given time. I also don't know what exactly to search for in the `Issues` field, therefore, if possible, please direct me to the issue where it may have been addressed already.
Thank you!
P.S. : Er... How might I go about generating a `.pdf` file through `markdown-preview-enhanced`, if possible...? Thank you again!

**Comment by shd101wyy** [comment]
@ShadowRylander no this is not supported now, but will in the future.
Thanks

**Comment by ShadowRylander** [comment]
Ah. Thank you very much for the heads-up. I will wait patiently until then. 😆

**Comment by abhayghatpande** [comment]
@ShadowRylander just to give you a heads up, multiple previews feature is now available. Just update the package.

**Comment by ShadowRylander** [comment]
@abhayghatpande Thank you kindly!
