### ISSUE TITLE
In a list , after a code block , the next line can not be aligned correctly

### ISSUE THREAD

**Issue by an15m** [shd101wyy/markdown-preview-enhanced#376]
![1](https://cloud.githubusercontent.com/assets/8855703/25366181/8faf8bb4-29a0-11e7-8f6e-57130e3ef6ba.png)
![2](https://cloud.githubusercontent.com/assets/8855703/25366180/8fa3b4c4-29a0-11e7-8770-1a8f94ca4b1e.png)

**Comment by shd101wyy** [comment]
`引用...` 前面加几个空格试试？

---
例如

* haha
    ```javascript 
    const x = 1
    ```
    Yoo

```markdown
* haha
    ```javascript 
    const x = 1
    ```
    Yoo
```

**Comment by an15m** [comment]
但是github上面不加空格也可以正常对齐，包括atom自带的markdown-preview也可以，我觉得这是一个bug。当然，决定权在你
这是markdown-preview的显示效果：
![1](https://cloud.githubusercontent.com/assets/8855703/25414108/12d0c442-2a62-11e7-9997-d9247a8461be.png)
![2](https://cloud.githubusercontent.com/assets/8855703/25414110/12fe8350-2a62-11e7-8c91-753d1cc17ac1.png)

**Comment by shd101wyy** [comment]
这个不是我这个插件的 bug，因为用的 parser 不一样。我还是建议你加空格吧。  
我用的是 [remarkable](https://github.com/jonschlinkert/remarkable)。

**Comment by an15m** [comment]
好吧，反正影响也不是很大。我去remarkable那里反馈一下试试

**Comment by shd101wyy** [comment]
嗯嗯～

**Comment by an15m** [comment]
我又回来了~
remarkable没有问题。

![3](https://cloud.githubusercontent.com/assets/8855703/25423802/8bbfe168-2a98-11e7-9713-f97b7c9b979e.png)

所以。。。我想应该是你的插件有bug

**Comment by shd101wyy** [comment]
是 [remarkable](https://github.com/jonschlinkert/remarkable)，不是 [Remarkable](https://github.com/jamiemcg/Remarkable)。
