### ISSUE TITLE
import 图片不能正常显示

### ISSUE THREAD

**Issue by lizhuoqi** [shd101wyy/markdown-preview-enhanced#377]
## import 图片不能显示
今天晚上升级到0.12.0，升级前原版本是0.10.10。
升级后，@import "images/image.png"不能正常显示。退到0.10.12都不行，只能先回退到0.10.10。

> 测试了一上，发现问题是由于import的图片路径上的**`/`**特殊符号，在生成html嵌入的路径上被encode成**%5C**。用export to disk生成html文件，在chrome下不能显示图片，在firefox可以。
退回到0.10.10之后，一切照常。再试尝试生成html文件，生成html文件源码中，图片路径无encode。

等待修复后，我再升级。

**Comment by shd101wyy** [comment]
@lizhuoqi 贴一下你的 markdown 文件

**Comment by shd101wyy** [comment]
我试了下，没遇到问题  
![screen shot 2017-04-26 at 2 36 35 pm](https://cloud.githubusercontent.com/assets/1908863/25453217/c6866d72-2a8d-11e7-91b3-fd75668907e4.png)

所以你贴一下你的文件吧，最好是 zip

**Comment by lizhuoqi** [comment]
[issue.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/960382/issue.zip)

```
+---issue
    |   index.md
    |
    +---assets
    |   \---puml
    |           classmodel.svg
    |
    \---contents
            design_datamodel.md
```

* 在design_datamodel.md使用相对路径`@import "../assets/puml/classmodel.svg"`引用图片。
* 在index.md里面引用design_datamodel.md
* 环境windows10，atom-1.16.0
-----
另外，现在我几乎拿atom+markdown-preview-enhanced当做gitbook来用。
如果我的文档内容比较多，需要在 _**`contents`**_ 里面又添加其它的子目录，如果在这些子目录里面编写引用 **_`assets`_** 下图片的md，而这些md文档也被引用到如design_datamodel.md这一级别的md时，在atom里面preview index.md时就会看不到图片。目前只能变通，把被index.md引用到的md直接放在 _**`contents`**_ 目录下面。

**Comment by shd101wyy** [comment]
嗯我有时间研究下吧。你先用 markdown 的 image 写法吧。
<pre>![]("../assets/puml/classmodel.svg)</pre>   
谢谢

**Comment by shd101wyy** [comment]
我试了下还是没有问题，你是不是用的是 windows 啊？

**Comment by lizhuoqi** [comment]
太好了，终于等到修复，可以升级啦
