### ISSUE TITLE
关闭源文件的后,能不能不要默认关闭预览呢?

### ISSUE THREAD

**Issue by zhoujin7** [shd101wyy/markdown-preview-enhanced#378]
关闭源文件的后,能不能不要默认关闭预览呢?
就是关闭了md文件, 但是该文件的预览还存在.

**Comment by shd101wyy** [comment]
Hi @zhoujin7 ，

这个目前是不支持的，以后可能我会在设置里添加个选项吧。

谢谢

**Comment by zhoujin7** [comment]
谢谢! 加油.




------------------ 原始邮件 ------------------
发件人: "Yiyi Wang";<notifications@github.com>;
发送时间: 2017年4月27日(星期四) 上午10:49
收件人: "shd101wyy/markdown-preview-enhanced"<markdown-preview-enhanced@noreply.github.com>; 
抄送: "周蒙牛"<zhoujin7@foxmail.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [shd101wyy/markdown-preview-enhanced] 关闭源文件的后,能不能不要默认关闭预览呢? (#378)




Hi @zhoujin7 ，
 
这个目前是不支持的，以后可能我会在设置里添加个选项吧。
 
谢谢

**Comment by baijiangliang** [comment]
Hi @zhoujin7 

我刚遇到类似的问题。可以把预览窗口左边框拖到最左边遮住 md 源文件窗口，这样就只有预览窗口了。要恢复原样按两次 Ctrl + Shift + M 即可。

我本来想提一个支持阅读模式的需求，不知道你的需求是否跟我一样，希望对你有帮助。

**Comment by zhoujin7** [comment]
谢谢, 这个方法管用.




------------------ 原始邮件 ------------------
发件人: "baijiangliang";<notifications@github.com>;
发送时间: 2017年4月29日(星期六) 晚上8:26
收件人: "shd101wyy/markdown-preview-enhanced"<markdown-preview-enhanced@noreply.github.com>; 
抄送: "周蒙牛"<zhoujin7@foxmail.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [shd101wyy/markdown-preview-enhanced] 关闭源文件的后,能不能不要默认关闭预览呢? (#378)




Hi @zhoujin7
 
我刚遇到类似的问题。可以把预览窗口左边框拖到最左边遮住 md 源文件窗口，这样就只有预览窗口了。要恢复原样按两次 Ctrl + Shift + M 即可。
 
我本来想提一个支持阅读模式的需求，不知道你的需求是否跟我一样，希望对你有帮助。

**Comment by shd101wyy** [comment]
现在 settings 里面添加了这个选项。
<img width="483" alt="screen shot 2017-06-08 at 12 45 19 pm" src="https://user-images.githubusercontent.com/1908863/26942628-5faf5e4c-4c48-11e7-9a7c-50bf1a25a0ae.png">

谢谢
