### ISSUE TITLE
TypeError: Cannot read property 'scrollTop' of null

### ISSUE THREAD

**Issue by ckdanny** [shd101wyy/markdown-preview-enhanced#38]
**Atom Version**: 1.7.4
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.6.8

### Stack Trace

Uncaught TypeError: Cannot read property 'scrollTop' of null

```
At C:\Users\dannychan\.atom\packages\markdown-preview-enhanced\lib\md-preview.js:248

TypeError: Cannot read property 'scrollTop' of null
    at HTMLDivElement.htmlView.onscroll (C:\Users\dannychan\.atom\packages\markdown-preview-enhanced\lib\md-preview.js:248:30)
```

### Commands

```
     -1:27.3.0 markdown-preview-enhanced:save-as-html (p.line)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-preview-enhanced": {
    "exportPDFPageFormat": "A4",
    "pdfOpenAutomatically": true,
    "useGitHubStyle": true,
    "useGitHubSyntaxTheme": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
color-picker, v2.1.1
markdown-preview-enhanced, v0.6.8
minimap, v4.24.3

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
huhh that's weird. How do you trigger this bug?

Also, do you still have problem with exporting html file?

Thanks

**Comment by ckdanny** [comment]
@shd101wyy exporting html file is fine after restart the atom ;)
This bug I don't know trigger again, it suddenly appear, and it is visible lol

**Comment by shd101wyy** [comment]
@ckdanny I will close this issue now ;)
