### ISSUE TITLE
New standard for file transclutions

### ISSUE THREAD

**Issue by borisrorsvort** [shd101wyy/markdown-preview-enhanced#381]
iA writer, a big player on the market of md writing tool just released a entire blog post on a new syntax for file transclusion. It seems many people think that's the way to go.
Could you have a look and say if that would make sense for md preview enhanced to support that?
https://ia.net/writer/blog/ia-writer-4

Would be a big plus for portability.

**Comment by shd101wyy** [comment]
Hi @borisrorsvort ,  

We discussed about it before [here](https://github.com/shd101wyy/markdown-preview-enhanced/issues/207#issuecomment-263066701).   
I will consider about it when I am free.  

Thanks
