### ISSUE TITLE
Plantuml bugs: update to current version?

### ISSUE THREAD

**Issue by Sandared** [shd101wyy/markdown-preview-enhanced#382]
Hi,

as mermaid has some issues with its class diagrams I tried plantuml, which works perfectly until it comes to skinparams and inclusion of files.

1) If you try to change the color of arrows you have to declare the according property like this before your diagram:

```@puml
skinparam Arrow{
  Color black
  FontSize 10
  FontColor red
}
... (diagram code)
```

This doesn't work as the FontColor is still black and the arrows themself are red.
[The guys from plantuml](http://plantuml.sourceforge.net/qa/?qa=6055/skinparams-for-arrow-not-working) told me that this might be sovled through a version update to the current version.

2) [According to plantuml documentation](http://plantuml.com/preprocessing) you can include some common diagram code by adding code like this in front of your diagram code:

```@puml
!include mysettings.xxx
... (diagram code)
```

I placed the file mysettings.xxx in the same folder as my markdown file but nothing happened (not even an error). Maybe this is also solved through an update?

Kind regards,
Thomas

P.S. I love your markdown-preview-enhanced! Keep up the good work!

**Comment by shd101wyy** [comment]
@Sandared I see.  

Sorry I am very busy recently, so I will fix it when I am free.   
The `plantuml.jar` is at `~/.atom/packages/markdown-preview-enhanced/dependencies/plantuml` folder. You can try replacing it by the newest version yourself.  

Thanks

**Comment by Sandared** [comment]
I replaced the jar and that fixed the issue with the arrows. 

Thank you very much 👍

**Comment by shd101wyy** [comment]
I will close this issue after I release a new version of this package ;)

**Comment by shd101wyy** [comment]
Done :)
