### ISSUE TITLE
LaTeX page break commands ignored

### ISSUE THREAD

**Issue by RickTorresJr** [shd101wyy/markdown-preview-enhanced#387]
Up until a recent version of "markdown-preview-enhanced", the LaTeX commands \newpage and \clearpage are ignored. Both are used to force a page break when generating the PDF. Running pandoc 1.16.0.2
markdown-preview-enhanced 0.12.0
Thanks for this awesome tool.

**Comment by shd101wyy** [comment]
Oh I see, I will get it fixed when I am free.

**Comment by shd101wyy** [comment]
@RickTorresJr should be fixed now.  
Cheers :)

**Comment by RickTorresJr** [comment]
Confirmed fixed. Thanks for the quick resolution!
