### ISSUE TITLE
math rendering issue when using pandoc

### ISSUE THREAD

**Issue by mcmahanp** [shd101wyy/markdown-preview-enhanced#388]
I'm having a strange issue with math rendering. I need to use pandoc to parse my markdown for various reasons, but somehow math markup is getting stripped before it makes it to mathjax or katex.

A simple file containing only one line
   
    $$\{v_i\}$$

will render just fine using remarkable:
<img width="89" alt="vi_remarkable" src="https://cloud.githubusercontent.com/assets/2372274/25670381/236b4620-2ff2-11e7-9e0f-14db76bcb920.png">

But rendering the same file with pandoc yields:
<img width="73" alt="vi_pandoc" src="https://cloud.githubusercontent.com/assets/2372274/25670402/39e8a488-2ff2-11e7-89f8-90804530bbdc.png">

Opening both versions in a web browser, mathjax will display the raw TeX commands for each. Using remarkable: `\{v_i\}`  ; using pandoc: `{vi}`. So it looks like the `\` (backslash) and `_` (underscore) characters are getting stripped when pandoc is selected as the parser.

Running the file directly through pandoc with

    pandoc -s --mathjax -o test.html test.md

turns out fine with a correct rendering. And as I said, the problem persists with both mathjax and KaTeX.

I'm using Atom 1.16.0 on Mac OS X 10.12.4 and markdown-preview-enhanced 0.12.0 (though the problem was around in the previous version of the package too)

Thanks for your help!

**Comment by shd101wyy** [comment]
@mcmahanp Sorry I am confused what you are trying to do.  
You wanna export `pdf` file or `html` file?

**Comment by shd101wyy** [comment]
Oh I see the problem. The `Use Pandoc Parser` is causing the issue. I will fix it when I am free.

**Comment by mcmahanp** [comment]
Great, thanks!

In case it's relevant here are the relevant snippets of of the two html files I get.

Without `Use Pandoc Parser`:

    <body class="markdown-preview-enhanced   "  >
    <p>$$\{v_i\}$$</p>
    </body>

With `Use Pandoc Parser`:

    <body>
    <p><br><span class="math display">$${vi}$$</span></p>
    </body>

**Comment by mcmahanp** [comment]
Amazing, thanks!
