### ISSUE TITLE
Linking does not support File name with space

### ISSUE THREAD

**Issue by ckdanny** [shd101wyy/markdown-preview-enhanced#39]
For example using file "Today is a good day.html"
`[filename](Today is a good day.html)` cannot work correctly

but if the file name is changed to "Today_is_a_good_day.html"
`[filename](Today_is_a_good_day.html)` then it can work properly

**Comment by shd101wyy** [comment]
@ckdanny  I think for the url with spaces, you need to write
`[filename](<Today is a good day.html>)` instead of `[filename](Today is a good day.html)`
You need to add `<>` between the url.

**Comment by ckdanny** [comment]
Hi @shd101wyy, It seems that Footnote and TOC cannot work in pdf? (e.g. jump to assigned position)

**Comment by shd101wyy** [comment]
Well that is an electron bug, please refer to [this issue](https://github.com/shd101wyy/markdown-preview-enhanced/issues/9#issuecomment-208489256).

The only way to get it work is to open it in browser, then print the html from the browser.

**Comment by shd101wyy** [comment]
closing this issue out
