### ISSUE TITLE
Customize remarkable?

### ISSUE THREAD

**Issue by joegnis** [shd101wyy/markdown-preview-enhanced#391]
I want remarkable to convert `\n` to `<br>`. But the option is hard-coded([source](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/md.coffee#L139)).

Any chance to make it configurable?

**Comment by shd101wyy** [comment]
This can be changed by running `Markdown Preview Enhanced: Toggle Break On Single Newline`.

**Comment by joegnis** [comment]
Thanks! Sorry, I kept searching for remarkable options...
