### ISSUE TITLE
pandoc equation parsing bug?

### ISSUE THREAD

**Issue by AStupidBear** [shd101wyy/markdown-preview-enhanced#392]
Superscripts cannot be rendered correctly using pandoc parser.

![image](https://cloud.githubusercontent.com/assets/16422976/25689112/79637e24-30b7-11e7-8535-ff270a41142b.png)

**Comment by shd101wyy** [comment]
@AStupidBear which version of this package are you using?

**Comment by shd101wyy** [comment]
And can you send me your markdown file?

**Comment by shd101wyy** [comment]
This is mine. I guess you are not using the newest version of this package.  
![screen shot 2017-05-03 at 10 08 17 pm](https://cloud.githubusercontent.com/assets/1908863/25689373/132966a6-304d-11e7-844b-4dbae1e223cf.png)
And my settings:  
![screen shot 2017-05-03 at 10 09 25 pm](https://cloud.githubusercontent.com/assets/1908863/25689384/354e8090-304d-11e7-9813-c76c610d406a.png)

**Comment by AStupidBear** [comment]
@shd101wyy Yes, version is the cause.
