### ISSUE TITLE
使用pandoc导出word，四级标题与五级标题没有格式

### ISSUE THREAD

**Issue by iehyxue** [shd101wyy/markdown-preview-enhanced#395]
很棒的插件，但是使用pandoc导出word，四级标题与五级标题没有格式
atom1.15.0
markdown-preview-enhanced 0.12.0
pandoc1.19.1

**Comment by shd101wyy** [comment]
Hi @iehyxue 

我试了下，没遇到问题。你的 markdown 文件是怎么写的呢？  
![screen shot 2017-05-05 at 11 29 15 am](https://cloud.githubusercontent.com/assets/1908863/25754797/288359f0-3186-11e7-8afc-b41e7fc0e7b2.png)
![screen shot 2017-05-05 at 11 29 02 am](https://cloud.githubusercontent.com/assets/1908863/25754800/29b834e4-3186-11e7-855b-2894975652bf.png)

谢谢

**Comment by iehyxue** [comment]
您好，又试了试，在标题和之前的正文之间留一个空行，输出正常了

谢谢
