### ISSUE TITLE
math rendering issue when using mathjax or pandoc

### ISSUE THREAD

**Issue by mcmahanp** [shd101wyy/markdown-preview-enhanced#396]
I'm having new issues since the 0.12.1 update with math rendering.

If I uncheck `Use Pandoc Parser` and select `KaTeX` for my `Math Rendering Option`, everything is fine. However changing *either* of those options messes up math rendering. Using a file containing only the line `$$\{v_i\}$$`, I get the following previews for the equation.

No Pandoc + KaTeX (correct rendering):
![image](https://cloud.githubusercontent.com/assets/2372274/25754287/462cd3c0-3184-11e7-978e-da69fd4de283.png)

Pandoc + KaTeX:
![image](https://cloud.githubusercontent.com/assets/2372274/25754198/f7cf0806-3183-11e7-82a1-b6279316c9b3.png)

No Pandoc + MathJax:
![image](https://cloud.githubusercontent.com/assets/2372274/25754327/5ac76944-3184-11e7-8022-d826deda9d72.png)

Pandoc + MathJax:
![image](https://cloud.githubusercontent.com/assets/2372274/25754343/691d495a-3184-11e7-8869-5dbd08dff47f.png)

Interestingly, if I export to an html file right-clicking the preview pane and choosing `Export to Disk`, the math renders fine in Chrome. But in Atom it looks like this
![image](https://cloud.githubusercontent.com/assets/2372274/25754460/e6273aaa-3184-11e7-8e85-6099237b618d.png)

I'm not sure what's going on here -- it looks like under any settings other than "No Pandoc + KaTeX" the math rendering is simply being turned off in the preview pane.

Thanks for being so responsive with my last issue. I love the package and this is my only sticking point :)

**Comment by shd101wyy** [comment]
@mcmahanp you need to type something in your markdown file after you make changes of settings.

**Comment by mcmahanp** [comment]
That doesn't seem to make any difference. I'm typing things and saving the file, but I'm still getting the unrendered math

![image](https://cloud.githubusercontent.com/assets/2372274/25754860/63bded50-3186-11e7-8f71-b361ceb3a074.png)

**Comment by shd101wyy** [comment]
![math](https://cloud.githubusercontent.com/assets/1908863/25754970/c0511e66-3186-11e7-9f15-01eb3f438659.gif)

**Comment by shd101wyy** [comment]
Show me your `config.json`?  
![screen shot 2017-05-05 at 11 37 33 am](https://cloud.githubusercontent.com/assets/1908863/25755106/40237fee-3187-11e7-9c6f-58ade6fb1177.png)

**Comment by mcmahanp** [comment]
```
  "markdown-preview-enhanced":
    breakOnSingleNewline: false
    enableTypographer: true
    enableWikiLinkSyntax: false
    enableZenMode: true
    pandocPath: "/usr/local/bin/pandoc"
    scrollSync: false
    showBackToTopButton: false
    usePandocParser: true
```

**Comment by shd101wyy** [comment]
Well I actually don't know why.  
Try click the `refresh` button or restart atom?

**Comment by mcmahanp** [comment]
Huh, restarting Atom (again) did the trick!

Thanks for your patience! 👍

**Comment by RoyiAvital** [comment]
How do I use MathJaX instead of KaTeX?

I found `mathRenderingOption` yet it doesn't say what string is needed to move to MathJaX.

**Comment by kachkaev** [comment]
@RoyiAvital a definition of `mathRenderingOption` in `config-schema` might help:
https://github.com/shd101wyy/markdown-preview-enhanced/blob/04d157748c9346af949ee8ee2ac793c2d7c319df/src/config-schema.ts#L158-L168

**Comment by RoyiAvital** [comment]
@kachkaev , 
This is perfect.  
I think the list of options should be part (At least for this short list) of hint line in the preferences.

Thank You.

**Comment by kachkaev** [comment]
@RoyiAvital I agree. Feel free to submit a PR for that 😉
