### ISSUE TITLE
How about a TOC window?

### ISSUE THREAD

**Issue by xnervwang** [shd101wyy/markdown-preview-enhanced#400]
Could MPE add a TOC window like Typora and other md editors? It would be more convenient to see the TOC tree in a alone window, and click each title to jump to the section of a page.

![image](https://cloud.githubusercontent.com/assets/4509104/25837277/9abaa334-34bf-11e7-836e-9049a03d88cb.png)

**Comment by shd101wyy** [comment]
@xnervwang partially done in version `0.12.4`.  
Thanks

**Comment by xnervwang** [comment]
@shd101wyy Thanks very much! Waiting for the surprise...

**Comment by shd101wyy** [comment]
I think I can close this issue now :)
