### ISSUE TITLE
Pandoc exports and absolute paths

### ISSUE THREAD

**Issue by adamaltmejd** [shd101wyy/markdown-preview-enhanced#409]
I have a file with a YAML with bibliography that is stated as an absolute path. The preview (using the pandoc parser) works great, but if I try to export using the right-click -> "Pandoc" i get an error. If I run the exact same command directly in my terminal or specify relative paths to my bibliography it works perfectly.

```
pandoc error
Error: Command failed: /usr/local/bin/pandoc -f markdown+tex_math_single_backslash+yaml_metadata_block+definition_lists+backtick_code_blocks+fenced_code_blocks+auto_identifiers+inline_notes+raw_html+pipe_tables+autolink_bare_uris+ascii_identifiers+intraword_underscores+strikeout+hard_line_breaks+shortcut_reference_links -o /Users/ad.3103/Downloads/pandoc_export_test.pdf --toc --toc-depth=2 --filter pandoc-citeproc
pandoc-citeproc: Could not find Users/ad.3103/Dropbox/Reading/Library/library.bib
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Pandoc.hs:224:39 in pandoc-citeproc-0.10.4.1-EdjBizYp62fCPHef3CymGR:Text.CSL.Pandoc
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

**Comment by shd101wyy** [comment]
I wil get it fixed next week.  
Thanks

**Comment by shd101wyy** [comment]
@adamaltmejd Should be fixed now.
Thanks :)

**Comment by jailsonfm** [comment]
I am having similar problems, although I guess it has nothing to do with the `markdown-preview-enhanced`. Once I include bibliography: in the YAML and the name of the bib file it pops up the freaking error, as below. I installed and reinstalled the pandoc and the citeproc, but nothing change.
`Error: Command failed: pandoc -f markdown+tex_math_single_backslash -o /Users/jfu/Documents/markdown_test/test.pdf --natbib --filter pandoc-citeproc`
`pandoc-citeproc: Error in $: expected product (:*:), encountered Object`
`CallStack (from HasCallStack):`
`error, called at ./Text/Pandoc/JSON.hs:99:48 in pandoc-types-1.16.1-480MEXEHIxeFvyjA2KK2ox:Text.Pandoc.JSON`
`pandoc: Error running filter pandoc-citeproc`
`Filter returned error status 1`
Thanks!

**Comment by jailsonfm** [comment]
Hi, I figured out what was going one. As suspected the problem has nothing to do with the brilliant `markdown-preview-enhanced` package. It was just missing the link of the pandoc-citeproc. I used in the terminal: `brew link --overwrite pandoc-citeproc`.
Thanks guys!

**Comment by adamaltmejd** [comment]
Hey! Sorry for never closing this. Completely forgot. It works great, but then today I wanted to use "~" to reference my home folder and then it breaks down again:

```
Error: Command failed: pandoc -f markdown-raw_tex+tex_math_single_backslash+yaml_metadata_block+definition_lists+backtick_code_blocks+fenced_code_blocks+auto_identifiers+inline_notes+raw_html+pipe_tables+autolink_bare_uris+ascii_identifiers+intraword_underscores+strikeout+hard_line_breaks+shortcut_reference_links -t html --mathjax --smart --filter pandoc-citeproc
pandoc-citeproc: error running filter.
CouldNotFindBibFile "~/Dropbox/Reading/Library/library.bib"
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```
