### ISSUE TITLE
Problems of table of content (toc) for linked texts

### ISSUE THREAD

**Issue by herohuyongtao** [shd101wyy/markdown-preview-enhanced#41]
There will be problems of table of contents (toc) for linked texts. It will still renders with links to original URLs instead of linking to the content in the file.

Take the following header as an example,

    # [Header test](www.test.com) xxx [Header test 2](www.test2.com)

In the TOC rendered, it cannot be re-directed to this header in the file, instead it will still show these two URL links.

**Comment by shd101wyy** [comment]
@herohuyongtao , the toc issue you mentioned should be fixed now. 
Please upgrade the package, then restart atom.

Thanks ;)

**Comment by herohuyongtao** [comment]
Yeah, it works. Thanks for the update. Happy markdown-ing. :+1:
