### ISSUE TITLE
Line number in code blocks (new feature)

### ISSUE THREAD

**Issue by dtgoitia** [shd101wyy/markdown-preview-enhanced#412]
Hi!

Could it be possible to show the line number in the code blocks as below?
```
1   // Declare myVariable
2   var myVariable string
3 
4   // Another comment
5   myVariable = ...
```

Is a very useful feature when you are describing the code and want to reference a specific line.

**Comment by shd101wyy** [comment]
Hi @dtgoitia ,

How would you like it to be supported?  So you want all code blocks to have line numbers? Or only some specific code block to have line number?

Thanks

**Comment by dtgoitia** [comment]
Hi @shd101wyy ,

I think the best way is that only some specific code blocks have line numbers, so that old markdown files can keep their style consistent if they will.

I don't how would be easier to achieve this. Maybe to create a new type of code block? Or maybe an optional flag in some point of the code block could enable the line numbers?
![2017-05-21 08_52](https://cloud.githubusercontent.com/assets/21012855/26282233/ebbc7be2-3e04-11e7-9453-ed414bc195e0.png)

Many thanks for your interest!

**Comment by shd101wyy** [comment]
My plan is to support `class:"lineNo"` so that the `lineno` will be added to the class list of code block.    
And `lineno` class will show line numbers.  
For example:  
 
![screen shot 2017-05-22 at 9 41 09 pm](https://cloud.githubusercontent.com/assets/1908863/26336313/62467898-3f37-11e7-8f6b-ee6a404c36c8.png)


I have finished implementing this feature [here](https://github.com/shd101wyy/markdown-preview-enhanced/commit/2421e0cbdc83c6d9fa01c07a71ae4ac44912bc03).    

However, I will not release the new version so soon because I am also working on some other new features. Feel free to give me suggestions.   

Thanks :)

**Comment by dtgoitia** [comment]
That's exactly what I was looking for. Great job @shd101wyy !

**Comment by shd101wyy** [comment]
@dtgoitia Done! 

Cheers :)

**Comment by shd101wyy** [comment]
Done, check [this doc](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics?id=lineno).  
Cheers :)

**Comment by dtgoitia** [comment]
@shd101wyy the numbers are now shown left-aligned. Without any kind of margin on the number left hand side. I think they looked better in the previous version, as they left some margin on the left hand side. :)

**Comment by dtgoitia** [comment]
@shd101wyy it works great using `{.lineNo}`, and it does work stating only `lineNo` too, but the second options shows the numbers left aligned without any margin. Not an issue, though :)

**Comment by shd101wyy** [comment]
Hi @dtgoitia , this is now changed again. Check [this doc](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics?id=line-numbers)

**Comment by dtgoitia** [comment]
Thanks for the update @shd101wyy ! :D

**Comment by GHjiangtao2014** [comment]
Hi @shd101wyy , in Atom, the line-numbers feature will affect the code color of the block. Is there any solution? e. g.

![problem](https://user-images.githubusercontent.com/11893394/28751797-127f11a0-7554-11e7-8010-5fd615289ee5.jpg)

Best,

Tao

**Comment by shd101wyy** [comment]
@GHjiangtao2014 try installing [language-gfm-enhanced](https://atom.io/packages/language-gfm-enhanced).

**Comment by truongcongtthanh** [comment]
you can try it in markdown on hackmd.io
```python=
// your code...
```

**Comment by cdddg** [comment]
origin style, use [command line mode](https://learnbyexample.gitbooks.io/vim-reference/content/Command_Line_mode.html) (:, /, ..) 
<img width="360" alt="origin_white" src="https://user-images.githubusercontent.com/39718445/104094552-87cb8480-52cc-11eb-9d5a-908fa8e6e24e.png"><img width="360" alt="origin_black" src="https://user-images.githubusercontent.com/39718445/104094572-a893da00-52cc-11eb-86da-afb36b6c36b3.png">

updated style, vimrc set `au CmdlineEnter * redraws`  and use [command line mode](https://learnbyexample.gitbooks.io/vim-reference/content/Command_Line_mode.html) (:, /, ..) 
<img width="360" alt="updated_white" src="https://user-images.githubusercontent.com/39718445/104094676-4c7d8580-52cd-11eb-8768-81b9bbe1ddbf.png"><img width="360" alt="updated_black" src="https://user-images.githubusercontent.com/39718445/104094678-4f787600-52cd-11eb-9eb0-766c98f1d64e.png">


I think this color is great and can increase the readability of my code when writing it. Hope it can be combined.
