### ISSUE TITLE
@import not working for images in another folder

### ISSUE THREAD

**Issue by Sandared** [shd101wyy/markdown-preview-enhanced#414]
Hi,

from the few words I can read in the issue #377  I think it might be the same one that I have ;)

I'm trying to import a PNG file via @import "..\images\someimage.png" and it only shows a default icon. 
If I'm using the same path in `![enter image description here](..\images\someimage.png)` it works, but I would prefer to use your @import.

Any advice is appreciated :)

Kind regards,
Thomas

**Comment by shd101wyy** [comment]
What operating system are you using? And can you send me a zip file of your files? Thanks

**Comment by shd101wyy** [comment]
And which version of this package are you using?

**Comment by shd101wyy** [comment]
@Sandared it seems that for `@import` you need to use `/` instead of `\`.  
For example: ` @import "../images/someimage.png"`

**Comment by Sandared** [comment]
Sorry for the late response.

I'm on Windows 10.
Version of MDPE is 0.12.5

Structure of my Folder is

- Root
    - chapters
         - MyChapter.md
         - OtherChapter.md
    - images
         - MyChapter
              - MyImage.png
         - OtherChapter
              - OtherImage.png

This is from left to right:
The result in Chrome, HTML for `@import` and `![]()`, source in markdown.

![import](https://cloud.githubusercontent.com/assets/5059773/26580215/77df99a4-4537-11e7-9c9f-b0e431bef4f2.png)

It seems as if the `@import` path is not correctly transformed.
It doesn't matter whether I'm using `/` or `\` .
`\` is working when I'm importing other markdown files.

Kind regards,
Thomas

**Comment by shd101wyy** [comment]
No, it matters. You have to use "/" instead of "\" because "\" will be encoded when processing the URL. Try using "/" instead and it should work.

**Comment by Sandared** [comment]
You were right.

`/` does the trick when I open the document in  a browser (via right-click on the preview), but in the preview itself it still shows just the placeholder icon for an image.
Also if exported to pdf the icon is shown instead of the actual image.

**Comment by shd101wyy** [comment]
I am testing it on Windows and it does cause issue. I will let you know once I fix it.  
Thanks

**Comment by shd101wyy** [comment]
I was testing it on Windows 10 and it did cause the issue.  
I will let you know once I fix it.  
Thanks

**Comment by shd101wyy** [comment]
@Sandared should be fixed now. Both `\` and `/` should work.

**Comment by Sandared** [comment]
Thank you so much!
I love your preview :)

Keep on with this good work!
