### ISSUE TITLE
No syntax highlight fenced diff/patch block in preview panel

### ISSUE THREAD

**Issue by barrygu** [shd101wyy/markdown-preview-enhanced#415]
Hi shd101wyy,

Your markdown preview is a great job.
I very like it, and use it  with high frequency.
I found that the diff/patch syntax highlighting is not supported?

I manually installed "language-diff".
![2017-05-27_135405](https://cloud.githubusercontent.com/assets/7963691/26518490/258c1baa-42e4-11e7-9a6e-0bf32b93da21.png)

And add "'diff': 'source.diff', 'patch': 'source.diff'," into extension-helper.coffee
Then highlight in edit panel is OK, but the preview panel no highlight as well.
![2017-05-27_133053](https://cloud.githubusercontent.com/assets/7963691/26518348/62137f12-42e1-11e7-8722-fc8bcc4d67f1.png)

But the highlight works OK when I export it to PDF
![image](https://cloud.githubusercontent.com/assets/7963691/26518525/d9cafd66-42e4-11e7-83ff-3cae8bf69386.png)

The highlight parser (diff.js) for diff/patch is existed in below folder:
...\atom\app-1.17.2\resources\app\node_modules\highlight.js\lib\languages\diff.js

Could you check and fix it?

Thanks a lot.

**Comment by shd101wyy** [comment]
Will be supported in next release. Thanks

**Comment by shd101wyy** [comment]
@barrygu I think that is because the preview theme that you are using is not compatible with the`language-diff` package. Try to use another preview theme.

**Comment by barrygu** [comment]
@shd101wyy 
I think you're right. The issue happened when I used atom-light-syntax as preview theme.
I try all themes on my system, the mpe-github-syntax is the best for diff-language.
Thank you, very much.
