### ISSUE TITLE
plantuml图像的生成时间很长

### ISSUE THREAD

**Issue by coolboy0961** [shd101wyy/markdown-preview-enhanced#417]
0.12.4当中追加了plantuml图像生成速度的改善，试了一下发现图像多的时候，最后一个图像的生成要花费很长时间
![screen shot 2017-05-29 at 14 29 08](https://cloud.githubusercontent.com/assets/12973893/26537540/65b3a890-447b-11e7-87ce-561b40d4ac9f.png)

测试文件内容：
~~~
# test
## 目次

<!-- toc orderedList:0 depthFrom:1 depthTo:6 -->
<!-- tocstop -->

## test2
```@plantuml
@startuml
class abc
class dfs
@enduml
```

## test3
```@plantuml
@startuml
class abc
class dfs
@enduml
```

### test4
```@plantuml
@startuml
class abc
class dfs
@enduml
```

```@plantuml
@startuml
class abc
class dfs
@enduml
```

```@plantuml
@startuml
class abc
class dfs
@enduml
```

```@plantuml
@startuml
class abc
class dfs
@enduml
```

```@plantuml
@startuml
class abc
class dfs
@enduml
```

```@plantuml
@startuml
class abc
class dfs
@enduml
```

~~~

**Comment by shd101wyy** [comment]
我没有遇到这个问题啊？你重启下试试？

**Comment by coolboy0961** [comment]
重启atom以后好了。谢啦！

**Comment by shd101wyy** [comment]
@coolboy0961 好像确实有问题，我修一下。

**Comment by shd101wyy** [comment]
@coolboy0961 修好了，谢谢。

**Comment by coolboy0961** [comment]
如果用稍微复杂些的plantuml的话还是出现最后一两个图一直显示不出来。

我发现plantuml的代码中写@startuml和@enduml的话就会卡在最后一两个图片上，
如果不写就完全没事儿。这个信息能成为hint吗？
但是不写@startuml和@enduml的话，save as markdown无法把代码变成图片。

我工作上的文档不能共享，我回头用Test文档测出来再共享。

**Comment by coolboy0961** [comment]
怎么也无法再现了，工作上的文档也没事儿了。
先关了。以后再有问题再反映。

非常感谢你的修正！
