### ISSUE TITLE
TOC无法自动生成了

### ISSUE THREAD

**Issue by coolboy0961** [shd101wyy/markdown-preview-enhanced#418]
升级到0.12.4以后发现TOC无法自动生成了。

![test1](https://cloud.githubusercontent.com/assets/12973893/26537576/b28df620-447b-11e7-9a4d-b491fda2ab64.gif)

**Comment by shd101wyy** [comment]
@coolboy0961 给我 30 分钟我修一下

**Comment by shd101wyy** [comment]
@coolboy0961 修好了。谢谢。

**Comment by coolboy0961** [comment]
试了，没问题了，非常感谢！
