### ISSUE TITLE
How to compile to pdf from a markdown doc?!

### ISSUE THREAD

**Issue by jailsonfm** [shd101wyy/markdown-preview-enhanced#421]
I know it is a very naive question, but I can't find a way to compile/save as pdf. I have followed the [pdf.md](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/pandoc/pdf.md) tutorial from the package but I didn't find a way to reproduce even a simple example. I use the "export to disk" and create a pdf and it works but the result is not what I expected [(see here)](https://www.dropbox.com/s/8sd7t6r1nqw9l3b/test_jai.pdf?dl=0). Here is the [markdown doc used](https://www.dropbox.com/s/87ioykpsopjohoe/test_jai.md?dl=0). When I run using RStudio the result is ok [(here)](https://www.dropbox.com/s/4z3j2lfw1w2awlj/test_jai_rstudio.pdf?dl=0). I tried to use instead of "export to disk" the "Pandoc" option but gives an error.
` a pandoc error -  Error: spawn pandoc ENOENT`.
Probably I am doing some mistake, but unfortunately, I didn't find a way to manage it with my limited programming power ;-)

**Comment by shd101wyy** [comment]
@jailsonfm Do you have `pandoc` installed and is it in your system path?

**Comment by jailsonfm** [comment]
Hi @shd101wyy! Thanks a lot. I reinstalled pandoc following your instructions!
Just one more question, I am trying to include affiliation of authors and subtitles in the YAML but these arguments do not appear in the resulting pandoc regenerated pdf. 
Do you have any idea what I should do here?

**Comment by shd101wyy** [comment]
Can I see your markdown file?

**Comment by jailsonfm** [comment]
Hi here is a very simple `.md` [(open here)](https://www.dropbox.com/s/mxoqo02ltwtvp4i/test_two.md?dl=0) And here is the [pdf that I get](https://www.dropbox.com/s/6u5gqcoyw5clcer/test_two.pdf?dl=0).
I have found some workaround in some forums but I wasn't able to resolve it.
It has being hard to make it work properly. For example when I include bibliography in the an error occur. `pandoc: Error running filter pandoc-citeproc
Filter returned error status 1`. You don't need to hep me with that because it is way distance from the #421 issue.
**Thanks!!!**

**Comment by jailsonfm** [comment]
Hi @shd101wyy! Thanks a lot for the friendly support.
I found a solution to include affiliation by altering the `default.latex` for multiple authors following the suggestions from [Peter Humburg](http://galahad.well.ox.ac.uk/repro/) and from an insightful discussion in the [pandoc-templates repository](https://github.com/jgm/pandoc-templates/pull/235).
