### ISSUE TITLE
报错 Error: spawn pandoc ENOENT

### ISSUE THREAD

**Issue by zhaoxieluoke** [shd101wyy/markdown-preview-enhanced#429]
Error: spawn pandoc ENOENT 如题，没有办法预览（win7系统，已经禁掉了默认的预览插件Markdown Preview）

**Comment by shd101wyy** [comment]
Hi @zhaoxieluoke ，

预览时不需要 pandoc 的，如果你启用了 pandoc parser 的话，你需要先安装好 pandoc。
[这是一个相似的问题](https://github.com/shd101wyy/markdown-preview-enhanced/issues/421)  

谢谢

**Comment by zhaoxieluoke** [comment]
@shd101wyy ,
谢了，我去再看看说明书再食用（逃）

**Comment by michael-rowe** [comment]
Hi there. I'm getting this error message when using this extension in VS code. Any ideas on what might be the problem?
