### ISSUE TITLE
How do I donate to this project?

### ISSUE THREAD

**Issue by taoeffect** [shd101wyy/markdown-preview-enhanced#430]
Hi @shd101wyy, I'm consistently astonished and impressed at how well you are taking care of this project, how responsive you are to issues, and also generally at the high quality software you've created, which has helped me immensely. Is there a way to support this project? A bitcoin address or paypal?

**Comment by xnervwang** [comment]
Give him a job offer, I guess ;)

**Comment by taoeffect** [comment]
> Give him a job offer, I guess ;)

Not a bad idea, I might have some work he might be interested in. Email sent. :)

**Comment by shd101wyy** [comment]
@taoeffect @xnervwang 

😀  thanks. I am planning to use **patreon** for donation, and I will post the link after I finish building the website for this project.  

Yes I am looking for **full-time job** position in **front-end web development** or **game development**. However, I am a noob in the game development area (I only developed a few mini games just for fun). As for the front-end development, I think I am good at it but I am not an expert. I am familiar with the React library and now I am learning Vue.     
  
I am an international student studying at UIUC. I just graduated this May and earned my BS/MCS degree. I am currently living in Urbana, Illinois.  
So If I work in US, I will need visa sponsorship. My current OPT extension allows me to work for 24-month, but after that I will need to H1B visa.  

Thank you :)

**Comment by taoeffect** [comment]
Cool that you're planning on setting up a Patreon. 👍 

 I don't think we'd be able to help with the visa sponsorship though, so if you need that I guess I'd recommend applying for a job at some bigger company. FYI, the email I sent went to your @illinois.edu address

**Comment by shd101wyy** [comment]
Yes I saw your email. Thank you very much for contacting me :) 

I will setup a patreon account next weekend.
