### ISSUE TITLE
Would you mind porting markdown-preview-enhanced to VSCode? 

### ISSUE THREAD

**Issue by specter119** [shd101wyy/markdown-preview-enhanced#433]
I think VSCode is also a quite good IDE over all platforms. But the most I missing feature is what markdown-preview-enhanced gives me, would you mind check and port this to VSCode.
Thanks in advance!

**Comment by dtgoitia** [comment]
I would love to use this brilliant package in VSCode too! :)

**Comment by shd101wyy** [comment]
@specter119 @dqisme will do when I have time, probably next next week.

**Comment by specter119** [comment]
@shd101wyy thanks!

**Comment by dqisme** [comment]
what's up?

**Comment by shd101wyy** [comment]
@specter119 @dtgoitia @zhoujin7 Made some progress this weekend :)  

![vscode-mpe](https://user-images.githubusercontent.com/1908863/27018705-fcc5fbf8-4ef7-11e7-9693-299d54b8d618.gif)
 
Gonna take me around 2 weeks to finish.

**Comment by zhoujin7** [comment]
thankSSS!!!!

**Comment by dtgoitia** [comment]
good job @shd101wyy ! :D

**Comment by specter119** [comment]
Thanks!

**Comment by shd101wyy** [comment]
I think I can close this issue now 🤣🤣🤣
