### ISSUE TITLE
The new feature "force to code block" for @import generates the invalid language code from the file extension

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/markdown-preview-enhanced#436]
Hi shd101wyy.

https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/file-import.coffee#L14-L17

fileExtensionToLanguageMap  is almost empty.

In many cases, the language code corresponds to the file extension with period.

[import_issue.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1052699/import_issue.zip)

Best Regards.

**Comment by shd101wyy** [comment]
Thanks a lot. Will be fixed in next release

**Comment by tmori3y2** [comment]
The dot language official file extensions are .dot and .gv (but not .viz).

https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/file-import.coffee#L227

Please update the extension list of dot language.

Best Regards.

**Comment by shd101wyy** [comment]
It would be great if you can send me a pull request

**Comment by shd101wyy** [comment]
nvm I will fix it myself.

**Comment by tmori3y2** [comment]
Oh, I must go to a coffee script school !

But now I do not have no environment, then I can only report some issues.

## remove extra period

* https://github.com/shd101wyy/markdown-preview-enhanced/blob/0.13.0/lib/file-import.coffee#L247
    * Maybe "#" is correct, not ".#".

## dot file extension

* https://github.com/shd101wyy/markdown-preview-enhanced/blob/0.13.0/lib/file-import.coffee#L281
    * Please remove ".viz".

Sorry, my example confused you.

By the way, another dot file extension .xdot is there, but I don't know it well.

## fileExtensionToLanguageMap 

* https://github.com/shd101wyy/markdown-preview-enhanced/blob/0.13.0/lib/file-import.coffee#L18-L23
    * Please consider to add other file extensions like ".less", ".plantuml".

Best Regards.

**Comment by shd101wyy** [comment]
Don't worry. I fixed it already :)

**Comment by tmori3y2** [comment]
https://github.com/shd101wyy/markdown-preview-enhanced/blob/0.13.0/lib/file-import.coffee#L295

The extra period of the language code for code block is here too.

**Comment by shd101wyy** [comment]
I add `.` here to prevent code block being executed.  
For example, for a <code>mermaid</code> code block, if you don't want to render it as graph, you can just write <code>```.mermaid</code> .  
I will mention this in the doc in the future. Thanks

**Comment by tmori3y2** [comment]
Hi @shd101wyy !

The .md file compiled by "Save as Markdown" has this extra period.

This file does not compatible with gfm, then the syntax highlight is not working when published to Github and so on.

**Comment by shd101wyy** [comment]
Ok I seeeeee

**Comment by tmori3y2** [comment]
I'm grateful for your great effort and support.

By the way, you removed `useStandardCodeFencingForGraphs` option and language code with @ mark.

https://github.com/shd101wyy/markdown-preview-enhanced/commit/af126c4c9a6258f49e11bd48b93c2f7038fa952b

I'm using this option for the tutorial of GraphViz and PlantUML like this;

\# Interface and Socket by Lollipop notation

\* PlantUML code

\```puml
@startuml

left to right direction

' lollipop & Sockect
ClassA -0)- ClassB : IClassA

@enduml
\```

\* Class Diagram

\```@puml
@startuml

left to right direction

' lollipop & Sockect
ClassA -0)- ClassB : IClassA

@enduml
\```

Now, I can write more simplify like this;

\# Interface and Socket by Lollipop notation

\* PlantUML code

@import "lollipop_tips.puml" {code_block: true}

\* Class Diagram

@import "lollipop_tips.puml"

May this function continue even the next version?

Best Regards

**Comment by shd101wyy** [comment]
Yes you can still write in that way in next version. Just <code>@graph</code> is not supported anymore.

**Comment by tmori3y2** [comment]
Thanks a lot !

**Comment by shd101wyy** [comment]
@tmori3y2 

DONE.

Cheers :)

**Comment by tmori3y2** [comment]
[lollipop_tips.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1066185/lollipop_tips.zip)

It seams good.

Great job !
