### ISSUE TITLE
关于标题语法的建议

### ISSUE THREAD

**Issue by Niefee** [shd101wyy/markdown-preview-enhanced#440]
在以前一些markdown软件中，`#`号后面是否加空格都可以表示标题的，就是下面的写法，是一致的。
```md
## hello world

##hello world
```
效果：

## hello world

我之前用markdown写的东西，用这个 插件，标题无法正常解析。Gitbook也支持这个语法，希望可以考虑这个问题。

**Comment by Niefee** [comment]
不知道怎样找到这部分功能的代码，其实也想自己去试试改的。。

**Comment by shd101wyy** [comment]
@Niefee 这个应该是 [remarkable](https://github.com/jonschlinkert/remarkable) 的问题。我找时间研究下，其实也不太难改。
