### ISSUE TITLE
插件很棒, 能否开发visual studio code的同款插件?

### ISSUE THREAD

**Issue by zhoujin7** [shd101wyy/markdown-preview-enhanced#443]
插件很棒, 能否开发visual studio code的同款插件?
多谢.

**Comment by shd101wyy** [comment]
Hi @zhoujin7 

我最近不一定有精力做这个东西，等我是么时候有时间了再研究下吧。
因为 vscode 不是用的是 coffeescript，而且 API 不一样，所以 60% 差不多要重写。  
而且我现在这个插件还没做到稳定，再等一阵子吧。

谢谢

**Comment by shd101wyy** [comment]
Duplicate issue [#433](https://github.com/shd101wyy/markdown-preview-enhanced/issues/433)

**Comment by shd101wyy** [comment]
@zhoujin7 我刚刚发布了一个初始的版本。本地安装的话可以去下载这个 [.vsix 文件](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/releases)。  
可以帮我测试一下。

谢谢

**Comment by zhoujin7** [comment]
@shd101wyy 不用谢 我很乐意 
很棒
