### ISSUE TITLE
todo在preview里打钩，.md文件不会同步打[x]？

### ISSUE THREAD

**Issue by mr-wind** [shd101wyy/markdown-preview-enhanced#445]
我记得之前有这个功能的。能直接在原文件上打x的。怎么更新后没有了？

**Comment by shd101wyy** [comment]
因为预览同步的逻辑改了，所以现在行与行无法对应上了。所以预览打勾就没用了。😂

**Comment by mr-wind** [comment]
好的吧😂

**Comment by miskovics** [comment]
I also really would like to get this function back. I write checksheets in Markdown and completing an action in the preview which also completes it in the source file is extremely useful for me. It is one of the main reasons I use this package.
Is there any workaround to make this working again, e.g. by disabling the scrolling feature?

**Comment by shd101wyy** [comment]
Sure, I will put it back, but gonna take me a while.

**Comment by shd101wyy** [comment]
@mr-wind @miskovics 

The [vscode version](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) now supported this feature.  
I will put this feature back to atom version soooooon...

Thanks

**Comment by mr-wind** [comment]
👍
真棒，期待atom版本的功能回归！

**Comment by shd101wyy** [comment]
@mr-wind @miskovics Done! Cheers :)

**Comment by miskovics** [comment]
@mr-wind Great! I tested it and it works! Thank you!
