### ISSUE TITLE
Cannot apply a style in pandoc export via "Style Reference"

### ISSUE THREAD

**Issue by gepcel** [shd101wyy/markdown-preview-enhanced#448]
As [Style Reference instructed here](https://shd101wyy.github.io/markdown-preview-enhanced/#/pandoc-word?id=style-reference), I created a new `a.md` file, with the following header, saved under the same directory with `style.docx`:
```
---
output:
    word_document:
        reference_docx: style.docx
---
```

But the style wasn't applied to the `docx` filed exported by pandoc. Changing the header to use [Pandoc Arguments instructed here](https://shd101wyy.github.io/markdown-preview-enhanced/#/pandoc-word?id=pandoc-arguments) as following will get the well styled doc:
```
---
output:
    word_document:
        reference_docx: style.docx
        pandoc_args: [
            "--reference-docx=style.docx"
            ]
---
```

I'm not sure this is an issue, or I'm making something usage mistake.

* Windows 10 x64
* Atom 1.17.2 x64
* markdown-preview-enhanced 0.13.0
* pandoc 1.19.2.1

**Comment by shd101wyy** [comment]
Hi @gepcel , this issue will be fixed in next version. Thanks :)

**Comment by shd101wyy** [comment]
Should be fixed now.
