### ISSUE TITLE
请问MPE简介中用的是什么语法主题

### ISSUE THREAD

**Issue by nextonr** [shd101wyy/markdown-preview-enhanced#449]
如图
<img width="406" alt="2017-06-14 4 34 04" src="https://user-images.githubusercontent.com/6022966/27123165-9a1d34f6-511f-11e7-97b7-2aac919600c9.png">

**Comment by shd101wyy** [comment]
Hello, 有的是 atom material 主题～

**Comment by nextonr** [comment]
cool of you
