### ISSUE TITLE
wiki link syntax [[Link Text|WikiLink]] is not working

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#45]
Syntax like `[[WikiLink]]` works but  `[[Link Text|WikiLink]]` does not.

**Comment by shd101wyy** [comment]
I don't think the pull request that you commit just now is correct.

For example, if I write

[[google | https://www.google.com]] 

Your code will generate a link that directs to https://www.google.com.md , which is incorrect

**Comment by xu4wang** [comment]
It depends on how you define the syntax.. for wikilink, as https://help.github.com/articles/adding-links-to-wikis/  says:
```
You can also create links with the wiki format of [[Link Text|WikiLink]]. In this case, WikiLink is the name of your wiki page, not the full URL. 
```

If I want to add a link for a full URL. I will use ```[google](https://www.google.com)``` instead.  Wikilink is just for interlinking markdown files.

**Comment by shd101wyy** [comment]
okay i see.

I will release the new version 7 days later on weekend.

Thanks

**Comment by shd101wyy** [comment]
@xu4wang fixed! Thanks

**Comment by xu4wang** [comment]
@shd101wyy   Fix verified. Thanks for the amazing plugin.
