### ISSUE TITLE
Is it possible to set math rendering engine manually?

### ISSUE THREAD

**Issue by ossphil** [shd101wyy/markdown-preview-enhanced#459]
Obviously Katex is more fast than mathjax while some math environments like 'gathered' are missing in the latest release version. But 'gathered' is supported in the latest development version, so maybe a option to manully set the rendering location is helpful for using the newest features of the engine.

**Comment by shd101wyy** [comment]
Hi @ossphil ,

Right now, no this is not possible. But you can manually replace `.js` and `.css` files in 
`~/.atom/packages/markdown-preview-enhanced/node_modules/katex/dist` folder.

Thanks

**Comment by ossphil** [comment]
@shd101wyy Thanks! Besides, ~/.atom/packages/markdown-preview-enhanced/node_modules/katex/katex.js should also been replaced with the newer version.
