### ISSUE TITLE
plantuml 渲染不出来

### ISSUE THREAD

**Issue by GuannanGuo** [shd101wyy/markdown-preview-enhanced#462]
您好，

PlantUML一直显示rendering PlantUML graph...但渲染不出来。

这个问题出现在我新装atom和这个插件的一台机器上；奇怪的是，很早以前就装上atom和这个插件（有一直更新）的一台机器没有这个问题。

两台机器都是Ubuntu 16.04， atom 1.18.0, markdown-preview-enhanced 0.13.0。

![bug](https://user-images.githubusercontent.com/17143421/27318171-8b30c7bc-55bd-11e7-9606-ef0ce0e8f771.png)

**Comment by shd101wyy** [comment]
哈罗。重启下有用吗？

**Comment by GuannanGuo** [comment]
没有用欸

**Comment by shd101wyy** [comment]
换个 plantuml 代码试试？

**Comment by GuannanGuo** [comment]
换过了，也没有用。
其实在那台能用的电脑上，我输入完```puml后，就算不输入具体的plantuml代码，右边就会出welcome to plantuml等等信息。这台不能用的电脑上一直就是rendering PlantUML graph...

**Comment by shd101wyy** [comment]
没安装 Java 吧？

**Comment by GuannanGuo** [comment]
嗯对，问题解决了，非常感谢！
