### ISSUE TITLE
升级到atom1.18.0后无法启动预览了。

### ISSUE THREAD

**Issue by stevennlj** [shd101wyy/markdown-preview-enhanced#465]
之前用这个插件用的很happy。今天没事在线升级atom到1.18.0，就无法启动预览了。 菜单toggle和ctl-shift-m都不行。 key binding resolver显示没有快捷键冲突。 

请教下怎么查找问题？

**Comment by stevennlj** [comment]
补充一下，重装了该插件还是不行。

**Comment by stevennlj** [comment]
找到问题了， 从屏幕最右边吧预览窗口拖了出来。
原来不是没有开启预览，而是预览窗口显示在了屏幕右端之外。

**Comment by shd101wyy** [comment]
😂

**Comment by shd101wyy** [comment]
可以尝试下新的 vscode 版本。   

https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced
