### ISSUE TITLE
能否增加https://github.com/adrai/flowchart.js这个功能

### ISSUE THREAD

**Issue by milenstack** [shd101wyy/markdown-preview-enhanced#466]
弄流程图的http://flowchart.js.org/

案例:https://www.zybuluo.com/mdeditor?url=https://www.zybuluo.com/static/editor/md-help.markdown#7-流程图

**Comment by shd101wyy** [comment]
你好，我并不打算支持。谢谢。

**Comment by shd101wyy** [comment]
@milenstack 现在支持了。

https://shd101wyy.github.io/markdown-preview-enhanced/#/diagrams

谢谢。

**Comment by tony-zhou-sphinx** [comment]
在 vscode 上使用没有效果，需要做什么额外的操作吗？
```flow
st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes
or No?:>http://www.google.com
io=>inputoutput: catch something...

st->op1->cond
cond(yes)->io->e
cond(no)->sub1(right)->op1
```

**Comment by shd101wyy** [comment]
@tony-zhou-sphinx 你发我张截图？

**Comment by tony-zhou-sphinx** [comment]
![image](https://user-images.githubusercontent.com/32887269/35138854-64774f7c-fd2b-11e7-9e29-458186f88eed.png)
@shd101wyy

**Comment by shd101wyy** [comment]
你这个预览开的不是我这个插件，我这个插件默认预览颜色是白色的

**Comment by shd101wyy** [comment]
cmd+k 然后 v

**Comment by tony-zhou-sphinx** [comment]
![image](https://user-images.githubusercontent.com/32887269/35139785-a68b6390-fd2f-11e7-8ef4-8971b81f9cf6.png)
@shd101wyy

**Comment by tony-zhou-sphinx** [comment]
![image](https://user-images.githubusercontent.com/32887269/35139898-0db8fb18-fd30-11e7-8719-3e0cf44eb9a5.png)
点击的那个预览按钮

**Comment by shd101wyy** [comment]
我的这个插件现在还不能通过预览按钮打开，你点击预览按钮打开的是原来内置的插件。所以 cmd+k 然后 v。README
下有个表格你可以看看快捷键。以后可能会 override 那个按钮，但我现在还不知道该怎么做。晚安

**Comment by tony-zhou-sphinx** [comment]
辛苦了！ 使用快捷键可以预览出效果。谢谢！
