### ISSUE TITLE
Line breaks in MD result in line breaks in the preview

### ISSUE THREAD

**Issue by drorata** [shd101wyy/markdown-preview-enhanced#469]
The following text

```
Hello
Worlds
```

Is rendered as

```
Hello
World
```

However, it should be (at least as far as I tested  ([example](https://gist.github.com/drorata/a99dcc4cf4b5305ad0ef7402c35bc2ba#file-foo-md))

```
Hello World
```

Note that when putting MarkDown under version control, it is useful to have one line per  sentence. Line breaks are normally introduced by an empty line in the source.

**Comment by shd101wyy** [comment]
You can change the "break on single newline" option from the package settings

**Comment by cinderblock** [comment]
Why is the default to have this option enabled?

https://github.github.com/gfm/#soft-line-breaks
