### ISSUE TITLE
Mathjax does not work on Xubuntu

### ISSUE THREAD

**Issue by sierxue** [shd101wyy/markdown-preview-enhanced#475]
I have been using markdown-preview-enhanced with katex for a long time, it works smoothly. Now, I want to use mathjax, and changed in the setting. Unfortunately, math expression does not work, and it is the same as what I typed in the source pane. 

Before I switched to markdown-preview-enhanced, I used markdown-preview-plus with mathjax. I switched back to markdown-preview-plus, it works. Then I tried on my another windows computer, with the same setting, markdown-preview-enhanced with mathjax works well. 

Do I miss something when I change the setting to use mathjax on my Xubuntu computer?

**Comment by shd101wyy** [comment]
@sierxue is this issue fixed now?

**Comment by sierxue** [comment]
Usually I work on Rmd files. I realize that after setting the file extension from ".md, .mmark, .markdown" to ".md, .mmark, .markdown, .Rmd, .rmarkdown", then Mathjax works. 

Looks like with katex, it works with Rmd files even I don't set the extension. But with mathjax, I have to set.

**Comment by shd101wyy** [comment]
Oh it seems to be a bug. The preview shouldn't open if you didn't set it to file extensions.
