### ISSUE TITLE
Python code chunk 输出中文乱码

### ISSUE THREAD

**Issue by jasper-wan** [shd101wyy/markdown-preview-enhanced#488]
![image](https://user-images.githubusercontent.com/15362491/28002668-d2ecc824-6569-11e7-987e-d4c03a0cb79a.png)
如图

**Comment by shd101wyy** [comment]
试试 python3？我尝试了下没有问题。

**Comment by shd101wyy** [comment]
或者这样 

    ```python {cmd:true}
    # -*- coding: utf-8 -*-

    print("中文")
    ```

**Comment by foolishflyfox** [comment]
@shd101wyy 
Python 版本： Python 3.6.2
code chunk :
```python {cmd}
# -*- coding: utf-8 -*-
print(u"测试")
```
显示为：
![image](https://user-images.githubusercontent.com/17536022/38284238-d116a654-37ec-11e8-8748-21ef6cd6530c.png)

**Comment by zombie110year** [comment]
Python 版本: 3.7.1
Windows 10 1809, 中文家庭版, chcp=936
遇到同样的问题.
另外, 在 `import numpy` 时, 发生 ImportError, 导入模块的名称也出现乱码, (在安装 Python 的路径中没有中文).

**Comment by Jasper0819X** [comment]
@zombie110year 
我和你一样的版本，把系统code page改成65001之后正常（控制面板/大图标/区域/管理/更改系统区域设置/Beta版：使用Unicode UTF-8提供全球语言支持）
![image](https://user-images.githubusercontent.com/15362491/54739616-b954f680-4bf3-11e9-8cef-7a9a9a76315c.png)
![image](https://user-images.githubusercontent.com/15362491/54739653-d7baf200-4bf3-11e9-92ff-a2702e2d622c.png)

**Comment by VVangYZ** [comment]
> @zombie110year
> 我和你一样的版本，把系统code page改成65001之后正常（控制面板/大图标/区域/管理/更改系统区域设置/Beta版：使用Unicode UTF-8提供全球语言支持）
> ![image](https://user-images.githubusercontent.com/15362491/54739616-b954f680-4bf3-11e9-8cef-7a9a9a76315c.png)
> ![image](https://user-images.githubusercontent.com/15362491/54739653-d7baf200-4bf3-11e9-92ff-a2702e2d622c.png)

太强了兄弟！

**Comment by lancerXXXX** [comment]
> > @zombie110year
> > 我和你一样的版本，把系统code page改成65001之后正常（控制面板/大图标/区域/管理/更改系统区域设置/Beta版：使用Unicode UTF-8提供全球语言支持）
> > ![image](https://user-images.githubusercontent.com/15362491/54739616-b954f680-4bf3-11e9-8cef-7a9a9a76315c.png)
> > ![image](https://user-images.githubusercontent.com/15362491/54739653-d7baf200-4bf3-11e9-92ff-a2702e2d622c.png)
> 
> 太强了兄弟！



> > @zombie110year
> > 我和你一样的版本，把系统code page改成65001之后正常（控制面板/大图标/区域/管理/更改系统区域设置/Beta版：使用Unicode UTF-8提供全球语言支持）
> > ![image](https://user-images.githubusercontent.com/15362491/54739616-b954f680-4bf3-11e9-8cef-7a9a9a76315c.png)
> > ![image](https://user-images.githubusercontent.com/15362491/54739653-d7baf200-4bf3-11e9-92ff-a2702e2d622c.png)
> 
> 太强了兄弟！

> 太强了兄弟！
