### ISSUE TITLE
Improving rendering speed

### ISSUE THREAD

**Issue by herohuyongtao** [shd101wyy/markdown-preview-enhanced#49]
Because of relatively slow rendering speed, it will stuck from time to time when editing large markdown files. Is it possible to improve this, e.g. to be comparable to Haroopad which can process large files in real-time?

**Comment by shd101wyy** [comment]
hi @herohuyongtao, could you please provide me with the size of file (it would be nicer if you can attach the file) so that I can test rendering speed better.

thanks

**Comment by herohuyongtao** [comment]
@shd101wyy I have sent an example of large markdown file (46Kb) to your email. Check it out. Hope you can improve it.

**Comment by shd101wyy** [comment]
Thank you very much

**Comment by herohuyongtao** [comment]
@shd101wyy Yeah, changing to **KaTex** helps a lot. Thanks for the hint. :+1:

**Comment by shd101wyy** [comment]
Sorry for the trouble. I will try to improve the rendering speed under **MathJax**.
