### ISSUE TITLE
Displaying colored text incorrectly

### ISSUE THREAD

**Issue by wwnk** [shd101wyy/markdown-preview-enhanced#490]
Thanks for your amazing plug-in first. This is one the the best plug-ins I have ever used for Markdown.

While using it, I have an issue (Maybe not an issue, just need some special settings) . It seems that this plug-in cannot display the colored text correctly. I compared the results between your plug-in (upper right) and "Markdown Preview Plus" (lower right). 

![diffpreview](https://user-images.githubusercontent.com/25244969/28055375-3f261c16-664b-11e7-8e4a-20f3b9fafef6.jpg)

Could you please help me to find a solution. Thank you so much in advance!

**Comment by shd101wyy** [comment]
@wwnk Update this package and try again?

![screen shot 2017-07-14 at 3 09 13 pm](https://user-images.githubusercontent.com/1908863/28228973-6a968e32-68a6-11e7-944d-2535a0b3e352.png)

**Comment by wwnk** [comment]
Thanks for the reply. It works the way you wrote it. However, if you insert a blank line between "font color="#ff0000"> and "This line should be red." (As I wrote in the previous comment), it still did not work. While it did work in other similar plug-ins. 

But anyway it is not a serious issue at all.

**Comment by shd101wyy** [comment]
Ok I changed the markdown parser from remarkable to markdown-it. So now it should work.  
Thanks :)

**Comment by wwnk** [comment]
It does work now. Thanks for all the effort :)
