### ISSUE TITLE
Pandoc export is broken (Ubuntu 16.04)

### ISSUE THREAD

**Issue by LuckyJimJD** [shd101wyy/markdown-preview-enhanced#495]
After updating the package today, I'm unable to export a document to PDF with Pandoc. The problem appears to be that the YAML front matter in the .md doc (screenshot attached) is not being recognized properly. So Pandoc throws an error as soon as it gets to a point in my .latex template (screenshot attached) that refers to a variable in the .md document's YAML front matter.

> Error: Command failed: pandoc -f markdown+tex_math_single_backslash -o /home/fink/Documents/Eric/Work/CivilProcedure/_syllabus/syllabus.pdf --latex-engine=xelatex --template=syllabus.latex !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ! ! fontspec error: "font-not-found" ! ! The font "" cannot be found. ! ! See the fontspec documentation for further information. ! ! For immediate help type H . !...............................................
> 
> l.49 ... Numbers={OldStyle}, Ligatures={Common}]{}
> 
> pandoc: Error producing PDF from TeX source

Here's the top of the .md document with the YAML front matter: 
![top of md file](https://user-images.githubusercontent.com/17663411/28233513-61ce4028-68c5-11e7-9d80-13ad6b257673.png)

And here's the relevant part of the .latex template: 
![snippet of latex template](https://user-images.githubusercontent.com/17663411/28233516-64ac69c8-68c5-11e7-9978-073b5e02f5c0.png)

So Pandoc appears to be ignoring the variable ($mainfont$) from the .md document's YAML block . Everything worked fine this morning before I updated the package. Nothing's changed in the .md document or .latex template since then.

**Comment by shd101wyy** [comment]
Ok I will have a look tonight. Thanks.

**Comment by shd101wyy** [comment]
It would be great if you can paste me your files here.

**Comment by LuckyJimJD** [comment]
Here you go. I've added a .txt extension so I could paste them. Thanks!

[syllabus.latex.txt](https://github.com/shd101wyy/markdown-preview-enhanced/files/1149891/syllabus.latex.txt)
[syllabus.md.txt](https://github.com/shd101wyy/markdown-preview-enhanced/files/1149892/syllabus.md.txt)

**Comment by shd101wyy** [comment]
Should be fixed now :)

**Comment by LuckyJimJD** [comment]
Yes, works perfectly. Thank you. This package is the greatest!
