### ISSUE TITLE
Preview tab not displayed

### ISSUE THREAD

**Issue by ogaaaan** [shd101wyy/markdown-preview-enhanced#499]
Hi. markdown-preview-enhanced is very cool!!!
i like it!!

this issue procces

1. open md file
2. Ctrl+Shift+M -> Preview Tab is open right side.
3. drag preview tab to md file side
4. preview is clear.

please fix.
regard!!

**Comment by shd101wyy** [comment]
Hi @ogaaaan will be fixed tonight.

**Comment by shd101wyy** [comment]
@ogaaaan Done :)

**Comment by ogaaaan** [comment]
Yeah!! it works!!
you are my hero!!
thanks a lot!
