### ISSUE TITLE
[BUG] Resizing the preview window

### ISSUE THREAD

**Issue by Digital-Playground** [shd101wyy/markdown-preview-enhanced#500]
**How to recreate the problem:**
- Open the .md preview window
- try to expand the window by dragging the border line
- as soon as you try to shrink the window with a decent mouse speed, it stops shrinking
(note: if you try to shrink it slow, it works)

**Possible causing problem:**
As soon as you enter the preview window with your mouse while shrinking the preview window, the tool block in the upper right handed corner is showing up. [[§] [reload] [UP]]

Hope this will be fixed soon because it's annoying.
Running Atom on a Win10.

**Comment by LuckyJimJD** [comment]
I've encountered this too. Resizing works fine if you drag by the tab. But not if you drag by the pane border.

**Comment by shd101wyy** [comment]
@Digital-Playground Will be fixed tonight.

**Comment by shd101wyy** [comment]
@Digital-Playground Fixed now.  
It's kinda weird that `iframe` is the one causing the issue. Even though the `iframe` didn't load any content, the problem still happens.  
So I switched from `iframe` to electron `webview`.  
Cheers :)

**Comment by Digital-Playground** [comment]
@shd101wyy Thanks alot! :) +1
