### ISSUE TITLE
vscode version: cannot open local file link

### ISSUE THREAD

**Issue by stevenniu** [shd101wyy/markdown-preview-enhanced#503]
MPE : 0.1.9
I have folder organized as:
```
- note.md
- doc\text.pdf
```
I added a link in note.md
```
[Note](doc/text.pdf)
```
When I click the link, it doesn't open the pdf file. It just open a file dialog with start loation is `My Documents`.

The same link works well in Atom version.

**Comment by shd101wyy** [comment]
I will fix this issue next weekend.

**Comment by shd101wyy** [comment]
@stevenniu should be fixed now. Thanks :)

**Comment by shd101wyy** [comment]
And please post the issue under [vscode-markdown-preview-enhanced](https://github.com/shd101wyy/vscode-markdown-preview-enhanced) repository next time :)

**Comment by stevenniu** [comment]
It works now. Thanks for you great work.
