### ISSUE TITLE
Pandoc header identifiers no longer supported?

### ISSUE THREAD

**Issue by K4zuki** [shd101wyy/markdown-preview-enhanced#506]
- Atom 1.18.0
- markdown-preview-enhanced 0.14.2
---
#### this markdown is not rendered as expected
- the code should make in-file link.
```
# foo{#foo}

[link to foo](#foo)
```
this style is inherited from pandoc header identifiers <http://pandoc.org/MANUAL.html#header-identifiers> 
#### result
- html could not dropped here so phantomjs rendered pdf is uploaded
[markdown.pdf](https://github.com/shd101wyy/markdown-preview-enhanced/files/1153138/markdown.pdf)
---
I am sure it was working with ` markdown-preview-enhanced<=0.13.0` versions.
Maybe pandoc supports crashed by these changes to `0.14.x`?

**Comment by shd101wyy** [comment]
I will fix this issue next weekend.

**Comment by shd101wyy** [comment]
@K4zuki Oh I see. Now, you need to write it as 

```markdown
# foo {id:"foo"}

[link to foo](#foo)
```
I changed to this syntax to make `pandoc` and `markdown-it` share the same logic.  

And actually you don't have to write the `id` yourself because it will be automatically generated for you.  

Thanks

**Comment by shd101wyy** [comment]
Check [this](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics?id=headers).

**Comment by K4zuki** [comment]
@shd101wyy thanks for confirmation.
I will be back after my check, then this could be closed

**Comment by K4zuki** [comment]
Hi,

Confirmed it is working. Close the thread

**Comment by shd101wyy** [comment]
@K4zuki I put the old way back.
