### ISSUE TITLE
 Mermaid.js is not displayed in the slide show.

### ISSUE THREAD

**Issue by cha2maru** [shd101wyy/markdown-preview-enhanced#510]
When using mermaid.js while creating a slide show, it was not displayed.
(Preview and Browser)

Although it seems that SVG is embedded in HTML as it confirmed in HTML, it seems that it is not displayed whether it is influence of CSS.
Please check if there is time.

**Comment by shd101wyy** [comment]
Sure I will have a look this weekend. Thanks :)

**Comment by shd101wyy** [comment]
Try delete `~/.mume` folder then restart your editor?

**Comment by cha2maru** [comment]
I tried it, but the situation did not change.
However, another Markdown did not reproduce the problem.
Let's also try to make the smallest Markdown which can reproduce the problem when time can be taken.

**Comment by cha2maru** [comment]
I have created a Markdown file that causes this problem.
Mermaid is not displayed in this Markdown file as it is, but it is displayed when you delete the first slide.

[sample.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1172043/sample.zip)

**Comment by shd101wyy** [comment]
I will have a look this weekend. Thanks :)

**Comment by cha2maru** [comment]
I tried version 0.14.7.
As a result, I confirmed that this problem was solved.
Perhaps, it seems that it was resolved by "Fixed revealjs html export style bug." Described in "newest.md".
Thank you for your response.
