### ISSUE TITLE
代码块无法显示行号哇..

### ISSUE THREAD

**Issue by initialzheng** [shd101wyy/markdown-preview-enhanced#514]
<img width="370" alt="screen shot 2017-07-20 at 00 01 07" src="https://user-images.githubusercontent.com/27876613/28377193-9f52fdea-6cde-11e7-8fab-7a0847f851f3.png">

<img width="571" alt="screen shot 2017-07-20 at 00 02 03" src="https://user-images.githubusercontent.com/27876613/28377232-bc3947ca-6cde-11e7-857c-8c47fc601bbb.png">

加了 {class:"line-numbers"}啊 QAQ

**Comment by shd101wyy** [comment]
你是前面空了 4 个格子嘛？

**Comment by shd101wyy** [comment]
最好发我一下 markdown 文件，我好看下你是怎么写滴。

**Comment by initialzheng** [comment]
前面有缩进是因为这个代码块是在内嵌在列表里面的。
删了空格还是没有=.=

**Comment by initialzheng** [comment]
我不是程序员，也是第一次接触markdown，文件有点儿傻，见笑了哈。
[new.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1162238/new.zip)

**Comment by shd101wyy** [comment]
![screen shot 2017-07-20 at 1 28 32 pm](https://user-images.githubusercontent.com/1908863/28432902-5fc492b2-6d4f-11e7-950a-a5a72bd428de.png)

我的没有问题哇。你用的是什么版本的这个插件？什么操作系统呢？

**Comment by initialzheng** [comment]
插件是2.4.10 操作系统是macOS 10.12.5

**Comment by initialzheng** [comment]
![image](https://user-images.githubusercontent.com/27876613/28449244-c4f8ba98-6e10-11e7-96b8-896f98caa05a.png)
我这边注脚、上下标、代码行号都用不了。是不是还要装别的什么markdown的插件啊？

**Comment by shd101wyy** [comment]
你插件按错了吧，我现在的最新版本是 `0.14.2`。😂  
安装完后把原生的 `markdown-preview` 给禁掉。

**Comment by shd101wyy** [comment]
你现在用的不是这个插件😂

**Comment by shd101wyy** [comment]
对，你安装的事 `markdown-preview-plus`。。。

**Comment by initialzheng** [comment]
史上最尴尬 :) 
Problem solved. 小小红包以表敬意.

**Comment by shd101wyy** [comment]
客气客气。
