### ISSUE TITLE
markdown文件太大，一直加载中

### ISSUE THREAD

**Issue by Jack-X-Yang** [shd101wyy/markdown-preview-enhanced#515]
如题，打开了一个比较大的markdown文件，大概2100行，55000字，然后就一直播放加载中的动画。
![image](https://user-images.githubusercontent.com/12390355/28403156-0534036c-6d56-11e7-8a79-3af3395cf892.png)

**Comment by shd101wyy** [comment]
最后加载出来了吗？是不是因为数学符号特别多？
方便的话可否把你的 markdown 文件发给我，我周末研究下。
谢谢

**Comment by Jack-X-Yang** [comment]
最后没加载出来。
忘了把错误信息截出来了
![image](https://user-images.githubusercontent.com/12390355/28405778-65060fc4-6d60-11e7-9862-d9b64a3c3124.png)
堆栈信息太长了，没贴出来。

感觉可能是markdown的编译器有问题，不知道marked行不行。

我看的文章：
https://github.com/getify/You-Dont-Know-JS/blob/1ed-zh-CN/async%20%26%20performance/ch3.md
https://github.com/getify/You-Dont-Know-JS/blob/1ed-zh-CN/async%20%26%20performance/ch4.md

感谢！

**Comment by shd101wyy** [comment]
@Jack-X-Yang 修好了。问题是我微循环太多了，所以我把一个函数重写了。

**Comment by Jack-X-Yang** [comment]
感谢，明天我测试一下，可以用的话就关了这个issue。

**Comment by Jack-X-Yang** [comment]
问题已经解决，非常感谢！
