### ISSUE TITLE
Pandoc-Parser can not correctly render numbered titles

### ISSUE THREAD

**Issue by liubianshi** [shd101wyy/markdown-preview-enhanced#516]
If I render file by **pandoc parser**, `# 1. Test` will be incorrectly rendered as 

# 1.Test {#1 test }

while `# Test` will be correctly rendered as

# Test

If I render the same file  by **markdown-it**, `# 1. Test`  and `# Test` will be rendered correctly.

**Comment by shd101wyy** [comment]
Will be fixed this weekend

**Comment by shd101wyy** [comment]
@liubianshi Fixed now. Thanks :)

**Comment by liubianshi** [comment]
Thanks :)
