### ISSUE TITLE
自动以第一行作为文件名保存文件

### ISSUE THREAD

**Issue by yueduz** [shd101wyy/markdown-preview-enhanced#518]
我常用atom来写文章，如果能自动以第一行来内容作为文件名来保存文件就好了。完成第一行后就自动保存文件，修改第一行也相应修改文件名。可能不是所有人都需要，可以把它作为一个选项。

**Comment by shd101wyy** [comment]
我觉得直接自己手动保存好 markdown 文件再编写吧
