### ISSUE TITLE
import sometimes not working, 404 return

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#521]
I am trying to import below link:
https://github.com/hakimel/reveal.js/wiki/Articles-&-Tutorials

```
@import "https://github.com/hakimel/reveal.js/wiki/Articles-&-Tutorials"
```
However, the preview window shows 

```
404: Not Found
```

**Comment by shd101wyy** [comment]
Hi @xu4wang ,

You **cannot** import a website. You are only allowed to import url that contains plain text like [this](https://raw.githubusercontent.com/shd101wyy/markdown-preview-enhanced/master/README.md).  

Thank you

**Comment by xu4wang** [comment]
Got it. thanks.
