### ISSUE TITLE
[Discussion] pandoc style markdown extension vs MPE style markdown extension

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/markdown-preview-enhanced#529]
* pandoc style markdown extension
    * to use id, class, and attribute
        * The code block of 0.13.0 or less supported this style, but discontinued.
    * other implementations
        * R markdown
        * PHP markdown Extra

* MPE style markdown extension
    * to use key-and-value pair
        * The code chunk and import directive of 0.13.0 or less supported this style.
        * The code block of 0.14.X supports this style, but it is buggy.

I am afraid that this change will make it impossible to pass options to pandoc well.

If compatibility is lost, I think I wanted all styles to be pandoc style.

**Comment by shd101wyy** [comment]
@tmori3y2 Don't worry. This package will automatically compile the key-value pairs style to the pandoc style if necessary.

For example
```markdown
# Hi {id:"my_id"}
```  
will be converted to 
```markdown
# Hi {#my_id}
```
and then being rendered by the pandoc parser.

**Comment by shd101wyy** [comment]
Yes you are correct. I am also struggling with which way to choose. The key-value pairs way breaks the consistency.  

```markdown
pandoc
# Hi {#id .class1 .class2 attr1=val1 attr2=val2}

mpe
# Hi {id:"id", class:"class1 class2", attr1:val1, attr2:val2}
``` 

So do you think should I only support the `pandoc` way and deprecate the second one(`mpe`)?

**Comment by shd101wyy** [comment]
@tmori3y2 After thinking for a while, I decide to adopt the the [pandoc way of defining attributes](http://pandoc.org/MANUAL.html#header-identifiers).  

```markdown

# Hi {#id .class1 .class2}

Show `line-numbers`
\`\`\`javascript {.line-numbers}
x = 1
\`\`\`

<!-- slide vertical=true .slide-class1 .slide-class2 #slide-id -->

@import "test.png" {width=50% height=30%}
```

I will release a new version this weekend.

**Comment by tmori3y2** [comment]
I was relieved to hear that.

I believe that MPE will become the strongest markdown preprocessor when it becomes possible to finely control linkage with other document processors that support markdown extension such as pandoc with classes, attributes, front-matters, and so on.

Best Regards

**Comment by shd101wyy** [comment]
Fixed now. Cheers :)

**Comment by tmori3y2** [comment]
Thanks a lot !
