### ISSUE TITLE
TOC ignore:ture does not work on my mac

### ISSUE THREAD

**Issue by cnin** [shd101wyy/markdown-preview-enhanced#531]
<img width="928" alt="screen shot 2017-07-27 at 12 55 24 am" src="https://user-images.githubusercontent.com/30452315/28633425-59e4c666-7266-11e7-931b-fccf38eb195e.png">

**Comment by cnin** [comment]
seems  that all the implementation in {} e.g. @import "test.py" {class:"line-numbers"} 
the content in {} does not work on my mac
Does anybody know why or encounter the same issue?
Could it be the permission issue or sth?

**Comment by shd101wyy** [comment]
@cnin which version of this package are you using? Please send me a bigger screenshot that contains everything.

**Comment by cnin** [comment]
version12 in atom
i turned to version14 plus vscode
everything is just perfect now
thank you again

**Comment by cnin** [comment]
and macOS
