### ISSUE TITLE
'Export to Disk' wont open with external CSS

### ISSUE THREAD

**Issue by gembutterfly** [shd101wyy/markdown-preview-enhanced#539]
Hi,

like the title says, importing an external CSS file into the markdown file makes the "Export to Disk" dialog fail and only open as soon as the preview is closed. The export does'nt work even then. 

Example:

```markdown

@import "Stil/bootstrap/css/bootstrap.min.css"

# Some stuff here

Some stuff there

```

Cheers, keep up the great work :)

**Comment by shd101wyy** [comment]
There shouldn't be export to disk option anymore. Are you using the newest version of this package?

**Comment by gembutterfly** [comment]
Ah, my bad. Thought apm install would install the latest from online repo, but it was 0.12.0.

Everything works fine with 0.14.0

Thanks

**Comment by shd101wyy** [comment]
That's weird that `apm install` didn't install the latest version...
