### ISSUE TITLE
Allow preview pane to be updated when switching between markdown tabs 

### ISSUE THREAD

**Issue by vjpr** [shd101wyy/markdown-preview-enhanced#541]
Not sure if a bug with `Automatically show preview of markdown being edited`...

**Comment by jmatsushita** [comment]
Hi there,

That is what I meant with #439

Would be great to have!

Jun

**Comment by shd101wyy** [comment]
Hi. I am a bit confused. Are you using single preview or multiple previews?

**Comment by jmatsushita** [comment]
Hi Yiyi, 

In my case I'm using only a single preview pane (on the right), but I'd like that when I switch panes (on the left) for the edited file, that the preview pane would update to the currently focused edited file.

If that's still not clear I'll do a little animated gif.

Hope that's also what @vjpr is talking about :)

Cheers,

Jun

**Comment by shd101wyy** [comment]
Please send me a gif :)

**Comment by jmatsushita** [comment]
Here you go!

![mpe-switch](https://user-images.githubusercontent.com/356097/28978673-233db338-7947-11e7-9aa7-0a12b9ccff7f.gif)

**Comment by jmatsushita** [comment]
Here's another related problem that maybe could be address at the same time ?

![mpe-switch-2](https://user-images.githubusercontent.com/356097/28978751-7e09a704-7947-11e7-8941-9e5dc9825c6b.gif)

**Comment by shd101wyy** [comment]
@jmatsushita I see. Which version of this package are you using?  
I didn't meet this issue at all. 
Can you also send me a photo of your settings?  
<img width="498" alt="screen shot 2017-08-04 at 12 09 37 pm" src="https://user-images.githubusercontent.com/1908863/28979026-d5b4720c-790d-11e7-8027-6bb9e4cd05d6.png">

**Comment by shd101wyy** [comment]
From the gif you sent me, it seems that you were not using the latest version of this package `0.14.4`.

**Comment by shd101wyy** [comment]
@jmatsushita which version of atom are you using?

**Comment by jmatsushita** [comment]
I use atom `v1.18.0`

**Comment by shd101wyy** [comment]
Well... I didn't meet this issue. So I actually don't know why. Can you open developer tool and check the console to see if there is any error?

**Comment by jmatsushita** [comment]
This is the console log for the last screen cap:

```
All dependencies installed, good to go
webview:  %c 17:33:51 (709) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/LICENSE.md
webview:  %c 17:33:51 (709) :%cDEBUG: 
webview:  %c 17:34:45 (096) :%cDEBUG: 
webview:  %c 17:34:45 (095) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/README.md
webview:  %c 17:34:45 (095) :%cDEBUG: 
webview:  %c 17:34:55 (873) :%cDEBUG: 
webview:  %c 17:34:55 (872) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/LICENSE.md
webview:  %c 17:34:55 (872) :%cDEBUG: 
webview:  %c 17:35:03 (476) :%cDEBUG: 
webview:  %c 17:35:03 (475) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/LICENSE.md
webview:  %c 17:35:03 (475) :%cDEBUG: 
webview:  %c 17:35:05 (338) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/README.md
webview:  %c 17:35:05 (338) :%cDEBUG: 
webview:  %c 17:35:15 (528) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/README.md
webview:  %c 17:35:15 (528) :%cDEBUG: 
webview:  %c 17:35:20 (935) :%cDEBUG: 
webview:  %c 17:35:20 (934) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/LICENSE.md
webview:  %c 17:35:20 (934) :%cDEBUG: 
webview:  %c 17:35:23 (572) :%cDEBUG: 
webview:  %c 17:35:23 (571) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/README.md
webview:  %c 17:35:23 (571) :%cDEBUG: 
webview:  %c 17:35:25 (677) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/LICENSE.md
webview:  %c 17:35:25 (677) :%cDEBUG: 
webview:  %c 17:36:46 (391) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/LICENSE.md
webview:  %c 17:36:46 (391) :%cDEBUG: 
webview:  %c 17:36:48 (833) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/README.md
webview:  %c 17:36:48 (833) :%cDEBUG: 
webview:  %c 17:40:44 (384) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/README.md
webview:  %c 17:40:44 (384) :%cDEBUG: 
webview:  %c 17:40:46 (291) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/LICENSE.md
webview:  %c 17:40:46 (291) :%cDEBUG: 
webview:  %c 17:41:07 (827) :%cDEBUG: 
webview:  %c 17:41:07 (826) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/README.md
webview:  %c 17:41:07 (826) :%cDEBUG: 
webview:  %c 17:41:29 (051) :%cDEBUG: 
webview:  %c 17:41:29 (050) :%cDEBUG: 
webview:  init webview: /Users/jun/dev/contentascode/markdown-preview-enhanced/README.md
webview:  %c 17:41:29 (050) :%cDEBUG: 
```

**Comment by vjpr** [comment]
@jmatsushita 

> In my case I'm using only a single preview pane (on the right), but I'd like that when I switch panes (on the left) for the edited file, that the preview pane would update to the currently focused edited file.

Yep, exactly the issue.

**Comment by shd101wyy** [comment]
@vjpr which version of this package are you using? And what operating system?

**Comment by shd101wyy** [comment]
@jmatsushita According to your last gif, after you disabled `open preview pane automatically when opening a markdown file` option, you need to run `Markdown Preview Enhanced: Toggle Preview` again to start preview. The old previews are disconnected.   

Besides, I didn't meet the double click issue...

**Comment by shd101wyy** [comment]
@jmatsushita  I think I understand why after staring at your gif for like 20 minutes 😂.  
You were using the `language-markdown` package right? I think that is the problem.  
I think [this line](https://github.com/shd101wyy/markdown-preview-enhanced/blob/0.14.4/src/extension.ts#L178) is causing the issue.  
I will fix this in next release.  

@vjpr Are you also using the `language-markdown` package?  

Thanks

**Comment by shd101wyy** [comment]
@vjpr @jmatsushita This package is now compatible with `language-markdown`.

**Comment by jmatsushita** [comment]
Awesome! Yes I was using `language-markdown` indeed. @shd101wyy Thanks so much for the vision and effort you put in the package! @vjpr I'll let you close the issue if it now works for you too.

**Comment by vjpr** [comment]
Perfect!
