### ISSUE TITLE
the shortcut key(ctrl-shift-M) doesn't work

### ISSUE THREAD

**Issue by zhuzhzh** [shd101wyy/markdown-preview-enhanced#545]
I install MPE and MPP. but MPP is disabled.

the toggle shortcut key doesn't work. but I checked the shortcut key setting in atom. everyting is ok.

Does anyone meet the same issue?

**Comment by shd101wyy** [comment]
@zhuzhzh You also need to disable `markdown preview` package.

**Comment by zhuzhzh** [comment]
before, I already disabled "markdown preview". 
I just upgrade to 0.14.6, now "c-s-M" works.
Thanks

**Comment by shd101wyy** [comment]
@zhuzhzh I didn't change anything lol... interesting. Reopen this if that issue still happens.
