### ISSUE TITLE
VSCode: Right Click at the Preview to open the context menu does not work,

### ISSUE THREAD

**Issue by 7Moses** [shd101wyy/markdown-preview-enhanced#546]
I am using MPE 02.3, VSCode 1.14.2, OS X Yosemite 10.10.5… Right Clicking at the Preview to open the context menu, works fine in Atom, does not work for me in VS Code… Any suggestions? It's likely obvious but I am not getting it,  Thanks,

**Comment by shd101wyy** [comment]
@7Moses paste a screenshot here.  Try restarting vscode.

**Comment by 7Moses** [comment]
Thanks for replying. Not sure which screenshot you want, here is one of right clicking on Preview and no context menu and one of settings.json ... Just an indication of how I have tweaked it,  Thanks,  


![settings_json_ _examples](https://user-images.githubusercontent.com/2755785/29005719-68d7e63e-7aaf-11e7-8e61-d7bd10f2f761.jpg)
![preview__article-critiquing_case_deaton_md__ _examples](https://user-images.githubusercontent.com/2755785/29005732-8a7189bc-7aaf-11e7-8528-a866c31827a7.jpg)

**Comment by shd101wyy** [comment]
@7Moses Can I see the whole window? And which operating system are you using?

**Comment by 7Moses** [comment]
MAC OSX 10.10.5 and here is settings json. Image is at the end. Thanks.  

// Place your settings in this file to overwrite the default settings
{
    //-------- Editor configuration --------

// Controls the font family.
"editor.fontFamily": "MinionPro-Disp",
    
// Controls the font size.
"editor.fontSize": 18,  
"vim.disableAnnoyingNeovimMessage": true,  
"terminal.external.osxExec": "iTerm.app",
"workbench.colorTheme": "Tiny Light",
"atomKeymap.promptV3Features": true,
"editor.multiCursorModifier": "ctrlCmd",
"editor.formatOnPaste": true,  

// Enable this option will render markdown by pandoc instead of remarkable.
"markdown-preview-enhanced.usePandocParser": false,
// In Markdown, a single newline character doesn't cause a line break in the generated HTML. In GitHub Flavored Markdown, that is not true. Enable this config option to insert line breaks in rendered HTML for single newlines in Markdown source.
"markdown-preview-enhanced.breakOnSingleNewLine": true,
// Automatic scroll sync. This is now partially supported.
"markdown-preview-enhanced.scrollSync": true,
// Open Only One Preview
"markdown-preview-enhanced.singlePreview": true,
// Enable smartypants and other sweet transforms.
"markdown-preview-enhanced.enableTypographer": true,
// Choose the Math expression rendering method here. You can also disable math rendering if you want by choosing 'None'.
"markdown-preview-enhanced.mathRenderingOption": "KaTeX",
// Use customized Math expression inline delimiters.
"markdown-preview-enhanced.mathInlineDelimiters": [
	[
		"$",
		"$"
	],
	[
		"\\(",
		"\\)"
	]
],
// Use customized Math expression block delimiters.
"markdown-preview-enhanced.mathBlockDelimiters": [
	[
		"$$",
		"$$"
	],
	[
		"\\[",
		"\\]"
	]
],
// Enable Wiki Link syntax support. More information can be found at https://help.github.com/articles/adding-links-to-wikis/
"markdown-preview-enhanced.enableWikiLinkSyntax": true,
// By default, the extension for wikilink is `.md`. For example: [[test]] will direct to file path `test.md`.
"markdown-preview-enhanced.wikiLinkFileExtension": ".md", 
// Enable extended table syntax to support merging table cells.
"markdown-preview-enhanced.enableExtendedTableSyntax": true,
// Front matter rendering option
"markdown-preview-enhanced.frontMatterRenderingOption": "code block",
// Mermaid theme, you can choose one from ["mermaid.css", "mermaid.dark.css", "mermaid.forest.css"]
"markdown-preview-enhanced.mermaidTheme": "mermaid.forest.css",
// Code block theme. If `auto.css` is chosen, then the code block theme that best matches the current preview theme will be picked.
"markdown-preview-enhanced.codeBlockTheme": "auto.css",
// Preview Theme
"markdown-preview-enhanced.previewTheme": "github-light.css",
// RevealJS Presentation Theme
"markdown-preview-enhanced.revealjsTheme": "white.css",
// Accepted protocols followed by `://` for links.
"markdown-preview-enhanced.protocolsWhiteList": "http, https, atom, file",
// When using Image Helper to copy images, by default images will be copied to root image folder path '/assets'
"markdown-preview-enhanced.imageFolderPath": "/Users/moses/Dropbox/GlobalInbox_Dropbox/",
// You can choose different image uploader to upload image
"markdown-preview-enhanced.imageUploader": "imgur",
// Whether to print background for PDF file export or not. If set to `false`, then `github-light` preview theme will be used.
"markdown-preview-enhanced.printBackground": false,
// PhantomJS executable path
"markdown-preview-enhanced.phantomPath": "phantomjs",
// Pandoc executable path
"markdown-preview-enhanced.pandocPath": "/usr/local/bin/pandoc",
// The pandoc markdown flavor you want
"markdown-preview-enhanced.pandocMarkdownFlavor": "markdown-raw_tex+tex_math_single_backslash",
// Comma separated pandoc arguments e.g. `--smart, --filter=/bin/exe`. Please use long argument names.
"markdown-preview-enhanced.pandocArguments": "",
// Default latex engine for Pandoc export and latex code chunk.
"markdown-preview-enhanced.latexEngine": "pdflatex",
// Disabling this will prevent executing code chunks and importing javascript files.
"markdown-preview-enhanced.enableScriptExecution": true,
"window.zoomLevel": 0,

}



![screenshot_06_08_2017_15_00](https://user-images.githubusercontent.com/2755785/29006157-6d1505ca-7ab8-11e7-8d65-b09e966deb41.jpg)

**Comment by shd101wyy** [comment]
@7Moses send me a screenshot like this:  

![screen shot 2017-08-06 at 3 37 25 pm](https://user-images.githubusercontent.com/1908863/29006833-2db5ea2a-7abd-11e7-8253-51284e0313a3.png)

**Comment by 7Moses** [comment]
Again Thank You For Replying, Here you Go:




![screenshot_20170806t1748](https://user-images.githubusercontent.com/2755785/29007369-cb4f8004-7acf-11e7-8438-9319410378d3.jpg)

**Comment by shd101wyy** [comment]
@7Moses And your settings? The picture you sent was so unclear.  
What preview theme are you using?  Are you using `singlePreview` now, if so, then the tab title should be `MPE preview` instead.

**Comment by 7Moses** [comment]
My apologies for taking up your time, I used the KeyBindings I used in Atom to pull up a Preview, thanks for the heads up, switched to MPE. 

Instigating Pandoc instigated a pandoc-citeproc RAM footprint of 9GB, but I will figure that myself, ;-)

Thanks for your guidance,

**Comment by shd101wyy** [comment]
@7Moses It's fine. Not a big problem :)  
Feel free to ask me question.
