### ISSUE TITLE
Problems of table of content (toc) for headers with footnotes

### ISSUE THREAD

**Issue by herohuyongtao** [shd101wyy/markdown-preview-enhanced#55]
There will be problems of table of contents (toc) for headers with footnotes.

Take the following header as an example,

    # Header [^1]

    [^1]: www.test-link.com

**Comment by shd101wyy** [comment]
Hi @herohuyongtao ,

This issue should be fixed now ;)

Thanks

**Comment by herohuyongtao** [comment]
@shd101wyy Thanks for the fix. :+1:
