### ISSUE TITLE
[[Wiki Link With Spaces]] gets converted to WikiLinkWithSpaces.md

### ISSUE THREAD

**Issue by mhulse** [shd101wyy/markdown-preview-enhanced#550]
This would not be a big deal, but BitBucket will convert `[[Wiki Link With Spaces]]` to `Wiki_Link_With_Spaces.md`.

I did't see an option to control this in the Atom prefs.

**Comment by shd101wyy** [comment]
@mhulse done.

**Comment by mhulse** [comment]
Wow, thanks @shd101wyy!

**Comment by mhulse** [comment]
Ooops, I forgot to close this issue. Thanks for doing that for me!

Thanks again for your help and the super useful code!!!!
