### ISSUE TITLE
Abbreviation and Highlight removed?

### ISSUE THREAD

**Issue by ketigid** [shd101wyy/markdown-preview-enhanced#557]
Hi,

I just updated to the 0.14.6, and I noticed that abbreviation and highlight no longer worked.

## Examples
I ==love== HTML
*[HTML]: Hypertext

They used to work in the older version, unfortunately, I didn't note the previous version number I used.

**Comment by shd101wyy** [comment]
@ketigid I will put it back in next release.  

reference: [markdown-it-abbr](https://github.com/markdown-it/markdown-it-abbr).

**Comment by shd101wyy** [comment]
@ketigid They are back now.
