### ISSUE TITLE
Awkward presentation style in browser

### ISSUE THREAD

**Issue by ttasovac** [shd101wyy/markdown-preview-enhanced#558]
Hi!

it's very cool that we can create reveal.js presentations in markdown-preview-enhanced. I'm using 0.14.6 on Mac OS X Sierra. 

Slides preview ok in Atom, but when viewed in a browser, they are not centered and only one part of the slide is visible. 

![2017-08-11 11 27 15](https://user-images.githubusercontent.com/5304839/29207931-45a42c22-7e88-11e7-92ce-8eadcba63677.png)

Is there a quick fix for this?

All best,
Toma

**Comment by ttasovac** [comment]
ok, I can fix this with:

```
html body[for="html-export"]:not([html-show-sidebar-toc]) .markdown-preview {
  transform:translateX(0%);
}
```

but i'd like to know why the default transformation here is 50% and whether everybody is seeing the effect that I'm seeing in the above screenshot

**Comment by shd101wyy** [comment]
@ttasovac  Fixed now.

**Comment by ttasovac** [comment]
Cool. Many thanks.
