### ISSUE TITLE
Disable auto image upload

### ISSUE THREAD

**Issue by dcorriveau-omniscient** [shd101wyy/markdown-preview-enhanced#561]
I quickly looked at the code and I don't see how to disable the new auto-upload to imgur function. I know I can switch the upload service but I don't see how I can disable this so that it would insert a relative link to the file on my computer instead of uploading it. How can I do this ?
Thanks.

**Comment by shd101wyy** [comment]
@dcorriveau-omniscient inserting relative path by dropping image files is not currently supported. You need to do it manually.

**Comment by ethernal** [comment]
But getting a package like markdown image helper solves the issue. Behavior of MPE autoupload cannot be configured for that - there should be at least "none" option in upload service or a checkbox to "Do not use autoupload feature"

Please remember that software is supposed to make it as easy for users to finish their work as possible, and this is an amazing piece of work you have done. I just miss the ability to define custom header and footer (ex, in LaTeX) and output an HTML render with it as PDF + automate this for my users - this could then allow us to throw Word from all use cases. People can't use 1% of Word offers, Markdown solves this easily.

**Comment by davecsmith-kcom** [comment]
Agreed - it should be able to toggle this feature off.

**Comment by shd101wyy** [comment]
Will do

**Comment by shd101wyy** [comment]
![screen shot 2017-09-30 at 9 29 19 pm](https://user-images.githubusercontent.com/1908863/31051156-749d98e0-a626-11e7-868f-e92205244b32.png)

@dcorriveau-omniscient @ethernal @davecsmith-kcom 

Done, you can set the option to `do nothing`.

**Comment by dcorriveau-omniscient** [comment]
Thank you !
