### ISSUE TITLE
Is it possible to make the output graph centralised?

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#562]
For example, by default, below puml code will generate one graph, which shows on the left side of the screen:

```puml
start
:Show QR Code in WeChat;
#LightBlue:Scan QR using EDC;
#LightBlue:Click Print;
#White:Print Form;
#Orange:Print Receipt with QR;
stop
```
Is there a way to center the generated picture?

Thanks

**Comment by shd101wyy** [comment]
@xu4wang   

    ```puml {align="center"}
    start
    :Show QR Code in WeChat;
    #LightBlue:Scan QR using EDC;
    #LightBlue:Click Print;
    #White:Print Form;
    #Orange:Print Receipt with QR;
    stop
    ```

**Comment by xu4wang** [comment]
seems not working for my installation?

![snip20170812_6](https://user-images.githubusercontent.com/311397/29237484-bbe860e6-7f51-11e7-945b-6f7a9f5cca8b.png)

**Comment by shd101wyy** [comment]
@xu4wang make sure you have upgraded this package to the newest version.  
![screen shot 2017-08-11 at 10 33 34 pm](https://user-images.githubusercontent.com/1908863/29237501-24291cc6-7ee5-11e7-8c08-754f5db0c193.png)

**Comment by xu4wang** [comment]
OK. Yes. The latest version works. 👍
