### ISSUE TITLE
Other css files?

### ISSUE THREAD

**Issue by RNCTX** [shd101wyy/markdown-preview-enhanced#564]
I'm trying to apply custom CSS rules but having limited success.

Here's my ~/.mume/style.less
```
@import url("https://fonts.googleapis.com/css?family=Open+Sans");
html body {
  // modify your style here
  // eg: background-color: blue;
  background-color: rgba(27,31,34,0.85);
  font-family: "Source Sans Pro", sans-serif;
  color: #ffffff;
}
h1, h2, h3, h4, h5, h6 {
  font-family: "Source Sans Pro", sans-serif;
  color: #ff0000;
  font-weight: 600;
  line-height: 1.5;
  text-transform: uppercase;
  letter-spacing: 0.2rem;
}
```

The preview window is picking up the font change on headers, for instance my H2s are now forced upper case as they should be, but they are ignoring the font color change, they're still black.

Here's an example....

![screen shot 2017-08-11 at 5 59 08 pm](https://user-images.githubusercontent.com/13775820/29234761-e3bb1aa2-7ebe-11e7-8b91-6b7fa7e98738.png)

**Comment by RNCTX** [comment]
Okay, nesting them got the markdown coded "test" to turn but not the headers at the top.  Where are they getting color from?

**Comment by shd101wyy** [comment]
@RNCTX I would recommend you to check [this doc](https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css).    

If you just want to use dark preview, you can change the `preview theme` from the package settings.

**Comment by RNCTX** [comment]
Well, I'm trying to mimic an existing site's appearance, the user wants a similar appearance to their live site and yours is the best markdown-preview I can find to start with, so thanks for it :).

I found the issue above, it turns out the default CSS doesn't have an entry for strong, or if it does, it's black. Once I defined text properties on` <strong>`it picked it up.

The only nagging issue I'm dealing with now before getting to work on custom tags for the markdown parser is inconsistent detection of front matter.

For example:

```
---
date: 2017-07-01 12:00:00 CDT
title: About
category: homemenu
---

## About Us
<div class="slides">
<img src="/panels/IMG_1309.JPG">
<img src="/panels/IMG_1310.JPG">
<img src="/panels/IMG_1311.JPG">
</div>
```

Renders as:

![screen shot 2017-08-11 at 9 44 10 pm](https://user-images.githubusercontent.com/13775820/29237173-45ebd008-7ede-11e7-9f49-c928a86f03f1.png)

But on the other hand, a file in the same folder is has its front matter detected properly...

```
---
date: 2017-08-03 14:22:37 CDT
title: Aksjfjs
category: post
tags: aksjfjs
facebook: Akjshfha
twitter: Aksjfjs
---
Ajsjhfha
```

The above shows up as...

![screen shot 2017-08-11 at 9 46 13 pm](https://user-images.githubusercontent.com/13775820/29237183-895e9e10-7ede-11e7-931b-86a94f1d1c60.png)

I don't think I can easily debug this one, since the only way I see to inspect the HTML output is to export it, but exporting it skips the header on properly-rendered files.  On the improperly rendered file the front matter is in the HTML, of course (between h2 tags).

**Comment by shd101wyy** [comment]
@RNCTX there are three ways to render front-matter (`yaml`, `table`, `none`), and you can change it from the package settings.     
In your case, you rendered front-matter as `yaml`.  
To see its structures, you can write yaml yourself. For example:    

    ```yaml   
    data: 2017-08-03
    ```

**Comment by RNCTX** [comment]
yes, I've changed those settings to test, but the problem is it detecting identical front matters differently, apparently by how the files are named.

I think I've found some errant mixed tabs/spaces after all, gonna chalk that up to a poor iOS editor.  Once I erased and retyped one of them it showed up properly.  Nevermind, all is well, thanks for the replies!

**Comment by shd101wyy** [comment]
BTW, there is a preview theme called none.css that applies nothing to the
preview.

**Comment by RNCTX** [comment]
Gotcha, thanks!

The only other request I have for you, it seems, is that the markdown parser does not honor the liquid `{% raw %} / {% endraw %}`tags used to bypass the parser.  I'll write a rule to output those as a space to fix it but it would be nice to have the parser pick those up in a future release.  Thanks again!

**Comment by shd101wyy** [comment]
It would be great if you can open a new issue as the new feature request if
you want. And include sample markdown files and links for references.

**Comment by RNCTX** [comment]
Will do.
