### ISSUE TITLE
Can't export ebook

### ISSUE THREAD

**Issue by qiujiahong** [shd101wyy/markdown-preview-enhanced#569]
When  I tried to export ebook. I got a error as following:
![image](https://user-images.githubusercontent.com/3654923/29254753-98edac14-80cc-11e7-83f2-f9b7344afca4.png)

![image](https://user-images.githubusercontent.com/3654923/29254755-a2214fa2-80cc-11e7-9bb4-cbb2468b2a69.png)

Windows 10
Atom 1.19.0 x64

**Comment by qiujiahong** [comment]
I tried to use vscode. But the problem still exist.
![image](https://user-images.githubusercontent.com/3654923/29254890-67071116-80ce-11e7-8569-cb825d241b8b.png)

**Comment by qiujiahong** [comment]
![image](https://user-images.githubusercontent.com/3654923/29254903-9a8d8380-80ce-11e7-8c5f-5d07167f6fa0.png)

**Comment by shd101wyy** [comment]
Hi. I will fix it when I am free. Thanks

**Comment by qiujiahong** [comment]
Hi @shd101wyy  
Thanks for you quick response.
I have just got a workaround. Use gitbook.
There are more details in the following page:
https://github.com/qiujiahong/notes-everthing/blob/master/git/readme.md.

but it is Chinese.  I hope it will help someone.

**Comment by shd101wyy** [comment]
没事儿，我中国人 😂

**Comment by shd101wyy** [comment]
@qiujiahong Fixed.

**Comment by qiujiahong** [comment]
@shd101wyy 你好，请教一个题外话。如下图的折叠目录是怎么实现的呢？我想给自己公司做一个知识库，需要这个东西；感谢；
![image](https://user-images.githubusercontent.com/3654923/29644741-2dd6cc30-88ab-11e7-96df-654c5514b32c.png)

**Comment by qiujiahong** [comment]
测试

**Comment by shd101wyy** [comment]
这个用的是 docsify.js.org 生成的。

**Comment by qiujiahong** [comment]
Thanks!
