### ISSUE TITLE
config the header and footer for exported pdf 

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#57]
Usually, there will be header and footer in normal pdf file. 
A header and a footer can be two strings located in the upper left and lower left of each pdf page.  Right now there is no header and footer in the exported pdf file.

Suggestions:
-  adding a configutation item for the header to be set in the exported pdf,
-  use the first H1 string as the footer of the page being exported

**Comment by shd101wyy** [comment]
Hi @xu4wang , I just checked electron api. 
It seems that electron does not support header and footer right now.
However, I will add header and footer support when electron adds the feature.

Thanks

**Comment by xu4wang** [comment]
Thanks @shd101wyy for your time. Awaiting for good news from electron then...

**Comment by shd101wyy** [comment]
Hi @xu4wang ,

The header and footer config is now supported.   
The Header and Footer config only works with `PhantomJS` option. You can find this option when you export the file.
You can run `Markdown Preview Enhanced: Config Header Footer` command to open config file.  
However, it is still under development so it could be buggy.     
Some known issues: https://github.com/marcbachmann/node-html-pdf/issues/113

Thanks

**Comment by xu4wang** [comment]
@shd101wyy Thanks for the new feature!
I'm trying to understand how to write a simple phantomjs_header_footer_config.js file.

It would be great if you can share one sample file..

Regards,Xu

**Comment by shd101wyy** [comment]
You can run the command that I mentioned above. It will open the config file. The config file itself includes an example.
More information can be found here https://github.com/marcbachmann/node-html-pdf

**Comment by xu4wang** [comment]
it opened an empty file named phantomjs_header_footer_config.js in my installation.

Regards,Xu

**Comment by shd101wyy** [comment]
Try restart atom and then run the command again. The file would be generated

**Comment by xu4wang** [comment]
restarted but no luck, the file is still empty.
is it a big file or just several lines? possible to share it here? thanks.

**Comment by shd101wyy** [comment]
Oh sorry I see the problem. You need to export the file to pdf first by 'PhantomJS' option, then the config file will be generated...

**Comment by shd101wyy** [comment]
```javascript
'use strict'
/*
config header and footer
more information can be found here:
    https://github.com/marcbachmann/node-html-pdf

eg:

  let config = {
    "header": {
      "height": "45mm",
      "contents": '<div style="text-align: center;">Author: Marc Bachmann</div>'
    },
    "footer": {
      "height": "28mm",
      "contents": '<span style="color: #444;">{{page}}</span>/<span>{{pages}}</span>'
    }
  }
*/
// you can edit the 'config' variable below
// everytime you changed this file, you may need to restart atom.
let config = {
  "header": {
  },
  "footer": {
  }
}

module.exports = config || {}
```

**Comment by xu4wang** [comment]
will try. 
downloading/installing phantomjs binary now.

**Comment by xu4wang** [comment]
Installed phantomjs, but still cannot get header/footer exported. 
I was able to see the generated phantomjs_header_footer_config, but atom complain about cannot find phantomjs..  A new ticket was opened #83

**Comment by xu4wang** [comment]
problem solved. thanks @shd101wyy
