### ISSUE TITLE
使用菜单启动Toggle时持续Loading preview

### ISSUE THREAD

**Issue by goldengrape** [shd101wyy/markdown-preview-enhanced#572]
如果使用菜单中的packages -> markdown-preview-enhanced -> Toggle
<img width="762" alt="2017-08-16 14 33 13" src="https://user-images.githubusercontent.com/1186927/29350170-ea8f423e-828f-11e7-901b-ca87c00eb039.png">
则在预览页面, 持续loading preview
<img width="803" alt="2017-08-16 14 28 51" src="https://user-images.githubusercontent.com/1186927/29350194-1566f600-8290-11e7-9222-2b4f08197838.png">

如果使用Toggle的快捷键shift+ctrl+M, 则出现正常预览

markdown-preview-enhanced 0.14.7
Atom 1.19.1
Mac OS 10.12.6

**Comment by shd101wyy** [comment]
@goldengrape 好的我找时间研究下。多谢啦 🙏

**Comment by shd101wyy** [comment]
修好了
