### ISSUE TITLE
Presentation with data-background-image can not use the local relative path?

### ISSUE THREAD

**Issue by GHjiangtao2014** [shd101wyy/markdown-preview-enhanced#575]
The url and the absolute local path work well whit data-background-image property. However, it seems that the relative path does not work.
How can I use a relative path?

Thank you!

Best,

Tao

**Comment by shd101wyy** [comment]
@GHjiangtao2014 It's a bug. Will be fixed in next release. Thanks

**Comment by GHjiangtao2014** [comment]
Grate! Thank you for your reply!

**Comment by shd101wyy** [comment]
I will close this issue after I fix it ;)

**Comment by shd101wyy** [comment]
@GHjiangtao2014 Fixed.

**Comment by miskovics** [comment]
@shd101wyy I can not get background image with relative file path, e.g. `<!-- slide data-background-image="test.jpg" -->`, working; a URL path, e.g. `<!-- slide data-background-image="https://i.loli.net/2017/07/12/5965b7edd3a2a.jpeg" -->`, does work. How can I confirm if the fix still works in the latest version and find out the right way to use relative path?
