### ISSUE TITLE
关闭 md 文件自动关闭预览失效

### ISSUE THREAD

**Issue by mgdreamingstar** [shd101wyy/markdown-preview-enhanced#578]
在设置里面勾选了相应选项，但好像不起作用。

另外，想问一下这张图片里面的 theme 和 syntax 是哪个？我使用的无法识别出公式以及括号。
![image](https://user-images.githubusercontent.com/26304780/29399800-402f1b1a-835d-11e7-84a1-59e9a9a1bef8.png)

另外，可否支持七牛图床呢？

**Comment by shd101wyy** [comment]
@mgdreamingstar   

安装下 [language-gfm-enhanced](https://atom.io/packages/language-gfm-enhanced)，禁用 `language-gfm`。  

syntax  是 `atom-material`。  
preview theme 是 `newsprint`。

然后关于你说的那个 bug 我有时间了再修一下吧

**Comment by shd101wyy** [comment]
哦，关于关闭预览那个，如果你是用的 single preview 的话，预览时不会自动关闭的。这个只有在你使用 multiple previews 的时候才会生效。
