### ISSUE TITLE
$$\left(x<0 \to x^2>0\right) $$ can't be rendered by Mathjax.

### ISSUE THREAD

**Issue by GitHub27182818** [shd101wyy/markdown-preview-enhanced#585]
> HTML error. Tag <0> not closed. </0> is required.

I tried using [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) to rendered and nothing arisen

**Comment by shd101wyy** [comment]
I will fix it tomorrow

**Comment by shd101wyy** [comment]
@GitHub27182818 Fixed now :)

**Comment by GitHub27182818** [comment]
<img width="788" alt="screen shot 2017-08-19 at 14 33 52" src="https://user-images.githubusercontent.com/15006150/29484197-1a03ce32-84ec-11e7-8282-6ccd76824b1b.png">
<img width="773" alt="screen shot 2017-08-19 at 14 33 43" src="https://user-images.githubusercontent.com/15006150/29484196-1a023d42-84ec-11e7-987e-6a495cb6ad91.png">
It looked absolute normal now, **thank you**!
