### ISSUE TITLE
Preview is now aggressively validating HTML :) 

### ISSUE THREAD

**Issue by ttasovac** [shd101wyy/markdown-preview-enhanced#586]
I've only noticed this today, so I'm not sure when this was introduced.

Preview is now asking for closed tags in inline code fragments, like this:

![2017-08-18 11 37 55](https://user-images.githubusercontent.com/5304839/29453708-dfdc19b2-840a-11e7-8d0e-c883bfbdd4b3.png)

I'm not sure this should be the case.

**Comment by shd101wyy** [comment]
Yes it's a bug. I will fix it today.

**Comment by shd101wyy** [comment]
@ttasovac Fixed now :)
