### ISSUE TITLE
Preview code block problem

### ISSUE THREAD

**Issue by illag** [shd101wyy/markdown-preview-enhanced#587]
Preview does not show code block highlight.

It occurred after updating to 0.14.9.

![aaaaa](https://user-images.githubusercontent.com/29787366/29478030-eb3c015a-84a5-11e7-881a-9705787b0129.png)

**Comment by shd101wyy** [comment]
@illag write it as 

<pre>
```scala
sealed trait Gender
...
```
</pre>

**Comment by illag** [comment]
OMG... thank you T.T
