### ISSUE TITLE
导出 HTML 中引入的 MathJax.js 文件无法加载

### ISSUE THREAD

**Issue by Zen-w** [shd101wyy/markdown-preview-enhanced#588]
即自动生成的此标签：
```html
<script type="text/javascript" async src="https://cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js"></script>
```
在 preview 时公式可以正常渲染，但生成的 HTML 中无法渲染，
我从官网介绍中找到这个："https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js"
是可以正常访问的，替换过后在 HTML 中可以正常渲染，
（今天（8.19）刚更新过）
我想可能是这个 CDN 在国内无法访问的原因？
还有就是在哪里可以修改这个引入 mathjax 文件的 script 标签的默认属性吗？
同时感谢你们能够做出这个插件。

**Comment by shd101wyy** [comment]
现在还不支持设置默认的 mathjax script 路径。你要不然先用 KaTeX。我下个版本换成 `cloudflare`

**Comment by Zen-w** [comment]
哦好的，谢谢

**Comment by shd101wyy** [comment]
@Zen-w 好啦。我把它换成 cloudflare host 了。

**Comment by Zen-w** [comment]
@shd101wyy    嗯 好的，谢谢
