### ISSUE TITLE
希望把一些功能添加到右键列表中, 这样会比快捷键更方便些

### ISSUE THREAD

**Issue by helloBibo** [shd101wyy/markdown-preview-enhanced#589]
![image](https://user-images.githubusercontent.com/22007931/29486268-56161178-8514-11e7-9bc3-a755f2952003.png)
把一些比如`Markdown Preview Enhanced: Toggle`这样的功能直接添加到右键列表中
个人觉得比按Ctrl+Shift+M要方便一点, 因为有的时候会忘记快捷键....
只是一些个人建议, 我觉得现在也已经非常好用了
Thanks.

**Comment by shd101wyy** [comment]
@helloBibo 这个是 vscode 还是 atom？

**Comment by helloBibo** [comment]
@shd101wyy 是vscode , vscode本身在右上角自带了一个markdown的预览, 丑的要死, 如果能直接替换这个预览就更完美了, 谢谢回复.

**Comment by shd101wyy** [comment]
@helloBibo 好啦

**Comment by helloBibo** [comment]
thank you
