### ISSUE TITLE
Need to copy the "katex/images" folder to the MPE "katex/" folder.

### ISSUE THREAD

**Issue by Matsuyanagi** [shd101wyy/markdown-preview-enhanced#590]
Does not exist MPE "katex/images" folder.
Copying "katex/images" folder in the [katex](https://github.com/Khan/KaTeX) released package to
"packages/markdown-preview-enhanced/node_modules/shd101wyy/mume/dependencies/katex/" then,
"$ \overrightarrow{AB} $" is rendering with arrow.

**Comment by shd101wyy** [comment]
@Matsuyanagi Ok I see. I will fix it in next release.

**Comment by shd101wyy** [comment]
@Matsuyanagi Done. But it seems that the newest version `0.8.3` removed the images folder.
