### ISSUE TITLE
Do not use ctrl-shift-I as keybinding

### ISSUE THREAD

**Issue by lucasdf** [shd101wyy/markdown-preview-enhanced#593]
Since ctrl-shift-I is used by Atom as one of the default keybindings (window:toggle-dev-tools) this should not be used by Markdown Preview Enhanced. Currently, it is using it for the command `markdown-preview-enhanced:image-helper`.

**Comment by shd101wyy** [comment]
Will be removed in next release.

**Comment by shd101wyy** [comment]
@lucasdf It is disabled now. Thanks.

**Comment by lucasdf** [comment]
Thank you for the quick fix and for this great package!
