### ISSUE TITLE
Preview renders front-matter as HTML table

### ISSUE THREAD

**Issue by Ultrabenosaurus** [shd101wyy/markdown-preview-enhanced#596]
Only appears in the preview, it is not there when saving the HTML to a file, but front-matter in `.md` files is rendered as a table at the top of the preview. It doesn't actually break anything as far as I can tell, but it doesn't seem to serve any real purpose either and it makes the preview look slightly "wrong."

**Comment by shd101wyy** [comment]
You can hide front-matter from [package settings](https://shd101wyy.github.io/markdown-preview-enhanced/#/usages?id=package-settings).
