### ISSUE TITLE
如何让导出的html文件与预览里面的一致包括style样式

### ISSUE THREAD

**Issue by ShynHan** [shd101wyy/markdown-preview-enhanced#597]
我更喜欢导出 html 文件，因为 浏览器 是每个系统必备的，而 PDF 可能会有打不开的时候
所以我想导出的 html 文件与预览里面的样式完全一样
包括主题、样式、颜色、字体、排版等

我想要一种在断网状态且只有一个浏览器的情况下打开导出 html 文件依然渲染良好
（减少对网络和其他 css 的依赖，比如一些公共css、网络字体等）

**Comment by ShynHan** [comment]
我目前使用自定义 CSS 的方法，在 style.less 文件中添加主题样式等来达到目的
.markdown-preview.markdown-preview {	
}

我并不懂 CSS，具体的 CSS 代码来自 markdown-preview-enhanced 安装包里的主题样式和代码区主题样式，完全复制粘贴，但是感觉这样实在是太笨了，插件本身没有这个导出功能么？

**Comment by shd101wyy** [comment]
可以去设置里把 printBackgroubd 设置为 true。
关于文件依赖难度很高，你试试 html 然后 offline 满足不满足你的需求吧

**Comment by ShynHan** [comment]
@shd101wyy 感谢你的解答，我想知道这个设置在哪个文件里

**Comment by shd101wyy** [comment]
在插件设置里。
https://shd101wyy.github.io/markdown-preview-enhanced/#/usages?id=package-settings

**Comment by ShynHan** [comment]
我最开始尝试过使用插件设置里面的这个功能，但是不知道为什么并没有效果
这次我将这个功能启用后，重启了 Atom，发现可以正常导出了，效果非常好
感谢你的及时回复，这是我用过最棒的 Markdown 编辑器
