### ISSUE TITLE
python inline plots

### ISSUE THREAD

**Issue by cnin** [shd101wyy/markdown-preview-enhanced#598]
Currently,  when the plot module is invoked, unlike any other output, the figures will be displayed in newly opened windows. 
Hope that one day the inline plots can be supported in this fantabulous Markdown Extension.

Ref.:
**%matplotlib inline**
in jupyter notebook

**Comment by shd101wyy** [comment]
If you are using code chunk, there is an option called "matplotlib", set it
to true. It's in the code chunk section of the doc website.

**Comment by cnin** [comment]
My bad. Thanks for reminding, you can close this issue now.
