### ISSUE TITLE
TOC broken with pandoc

### ISSUE THREAD

**Issue by wotanii** [shd101wyy/markdown-preview-enhanced#599]
The Function "Markdown Preview Enhance: _Create TOC_" only works when _pandoc_ is not used. 

**reproduction**: 

1. ctrl+',' 
1. search "markdown-preview-enhanced"
1. check "use pandoc parser"
1. create test.md (content below)
1. observe, that no TOC is generated, even after changing headings and saving the file
1. uncheck "use pandoc parser"
1. observe, that TOC is generated immediately after the next safe

**environment**: 

* atom 1.15.0 x64
* markdown-preview-enhanced 0.12.0
* ubuntu 17.04
* additional md-plugins:
  * markdown-img-past
  * markdown-writer
  * tool-bar-markdown-writer
* disabled plugins: markdown-preview-plus

**test.md**: 

```
### head 0
### head 1
### head 2

<!-- toc orderedList:0 depthFrom:1 depthTo:6 -->
<!-- tocstop -->
```

**Comment by shd101wyy** [comment]
@wotanii Huhh that's weird. I just tested on my machine and it works. Try restarting your editor.  
And it seems that you are not using the newest version of this package.

**Comment by wotanii** [comment]
Thanks for the hint. My atom-version seems to be out-of-date, so 0.12.0 was the newest version of this plugin I could install. 

I'm updating right now and then it should work. (I'll close this issue when it does)

**Comment by wotanii** [comment]
It works. Thanks for the help. 

(I forgot, that atom is not auto-updated by default under ubuntu, because for whatever reason it's not part of the official repo. I just hope, that the next person who is as stupid as me while safe some time by finding this issue.)

**Comment by shd101wyy** [comment]
@wotanii Not a big problem :) Feel free to ask issues.
