### ISSUE TITLE
<pre>this text is not rendered</pre>

### ISSUE THREAD

**Issue by Camypaper** [shd101wyy/markdown-preview-enhanced#60]
When I use \<pre\> tag manually, text was not rendered(I think it is because of highlighting). Is there any solution?

**Comment by shd101wyy** [comment]
Thanks for your reply.

I realized it's a bug.

I will let you know once I fix it. thanks

**Comment by shd101wyy** [comment]
Hi @Camypaper , 

this bug is now fixed in version `0.7.2`. 

Cheers
