### ISSUE TITLE
Unable to display block math formula in github

### ISSUE THREAD

**Issue by secsilm** [shd101wyy/markdown-preview-enhanced#601]
I finish my md file in VSCode and use 'Save as Markdown' to save a md file, whick I can upload it to github. But the problem is the block math formula can't display, it just display nothing. Inline math formula works fine.

![](https://i.imgur.com/G0qBtqL.png)

**Comment by shd101wyy** [comment]
@secsilm I will try to fix this issue in next release. Thanks.

**Comment by shd101wyy** [comment]
@secsilm 你是不是用了 <code>```math</code> 的写法？

**Comment by secsilm** [comment]
@shd101wyy 我用的是 `$$math$$` 写法

**Comment by shd101wyy** [comment]
@secsilm 把你的数学式发给我看看？我试了下没有问题。  
我猜可能是图片加载的问题。

**Comment by shd101wyy** [comment]
你可以看看生成的 markdown 文件是不是有给数学式子生成一个图片链接。

**Comment by secsilm** [comment]
```
Bagging 表示的是 **b**ootstrap **agg**regat**ing**。降低一个估计的方差的一个方法就是平均多个估计。例如，我们可以在一个数据集的不同子集上（有放回的随机选取）训练 <img src="https://latex.codecogs.com/gif.latex?M"/> 个不同的树然后计算结果的平均值： <p align="center"><img src="https://latex.codecogs.com/gif.latex?f(x)=&#x5C;frac{1}{M}&#x5C;Sigma_{m=1}^M f_m(x)"/></p> bagging 使用[自助抽样法](https://en.wikipedia.org/wiki/Bootstrapping_(statistics ))（bootstrapping）来为每个基学习器获得一个数据集的子集。对于如何聚合多个基学习器的结果，bagging 在分类任务中使用投票，而在回归任务重使用平均。
```

@shd101wyy 上面这段就是原文，里面有图片链接，行内公式可以正常显示，但是行间的就不行，我等了半天也还是空白

**Comment by shd101wyy** [comment]
@secsilm 把你的 markdown 文件发给我看看？

**Comment by secsilm** [comment]
@shd101wyy 在我的 GitHub 上：https://github.com/secsilm/awesome-posts/blob/master/MDs/EnsembleLearningtoImproveMachineLearningResults.md

**Comment by shd101wyy** [comment]
@secsilm 我的意思是带 `$$...$$` 的源文件，不是生成好的文件。
😂

**Comment by secsilm** [comment]
@shd101wyy 好吧，刚没理解你的意思，:stuck_out_tongue_closed_eyes:，文件在这：https://gist.github.com/secsilm/b4285a41835f226e5d67a42a4071934b

**Comment by shd101wyy** [comment]
就是你显示不出来的那一部分的`$$...$$` 中的式子是什么？我想要看一下，这样我才能 debug。😂

**Comment by shd101wyy** [comment]
妥，我看下问题出在哪里。

**Comment by shd101wyy** [comment]
@secsilm 应该是修好了现在。插件版本 `0.14.10`。

**Comment by secsilm** [comment]
@shd101wyy 我突然意识到，你说的是 atom 版本的吗？我的问题出现在 VSCode 上。:stuck_out_tongue_closed_eyes:

**Comment by shd101wyy** [comment]
@secsilm 一样的。应该都好了。这两个编辑器共享了一个插件内核。

**Comment by secsilm** [comment]
@shd101wyy 那我怎么升级呢？直接卸载重装？

**Comment by shd101wyy** [comment]
我记得 vscode 会自动升级插件的。  

如果没有的话，你可以自己去 [这里](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/releases) 下载最新的版本 `.vsix` 文件。  
然后打开 vscode，`cmd-shift-p` 接着选择 `Extensions: Install from VSIX `，选择你下载好的文件就行了。

**Comment by secsilm** [comment]
@shd101wyy release 页显示的最新版本是 `0.2.8`，是这个吗？

**Comment by shd101wyy** [comment]
对头

**Comment by secsilm** [comment]
@shd101wyy 那个问题解决了，但是有个新的问题出现了，有些行内公式的显示有问题，显示到了下一行，但是在 vscode 中的预览是正常的。
![](https://i.imgur.com/QCs7TBQ.png)

**Comment by shd101wyy** [comment]
你要是不急的话我下周末再看看了。😂

**Comment by shd101wyy** [comment]
@secsilm 我建议你这么写就没有问题了：

```markdown
梯度树提升（**Gradient Tree Boosting**）是 boosting 在任意可微分损失函数的一种推广，既可用于回归也可用于分类，同样是顺序生成基学习器。

$$F_m(x)=F_{m-1}(x)+\gamma_mh_m(x)$$ 

每一步基于当前模型 $F_{m-1}(x)$ 来计算损失 $L$，并最小化 $L$ 来训练决策树 $h_m(x)$：

$$F_m(x)=F_{m-1}(x)+\text{argmin}_h\Sigma_{i=1}^n L(y_i, F_{m-1}(x_i)+h(x_i))$$ 

使用该算法进行回归和分类任务时不同在于损失函数。
```

把 `$$...$$` 单独拿出来。

**Comment by secsilm** [comment]
@shd101wyy 确实那样把行间公式单独拿出来就好了，原本我也打算这么写的，但是我之前发现这样写的话有些markdown渲染的时候会导致公式上下间距不一致，不太美观。
