### ISSUE TITLE
更新后pdf显示不一样了, 字体变大了, 对齐也不是特别好..

### ISSUE THREAD

**Issue by salwyn** [shd101wyy/markdown-preview-enhanced#602]
没更新前preview右键导出pdf会弹出来一个灰黑的面板, 默认好像勾了Prince的, 生成的pdf跟preview基本一模一样.
更新后, 有好几个pdf的选项, chrome/ebook/PDF(prince)都需要额外加东西. 能直接使用的是 PhantomJS, 但生成的 PDF 页面跟preview显示的相差太多.
有选项可以恢复成以前那种吗? 感谢.

**Comment by shd101wyy** [comment]
Open in browser 然后手动 print 成 pdf 吧

**Comment by salwyn** [comment]
感谢，我去试试~
