### ISSUE TITLE
latex displayed twice

### ISSUE THREAD

**Issue by manroygood** [shd101wyy/markdown-preview-enhanced#604]
I created the following document with MPE, which I exported to HTML by right-clicking on the preview. It looks great on my laptop, but when I upload it to the server, the equations are displayed wrong:

https://web.njit.edu/~goodman/Math222/matlab1.html

* Following the equation $\frac{dx}{dt}=x-x^3$, the raw LaTeX for the equation appears. 
* Later on, I used \$\to\$ to draw an arrow in my text and the arrow appears twice.

**Comment by shd101wyy** [comment]
@manroygood make sure you are exporting HTML as `CDN` not `offline`.

**Comment by manroygood** [comment]
That fixed it. Thanks.
