### ISSUE TITLE
Foldable headers

### ISSUE THREAD

**Issue by aeroflux** [shd101wyy/markdown-preview-enhanced#605]
Hi there,
I am really enjoying using MPE, great piece of work. I wanted to add a possible feature request and that is foldable headers. I am writing large sections of texts and it would so convenient if one could fold headers/subheaders and its respective paragraphs. It would save a lot space.

Many thanks

**Comment by shd101wyy** [comment]
Hi @aeroflux , 

This plugin only deals with the preview part but not the editor pat.  
You might need to search for some other plugins to achieve that goal.  

Thanks :)

**Comment by aeroflux** [comment]
Thanks for the quick reply. Makes sense! If I find one that works I will post it here.
