### ISSUE TITLE
Configure Side TOC

### ISSUE THREAD

**Issue by Rodvi** [shd101wyy/markdown-preview-enhanced#606]
Hello. 
Are there any ways to configure the Side TOC (depthFrom, depthTo etc)?
I know how to configure an ordinary TOC but I don't know how to do it for the Side TOC.

Thanks.

**Comment by shd101wyy** [comment]
I will support it in next release. Thanks

**Comment by shd101wyy** [comment]
You want me to add the configuration to package settings or as front-matter?

**Comment by Rodvi** [comment]
Great.
It would be convenient to have a possibility to configure Side TOC for every separate md file. It might be hard to implement in the package settings. So I think front matter configuration would be better. Also it would be nice to have an option to configure both TOCs (side and ordinary) using the same options because most of the people don't need to configure each TOC separately.

**Comment by shd101wyy** [comment]
@Rodvi you can now configure both `[TOC]` and sidebar TOC with front-matter:    

```markdown
---
toc:
    depth_from: 1
    depth_to: 6
    ordered: false
---
```

Thanks

**Comment by Rodvi** [comment]
@shd101wyy Very well. It works but also table appears at the preview screen:
![default](https://user-images.githubusercontent.com/14225508/30001755-d6860d72-909f-11e7-9c90-17bdc1cf168a.png)

How to hide this table? 
I tried to comment the code section from previous post (using `<!--` and `-->` symbols) but that didn't work.

**Comment by shd101wyy** [comment]
You can change how to render front matter from the package settings.
Choosing "none" will hide.

**Comment by Rodvi** [comment]
@shd101wyy Thanks again.

**Comment by shexuelang** [comment]
hi， I wonder the toc front matter seetings. "sidebar TOC " means the left sidebar or something like navbar under the first title?
if "sidebar TOC " means the left sidebar, It seems it don‘t work. Here is my settings:
`
\---
toc:
  depth_from: 1
  depth_to: 6
  ordered: false
html:
  embed_local_images: true
  embed_svg: true
  offline: true
  toc: true
  print_background: false
\---
\# the first title
\[TOC]

`
