### ISSUE TITLE
可以提供命令行批量转换markdown到html的工具吗

### ISSUE THREAD

**Issue by kjgfcdb** [shd101wyy/markdown-preview-enhanced#608]
现在的转换都是要先切换出预览界面，然后右键再选择保存为html文件。能否提供一个命令行接口，使得能够批量转换markdown文件呢？
BTW，感谢你们能做这个插件，目前转换效果都非常好。

**Comment by shd101wyy** [comment]
文档里有记述过 front-matter 里面设置 export_on_save 这个功能。你可以查看一下

**Comment by xu4wang** [comment]
用 https://github.com/shd101wyy/mume 做一个命令行脚本？

**Comment by kjgfcdb** [comment]
嗯，利用提供的API做出来了，谢谢。

**Comment by xu4wang** [comment]
@kjgfcdb 方便发我一份？ 谢谢。 xu4wang@gmail.com

**Comment by wuzhidexiaoming** [comment]
老哥能不能发我一份啊  807816400@qq.com

**Comment by kjgfcdb** [comment]
@wuzhidexiaoming 按照这个安装即可
[md2pdf_wxhtmltopdf](https://www.npmjs.com/package/md2pdf_wxhtmltopdf)
