### ISSUE TITLE
编辑器中code块内的*号后的内容被认为是斜体了

### ISSUE THREAD

**Issue by xiaomingplus** [shd101wyy/markdown-preview-enhanced#61]
也就是 空了4个空格后的内容中如果出现了*号，会被编辑器认为是斜体,看着特难受，希望fix下..如下图：

![xx](http://ww1.sinaimg.cn/large/d9f8fd81gw1f55fauq7suj20se0be0u8.jpg)

(本来准备写英文的没想到 戳进代码看到了中文的注释：）

**Comment by xiaomingplus** [comment]
[](url)

**Comment by shd101wyy** [comment]
你好，

现在关于代码块，建议使用 <code>\`\`\` ... \`\`\`</code> 来写。
例如
![screen shot 2016-06-23 at 9 44 42 pm](https://cloud.githubusercontent.com/assets/1908863/16305404/37731eca-398c-11e6-82d7-3992a425f0b8.png)  

我以后有时间会考虑支持 `空4个空格` 的代码块表达方式

**Comment by shd101wyy** [comment]
最近比较忙😄 
抱歉

**Comment by shd101wyy** [comment]
我先关闭这个问题了。请看我上面的回复。
