### ISSUE TITLE
Is there a way to specify image width?

### ISSUE THREAD

**Issue by ketigid** [shd101wyy/markdown-preview-enhanced#610]
Firstly, I enjoyed using MPE very much. Thanks!

Currently, I am using html tags to do this `<img src="hog.png" alt="hog-pic" style="width:50%"/>`.

Is there another way to do this with markdown-like syntax in MPE? Or insert attributes like in headers?

**Comment by shd101wyy** [comment]
Hi @ketigid , check [this](https://shd101wyy.github.io/markdown-preview-enhanced/#/file-imports?id=configure-images).

**Comment by ketigid** [comment]
@shd101wyy It works great! My bad for missing that on the documentation.

Just one more thing, I used to center my image by using `<p style="text-align:center"><img src="hog.png" alt="hog-pic" style="width:50%"/></p>`. How do I do this with `@import`?

**Comment by shd101wyy** [comment]
@ketigid 

```markdown
@import "test.jpg" {style="position:relative; left:50%; transform:translateX(-50%);"}
```

**Comment by ketigid** [comment]
@shd101wyy 
Thanks for the quick reply. Works great! Thanks.
