### ISSUE TITLE
更新插件，设置有问题。

### ISSUE THREAD

**Issue by gaoshuming** [shd101wyy/markdown-preview-enhanced#614]
我的设置公式为 `math`, 早上更新了插件，这个设置失效了。
![b14f80e9-c272-4b1e-829b-a1f2607d8c7b](https://user-images.githubusercontent.com/8255532/30260113-085d0b1c-96f8-11e7-95c8-735bfbd75ab4.png)

**Comment by gaoshuming** [comment]
![8ed1aecb-4ed4-4e72-ba94-f23ee8cc0a6c](https://user-images.githubusercontent.com/8255532/30260165-5147b1ec-96f8-11e7-8f66-8cae7af62755.png)

**Comment by gaoshuming** [comment]
这是我的设置。

**Comment by shd101wyy** [comment]
因为设置的名称变了，你可以去 ~/.atom/config.json 把老的 markdown-preview-enhanced 部分删掉来重置设置。

原来的 math indicator 变为 math delimiter 了

**Comment by gaoshuming** [comment]
我删除了之后又重新设置了一下可是并没有生效～～～
![58e9b1bd-5752-40b7-a3a2-12f679660953](https://user-images.githubusercontent.com/8255532/30356028-7d62f01c-9869-11e7-9a4b-9d6714010864.png)

**Comment by shd101wyy** [comment]
不大可能吧。你把你的设置发张截图给我看看？

**Comment by gaoshuming** [comment]
"*":
  "atom-beautify":
    general:
      _analyticsUserId: "07ea44bc-18a4-4101-9770-f9f758e8aec4"
    markdown:
      beautify_on_save: true
      commonmark: true
      default_beautifier: "Remark"
  "autohide-tree-view": {}
  autosave:
    enabled: true
  core:
    disabledPackages: [
      "welcome"
      "language-gfm"
      "markdown-preview-plus"
    ]
    ignoredNames: [
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "._*"
      "Thumbs.db"
      "desktop.ini"
      "assets"
    ]
    packagesWithKeymapsDisabled: [
      "zentabs"
    ]
    telemetryConsent: "limited"
  editor:
    fontSize: 10
    invisibles: {}
    preferredLineLength: 999
    scrollPastEnd: true
    softTabs: false
    tabLength: 4
    tabType: "hard"
  "exception-reporting":
    userId: "d5795806-99f7-484e-b92a-42c35e31143e"
  "language-markdown":
    disableLanguageGfm: false
    emphasisShortcuts: false
  "local-history": {}
  "markdown-preview-enhanced":
    imageFolderPath: "assets"
    mathInlineDelimiters: "[[\"`math \",\"`\"],[\"$\",\"$\"],[\"\\\\(\", \"\\\\)\"]]"
    mermaidTheme: "mermaid.dark.css"
    previewTheme: "github-dark.css"
    revealjsTheme: "black.css"
    scrollDuration: "300"
  "markdown-preview-plus":
    breakOnSingleNewline: true
    enableLatexRenderingByDefault: true
    useLazyHeaders: false
  "pinned-tabs":
    animated: false
  tabs: {}
  "tidy-tabs": {}
  "tree-view":
    alwaysOpenExisting: true
    hideIgnoredNames: true
  "vim-mode": {}
  "vim-mode-plus":
    statusBarModeStringStyle: "long"
  "vim-mode-plus-ex-mode":
    notifiedUseExMode: true
  welcome:
    showOnStartup: false
  wordcount:
    ignorecode: true
  zentabs:
    maximumOpenedTabs: 4
    neverCloseUnsaved: true
    showPinnedIcon: false
".gfm.source":
  editor:
    nonWordCharacters: "/\\()\"':,.;<>~!#$%^&*|+=[]{}`?-…@"
    showIndentGuide: false
    softWrapAtPreferredLineLength: false
    tabLength: 4
".md.text":
  editor:
    showIndentGuide: true
    showInvisibles: false
    softWrapAtPreferredLineLength: false

**Comment by shd101wyy** [comment]
你的 mathInlineDelimiters 那一栏貌似写的不对，我感觉是 parse 不了的，里面得是合法的
json。😂。首先双引号里面的双引得 backslash \ escape。

你把 mathInlineDelimiter 那一栏也给删了再试试我觉得肯定可以。

**Comment by gaoshuming** [comment]
完可不可以加一下你的QQ

**Comment by gaoshuming** [comment]
mathInlineDelimiters: "[[\"`math \", \"`\"], [\"$\", \"$\"], [\"\\\\(\", \"\\\\)\"]]"
更改之后这个应该是没问题的，但是在md预览那边还是没有作用。
![2895e4f9-4c96-446c-ad70-16670f67d65c](https://user-images.githubusercontent.com/8255532/30359238-ead00236-987b-11e7-8d33-590c72b293b3.png)

**Comment by gaoshuming** [comment]
![c2886971-4908-417e-9dcf-9a888f82184e](https://user-images.githubusercontent.com/8255532/30359275-34f19b2c-987c-11e7-9f47-234783e3f46b.png)

更改之后这个应该是没问题的，但是在md预览那边还是没有作用。
![2895e4f9-4c96-446c-ad70-16670f67d65c](https://user-images.githubusercontent.com/8255532/30359279-3dc6a206-987c-11e7-9849-a078e9ffd8c7.png)

**Comment by shd101wyy** [comment]
因为 code 的优先级更高一些，所以`math ...` 这种写法会把数学的给覆盖掉。为什么要这么写呢？直接 $...$ 就好了呀

**Comment by gaoshuming** [comment]
在atom里面直接$  ...$  这个在保存的时候自动给 \frac 这公式自动加 成 \\frac

**Comment by shd101wyy** [comment]
没懂你的意思，来张截图吧😅

**Comment by shd101wyy** [comment]
而且 block 的直接 $$..$$ 就好了，不需要写 center 元素

**Comment by gaoshuming** [comment]
\frac 保存的时候自动变成 \\frac

**Comment by shd101wyy** [comment]
\frac 和 \frac 有什么不同吗😂

**Comment by gaoshuming** [comment]
是 \\\ frac

**Comment by gaoshuming** [comment]
少写一个\

**Comment by shd101wyy** [comment]
你来张截图吧，保存前和保存后的。我现在搞不懂你的意思。

**Comment by shd101wyy** [comment]
我看你的设置中 
```
"atom-beautify":
general:
analyticsUserId: "07ea44bc-18a4-4101-9770-f9f758e8aec4"
markdown:
beautify_on_save: true
```
beautify_on_save 这个可能是问题。
我觉得你把其他的插件给 disable 试试吧。

**Comment by gaoshuming** [comment]
![31d35ddd-6052-4a29-ae40-48a89d2f3b0f](https://user-images.githubusercontent.com/8255532/30360930-e2ffee3a-9886-11e7-9a67-4137c5d0d8e4.png)
保存后
![d79105e5-3ffc-4be7-b268-d97a3afa036b](https://user-images.githubusercontent.com/8255532/30360950-f922180a-9886-11e7-8b16-0f8759c67769.png)

**Comment by shd101wyy** [comment]
<img width="471" alt="screen shot 2017-09-13 at 12 26 19 am" src="https://user-images.githubusercontent.com/1908863/30361004-310c156c-981a-11e7-8adc-902689d8acf4.png">

没错，是这个 `atom-beautifier` 的问题。你把这个 markdown 部分给禁掉吧。或者把 `Remark` 换成 `Tidy`。

**Comment by gaoshuming** [comment]
我怎么恢复到默认的公式输入模式。例如:  $ ... $

**Comment by shd101wyy** [comment]
进 `markdown-preview-enhanced` 插件设置里面，然后把相应的内容给删掉就是默认的内容了。

<img width="439" alt="screen shot 2017-09-13 at 12 29 26 am" src="https://user-images.githubusercontent.com/1908863/30361094-b2a71f90-981a-11e7-8970-ecd44bd6466c.png">

**Comment by gaoshuming** [comment]
我只有     markdown-preview   插件哦

**Comment by shd101wyy** [comment]
哈？

**Comment by gaoshuming** [comment]
settings -> packages 直有三个，就是下面的三个。
atom-beatufiy
ex-mode
language-gfm-enhanced
没有你说的markdown-preview-enhanced 插件

**Comment by shd101wyy** [comment]
@gaoshuming 那就是大兄弟你没有安装我这个插件。。。

**Comment by gaoshuming** [comment]
install里面也没找到
我的配置文件里面却有这个。。配置

**Comment by shd101wyy** [comment]
估计配置是以前的。你重新安装下这个插件吧😂

**Comment by gaoshuming** [comment]
language-gfm-enhanced卸载了才能找到这两个

**Comment by shd101wyy** [comment]
我先睡了，你先自己研究下吧。怎么安装中文文档里面有。

晚安😴

**Comment by gaoshuming** [comment]
好了。全卸载重装了

**Comment by gaoshuming** [comment]
晚安晚安
