### ISSUE TITLE
Pandoc and code blocks

### ISSUE THREAD

**Issue by gmd7** [shd101wyy/markdown-preview-enhanced#617]
When using code blocks in Markdown
<pre>
``` {.java}
for (int k = 0){}
```
```java
for (int k = 0){}
```
</pre>
pandoc creates html code with syntax-highlighting:
  
&lt;div class="sourceCode"&gt;&lt;pre class="sourceCode java"&gt;&lt;code class="sourceCode java"&gt;&lt;span class="kw"&gt;for&lt;/span&gt; (&lt;span class="dt"&gt;int&lt;/span&gt; k = &lt;span class="dv"&gt;0&lt;/span&gt;){}&lt;/code&gt;&lt;/pre&gt;&lt;/div&gt;  
&lt;div class="sourceCode"&gt;&lt;pre class="sourceCode java"&gt;&lt;code class="sourceCode java"&gt;&lt;span class="kw"&gt;for&lt;/span&gt; (&lt;span class="dt"&gt;int&lt;/span&gt; k = &lt;span class="dv"&gt;0&lt;/span&gt;){}&lt;/code&gt;&lt;/pre&gt;&lt;/div&gt;  
  
  
but markdown-preview-enhanced does this only for the second code block:  
  
 &lt;pre class="language-{.java}"&gt;for (int k = 0){}  

--  

  | &lt;/pre&gt;  
  | &lt;pre class="language-java"&gt;&lt;span class="token keyword"&gt;for&lt;/span&gt; &lt;span class="token punctuation"&gt;(&lt;/span&gt;&lt;span class="token keyword"&gt;int&lt;/span&gt; k &lt;span class="token operator"&gt;=&lt;/span&gt; &lt;span class="token number"&gt;0&lt;/span&gt;&lt;span class="token punctuation"&gt;)&lt;/span&gt;&lt;span class="token punctuation"&gt;{&lt;/span&gt;&lt;span class="token punctuation"&gt;}&lt;/span&gt;  
  | &lt;/pre&gt;

_Is there any explanation for this?_

**Comment by shd101wyy** [comment]
@gmd7 Send me a zip of your source file.

**Comment by gmd7** [comment]
[test.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1307197/test.zip)

**Comment by shd101wyy** [comment]
@gmd7 Yes only the second one is supported. Why do you need to write it in the second way?

**Comment by shd101wyy** [comment]
MPE will first transform the markdown that uses special syntax to plain markdown, then processed by pandoc.

**Comment by gmd7** [comment]
Is there a possibility to do line numbering for code blocks like
<pre>
```{.java .numberLines}
for (int k = 0){}
```
</pre>

**Comment by shd101wyy** [comment]
@gmd7 There is an [issue here](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/16).  

And https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics?id=line-numbers

**Comment by shd101wyy** [comment]
I will add `.numberLines` class support.

**Comment by shd101wyy** [comment]
<pre>
```java {.line-numbers}
// This should work for now
```
</pre>

**Comment by gmd7** [comment]
Thx. Indentation is also a problem.
[test.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1308071/test.zip)

**Comment by shd101wyy** [comment]
@gmd7

Indentation bug should be fixed now. 
`.numberLines` is supported now.  

Cheers

**Comment by gmd7** [comment]
Thank you very much. Best atom-package ever!!!
