### ISSUE TITLE
LaTeX语法不能高亮

### ISSUE THREAD

**Issue by hujianhang2996** [shd101wyy/markdown-preview-enhanced#625]
刚接触markdown和LaTeX，很多问题不懂。装了markdown preview enhanced 和language LaTeX，比如公式里的“\dfrac”就只有“\d”颜色不一样。我看网上还要安装TeX Live，请问是这个原因吗？

**Comment by shd101wyy** [comment]
你是说编辑器里没有高亮，还是预览里面没有高亮呢？

**Comment by shd101wyy** [comment]
你要是指编辑器的话，并且你用的是 atom，可以安装 [language-gfm-enhanced](https://atom.io/packages/language-gfm-enhanced) 插件。

**Comment by hujianhang2996** [comment]
可以啦，谢谢！！
