### ISSUE TITLE
TOC bug

### ISSUE THREAD

**Issue by noullove** [shd101wyy/markdown-preview-enhanced#63]
The TOC function seems to be a bug.

When start with "##" is work subtitle indent.
but the start with "H1" size is not working subtitle indent. 

![good](https://cloud.githubusercontent.com/assets/2210413/16382878/91f85c00-3cbd-11e6-80aa-f89e8040d457.png)

[Good Work]

![bad](https://cloud.githubusercontent.com/assets/2210413/16382883/970d37c4-3cbd-11e6-84e3-b2f44ddb8429.png)

[Bad Work]

I hope when the next release this bug fixed.
Thanks.

**Comment by shd101wyy** [comment]
Hi, 

I recommend you to write 
```markdown
TOC 
===

## Title1
### Subtitle 2

## Title 2
### Subtitle 2
```

as 
```
TOC
===
```
is **heading1**, the next heading should be **heading2**.

;)

**Comment by noullove** [comment]
Thank you...
