### ISSUE TITLE
Export to html with pandoc

### ISSUE THREAD

**Issue by dpo** [shd101wyy/markdown-preview-enhanced#632]
How would you export to HTML with pandoc? I'm trying the `custom_document` route by adding the following to my YAML header:
```yaml
output:
  custom_document:
    path: mydoc.html
    pandoc_args: [
      "-r",  "markdown+tex_math_single_backslash+simple_tables+table_captions+yaml_metadata_block",
      "-w", "html",
      "-S",
      "--template=/path/to/some.template",
      "--css=/path/to/some.css"
    ]
```
but trying to export with Pandoc yields the error "Output format needs to be specified". I tried replacing `"-w"` with `"-t"` but the result is the same.

Thanks!

**Comment by shd101wyy** [comment]
It's a bug. I will fix it soon.  

Thanks

**Comment by shd101wyy** [comment]
@dpo Fixed now.

**Comment by dpo** [comment]
Awesome! Thanks!
