### ISSUE TITLE
Pandoc: "YAML metadata block" not working

### ISSUE THREAD

**Issue by SergeGardien** [shd101wyy/markdown-preview-enhanced#638]
I'm trying to change the font size of a markdown document with the following YAML block but nothing happens:
```
---
fontsize: 12pt
---
```

I've already enabled pandoc in markdown-preview-enhanced and it is working fine but not this YAML option (I haven't tried other YAML block options).

Same thing if I add the command "-V fontsize=10pts" in the pandoc commandline arguments. Still nothing happens.

Does it work for you?

**UPDATE:**
I've realized the above setting should work using LaTeX with PDF output [https://shd101wyy.github.io/markdown-preview-enhanced/#/pandoc-pdf?id=latex-options](https://shd101wyy.github.io/markdown-preview-enhanced/#/pandoc-pdf?id=latex-options).

Is it possible to change the fontsize in the preview too?

**Comment by shd101wyy** [comment]
To change the fontsize in preview, you need to modify the `style.less` file.
Check https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css

**Comment by SergeGardien** [comment]
Many thanks @shd101wyy, that works :-)
