### ISSUE TITLE
pdf import - wrong order of pages

### ISSUE THREAD

**Issue by docfour** [shd101wyy/markdown-preview-enhanced#641]
When importing a pdf file, the javascript code reads the files from the file system in lexicographically sorted order which is not the right page ordering.

I suggest to change the code by using string-natural-compare

var naturalCompare = require('string-natural-compare');
and inserting an

item.sort(naturalCompare) 

before converting.

**Comment by shd101wyy** [comment]
Hi @docfour ,

I am a bit busy recently. It would be great if you can submit me a pull request for that issue.  
The corresponding file is [transformer.ts](https://github.com/shd101wyy/mume/blob/master/src/transformer.ts) at [this line](https://github.com/shd101wyy/mume/blob/master/src/transformer.ts#L704

Thanks

**Comment by shd101wyy** [comment]
@docfour Done. Thanks.
