### ISSUE TITLE
Error: spawn [_______] ENOENT

### ISSUE THREAD

**Issue by icarlsen** [shd101wyy/markdown-preview-enhanced#643]
Getting both `Error: spawn gnuplot ENOENT` and  `Error: spawn erdENOENT` when running the example gnuplot and erd code chunks from the documentation
![2017-10-07 18_45_24-bpsq47 specifications md preview f__onedrive - sfu ca_ballard power systems](https://user-images.githubusercontent.com/15159990/31313181-c76b07e2-ab8f-11e7-925b-5122d0406d2a.png)

**Comment by shd101wyy** [comment]
That means you don't have `gnuplot` and `erd` installed. You need to have them installed first.

**Comment by icarlsen** [comment]
`erd` was not installed, but `gnuplot is.  I use it with Octave.

**Comment by shd101wyy** [comment]
try run `gnuplot` in terminal. if failed, then you need to add it to your path.

**Comment by icarlsen** [comment]
![image](https://user-images.githubusercontent.com/15159990/31313286-53ffd9e6-ab93-11e7-820e-e704e9f48d04.png)

`gnuplot_lib` was added, but not `gnuplot`
