### ISSUE TITLE
Ditaa Renders Broken Image

### ISSUE THREAD

**Issue by icarlsen** [shd101wyy/markdown-preview-enhanced#644]
![image](https://user-images.githubusercontent.com/15159990/31313217-fd6d3b52-ab90-11e7-8988-5a017aacb3b2.png)
Java is installed.

**Comment by icarlsen** [comment]
`plantUML` rendering seems to be fine but `

<img width="890" alt="2017-10-09 11_49_20-microsoft edge" src="https://user-images.githubusercontent.com/15159990/31353641-20636f98-ace8-11e7-92ce-8402396d3405.png">
<img width="888" alt="2017-10-09 11_48_21-microsoft edge" src="https://user-images.githubusercontent.com/15159990/31353640-205cd6ce-ace8-11e7-8d7b-029d6aa34589.png">


ditaa` hangs the previewer.

**Comment by shd101wyy** [comment]
You can't use ditta inside plantuml. It's not supported by MPE yet.

**Comment by shd101wyy** [comment]
https://github.com/shd101wyy/markdown-preview-enhanced/issues/258
