### ISSUE TITLE
Sample javascript from docs doesn't chunk (NOENT)

### ISSUE THREAD

**Issue by clozach** [shd101wyy/markdown-preview-enhanced#649]
When I paste [the code below](https://shd101wyy.github.io/markdown-preview-enhanced/#/code-chunk) into a markdown file and Run All Code Chunks, the enhanced preview shows:

_code_
\```javascript {cmd="node"}
const date = Date.now()
console.log(date.toString())
\```  

_output_
`Error: spawn node ENOENT `

Other code samples work fine, just not _javascript_.

**Comment by shd101wyy** [comment]
Do you have `nodejs` installed?

**Comment by clozach** [comment]
I believe so. When I type `node` in Terminal, I get a `>` prompt.

**Comment by shd101wyy** [comment]
I dunno why. I just tried it on my Mac and it works:  

    ```javascript {cmd="node"}
    const date = Date.now()
    console.log(date.toString())
    ```

Try restarting your editor?

**Comment by clozach** [comment]
Well…that's embarrassing! Yes, restarting worked. Sorry to trouble you. 😬

**Comment by shd101wyy** [comment]
no problem :)
