### ISSUE TITLE
plantuml rendering issue

### ISSUE THREAD

**Issue by noullove** [shd101wyy/markdown-preview-enhanced#65]
Thank you for your support.

I'm tested 0.7.2 version.

PlantUML feature is very nice working but sometimes when rendering seems to be showing the wrong.

when first rendering
![work](https://cloud.githubusercontent.com/assets/2210413/16417836/6a171030-3d82-11e6-9d73-531072b27984.png)

when save file or markdown tag add...
![bad](https://cloud.githubusercontent.com/assets/2210413/16417844/6fd870f4-3d82-11e6-9bef-a207a536e4c0.png)

plantuml string is showing left of plantuml rendering image.

Thanks.

**Comment by noullove** [comment]
Add Issue

Dash line not print properly to PDF.

Solution
puml.coffee

original
data = Buffer.concat(chunks).toString()

patch
data = Buffer.concat(chunks).toString().replace(/stroke-dasharray:/g, "fill: none; stroke-dasharray:")

reference url
http://stackoverflow.com/questions/30450905/svg-line-stroke-dasharray-not-print-properly-to-pdf

**Comment by noullove** [comment]
inside package vender directory 'plantuml.jar' is old version.
next release including new version 'plantuml.jar'.

thanks

**Comment by xu4wang** [comment]
Is pluntuml already supported? 
It's a nice feature. 👍

**Comment by xu4wang** [comment]
Just did a quick test. For the two sequence diagrams below, the first one works, the second one does not.

```plantuml

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Bob --> Alice: another authentication Response

```

```plantuml

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response

```

**Comment by shd101wyy** [comment]
Hi @noullove , 

I have never used **plantuml** before. 
Right now I am using [node-plantuml](https://github.com/markushedvall/node-plantuml) to generate diagrams.
I see people posted issue [here](https://github.com/markushedvall/node-plantuml/issues/9)
I am not sure if the newest version of **plantuml** is compatible with **node-plantuml**?
I will check it when I have time, or you can post a pull request so that I can merge later.

Thanks

**Comment by xu4wang** [comment]
I just updated the jar file to the latest one downloaded from plantuml sourceforge page. The problem I reported was not fixed. 
![1 pic](https://cloud.githubusercontent.com/assets/311397/16482328/dc943c90-3ee1-11e6-9dc0-1d326ab7bf83.JPG)

**Comment by shd101wyy** [comment]
Hi @noullove , 

I have upgraded **PlantUML** to the newest version. 
Please have a look if it works as you expect.

Thanks

**Comment by noullove** [comment]
Hi @shd101wyy,

I have tested PlantUML to the 0.7.5.
previous issue resolved but the new issue.

0.7.2 rendering success but 0.7.5 rendering error occured.
![screenshot_20160712001042](https://cloud.githubusercontent.com/assets/2210413/16735833/7e45bcd0-47c5-11e6-87dd-bff3fee43a9d.png)

I rollback 0.7.2.

i think this issue because the graphviz option.

thanks.

**Comment by shd101wyy** [comment]
Hi @noullove , sorry for the trouble. should be fixed this time ;)

**Comment by noullove** [comment]
Hi @shd101wyy 

Thanks for your speedy response and fix!
The new version seems to solve the problem.
