### ISSUE TITLE
Option to use *bold*?

### ISSUE THREAD

**Issue by JacquilynDesigns** [shd101wyy/markdown-preview-enhanced#650]
Would it be possible for you to add some sort of setting of congif file option to make a single asterisks bold? I'm to \_italics\_ and \*bold\*, and would really like to use it in atom. 

I know this isn't standard markdown behavior, so I wouldn't want it to be the default.

**Comment by shd101wyy** [comment]
No. That is hard to support. You can ask this issue under [markdown-it](https://github.com/markdown-it/markdown-it) repository.

**Comment by JacquilynDesigns** [comment]
That's ok. I closed it because I found someone who said the creator of markdown always **always** has had a single * for emphasis or italics. Probably better for me to just learn /get used to standard markdown anyway (and possibly simpler for my own life). Well and I closed it because I couldn't figure out how to delete it.
