### ISSUE TITLE
Fonts are wrong outside of atom

### ISSUE THREAD

**Issue by Cutuchiqueno** [shd101wyy/markdown-preview-enhanced#655]
I use atom 1.20.1 on Ubuntu 16.04 LTS. I tried Google Chrome and Firefox

I have much trouble with the rendering of fonts.

1. The fonts that are not installed on my machine belonging to certain themes such as Helvetica do not show up neither in the atom preview nor in the browser.

2. Other fonts that were also not installed, like Montserrat, showed up in the preview pane but not in the browser.

3. After I installed Montserrat the browser uses the font but not the right variant of the font (see image)

![grafik](https://user-images.githubusercontent.com/306064/31709001-f8517846-b3f0-11e7-958f-63ca93286ba9.png)

Shouldn't the browser get the fonts that do not exist on a machine automatically, at least this happened when I work with just reveal.js myself. And why does the exported version of the presentation does not use the bolder variant of the font even when it exists on the machine?

As I said, I do not have these problems when I create a reveal.js presentation on my own without using markdow-preview-enhanced

UPDATE: I found out that the css which is used for the 'open in browser' option and the HTML Offline export seems to be different from the one in the preview. When I look into the source file of the first two the `font-weight` rule is set to `normal`, thus it looks different from the preview. If I add custom css to the presentation that sets `font-weight` to `bold` the browser version looks the same like the preview version. Overall, there seems to be no theme consistency between preview and export. Furthermore, it does also not explain why the correct font is not imported by browsers if it does not exist locally.

**Comment by shd101wyy** [comment]
I will have a look when I have time. Thanks

**Comment by shd101wyy** [comment]
@Cutuchiqueno The font issue is fixed now. Thanks.

**Comment by Cutuchiqueno** [comment]
Thank you very much!
