### ISSUE TITLE
SHIFT + RETURN shortcut conflicts with find-and-replace package

### ISSUE THREAD

**Issue by chbk** [shd101wyy/markdown-preview-enhanced#656]
In [find-and-replace](https://github.com/atom/find-and-replace), <kbd>shift</kbd> + <kbd>return</kbd> is used to find previous matches. Would it be possible to change the <kbd>shift</kbd> + <kbd>return</kbd> shortcut in this package so it doesn't conflict?

**Comment by shd101wyy** [comment]
Oh thanks I never thought about that. I will fix this issue in next release when I have time.

**Comment by shd101wyy** [comment]
@chbk Should be fixed now. Thanks.
