### ISSUE TITLE
Unable to render plotly

### ISSUE THREAD

**Issue by CoruNethron** [shd101wyy/markdown-preview-enhanced#657]
Some variants, that i checked:
```{javascript id:"izbr5wl4", element:"<div id=\"tester\"></div>", require: ["https://cdn.plot.ly/plotly-latest.min.js"]}
//```{javascript id:"izbr5wl4", element:"<div id=\"tester\"></div>", require: ["https://cdn.plot.ly/plotly-latest.min.js"]}
TESTER = document.getElementById('tester');
Plotly.plot( TESTER, [{
x: [1, 2, 3, 4, 5],
y: [1, 2, 4, 8, 16] }], {
margin: { t: 0 } } );
''
```
Also tried to replace first string like:
{javascript ...}
javascript {...}

Also, unable to see anything when try:
```{javascript element:"<div id=\"tester\">Hello world</div>"}
//```{javascript element:"<div id=\"tester\">Hello world</div>"}
document.getElementById("tester").innerHTML("John Smith");
```

Tried to install "browser-plus" package - no change.

Also, next code works nice:
```javascript {cmd="node"}
//```javascript {cmd="node"}
console.log("Hello");
```
So, i can see "Hello" under code.

May be i miss something to get javascript to run like in browser?

**Comment by shd101wyy** [comment]
@CoruNethron Oh I forget to update the docs. Try the following code:  

<pre>
@import "https://cdn.plot.ly/plotly-latest.min.js"

```javascript {cmd=true  element="<div id='tester'></div>"}
var TESTER = document.getElementById('tester')
Plotly.plot(TESTER, [{
    x: [1, 2, 3, 4],
    y: [1, 2, 3, 4]
}, {
    margin: {t: 0}
}])
''
```
</pre>

![screen shot 2017-10-20 at 10 41 25 am](https://user-images.githubusercontent.com/1908863/31829580-526a0c06-b583-11e7-82f2-09ea7a0b9672.png)

**Comment by CoruNethron** [comment]
Thanks, now it works w/o any additional plugins ~ out of box. So, closing issue.
