### ISSUE TITLE
stdout maxBuffer exceeded on long documents

### ISSUE THREAD

**Issue by scarwire** [shd101wyy/markdown-preview-enhanced#660]
Hello everyone,

In a long markdown document, going beyond a certain length will result in a "stdout maxBuffer exceeded" error and the preview will fail.

Minimal example: fill a document with lorem ipsum or other random text for 204183 characters. Preview will work fine. Then add one or more extra characters and the preview will fail.

Similar to [this issue in another package](https://github.com/atom-community/markdown-preview-plus/issues/316) that I also reported.

All best,

Daniel

**Comment by shd101wyy** [comment]
@scarwire Thanks for reporting this. I am busy recently. I will fix this issue when I have time.

**Comment by shd101wyy** [comment]
@scarwire Fixed now. Thanks.
