### ISSUE TITLE
我下载了phantomjs但是还是提示错误

### ISSUE THREAD

**Issue by youngjuning** [shd101wyy/markdown-preview-enhanced#663]
![2017-10-29_133505](https://user-images.githubusercontent.com/13204332/32140965-03db331c-bcae-11e7-919e-dcd8ab617d35.png)

![2017-10-29_133556](https://user-images.githubusercontent.com/13204332/32140966-22b787cc-bcae-11e7-8d7a-47db9438b63b.png)

**Comment by youngjuning** [comment]
@shd101wyy 我重新 npm install ,还是报错

**Comment by shd101wyy** [comment]
得把 phantomjs 添加到系统路径。cmd 得能运行它才行

**Comment by youngjuning** [comment]
1. 执行什么命令测试

**Comment by youngjuning** [comment]
@shd101wyy 你是指系统的环境变量吗？

**Comment by youngjuning** [comment]
@shd101wyy 麻烦了，我已经解决了，不是通过npm下载，而是要去官网下那个才行，谢谢你

**Comment by shd101wyy** [comment]
没事儿～
