### ISSUE TITLE
无法开启啊

### ISSUE THREAD

**Issue by navy2016** [shd101wyy/markdown-preview-enhanced#664]
快捷键没用啊，也没有快捷键冲突，求助，谢谢

**Comment by ZYYaoYaoYao** [comment]
Please type Ctrl+k first, and then release the two keys. Then you can type a 'v' to open the preview window.

**Comment by shd101wyy** [comment]
cmd+shift+p 然后看看有没有 markdown preview enhanced 相关的命令。没有的话就说明你现在没安装成功

**Comment by navy2016** [comment]
您好，我是win10,64位，按ctrl+shift+P可以找到 markdown preview enhanced 相关的命令啊，我截了图，您帮我看一下，是什么问题

 




------------------ 原始邮件 ------------------
发件人: "Yiyi Wang";<notifications@github.com>;
发送时间: 2017年10月30日(星期一) 晚上9:46
收件人: "shd101wyy/markdown-preview-enhanced"<markdown-preview-enhanced@noreply.github.com>;
抄送: "简小飞"<2603451187@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shd101wyy/markdown-preview-enhanced] 无法开启啊 (#664)




cmd+shift+p 然后看看有没有 markdown preview enhanced 相关的命令。没有的话就说明你现在没安装成功

**Comment by navy2016** [comment]
您好，按照您的提示，但还是没法启动啊，请问这是什么原因啊？
谢谢您



 




------------------ 原始邮件 ------------------
发件人: "Yao Zou";<notifications@github.com>;
发送时间: 2017年10月30日(星期一) 晚上9:13
收件人: "shd101wyy/markdown-preview-enhanced"<markdown-preview-enhanced@noreply.github.com>;
抄送: "简小飞"<2603451187@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shd101wyy/markdown-preview-enhanced] 无法开启啊 (#664)




Please type Ctrl+k first, and then release the two keys. Then you can type a 'v' to open the preview window.

**Comment by shd101wyy** [comment]
看不到截图啊。你是怎么安装的呢？我推荐直接通过编辑器安装而不是手动安装

**Comment by navy2016** [comment]
您好，也是直接通过编辑安装的啊，能找到你说的那些项目，就是快捷键无反应，但是用自带的markdown-preview是可以用的呀
------------------ 原始邮件 ------------------
发件人: "Yiyi Wang";<notifications@github.com>;
发送时间: 2017年10月31日(星期二) 下午2:33
收件人: "shd101wyy/markdown-preview-enhanced"<markdown-preview-enhanced@noreply.github.com>;
抄送: "简小飞"<2603451187@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shd101wyy/markdown-preview-enhanced] 无法开启啊 (#664)




看不到截图啊。你是怎么安装的呢？我推荐直接通过编辑器安装而不是手动安装

**Comment by shd101wyy** [comment]
你得把自带的 markdown—preview 给禁掉

**Comment by navy2016** [comment]
您好，自带有禁用的，刚刚原因找到了，原来是新建的，需要我保存（ctrl+S）之后，快捷键ctrl+shift+M才能生效！


非常感谢！





------------------ 原始邮件 ------------------
发件人: "Yiyi Wang";<notifications@github.com>;
发送时间: 2017年11月1日(星期三) 凌晨0:48
收件人: "shd101wyy/markdown-preview-enhanced"<markdown-preview-enhanced@noreply.github.com>;
抄送: "简小飞"<2603451187@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shd101wyy/markdown-preview-enhanced] 无法开启啊 (#664)



你得把自带的 markdown—preview 给禁掉

**Comment by p5ydn0** [comment]
请问如何禁用自带的markdown-preview？我在扩展中查找内置的扩展，并没有找到markdown-preview插件(在网上也没找到解决办法)。

**Comment by shd101wyy** [comment]
插件列表里有叫做 markdown preview 的一个插件，禁用掉就好了。
