### ISSUE TITLE
Mac vs code 中markdown-preview-enhanced的菜单完全没有响应

### ISSUE THREAD

**Issue by daizhirui** [shd101wyy/markdown-preview-enhanced#667]
即使我重装vscode，只装这一个插件也不行，已经排除了插件冲突

**Comment by shd101wyy** [comment]
@daizhirui 什么菜单？

**Comment by daizhirui** [comment]
<img width="1680" alt="2017-10-31 10 02 20" src="https://user-images.githubusercontent.com/26495795/32204305-624529b4-be23-11e7-9473-d23001322b7f.png">
又进行了一下测试，我这个markdown文件在预览的时候，菜单无法响应。
<img width="1680" alt="2017-10-31 10 05 49" src="https://user-images.githubusercontent.com/26495795/32204337-859fc144-be23-11e7-9275-bcbaf1b2f838.png">
但是写一个简单的测试文件，菜单响应正常。
[HOMEWORK#7_15307110218.md.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1429354/HOMEWORK.7_15307110218.md.zip)
这个是问题文件的压缩包。谢谢！

**Comment by shd101wyy** [comment]
@daizhirui 我研究了下，貌似是因为你的文件名有 `#` 的缘故。现在你可以先把它给删除了，例如把 `HOMEWORK#7_15307110218` 换成 `HOMEWORK_7_15307110218` 然后就好了。我这周末看着修一下。

谢谢～

**Comment by daizhirui** [comment]
我试了一下，确实是这个“#”搞的鬼，不过atom版的没有这个问题。

**Comment by shd101wyy** [comment]
@daizhirui Fixed now.
