### ISSUE TITLE
I can't sync scroll and live preview 

### ISSUE THREAD

**Issue by ErrolLin** [shd101wyy/markdown-preview-enhanced#670]
this week, I update some packages, then My markdown package does not work at all.

It can't sync scroll, and it can't auto update context

this is my installed package list
```
├── atom-beautify@0.30.6
├── autocomplete-python@1.10.3
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── emmet@2.4.3
├── file-icons@2.1.13
├── git-log@0.4.1
├── hex-editor@0.1.1
├── intentions@1.1.5
├── language-babel@2.76.4
├── linter@2.2.0
├── linter-csslint@2.0.0
├── linter-flake8@2.2.1
├── linter-htmlhint@1.4.0
├── linter-jshint@3.1.6
├── linter-ui-default@1.6.10
├── markdown-preview-enhanced@0.14.11
├── minimap@4.29.7
├── platformio-ide-terminal@2.7.0
├── python-autopep8@0.1.3
└── python-tools@0.6.9
```

**Comment by shd101wyy** [comment]
@ErrolLin Did you disable `markdown-preview` package?  
You can try opening the developer tool (`View -> Developer -> Toggle Developer Tools`) then check if there is error happened in the javascript console.  

Thanks

**Comment by ErrolLin** [comment]
I can sync scroll and live preview now.
I open another .md file can sync scroll and live preview.
so I copy it to cracked md file, then reinsert the content, it work
amazing!
