### ISSUE TITLE
imagehelper filename has space,vscode cannot priview

### ISSUE THREAD

**Issue by wqfantexi** [shd101wyy/markdown-preview-enhanced#672]
本地文件生成的文件名中 class model中间有空格，vscode无法显示，把空格去掉就可以了。

谢谢

**Comment by shd101wyy** [comment]
你的图片名是什么呢？可否发给我看看？

**Comment by shd101wyy** [comment]
@wqfantexi done.

**Comment by wqfantexi** [comment]
你好，我今天试了下最新版本shd101wyy.markdown-preview-enhanced-0.3.3,好像还是不行。
markdown内容如下：
# hello
![可以显示](timg.jpg)
![不能显示](timg  nihao.jpg)

图片文件和md文件放在同一个目录，分别为timg  nihao.jpg和timg.jpg。
timg.jpg可以正常显示，但是文件名有空格的无法显示。

**Comment by wqfantexi** [comment]
···
# hello

![可以显示](timg.jpg)



![不能显示](timg  nihao.jpg)
···

**Comment by wqfantexi** [comment]
现在使用image helper导入的文件，会自动把空格替换为%20；
我还以为是再把markdown解析为html的时候转换的呢。

谢谢了。
