### ISSUE TITLE
Feature Request: Export documents via Command Palette.

### ISSUE THREAD

**Issue by gepcel** [shd101wyy/markdown-preview-enhanced#676]
Is there any way to export a document through `Command Palette`, and binding some export to a key shortcut?

I know this is a "Markdown Preview ..." package, so `Preview` is the key point, to export documents via the context menu of preview pane is obvious. And it is indeed very useful to write documents while can previewing the output at the same time. But:

* Sometimes when I write a **very little** document, or I just modify a little bit of a document, I prefer to do it without the preview pane open. 
* When I work on my laptop (with a little screen, not like the screen of desktop), it's hard to write document with the preview pane open.

So I very much need to export the document via a shortcut key, or the Command Palette.

**Comment by shd101wyy** [comment]
@gepcel Some features of this package like `mermaid` and `wavedrom` diagrams requires the preview to be open first.  

I might support your request in the future. 

Thanks

**Comment by gepcel** [comment]
Ok, noted. May be pandoc first?
