### ISSUE TITLE
simple way to remove frame of images in slides?

### ISSUE THREAD

**Issue by zahachtah** [shd101wyy/markdown-preview-enhanced#679]
I need to use the white theme but it adds a black frame around images/figures I add with ```![](path)```. Is there a simple way to turn that off, besides finding and hacking the theme file?

Many thanks, this markdown editor is pretty amazing!

**Comment by shd101wyy** [comment]
Can you please show me a scrrenshot? Thanks

**Comment by zahachtah** [comment]
<img width="977" alt="screen" src="https://user-images.githubusercontent.com/5242870/32500255-1ada76da-c3d5-11e7-8ffd-5ef875cba59a.png">

**Comment by shd101wyy** [comment]
@zahachtah Does you image file itself have a black frame?

**Comment by zahachtah** [comment]
No

**Comment by shd101wyy** [comment]
Hm that's weird. Can you please send me a zip of your source files? Thanks.

**Comment by zahachtah** [comment]
[Archive.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1453248/Archive.zip)

I found multiple ways to get rid of it, one is to add:

```
<style>
.reveal section img { background:none; border:none; box-shadow:none; }
</style>
```

at top of document

or instead of ```![](path)``` I just write

```
<img class="plain"  src="sdgs-food-azote.jpg"/>
```
or 

```
<img src="sdgs-food-azote.jpg" style="background:none; border:none; box-shadow:none;">
```

**Comment by shd101wyy** [comment]
@zahachtah I think that is the default style of revealjs white theme.  
To remove border, you can also run `Markdown Preview Enhanced: Customzie Css` command then modify the style.less file like below:  

```
.markdown-preview.markdown-preview {
  .reveal section img {
    border: none;
    box-shadow: none;
  }
}
```

Thanks

**Comment by zahachtah** [comment]
All works great, thanks a lot!

How do I add vertical slides using this markdown editor? in html it nesting <section> tags...?

**Comment by shd101wyy** [comment]
@zahachtah  `<!-- slide vertical=true -->`

**Comment by zahachtah** [comment]
Yes, thanks, i found it. Just missed it while reading the documentation
