### ISSUE TITLE
Is that possible to change markdown-preview-enhanced preview window background

### ISSUE THREAD

**Issue by TKFB** [shd101wyy/markdown-preview-enhanced#68]
Hello,  new here. Just registered. And basically new to everything markdown/atom etc.
Simply wondering is that possible to change the preview window background colour/font size. 
From the read me file, it seems you can customise the styles.less like
.markdown-preview-enhanced-custom {
  // please write your custom style here
  // eg:
  //  color: blue;          // change font color
  //  font-size: 18px;      // change font size
  //
  font-size:1.2em !important;
  // custom pdf output style
  @media print {

  }
}

But nothing worked. I have no idea regarding to how to write less code to change the font size and background colour.

Thanks.

**Comment by shd101wyy** [comment]
Hi @TKFB ,

You can edit `.markdown-preview-enhanced-custom` section like this 
![example](http://ooo.0o0.ooo/2016/07/04/577a4515ceaf6.png)  

After you make changes, you need to save the `style.less` file to make it work.

Thanks

**Comment by TKFB** [comment]
Wow,  this is fast reply! Thank you so much!
Everything just works!

I think this preview is probably the best preview for markdown out there.

In fact, the preview you developed should be called Markdown-Preview-Wonderful/Power pack, since it’s done more than just “enhanced” 👍 :) 
It’s just my two cents.

Thank you again!

**Comment by Malachov** [comment]
There is also fast option
    "markdown-preview-enhanced.previewTheme": "monokai.css" 
 in vs json settings...
