### ISSUE TITLE
Include external javascript files and execute functions from code blocks

### ISSUE THREAD

**Issue by flamed0011** [shd101wyy/markdown-preview-enhanced#684]
What I'm trying to achive is to define a global javascript function which can be triggered from various javascript code blocks.

Custom lib.js file to import:
```javascript
let write = function(word) {
  console.log('Hello ' + word);
}
```

In a previous version it was possible to require above lib.js from code blocks and trigger the function as following:

```javascript
write('Markdown');
```

This is also documented here:

> You can set require option to require external javascript files, both local and remote are supported.

https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/test/code-chunks-test.md#browser-javascript

I also tried to import lib.js as following, but it is also not working:

```
@import "lib.js" {cmd="node" hide=true}
```

Is it still possible to import external javascript files?

**Comment by shd101wyy** [comment]
If you want to use nodejs, you can write it like this:

    @import "./lib.js" {cmd="node" id="global"}

    ```javascript {cmd="node" continue="global"}
    write('Markdown');
    ```

So you import `lib.js` file, and give it a id `global`. The second code chunk continue from the id `global`.

**Comment by flamed0011** [comment]
Hi Yiyi, works very nicely. Thank you so much for all your great work!
