### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mcondarelli** [shd101wyy/markdown-preview-enhanced#687]
I tried to install (directly from within Atom) and I got an error.
I reported it as prompted ([here is bug report](https://github.com/atom/atom/issues/16175#issuecomment-343974243)), but I was redirected here by maintainers.

> It appears that this is being caused by the markdown-preview-enhanced package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The Atom FAQ has information on how to contact the maintainers of any Atom community package or theme.

Please have a look.
I will be available to help, but I have no clue on error itself and on how to track it down.

Regards

**Comment by shd101wyy** [comment]
Which version of atom are you using?

**Comment by mcondarelli** [comment]
I just installed v. 1.22.0

**Comment by shd101wyy** [comment]
Try installing from the terminal. `apm install markdown-preview-enhanced`.

**Comment by mcondarelli** [comment]
Installing from command line works.

**Comment by shd101wyy** [comment]
I actually don't know why the installation failed in atom. May I close this issue?

**Comment by mcondarelli** [comment]
I will close the issue.
If You want to dig into the problem You can contact me.

While I have You on line: Is there any plan to support also Textile?
