### ISSUE TITLE
crash with more than 1300 lines files

### ISSUE THREAD

**Issue by yxunknown** [shd101wyy/markdown-preview-enhanced#690]
always crash, when i am editing a file which is more than 1,300 lines and 30,800 Chinese characters in VS Code.

**Comment by shd101wyy** [comment]
Could you please send me your file? Thanks

**Comment by yxunknown** [comment]
Sorry for replying you until now because of busy with my exam!!! Last two days The MPE Preview didn't crash again, i don't know whether if i edit it from head ,and today i append some contents to test but not crash.If the MPE crash again i will take some screen captures and more info,Thanks your reply to my issue report!And the MPE Preview is a really helpful tools.
