### ISSUE TITLE
Vega diagram rendering (MPE vs Vega Editor)

### ISSUE THREAD

**Issue by scokobro** [shd101wyy/markdown-preview-enhanced#691]
I have a json file imported into a markdown document 'as vega-lite'; it renders _incorrectly_ in MPE while producing the expected output in the Vega website's editor (see below). Just wonder if there was any solution/explanation?

<img width="402" alt="mpe" src="https://user-images.githubusercontent.com/1475484/32899394-dbec9e86-cab8-11e7-9b78-bda1434c2131.png">This is the output in MPE

<img width="464" alt="vega editor" src="https://user-images.githubusercontent.com/1475484/32899395-dc502dc0-cab8-11e7-9131-d6a1f10e1863.png">This is in the Vega Editor

As you can see there is an issue with line colour and with how the axes are rendered.

**Comment by shd101wyy** [comment]
@scokobro can you send me your files? I will have a look when I have time. Thanks.

**Comment by scokobro** [comment]
Hi - this is an MD file containing a MWE ...

````
---
title: MWE
date: 17 Nov 2017
---

```vega-lite
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "two stepped lines",
  "width": 300,
  "data": { "values": [
  {"year": 2012,"RSF": 53,"FH": 22},
  {"year": 2013,"RSF": 53,"FH": 24},
  {"year": 2014,"RSF": 59,"FH": 25},
  {"year": 2015,"RSF": 61,"FH": 25},
  {"year": 2016,"RSF": 72,"FH": 26},
  {"year": 2017,"RSF": 72,"FH": 27}]
          },
  "layer": [
    {
     "mark": {"type": "line", "interpolate": "step-after"},
   "encoding": {
    "x": {"field": "year", "type": "ordinal", "axis": {"format": "%Y"}},
    "y": {"field": "RSF", "type": "quantitative"}}},
    {
     "mark": {"type": "line", "interpolate": "step-after", "color": "#ff9933"},
   "encoding": {
    "x": {"field": "year", "type": "ordinal", "axis": {"format": "%Y"}},
    "y": {"field": "FH", "type": "quantitative"}}}
           ],
  "resolve": {"scale": {"y": "independent"}}
}
```
ends

````

Thanks for your help!

**Comment by shd101wyy** [comment]
@scokobro I just upgraded vega and vega-lite to their newest versions. 
It should work correctly now. Thanks.

**Comment by scokobro** [comment]
Works as expected. Excellent! Many Thanks!!

Best Regards,

Scott Koga-Browes
+1 202 320 5007
+++++
