### ISSUE TITLE
">" symbol in table is not being rendered in preview.

### ISSUE THREAD

**Issue by eliiik** [shd101wyy/markdown-preview-enhanced#695]
The markdown file looks like this, with only **greater than** symbol(>) in a unit of the table (line **148**).

<img src="https://user-images.githubusercontent.com/11450267/32990665-6504e500-cd68-11e7-8e49-d1a7be206cc3.png " width="40%">

|the ">" symbol disappears in MPE|It works OK with VSC built-in markdown preview. |
|:------:|:------:|
|<img src="https://user-images.githubusercontent.com/11450267/32990667-6c0d52a6-cd68-11e7-8112-5a1dc27503ca.png " width="300px">|<img src="https://user-images.githubusercontent.com/11450267/32990668-6ea0f1f8-cd68-11e7-8e91-409206b4fbfb.png" width="300px">|
|↑ MPE view|↑ VSC built-in view|

If more words being added in ">" unit, MPE will render it properly.

<img src="https://user-images.githubusercontent.com/11450267/32990742-b1961e60-cd69-11e7-9ad3-dd1d0e208934.png" width="40%" alt="markdown file"> -> <img src="https://user-images.githubusercontent.com/11450267/32990669-702e6258-cd68-11e7-9dd4-435e85974447.png" width="40%" alt="MPE">

**Comment by shd101wyy** [comment]
Go to settings of this packagr and disable extended table syntax.

**Comment by shd101wyy** [comment]
I mean to disable `enableExtendedTableSyntax` option in package settings.

**Comment by eliiik** [comment]
I got it, It works thanks.
