### ISSUE TITLE
Single images not rendering in table cells

### ISSUE THREAD

**Issue by mirage3d** [shd101wyy/markdown-preview-enhanced#696]
Single images do not render in table cells anymore. They used to render correctly, but not anymore. If another image or another letter is added to that cell, the image renders ok.
Other markdown previewers show single images fine with no problem.
It used to work earlier in the morning, but after I wanted to continue work, it doesn't anymore. I suspected maybe other plugins interfere, so I disabled and uninstalled a few non-essential plugins, to no avail.
From the rendering, it looks like both cells are merged into one.

Code and render - unaltered:
![screen shot 2017-11-19 at 11 02 00 pm](https://user-images.githubusercontent.com/56555/32991848-04f49d2a-cd7e-11e7-8524-88762b975ca5.jpg)
![screen shot 2017-11-19 at 11 01 26 pm](https://user-images.githubusercontent.com/56555/32991849-0eb5c58c-cd7e-11e7-99f1-e8a95a842ea5.jpg)

Forcing single images to render by adding other images or letters:
![screen shot 2017-11-19 at 11 01 47 pm](https://user-images.githubusercontent.com/56555/32991852-150c42da-cd7e-11e7-9b6e-22d428624dd7.jpg)
![screen shot 2017-11-19 at 11 01 42 pm](https://user-images.githubusercontent.com/56555/32991856-1bbae230-cd7e-11e7-80bf-61316898237c.jpg)

**Comment by shd101wyy** [comment]
Could you please see the your files? Thanks

**Comment by mirage3d** [comment]
Here are sample the files using two different table styles. They should be in the same folder for ease...

Source:
```Markdown
## Single Image does not show

Header | Image
-------|---------------
Text   | ![](Key-A.png)

| Header | Image          |
|--------|----------------|
| Text   | ![](Key-A.png) |

## Two Images show

Header | Image
-------|-----------------------------------
Text   | ![](Key-A.png) ![](Mouse-Move.png)

| Header | Image                              |
|--------|------------------------------------|
| Text   | ![](Key-A.png) ![](Mouse-Move.png) |
```
![key-a](https://user-images.githubusercontent.com/56555/32992955-399d2926-cd8c-11e7-8fe2-7407c725fd13.png)
![mouse-move](https://user-images.githubusercontent.com/56555/32992956-39d21b7c-cd8c-11e7-88f9-a2b4bc7a71f1.png)

**Comment by mirage3d** [comment]
Found the culprit!!!

![screen shot 2017-11-20 at 1 00 57 am](https://user-images.githubusercontent.com/56555/32993091-58d76c64-cd8e-11e7-8cea-84f458f15203.jpg)

This setting was "on". Proper image rendering works after I turned this off.
Still probably a bug, but this is a workaround for me.
