### ISSUE TITLE
Utf-8 link in TOC doesn't work in PDF exported from chrome

### ISSUE THREAD

**Issue by sylens9** [shd101wyy/markdown-preview-enhanced#699]
test.md:

```
## test
...
## 测试
...
```
Create TOC:

```
<!-- @import "[TOC]" {cmd="toc" depthFrom=1 depthTo=6 orderedList=false} -->
<!-- code_chunk_output -->

* [test](#test)
* [测试](#测试)

<!-- /code_chunk_output -->

## test
...
## 测试
...
```

Open in browser, or export offline HTML:

```
...
<li><a href="#%E6%B5%8B%E8%AF%95">测试</a></li>
...
<h2 class="mume-header" id="&#x6D4B;&#x8BD5;">测试</h2>
...
```

The link of "测试" works in browser. 

In chrome, print to PDF, the link "test" works, but the link "测试" doesn't work.

I manually change the id of h2 tag to "%E6%B5%8B%E8%AF%95", like: 

```
...
<h2 class="mume-header" id="%E6%B5%8B%E8%AF%95">测试</h2>
...
```

then the link works in both browser and PDF. 

Cound MPE generate the HTML code in such format?

**Comment by shd101wyy** [comment]
@sylens9 Fixed now. Thanks.

**Comment by sylens9** [comment]
Thank you very much. Now the extension is perfect to me!
