### ISSUE TITLE
Problems of Latex display of exported HTML on another PC

### ISSUE THREAD

**Issue by herohuyongtao** [shd101wyy/markdown-preview-enhanced#70]
There will be problems to display Latex content of exported HTML on another PC, but no problems on the same PC. Could you please help to improve the cross-platform compatibility?

Take `$\max(x,y)$` as an example, it will show as the following figure on another PC.

![qq 20160709161515](https://cloud.githubusercontent.com/assets/1265400/16706897/5513f7cc-45f0-11e6-855f-f0d71b0498d2.jpg)

**Comment by shd101wyy** [comment]
Hi,

You may need to **enable cdn option** when exporting html.
In this way, the html generated will require network to work properly.

Thanks

**Comment by herohuyongtao** [comment]
Yes, in this way, it will use the online CSS file instead. Thanks for the hint.
