### ISSUE TITLE
toc不会使用问题，请教参数和使用方法

### ISSUE THREAD

**Issue by prlei** [shd101wyy/markdown-preview-enhanced#704]
1. 请问一下左侧边栏的编辑语法都有什么
 1.1 比如：
 
 
 这个语法参数的详细说明有么？
 1.2 左侧边栏我能自定义url吗？例如我想链接我本地的.md文档，我怎么写
    我尝试用 # 标题1 (file_1.md) 这样不可以，可是没找到其他文档
    我也遇到了这个问题：
    https://github.com/shd101wyy/markdown-preview-enhanced/issues/606
    可是没看懂解决方法，能详细点说怎么设置吗 感谢 ：）
1.3 或是是否能提供一个和您的使用文档一样结构的 demo 模版
    这个：https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/
1.4 使用文档的search是个插件么？有集成方法么？
非常感谢···！

**Comment by shd101wyy** [comment]
Hello，

你说的这个这个插件没有关系。清查看：https://docsify.js.org/#/

谢谢

**Comment by prlei** [comment]
万分感谢，很好用。
