### ISSUE TITLE
nothing generate when import .js file

### ISSUE THREAD

**Issue by visnz** [shd101wyy/markdown-preview-enhanced#706]
![1511850399 1](https://user-images.githubusercontent.com/26197210/33305250-3835fda2-d448-11e7-95ee-be168f100cd1.jpg)

and i had used  but nothing
is that something i did wrong

**Comment by shd101wyy** [comment]
@import "./code/http.js" {code_block=true}


https://shd101wyy.github.io/markdown-preview-enhanced/#/file-imports?id=force-to-render-as-code-block

**Comment by visnz** [comment]
thx !! 👍  and sorry for any inconvenience. ;P
