### ISSUE TITLE
安装了markdown-preview-enhanced后不能用

### ISSUE THREAD

**Issue by MrQ-study** [shd101wyy/markdown-preview-enhanced#711]
通过atom的setting下的package安装的markdown-preivew-enhanced，应该是安装成功了的，有部分快捷键，如插入表格什么的，是可以用的，但是打不开toggle，直接在菜单栏中的package中点击，也不能弹出toggle，关了atom自带的markdown也不行（ps，在ubuntu系统和windows系统都试过）
求大佬指教！！！

**Comment by shd101wyy** [comment]
Hi @MrQ-study 我记得这个插件没有提供插入表格的快捷键啊？你是不是安装错了插件呢？放张截图给我看看。谢谢

**Comment by MrQ-study** [comment]
sorry，快捷键是我看错了-_-||，插件是安装好了的
![selection_021](https://user-images.githubusercontent.com/15605400/33532521-4e88d084-d8d5-11e7-84b1-f2a99dbdcb62.png)

**Comment by shd101wyy** [comment]
@MrQ-study 你开以下 developer tool，然后看看 console 里面有没有报错？

**Comment by MrQ-study** [comment]
没有，console里什么信息都没有

**Comment by shd101wyy** [comment]
`cmd-shift-p` 看看有没有 `Markdown Preview Enhanced: Toggle Preview` 这条命令？

**Comment by MrQ-study** [comment]
有的
![selection_022](https://user-images.githubusercontent.com/15605400/33532770-820daa04-d8d7-11e7-8922-4afad53620f5.png)

**Comment by shd101wyy** [comment]
这个命令能用吗？

**Comment by MrQ-study** [comment]
不能，按快捷键或者直接点击都没反应

**Comment by shd101wyy** [comment]
那你卸载了重新安装试试吧。我的 Windows 并没有遇到问题。

**Comment by shd101wyy** [comment]
你可以先尝试把其他的插件给禁掉。
然后确定你的文件后缀是 `.md`。不许是已经保存好的文件，才可以打开预览。

**Comment by MrQ-study** [comment]
重装后可以了，感谢大佬！！！
