### ISSUE TITLE
[Feature Request] implicate with bib file

### ISSUE THREAD

**Issue by specter119** [shd101wyy/markdown-preview-enhanced#714]
Is it possible to implicate the reference with `*.bib` files?
Some thing like [zotero-picker](https://github.com/oztalha/zotero-picker) for atom.

My final goal is to implement the feature of Docear with MPE. Simply, It is a literature tool to connect the mind map with literature.

My ideal workflow is

1.  literatures in (Zotero)[https://www.zotero.org/],
1.  format to `*.bib` by [BBT](https://github.com/retorquere/zotero-better-bibtex),
1.  write markdown to order my idea,
1.  generate(and preview) mind map with MPE.

**Comment by shd101wyy** [comment]
Hi @specter119 , sorry for replying to you so late.
This seems to be very hard to implement. I am not very familiar with `.bib` file.
It would be great if you can submit a pull request for that feature. 
Thanks

**Comment by specter119** [comment]
@shd101wyy thanks, I think it needs to know more about pandoc. I will try if add features if I can, thanks.
