### ISSUE TITLE
无法输入$本身？

### ISSUE THREAD

**Issue by V0idk** [shd101wyy/markdown-preview-enhanced#717]
\$  111  \$ 还是被解析成公式

**Comment by shd101wyy** [comment]
@V0idk `\$`，加个 `\`

**Comment by V0idk** [comment]
...抱歉，为了输入的是markdown。

\\$ 111 \\$ 还是被解析成公式

**Comment by V0idk** [comment]
@shd101wyy 。是我的问题，没发现后面的语法错误影响了前面。我一直在前面找语法错误
![image](https://user-images.githubusercontent.com/17514799/33748072-792b21be-dc01-11e7-980e-7bc03fd27393.png)
---
![image](https://user-images.githubusercontent.com/17514799/33748089-8ec2e4b2-dc01-11e7-9b27-5570e249efa0.png)
