### ISSUE TITLE
preview link open file localy

### ISSUE THREAD

**Issue by maplewizard** [shd101wyy/markdown-preview-enhanced#72]
Hi, I want to click some link that link to some of my local pdf file. I want when I click the link, it can be opened in atom. Could you please implement this function?

**Comment by shd101wyy** [comment]
Hi @maplewizard ,

**Open in Browser** is used to open the whole rendered preview content in browser, not the link.   
To open a link of file, you can just click that link in preview.  
It now only supports opening **.md** extension file in atom. But I will support opening other types of files in atom in the future (maybe next release).  

Thanks

**Comment by maplewizard** [comment]
@shd101wyy Thanks, and I'm looking forward to see this feature. Is there any time for next release?

**Comment by shd101wyy** [comment]
By next weekend I guess.

**Comment by shd101wyy** [comment]
@maplewizard Done ;)

**Comment by maplewizard** [comment]
@shd101wyy  Thanks, but it seems only work when I open a browser with absolute path.
1. Can I call system application to open a pdf file link?
2. Can I open it with out open in broswer?

**Comment by maplewizard** [comment]
@shd101wyy Is it possible to call a system reader to open a pdf file link?

**Comment by shd101wyy** [comment]
Hi @maplewizard ,

This feature will be supported in next release.

Thansk

**Comment by shd101wyy** [comment]
Hi @maplewizard , the feature your requested is now supported. 
Cheers

**Comment by maplewizard** [comment]
It works. Great
