### ISSUE TITLE
在哪可以设置pdf自定义导出路径？

### ISSUE THREAD

**Issue by merz9b** [shd101wyy/markdown-preview-enhanced#720]
我一般使用 phantomjs 导出pdf， 但无论我在phantomjs_config.js 中添加：
```js
let config = {
"directory":"/tmp",
}
```
还是在 front-matter 中设置
```
---
phantomjs:
  output:
    path: /out_pdf/a.pdf
---
```
导出的pdf还是在当前路径下。请问应该如何设置？

**Comment by shd101wyy** [comment]
Hi @merz9b ，现在还不支持 phantomjs 导出路径。以后可能会支持。谢谢

**Comment by xu4wang** [comment]
pandoc支持pdf导出路径
