### ISSUE TITLE
Matplotlib not working

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [shd101wyy/markdown-preview-enhanced#723]
Why doesn't MPE render my graph:
![image](https://user-images.githubusercontent.com/6263572/33836468-65c41cac-de81-11e7-921e-d63ceec505be.png)

Python is installed properly as it works on the commandline:
![image](https://user-images.githubusercontent.com/6263572/33836564-a3a1afe4-de81-11e7-8362-3d6caccdf351.png)

**Comment by shd101wyy** [comment]
https://shd101wyy.github.io/markdown-preview-enhanced/#/code-chunk?id=matplotlib

It should be:

![screen shot 2017-12-11 at 10 27 12 am](https://user-images.githubusercontent.com/1908863/33841600-ded3d26e-de5d-11e7-943f-e5210f67b35e.png)

**Comment by Kshitiz-Sharma** [comment]
@shd101wyy Not working for me. Any ideas on what I can do to debug it? Is it automatically rendered or require any manual steps?

**Comment by shd101wyy** [comment]
@Kshitiz-Sharma `shift-enter` or `ctrl-shift-enter` to run a code chunk?
