### ISSUE TITLE
`Export PDF - Chrome(Puppeteer)` is Failur on windows

### ISSUE THREAD

**Issue by cha2maru** [shd101wyy/markdown-preview-enhanced#725]
PDF output using Chrome (Puppeteer) fails.

The cause is as follows.

markdown-preview-enhanced\node_modules\@shd101wyy\mume\out\src\markdown-engine.js
```javascript
            if (!puppeteer) {
                try {
                    const globalNodeModulesPath = (yield utility.execFile('npm', ['root', '-g'])).trim().split('\n')[0].trim();
                    puppeteer = require(path.resolve(globalNodeModulesPath, './puppeteer')); // trim() function here is very necessary.
                }
                catch (error) {
                    throw "Puppeteer (Headless Chrome) is required to be installed globally. Please run `npm install -g puppeteer` in your terminal.  \n";
                }
            }
```

In Windows environment 'npm' seems to have to be 'npm.cmd'.

https://github.com/nodejs/node/issues/3675

Please confirm when there is time.

**Comment by shd101wyy** [comment]
Hi @cha2maru ,

I think I tested it before on Windows. After installing puppeteer globally `npm install -g puppeteer`, you need to close Atom editor completely, then reopen the editor.
If it still doesn't help, I will have a look when I have time in the future (probably after Christmas).

Thanks

**Comment by cha2maru** [comment]
Thank you for your quick reply.

I tried restarting 'npm install -g puppeteer' and Atom which is being written, and confirmed that the problem is reproduced.
Also, by rewriting the above source from 'npm' to 'npm.cmd' in the debugging environment, we confirmed that the problem will be solved.

Perhaps, the fact that node.js in my environment is old may have influence. (If it fails at npm, is it better to try it at npm.cmd?)

have a nice Christmas!

**Comment by shd101wyy** [comment]
Yes you can try upgrading your nodejs and non to the newest version. Thank
you ;)

**Comment by shd101wyy** [comment]
I mean npm (Android keyboard is not my friend)

**Comment by cha2maru** [comment]
I tried upgrading npm to v5.6.0, but the problem did not solve it.

My environment is Windows 7 x64.
node.js v.8.4.0
npm v.5.6.0

It can be used by forcibly rewriting the corresponding part to 'npm.cmd', so it's okay for the time being. I am waiting after Christmas.

**Comment by shd101wyy** [comment]
@cha2maru Fixed now. Sorry for the delay. Thanks

**Comment by cha2maru** [comment]
Thank you very much. 
I upgraded today and confirmed that it works without problems.
