### ISSUE TITLE
Linting and beautifying text inside code chunks

### ISSUE THREAD

**Issue by kachkaev** [shd101wyy/markdown-preview-enhanced#729]
I recently discovered an option to add [`{cmd=true}`](https://shd101wyy.github.io/markdown-preview-enhanced/#/code-chunk) to code blocks, which turns out to be a truly great feature! Now that I'm writing some executable code straight in a markdown file, I'm facing a need to beautify or lint that code from time to time.

Although this job is probably outside the scope of this package, I'm wondering in something on code linting and beautifying could be discussed in the docs. What would you recommend @shd101wyy?

**Comment by shd101wyy** [comment]
Hi @kachkaev , 

I have never tried any linter tools, so I am not sure how they work and affect this package. Yeah I think it's a good idea to clarify it in the docs. 

Thank you

**Comment by kachkaev** [comment]
I'll explore the options and document them once I find anything meaningful, just give me a few weeks. If anyone has any experience in beautifying code chunks inside markdown, feel free to share your thoughts here!

**Comment by kachkaev** [comment]
Started a [PR in `atom-beautify`](https://github.com/Glavin001/atom-beautify/pull/1990), looking for feedback and help! Linting is still a question that I'm not sure how to approach.

**Comment by kachkaev** [comment]
I guess this issue is more or less solved by [Prettier](https://prettier.io) now.
