### ISSUE TITLE
WaveDrom support

### ISSUE THREAD

**Issue by Aionios** [shd101wyy/markdown-preview-enhanced#73]
[WaveDrom](https://github.com/drom/wavedrom) is a simple and powerful tool to draw timing diagram. Please consider supporting WaveDrom. Thanks!!

**Comment by shd101wyy** [comment]
Hi @Aionios ,

I just added support for **WaveDrom**, please check it out.    

![Screen Shot 2016-07-11 at 10.11.25 PM](http://ooo.0o0.ooo/2016/07/11/5783ab66a930f.png)

Just also as a remainder, **WaveDrom** is using **eval** function to parse string inside ```<script>``` tag, which is very unsafe. In my implementation, I am using **JSON.parse** to parse string. Therefore, you would have to write valid JSON string inside ```wavedrom``` notation code block. 

Thanks

**Comment by Aionios** [comment]
It works perfectly. Thank you @shd101wyy
