### ISSUE TITLE
Uncought error made package not working

### ISSUE THREAD

**Issue by fhchl** [shd101wyy/markdown-preview-enhanced#732]
Just installed markdown preview enhanced on a fresh Atom 1.23.1 install and wondered why it
s not working.

Console gives the following error message. Reason was not enough disc space.

```
Uncaught (in promise) Error: watch /home/fmheu/.mume ENOSPC
    at exports._errnoException (util.js:1022)
    at FSWatcher.start (fs.js:1316)
    at Object.fs.watch (fs.js:1341)
    at Object.<anonymous> (/home/fmheu/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:42)
    at Generator.next (<anonymous>)
    at fulfilled (/home/fmheu/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:4)
exports._errnoException @ util.js:1022
FSWatcher.start @ fs.js:1316
fs.watch @ fs.js:1341
(anonymous) @ /home/fmheu/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:42
fulfilled @ /home/fmheu/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:4
```

**Comment by shd101wyy** [comment]
How did you install this package? Through package manager or you install it
manually?

**Comment by fhchl** [comment]
I used the package manager. After I cleared some space, the package worked fine.

**Comment by shd101wyy** [comment]
Ok I will close this issue. Reopen it if that happens again. Thanks

**Comment by fhchl** [comment]
Weird, the exact same problem just popped up again. Disk space is not an issue this time.

**Comment by 2E0PGS** [comment]
I had this same issue just now. I found it's because of Linux watches. 

I saw an error in the console of Atom referencing watches and found Ubuntu 18.04 has a lower `cat /proc/sys/fs/inotify/max_user_watches` than previous versions for some reason. 

I set it to a higher number and this package worked fine after reloading it: `# echo 524288 > /proc/sys/fs/inotify/max_user_watches`
