### ISSUE TITLE
你好 请教扩展表格的问题

### ISSUE THREAD

**Issue by 4440124** [shd101wyy/markdown-preview-enhanced#733]
看见手册中的 表格扩展示例  自己试没有成功
| a | b |
|---|---|
| > |  a |
| 2 | | 
实现不了 colspan 求实现方法

**Comment by shd101wyy** [comment]
这个在插件设置中是默认关闭的，你得进插件设置然后打开。貌似是叫 `enableExtendedTableSyntax`

**Comment by 4440124** [comment]
Markdown  多行代码注释 现在会出现 ```<p data-line="112" class="sync-line" style="margin:0;"></p>```  严重影响阅读
