### ISSUE TITLE
How can I change flowchart.js style? 

### ISSUE THREAD

**Issue by Wacky515** [shd101wyy/markdown-preview-enhanced#734]
Hi,
I want to change my flowchart's style as below Demo2.

http://flowchart.js.org/

Could you please tell me how to setting?

**Comment by shd101wyy** [comment]
@Wacky515 Right now changing the style is not supported.
Might be supported in the future.
Thanks

**Comment by Wacky515** [comment]
Thank you for your answer, I undersand.
