### ISSUE TITLE
Customize Css Force Closed

### ISSUE THREAD

**Issue by NamedDavidChan** [shd101wyy/markdown-preview-enhanced#736]
Markdown Preview Enhanced: Customize Css
Edit and save , 
oops ~ 
then force closed.
AT Atom 1.23.1 x64

**Comment by shd101wyy** [comment]
No clue why that happened. May I see your style.less file?
Try removing any texts from `style.less` then save it. 
Thanks

**Comment by NamedDavidChan** [comment]
谢谢，又自己好了，感觉啥都没动过、、、

**Comment by shd101wyy** [comment]
吼～
