### ISSUE TITLE
拖拽插入图片又不可以用了

### ISSUE THREAD

**Issue by NamedDavidChan** [shd101wyy/markdown-preview-enhanced#737]
刚装的时候都还可以用，之后因为改less，软件奔溃了几次，然后图片拖拽插入就不起作用了。
拖过去后鼠标显示一个“禁止”样式，松开鼠标没有任何反应，就没然后了。。
已经卸载重装几次了。
希望解决一下。

**Comment by NamedDavidChan** [comment]
然后也不用这个的图片助手了，发现markdown-img-paste挺好用的。。。

**Comment by youngjuning** [comment]
我也是不能用拖拽插入图片了
