### ISSUE TITLE
数学公式的块状边界无法设置

### ISSUE THREAD

**Issue by iDragonfly2050** [shd101wyy/markdown-preview-enhanced#740]
我在用0.15.1版。

行内我设置成了：`[["$", "$"], ["\\(", "\\)"], ["`math", "`"]]`     是有效的。
但是块内设置成：`[["$$", "$$"], ["\\[", "\\]"], ["```math", "```"]]`  没有生效。

**Comment by shd101wyy** [comment]
块内不用设置，默认就已经支持 <pre>```math</pre> 。

**Comment by iDragonfly2050** [comment]
Thinks. @shd101wyy

**Comment by iDragonfly2050** [comment]
Thanks. @shd101wyy
