### ISSUE TITLE
[SOLVED] TOC doesn´t update when imported child structure changes

### ISSUE THREAD

**Issue by dtgoitia** [shd101wyy/markdown-preview-enhanced#743]
Hi @shd101wyy ,

I have a `parent.md` file where I import 2 childs (`child1.md` and `child2.md`). The parent contains the TOC and it reads without problem the header structure from both children.

**`parent.md`** file:
```markdown
# MJA Menu

## Table of Contents

<!-- @import "[TOC]" {cmd="toc" depthFrom=2 depthTo=3 orderedList=false} -->
<!-- code_chunk_output -->

* [Table of Contents](#table-of-contents)
* [Child1 Header](#child1-header)
* [Child2 Header](#child2-header)

<!-- /code_chunk_output -->

@import "child1.md"
@import "child2.md"
```

**`child1.md`** file:
```markdown
## Child1 Header
...
```

**`child2.md`** file:
```markdown
## Child2 Header
...
```
Till here everything okay. The issue comes when I update a header in any of the child files. Once I have created a TOC table in the parent, it doesn't update the entry. It adds new headers, but doesn't update/remove existing ones.

**Didn't work**:
* Delete the TOC partially or completelly.
* Change TOC `depthFrom` and `depthTo` values.
* Open/close preview panel.

The only work-around I've found is to reload Atom.

Let me know if you need any other detail

**Comment by shd101wyy** [comment]
Click the refresh button in the top right corner of your preview.

**Comment by dtgoitia** [comment]
Thanks @shd101wyy ! Solved.

For future references:
1. Click the refresh button in the top right corner of the parent preview.
2. Force a save.

This should update the TOC in the parent.
