### ISSUE TITLE
Feature request: 支持目录结构的markdown-tree生成

### ISSUE THREAD

**Issue by Vxider** [shd101wyy/markdown-preview-enhanced#748]
希望可以支持基于目录结构的markdown-tree生成（类似linux tree命令），这个功能在管理wiki `home.md` 时十分有用。

比如我现在的目录结构为

```
-A
--a.md
-B
--b.md
-home.md
```

希望可以在`home.md`中自动生成目录列表

```md
* A
    * [a](A/a.md)
* B
    * [b](B/b.md)
```

**Comment by shd101wyy** [comment]
@Vxider 这个我就不 implement 了，因为它可以通过使用 [Code Chunk](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/code-chunk) 来实现。
我写了一个简单的 [Code Chunk 脚本](https://gist.github.com/shd101wyy/cd21508dd886636a7bbbc67f69f17caa)。
你可以在你的 `home.md` 中插入以下文本：

```markdown
<!-- @import "https://gist.githubusercontent.com/shd101wyy/cd21508dd886636a7bbbc67f69f17caa/raw/01eb9fb4227902dc7b344fab96f6976a89a2f01e/markdown-tree.js" {cmd=node run_on_save=true hide=true output=markdown modify_source=true} -->
```

然后 **保存** 文档的时候会自动运行 Code Chunk 代码更新 tree (你需要有网以及安装了 nodejs)。

谢谢

**Comment by Vxider** [comment]
完美解决了我的问题，非常感谢！
