### ISSUE TITLE
Issue with preview

### ISSUE THREAD

**Issue by domenico-simone** [shd101wyy/markdown-preview-enhanced#75]
Hello,

for a while I have been able to have multiple previews, but all of a sudden when I toggle another preview the one that is currently open disappears (even if the upper label is still there) and I can not display any other preview, as shown in this picture:

![preview_error](https://cloud.githubusercontent.com/assets/11278300/16726845/a6d2803c-475e-11e6-844d-d7b4a3c3f131.png)

I tried to disable/enable the package, and also to uninstall/reinstall it. I am using Atom v.1.8.0 on Ubuntu 16.04.

Best,
Domenico

**Comment by shd101wyy** [comment]
Hi,

Yea it's a bug. I will fix it as soon as possible.

Thanks

**Comment by shd101wyy** [comment]
Hi @domenico-simone ,

I just uploaded a new version `0.7.5`, please help me check if that fixed the problem.

Thank you very much

**Comment by domenico-simone** [comment]
Hi @shd101wyy, sorry but now when I toggle the second preview the only result that I get is the first disappearing.

Thanks,
Domenico

**Comment by domenico-simone** [comment]
Hi @shd101wyy, here's an update. I used to toggle the preview from the Atom menu: Packages > markdown-preview-enhanced > toggle, and this reproduces the behaviour I exposed before. But when I toggle the preview with ctrl+shift+m I can get multiple previews.

**Comment by shd101wyy** [comment]
Huh I think I might understand what u mean.
For this package, there will be only **one** preview. (Unlike markdown-preview which will open different preview window for different markdown file).
When you edit another markdown file, the preview will be switched to render the content of markdown that you are editing as well.

**Comment by domenico-simone** [comment]
I see! But I am pretty sure that until yesterday I was able to have multiple previews :) Anyway tomorrow I will try this behaviour.

Thanks,
Domenico

**Comment by shd101wyy** [comment]
Hi,

I think that is because of the keymap conflict between the official **markdown preview** and this package. As they both use <keyboard>ctrl+M</keyboard> to toggle preview. You may need to disable the keymap of the official markdown preview package.

Thanks
