### ISSUE TITLE
Pandoc PDF creation problem with images on linux

### ISSUE THREAD

**Issue by bayjan** [shd101wyy/markdown-preview-enhanced#769]
There seems to be a bug when creating a pdf file using pandoc when there are images in the resulting markdown file. There seems to be two issues:
1) --pdf-engine=pdflatex  argument to pandoc should be --latex-engine=PROGRAM_YOU_HAVE or that option should be completely removed. I just removed that option and it worked fine with markdown pages without images.
So, current "solution" is: 

 - Create a PATH/bin/my_pandoc.sh, which contains followings:
```
#!/bin/bash
a=$(echo $*|sed -re 's/--pdf-engine=pdflatex//')
pandoc $a

```

 - Then change the following option in **vscode** as following: "markdown-preview-enhanced.pandocPath": "PATH/bin/my_pandoc.sh",

2) If there is an image in the resulting markdown preview and then exporting from there using pandoc pdf option gives such an error "ImageMagick is required to be installed to convert svg to png.". Which can be "solved" by creating a symbolic link to imagemagick's convert tool as a magick that are reachable through PATH.
The "solution" is:
ln -s /usr/bin/convert PATH/bin/magick

I have an ubuntu 16.04 on x64 and vscode 1.19.2.
Both are not real solutions, but just a temporary solutions. Just sharing it might help someone.

**Comment by shd101wyy** [comment]
I guess you are using pandoc whose version is below 2.0? Try using pandoc 2.0 instead

**Comment by bayjan** [comment]
Thank you, indeed I am using pandas version below 2.0.
