### ISSUE TITLE
Mermaid Subgraph doesn't render

### ISSUE THREAD

**Issue by ahaefner** [shd101wyy/markdown-preview-enhanced#77]
Hello, 
Really enjoying the package so far, thank you. 

I've run into this issue where subgraphs are not rendered correctly using mermaid after pressing the save key command:
![screen shot 2016-07-12 at 11 43 38 am](https://cloud.githubusercontent.com/assets/1606248/16779203/20fae4ae-4826-11e6-817f-3e32e316c598.png)

The subgraph seems to disappear after pressing save (command+s) on mac and is rendered correctly while live updating.  

Here's the graph:

```
mermaid
graph LR
  f-->z;
  subgraph 
    z-->y
  end
```

**Comment by shd101wyy** [comment]
Hi @ahaefner , thanks for your reply.  

It seems the mermaid library is a bit buggy after I tested several codes.
I will notice you once I solve this problem.

Thanks

**Comment by shd101wyy** [comment]
Also, **mermaidAPI.render** doesn't work properly with `sequenceDiagram` graph.

**Comment by shd101wyy** [comment]
Alright I finally figured out what caused the problem. 
The **cheerio (0.20.0)** library generated wrong code. The `html` function will convert `<div></div>` inside `svg` tag into `<div \>`. (Don't know why it is self-closed...)
It works after I downgrade it to **0.15.0**...
I will publish a new version soon.

**Comment by shd101wyy** [comment]
Hi @ahaefner , I just post a new version `0.7.6`. This problem should be fixed now. Thanks

**Comment by ahaefner** [comment]
Thanks for your speedy response and fix! The new version seems to solve the
problem.
