### ISSUE TITLE
使用 Code Chunk 时,自动添加了文件所在路径

### ISSUE THREAD

**Issue by unkownY** [shd101wyy/markdown-preview-enhanced#771]
实际的路径
>ed2k://|file|%E6%98%9F%E9%99%85%E8%BF%B7%E8%88%AA%EF%BC%9A%E5%8F%91%E7%8E%B0%E5%8F%B7.Star.Trek.Discovery.S01E01.%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95.WEBrip.720P-%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86V2.mp4|515400048|d31fa664041182f7d8fb3a5f5143a695|h=rzdzywjcih2gizjpzdnly6au64rnlgj2|/

显示在md中的路径
>file:///c:\Users\YangChenjie\Desktop\美剧进度\ed2k:\|file|%E6%98%9F%E9%99%85%E8%BF%B7%E8%88%AA%EF%BC%9A%E5%8F%91%E7%8E%B0%E5%8F%B7.Star.Trek.Discovery.S01E01.%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95.WEBrip.720P-%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86V2.mp4|515400048|d31fa664041182f7d8fb3a5f5143a695|h=rzdzywjcih2gizjpzdnly6au64rnlgj2|

md文件所在路径
>file:///c:\Users\YangChenjie\Desktop\美剧进度\

自动在链接前添加了文件路径,但是为什么?

**Comment by shd101wyy** [comment]
应该是 bug，把你的文件发给我看看？谢谢

**Comment by unkownY** [comment]
javascript {cmd="node"}
```
var http = require("http");
var fs = require("fs");

var jsdom = require("jsdom");
const { JSDOM } = jsdom;

let req;
req = http.request("http://www.msj1.com/archives/5750.html", res => {
  let html = "";
  res.on("data", data => {
    html += data;
  })
  res.on("end", () => {
    const dom = new JSDOM(html);
    let data = dom.window.document.getElementById("download").nextElementSibling.outerHTML;
    console.log("<b>神盾局特工 第五季</b>");
    console.log(data);
    fs.writeFileSync("table5.txt",data)
  })
  res.on("error", () => {
    console.log("error");
  })
});
req.end();
```

**Comment by shd101wyy** [comment]
@unkownY 插件设置里面有一项叫做 `protocolsWhitelist`，你把 `ed2k` 也加进去这个白名单里就好了。

**Comment by unkownY** [comment]
thanks. 
😄
