### ISSUE TITLE
prince 导出PDF为空

### ISSUE THREAD

**Issue by Rogerspy** [shd101wyy/markdown-preview-enhanced#776]
我用prince导出PDF为空，什么都没有。用浏览器的方法也是一样的，预览的时候没问题，只是导出会有问题。请问这是什么情况？

**Comment by Rogerspy** [comment]
我没说清楚，不是没有pdf文件，是pdf文件是空白的，没有内容。

**Comment by shd101wyy** [comment]
把你的文件发我看看？

**Comment by Rogerspy** [comment]
呃呃呃， 我二了，.md文件没有保存，直接在预览页执行的prince。现在可以了。




在 2018-02-01 00:21:15，"Yiyi Wang" <notifications@github.com> 写道：


把你的文件发我看看？

**Comment by Rogerspy** [comment]
Hi，我经过这两天的试用，发现了几个问题。


1. 表格扩展，按照文档用"^"，">"和“空”并不能合并单元格
2. 图片不能上传，无论是拖拽还是直接![]()这种形式，还是image-helper都不能
3. 缩略那个功能的显示效果是什么样的？我这里测试的时候按照文档的写法就是我截图的样子，星号后面的内容无法显示。





在 2018-02-01 00:21:15，"Yiyi Wang" <notifications@github.com> 写道：


把你的文件发我看看？

**Comment by shd101wyy** [comment]
@Rogerspy 

1. 在设置里面有一个叫做 `enableExtendedTableSyntax` 类似的选项你得开启才行。
2. 我试了下没问题，你 `![]` 写法路径是什么？
3. 缩略图是啥，我咋不知道？你来张截图。

你用的是 Atom 还是 VSCode?

**Comment by Rogerspy** [comment]
表格那个好了，谢谢。

我用的是Atom，图片路径写的是本地文件夹的路径，比如我在桌面上有一张图片test.jpg，那我在atom里写的就是
![](/home/csong/Desktop/test.jpg)

不是缩略图，就是你在文档里的例子：

*[HTML]: Hyper Text Markup Language
*[W3C]: World Wide Web Consortium
The HTML specification
is maintained by the W3C.

在我这里上面带星号的两行预览页没有显示，只有下面的两行。嗯，我前面发了截图给你。

在 2018-02-02 14:22:42，"Yiyi Wang" <notifications@github.com> 写道：


@Rogerspy

在设置里面有一个叫做 enableExtendedTableSyntax 类似的选项你得开启才行。
我试了下没问题，你 ![] 写法路径是什么？
缩略图是啥，我咋不知道？你来张截图。

你用的是 Atom 还是 VSCode?

**Comment by shd101wyy** [comment]
关于第一个路径的问题，markdown 不支持相对于系统的绝对路径，你这种写法是错误的。`/` 开头的路径指的是相对于项目根目录的路径。

第二个你说的缩略图那个，本来前两行就不会显示，那是用来定义 url 的。
