### ISSUE TITLE
Pandoc + KaTeX + Tables causes narrow tables

### ISSUE THREAD

**Issue by gembutterfly** [shd101wyy/markdown-preview-enhanced#778]
Hi,
when I put Formulas in Tables, the cell width seems to be calculated incorrectly.

![kkk](https://user-images.githubusercontent.com/6540152/35743192-18a91194-083d-11e8-9ec7-b4f50053c016.png)

**Comment by gembutterfly** [comment]
PS: Without Pandoc, it's fine - but then exported HTML displays formulas incorrectly.

**Comment by gembutterfly** [comment]
PPS: Sorry, seems to be a pandoc "feature": [https://github.com/jgm/pandoc/issues/2574](url)

**Comment by shd101wyy** [comment]
no worry. feel free to post issues.
