### ISSUE TITLE
mermaid_config.js from being reset to the initial state

### ISSUE THREAD

**Issue by cha2maru** [shd101wyy/markdown-preview-enhanced#78]
When you operate in the following way , mermaid_config.js from being reset to the initial state .

1. Edit a mermaid_config.js.
1. After saving the mermaid_config.js, to close .
1. Restart the Atom.
1. Open a Markdown file from the file menu .
  - (Mermaid_config.js at this timing is reset )
1. When you open the mermaid_config.js it has been reset .

**Comment by shd101wyy** [comment]
Yea the reset is a bug. I will fix it in the next version.

However, if the mermaid_config.js is reset, then it means it failed to `require` that file. Therefore, there are errors in your `mermaid_config.js` file.

Thanks

**Comment by shd101wyy** [comment]
I was missing lines in `md.coffee`
![Screen Shot 2016-07-15 at 2.44.36 PM](http://ooo.0o0.ooo/2016/07/15/578887d9c41ac.png)

**Comment by shd101wyy** [comment]
Hi @cha2maru , it should be fixed now. 
Thanks

**Comment by cha2maru** [comment]
Thanks.
The new version seems to solve the problem.
