### ISSUE TITLE
Subscript does not work in equation

### ISSUE THREAD

**Issue by nocibambi** [shd101wyy/markdown-preview-enhanced#784]
I try to use '~' for subscription in a `math` block , but it does not work

Ouside the math block this works:

> P\~i\~

With the math block it does not (but seemingly everything else).

> $ P\~i\~ $

**Comment by kachkaev** [comment]
Hi @nocibambi,

Can you try `$ P_i $`?

https://www.sharelatex.com/learn/Subscripts_and_superscripts

**Comment by nocibambi** [comment]
Hi @kachkaev, yes that worked, many thanks!

I was relying on [KaTeX documentation](https://khan.github.io/KaTeX/function-support.html). Thanks for the other link, nice collection!
