### ISSUE TITLE
flow cannot use 流程图无法使用

### ISSUE THREAD

**Issue by jneless** [shd101wyy/markdown-preview-enhanced#786]
![2018-02-12 12 44 17](https://user-images.githubusercontent.com/21362547/36083868-96a16724-0ff2-11e8-8275-d7908cd4da89.png)

无法识别这个flow,我不知道是需要额外的配置吗？还是就我有错？

It can not recognize the key of "flow".
Should I need to configure some else?

**Comment by jneless** [comment]
sorry about that .
It is working ,cause I miss some notification ......

**Comment by EricZQWon** [comment]
请问需要什么配置啊，出现了同样的问题

**Comment by jneless** [comment]
他这个本身没问题、你复制整个代码进去，不要一点一点复制。

渲染的时候是整体渲染，如果你没有把全部的写完，暂时写完的这些渲染不了，也就暂时表现为报错。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: EricZQWon <notifications@github.com>
发送时间: 2018年6月19日 23:58
收件人: shd101wyy/markdown-preview-enhanced <markdown-preview-enhanced@noreply.github.com>
抄送: jneless <pm.ccc@hotmail.com>, State change <state_change@noreply.github.com>
主题: 回复：[shd101wyy/markdown-preview-enhanced] flow cannot use 流程图无法使用 (#786)


请问需要什么配置啊，出现了同样的问题
