### ISSUE TITLE
Exporting outside of Atom?

### ISSUE THREAD

**Issue by dzackgarza** [shd101wyy/markdown-preview-enhanced#788]
Since this plugin adds a number of extra features to markdown (things like @input or runnable code blocks, for example), I was wondering how portable my documents will be. Is there any way to convert them to PDF or HTML without going through Atom's interface? 

Is there a node command or something I can pass the markdown file to on the command line perhaps?

Edit: It looks like there is the [mume](https://www.npmjs.com/package/@shd101wyy/mume) package, what kind of setup would be needed to duplicate the export happening inside of Atom?

**Comment by kachkaev** [comment]
You are right @dzackgarza: [mume](https://github.com/shd101wyy/mume) is the thing to look at. Your node.js script to convert markdown into an html may look like this:

```js
const mume = require("@shd101wyy/mume");

(async () => {
  console.log("initializing...");
  await mume.init();

  console.log("starting engine...");
  const engine = new mume.MarkdownEngine({
    filePath: "/path/to/my/markdown.md",
    config: {
      previewTheme: "github-light.css",
      codeBlockTheme: "default.css",
      printBackground: true
    }
  });
  console.log("exporting to html...");
  await engine.htmlExport({ offline: false, runAllCodeChunks: true });

  console.log("done.");
})();
```

**Comment by kachkaev** [comment]
Are you happy with the solution @dzackgarza? If so, feel free to close this issue.

**Comment by dzackgarza** [comment]
I think so! I haven't had a chance to try it, but it sounds like this should work just fine. I'll close for now, and reopen if I run into any trouble down the line.

**Comment by dzackgarza** [comment]
Follow up - I tried this, and after messing with the config object a bit, this seems to work! The only issue I'm running into now is that certain code cells don't seem to be running - in my case, embedded standalone Latex documents that seem to work alright within the Atom markdown preview pane. Do you guys have any idea what might cause that?
