### ISSUE TITLE
HTML comments are ignored

### ISSUE THREAD

**Issue by kachkaev** [shd101wyy/markdown-preview-enhanced#79]
Looks like the contents of HTML comments end up in the output

```md
I should see this

<!--
I should not see this
-->

I should see this
```

![screen shot 2016-07-17 at 14 07 13](https://cloud.githubusercontent.com/assets/608862/16900810/cfa91200-4c27-11e6-820b-153a104681b4.png)

The bug disappears when the comment is not closed:

![screen shot 2016-07-17 at 14 07 25](https://cloud.githubusercontent.com/assets/608862/16900811/d28ccb38-4c27-11e6-845e-cf0cbff48f2e.png)

**Comment by shd101wyy** [comment]
Hi @kachkaev , thanks for your reply.

I will fix this problem as soon as possible. 

Sorry for the trouble.

**Comment by shd101wyy** [comment]
Hi @kachkaev , 

This issue might be fixed now.  Can you help me check? Thanks ;)  

I also added a new feature **Presentation Writer** for this package. It is still under development, but you can have a look if you are interested. Link is [here](https://cdn.rawgit.com/shd101wyy/markdown-preview-enhanced/master/docs/presentation-intro.html)

Thanks
