### ISSUE TITLE
Support for Brackets?

### ISSUE THREAD

**Issue by Archetipo95** [shd101wyy/markdown-preview-enhanced#803]
Guys are you going to add support for Brackets IDE in the future ?

**Comment by baoang** [comment]
It could be great if MPE offers sublime text's package.

**Comment by kachkaev** [comment]
`markdown-preview-enhanced` and [`vscode-markdown-preview-enhanced`](https://github.com/shd101wyy/vscode-markdown-preview-enhanced) are just slim wrappers around [`mume`](https://github.com/shd101wyy/mume/), which contains the main functionality. This package can be wrapped in more ways, which opens lots of opportunities.

If you are interested in seeing Markdown Preview Enhanced in Brackets or Sublime, feel free to experiment with the extensions for these editors 😉
