### ISSUE TITLE
add graphviz support

### ISSUE THREAD

**Issue by maplewizard** [shd101wyy/markdown-preview-enhanced#81]
I want to use dot language to make graph in the markdown. Is it possible, I have seen some atom plugin can do this, but it is not with markdown, I think it can be conbined together.

**Comment by shd101wyy** [comment]
Hi,
it is supported by default. You just need to download and install graphviz by yourself.

If you are using Mac, run 'brew install graphviz'

Thanks

**Comment by maplewizard** [comment]
The document said that I should use puml mode. but I found it's not graphviz. for example, I use `a->b`, I got 
![image](https://cloud.githubusercontent.com/assets/1419566/16907460/8b6aa9d0-4cf6-11e6-81c9-8702e33614c0.png)
I want only a circle a point to circle b.

**Comment by shd101wyy** [comment]
Can you give me a screenshot of the result that you want? Thanks

**Comment by maplewizard** [comment]
please see this plugin :https://github.com/jumpkick/graphviz-preview
is it possible to do like that?

**Comment by shd101wyy** [comment]
I see.

I will be absent traveling abroad for a week, so I will check it out after I come back home.

Thanks

**Comment by maplewizard** [comment]
@shd101wyy Thanks. Please contact me if any question. have a nice trip.

**Comment by shd101wyy** [comment]
@maplewizard Done.

![Screen Shot 2016-07-25 at 5.10.24 PM](http://ooo.0o0.ooo/2016/07/25/5795d78e5f264.png)

you can write dot language inside `viz` code block

**Comment by shd101wyy** [comment]
I will close this issue now as `viz` is supported already.
