### ISSUE TITLE
diagrams are not rendered any more

### ISSUE THREAD

**Issue by gmd7** [shd101wyy/markdown-preview-enhanced#817]
Tested with plantuml, dot, ...
All diagrams are displayed as text blocks.

**Comment by kachkaev** [comment]
@gmd7 could you please share a file that does not work? Some details on your environment would be useful too!

**Comment by gmd7** [comment]
There are two examples in the [attachment](https://github.com/shd101wyy/markdown-preview-enhanced/files/1813718/diagram.zip)
 that worked before the last update.


Deactivating 

* use pandoc parser

in settings showed the rendered diagrams. 

Other settings:
 
* Pandoc Options: Commandline Arguments
--number-sections, --toc

* Pandoc Options: Markdown Flavor
markdown-raw_tex+tex_math_single_backslash+pandoc_title_block+yaml_metadata_block

```
> pandoc --version
pandoc 2.0.6
Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.5
```

OS: Debian Stretch

**Comment by gmd7** [comment]
Same problem for codeblocks:

        ```html
        <strong>
        fff
        </strong>
        ```

is not correctly rendered with pandoc.

**Comment by shd101wyy** [comment]
@gmd7 Yes the diagrams suddenly stopped working on my Windows as well. 
What I did to fix this issue was to uninstall atom => remove `~/.atom` folder =>  reinstall atom and mpe. Then everything works. But this is not a very good solution. I will try to figure out why diagrams stop working. Thank you.

**Comment by shd101wyy** [comment]
The codeblock one that you mentioned is a bug. Will be fixed in next release. Thank you.
