### ISSUE TITLE
cannot preview tiff format image

### ISSUE THREAD

**Issue by dvpfrcrb** [shd101wyy/markdown-preview-enhanced#823]
TIFF images could not previewed in Atom editor. Will tiff image preview be supported in future release?

**Comment by shd101wyy** [comment]
Seems that tiff image is not supported by chrome according to [this](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support), so there is no way to display tiff image right now.

**Comment by kachkaev** [comment]
Will close this for now given that fixing is blocked by a problem upstream.
