### ISSUE TITLE
今天更新到最新版本后，出现点击TOC跳转走样问题。

### ISSUE THREAD

**Issue by iDragonfly2050** [shd101wyy/markdown-preview-enhanced#824]

**Comment by iDragonfly2050** [comment]
![image](https://user-images.githubusercontent.com/16486215/37580489-ec543f50-2b7e-11e8-98f4-3417f6ac779e.png)

**Comment by shd101wyy** [comment]
嗯嗯嗯嗯，可否把你的 markdown 文件发我一份，谢谢。

**Comment by lfire** [comment]
我也遇到同样的问题，
![image](https://user-images.githubusercontent.com/2528719/37693484-df664914-2cfa-11e8-9bea-0941e2db18c1.png)

**Comment by lfire** [comment]
这个是 markdown 源文件
[jetbrains-ide-active-server.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1831986/jetbrains-ide-active-server.zip)

**Comment by iDragonfly2050** [comment]
找到了复现方法：如果标题是中文的话，会出现问题，但如果标题是英文的话，表现正常。 @shd101wyy

**Comment by iDragonfly2050** [comment]
[Markdown源文件.zip](https://github.com/shd101wyy/markdown-preview-enhanced/files/1832133/Markdown.zip)

**Comment by shd101wyy** [comment]
吼，我下周有时间了会去修下，多谢

**Comment by pollyduan** [comment]
同样遇到，怎么回退版本？

**Comment by shd101wyy** [comment]
This [pull request](https://github.com/shd101wyy/mume/pull/54) should fix the problem.  
But we will probably release a new version next week.  

wo de ubuntu mei zhong wen shu ru fa yong bu liao... jiong

**Comment by shd101wyy** [comment]
@iDragonfly2050 @lfire  @pollyduan 
久等了，应该修好了。
