### ISSUE TITLE
Text is not selectable

### ISSUE THREAD

**Issue by lieanu** [shd101wyy/markdown-preview-enhanced#825]
After Export to HTML，the text or code block in HTML pages is unselectable.

**Comment by kachkaev** [comment]
@lieanu could you please share an example HTML file that does not work for you? Have you tried selecting text in another browser?

**Comment by lieanu** [comment]
MarkDown:
```markdown
---
presentation:
  width: 1600
  height: 900
  slideNumber: 'c/t'
  showSlideNumber: "all"
  center: true
  enableSpeakerNotes: true
  theme: none.css
---

<!-- slide -->

# Just For Testing

### Show the TEXT not selectable

<!-- slide -->

## Testing Code Block
#### A simple Python example

\```python
import os,sys

print "Hello World!"
\```

<!-- slide class="middle"-->

# Thanks!

```

Generated HTML file:
<https://raw.githubusercontent.com/lieanu/files/master/test_for_MPE/test.html>

**Comment by kachkaev** [comment]
After inspecting your html, I see that the problem comes from here:

```
.markdown-preview.markdown-preview .reveal .slides {
  text-align: left;
  float: left;
  z-index: -10;   // <---------------------------------------------------------
  height: 100%;
  width: 100%;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 0px;
  margin: 0 auto;
  line-height: 1.375;
}
```

Removing `z-index` works as a fix. Is this your custom CSS?

**Comment by lieanu** [comment]
yeah, it's a custom CSS，thanks a lot.👍

**Comment by kachkaev** [comment]
You can then simply remove `z-index: -10;` from it and all will work. I'll close this issue, but feel free to continue the discussion if you're still struggling with it.
