### ISSUE TITLE
ability to swap back to default css

### ISSUE THREAD

**Issue by djh1997** [shd101wyy/markdown-preview-enhanced#826]
i use solarised dark theme and this gets added to the preview when i export it would be nice to have as an option

**Comment by shd101wyy** [comment]
Hi @djh1997 , 

https://shd101wyy.github.io/markdown-preview-enhanced/#/html  
You could set `print_background: true` in front matter.

Thank you

**Comment by djh1997** [comment]
edit->config... 

 "markdown-preview-enhanced":
    enableExtendedTableSyntax: true
    previewTheme: "solarized-dark.css"
    print_background: true

adding into config didnt work for me now the .html wont even open in firefox it just crashed

**Comment by djh1997** [comment]
not sure why but it seems to have worked now thanks for the help
