### ISSUE TITLE
Order list nesting limit

### ISSUE THREAD

**Issue by dtgoitia** [shd101wyy/markdown-preview-enhanced#828]
Hi @shd101wyy ,

Is there any possibility to support more nested order list levels? At the moment I can only achieve 2 levels:
```markdown
1. Item 1, level 1.
  1.1. Item 11, level 2.
  1.2. Item 12, level 2.
2. Item 2, level 1.
```
I am looking to achieve deeper levels:
```markdown
1. Item 1, level 1.
  1.1. Item 11, level 2.
    1.1.1. Item 111, level 3.
      1.1.1.1. Item 1111, level 4.
        1.1.1.1.1. Item 11111, level 5.
          1.1.1.1.1.1. Item 111111, level 6.
    1.1.2. Item 112, level 3.
  1.2. Item 12, level 2.
2. Item 2, level 1.
```
I know GitHub doesn't support it, but I think it's very useful. It kind of feels natural to me, as the unordered lists do support this "deep" nesting.

Let me know your thoughts please :)

**Comment by shd101wyy** [comment]
To be honest I would suggest you write it using unordered list like this:

```
* 1. Item 1, level 1.
  * 1.1. Item 11, level 2.
    * 1.1.1. Item 111, level 3.
      * 1.1.1.1. Item 1111, level 4.
        * 1.1.1.1.1. Item 11111, level 5.
          * 1.1.1.1.1.1. Item 111111, level 6.
    * 1.1.2. Item 112, level 3.
  * 1.2. Item 12, level 2.
* 2. Item 2, level 1.
```

Thank you

**Comment by dtgoitia** [comment]
XD looks like something tricky to implement

**Comment by kachkaev** [comment]
@dtgoitia I guess you can achieve the numbering you are looking for with CSS – see https://stackoverflow.com/questions/10405945/html-ordered-list-1-1-1-2-nested-counters-and-scope-not-working for example.
