### ISSUE TITLE
Preview does not work with pandoc 2.1.1

### ISSUE THREAD

**Issue by gunwald** [shd101wyy/markdown-preview-enhanced#829]
This great extension does not work with latest Pandoc version:
```
pandoc --version
pandoc 2.1.1
Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.6
```
The preview isn't rendered and only the following message is shown:

`[WARNING] Deprecated: --latexmathml, --asciimathml, -m`

By the way, this warning is also shown by the competitor `markdown-preview-plus`, but it renders the preview never the less. Maybe this helps to track down the cause of this issue.

**Comment by gunwald** [comment]
I just found out that the problem was connected with the `-smart` option, I had included in the pandoc option field. Removing this, makes the Warning disappear and the rendering works again. I guess in Pandoc 2.1.1 changes where made to this option...

**Comment by shd101wyy** [comment]
closing this issue now ;)
