### ISSUE TITLE
How to bind preivew to the "Open Preview to the Side" button? 如何绑定预览功能到“打开侧边预览”按钮？

### ISSUE THREAD

**Issue by painty** [shd101wyy/markdown-preview-enhanced#833]
![qq 20180327101930](https://user-images.githubusercontent.com/5387771/37944436-27985814-31ae-11e8-8a5b-92a5fab1dbc8.png)

**Comment by shd101wyy** [comment]
@painty 我也想知道这个该怎么做。你要是知道了请告诉我。谢谢。😂

**Comment by shd101wyy** [comment]
好了，我添加了一个按钮，但是我无法删除默认的按钮，所以现在有两个。
