### ISSUE TITLE
Default Image Behavior

### ISSUE THREAD

**Issue by caseywatts** [shd101wyy/markdown-preview-enhanced#836]
I suggest we change the default to be "copy to folder". 

When I installed this, I was very surprised to have my images uploaded to a provider. It made me want to disable this package because it makes me a bit worried about my work data leaking.

The defaults in this other package are the same as our setting "copy to folder". This behavior in these three are all the behavior I expected to be the default:
- https://github.com/tlnagy/atom-markdown-image-assistant
- https://github.com/nmecad/markdown-img-paste
- https://github.com/cocoakekeyu/markdown-img-paste

What do you think? :)

**Comment by caseywatts** [comment]
Thanks also to @dmgt for helping me look through these related plugins :)

**Comment by shd101wyy** [comment]
@caseywatts Good suggestion. I will change it in the next version. Thank you!

**Comment by caseywatts** [comment]
awesome! Thank you for being positive & responsive :D

**Comment by shd101wyy** [comment]
@caseywatts Changed now. Thank you.
