### ISSUE TITLE
Could not open preview window in vs code

### ISSUE THREAD

**Issue by ngfat** [shd101wyy/markdown-preview-enhanced#842]
Dear developer,

I just found with the recent update that I could no longer open the preview window. When I right click the document and select "Markdown Preview Enhanced: open preview" nothing would be shown and when I type in "Markdown Preview Enhanced: open preview" in the command palette, an error message that said "command 'markdown-preview-enhanced.openPreview' not found". Is there anything I could do? Thank you for your wonderful package and help!

**Comment by shd101wyy** [comment]
Hi @ngfat , have you tried reinstalling the package? Thank you.

**Comment by ngfat** [comment]
Hi @shd101wyy , it is working now. Thank you so much for your reply!
