### ISSUE TITLE
Disable all HTML script tags when exporting to HTML

### ISSUE THREAD

**Issue by RickTorresJr** [shd101wyy/markdown-preview-enhanced#843]
Provide an option to disable all HTML script tags when exporting to HTML for security. This would keep exported HTML static. Even when `Enable Script Execution` is disabled the following is still rendered at the bottom of the HTML (both offline and cdn):

```html
<script>
(function bindTaskListEvent() {
  var taskListItemCheckboxes = document.body.getElementsByClassName('task-list-item-checkbox')
  for (var i = 0; i < taskListItemCheckboxes.length; i++) {
    var checkbox = taskListItemCheckboxes[i]
    var li = checkbox.parentElement
    if (li.tagName !== 'LI') li = li.parentElement
    if (li.tagName === 'LI') {
      li.classList.add('task-list-item')
    }
  }
}())    
</script>
```

**Comment by shd101wyy** [comment]
Hi,

Yes we are working on this now in pull request 837.
https://github.com/shd101wyy/markdown-preview-enhanced/pull/837
It will be done in next version.

Thank you
