### ISSUE TITLE
pandoc & code chunks

### ISSUE THREAD

**Issue by gmd7** [shd101wyy/markdown-preview-enhanced#846]
```latex {cmd=true}
    \documentclass{standalone}
    \begin{document}
      Hello world!
    \end{document}
    ```

    ```python {cmd=true}
    print "test"
    ```
does not work with pandoc but with markdown-it.

**Comment by shd101wyy** [comment]
Hi there,

This pull request will fix the issue:
https://github.com/shd101wyy/mume/pull/59

We will publish a new version this week.

Thank you

**Comment by chrisjsewell** [comment]
The problem with your solution is that it only works if using pandoc within MPE (i.e. pre-processing the markdown file so `python {cmd=true}` -> ` {.python cmd=true}`). Surely it would be better to just allow MPE to interpret the conventional pandoc syntax?

    ``` {.python cmd=true}
     print("test")
    ```
(apart from this, its a great package thanks :))
