### ISSUE TITLE
Both mathtype and diagram not working

### ISSUE THREAD

**Issue by parthi2929** [shd101wyy/markdown-preview-enhanced#849]
Hi

I tried to use just default setting.  

Both Katex and graphviz seem to be not working. I tried reinstalling but in vain. Can you please help asap? 

![2018-04-12_22h04_28](https://user-images.githubusercontent.com/11896263/38691169-aba29d62-3e9d-11e8-9a92-d085c3ee268c.png)

**Comment by parthi2929** [comment]
I tried MathJax also but same result. Its not working.

**Comment by shd101wyy** [comment]
Hi @parthi2929 ,

This is because the preview is from the default `Markdown Preview` extension but not this extension. It is supposed to have tab title `MPE Preview` on vscode.   
I would assume you clicked that preview icon to open preview, which is not supported yet.  
I would suggest you to press `ctrl+k v` or run `Markdown Preview Enhanced: Open preview` command to open the preview. Or you can right click at the editor, then choose `Markdown Preview Enhanced: Open Preview`.

Thank you.

**Comment by parthi2929** [comment]
Thank you for such fast response :)
ctrl+k  v did nothing in VS. I tried Markdown Preview Enhanced: Open Preview, it is now showing latex. However, Graphviz is still showing error. 
![2018-04-12_22h20_22](https://user-images.githubusercontent.com/11896263/38691859-b2bc28b4-3e9f-11e8-97dd-29944b9352ad.png)
Further, how do I get rid of Markdown Preview which comes up with ctrl+shift+v. I seem to not have any other markdown preview tool installed except this. 
![2018-04-12_22h21_18](https://user-images.githubusercontent.com/11896263/38691910-d5d64d3e-3e9f-11e8-8837-919ec08b2553.png)

**Comment by shd101wyy** [comment]
It should be `digraph` not `diagraph`?

**Comment by shd101wyy** [comment]
btw, if you are using mac, then it should be `cmd+k v`

**Comment by parthi2929** [comment]
Great. That fixed it. Sorry for rookie question. New to these. 

I could see the keyboard shortcut still its not working to open preview.
![2018-04-12_22h25_00](https://user-images.githubusercontent.com/11896263/38692175-9f5b6180-3ea0-11e8-8766-828e93285485.png)

**Comment by parthi2929** [comment]
I am using win 10

**Comment by parthi2929** [comment]
Is it probably causing conflict with internal markdown support by VS code?

![2018-04-13_10h34_35](https://user-images.githubusercontent.com/11896263/38717739-66c64f04-3f06-11e8-9788-2233dc8f1c1b.png)

**Comment by parthi2929** [comment]
For now, I changed the former's keybinding, and now this works :)
