### ISSUE TITLE
auto execute flag on "cmd" macros

### ISSUE THREAD

**Issue by rbuckland** [shd101wyy/markdown-preview-enhanced#854]
Currently command macros need to be executed, via the "execute" icon over the code block, or `[shift][enter]`

The TOC  generator "recreates" the TOC upon save

It would be good to add a flag to the execution macro, so that it auto executes upon saving and exporting.
(tip: I find puppeteer the best exporter for PDF and HTML).

This would open up the ability to auto create dir indexes like #442 and automatic executing JS scripts, e.g. #684 

For example, add an "autoexec" attribute

```
```javascript {cmd="node" output="markdown" hide autoexec}
function atom_hello_world(){
   return "**Hello from Javascript**"
}
console.log(atom_hello_world());
```

**Comment by rbuckland** [comment]
I am so sorry - I missed that in the documentation. 
Excellent - thanks.

**Comment by shd101wyy** [comment]
No problem ;)
