### ISSUE TITLE
关于必须点击md，右侧预览才会跳转的问题

### ISSUE THREAD

**Issue by BlackHole1** [shd101wyy/markdown-preview-enhanced#870]
当我在左侧md文件滚轮时，右侧的预览不能实时的跳转到和左侧md一样的位置，必须点击md文件的某一行，右侧的预览才会跳转。很是不方便。

**Comment by shd101wyy** [comment]
@BlackHole1 我猜你指的是 vscode，因为 vscode 没有提供相关的滚动 API，所以没法像 atom 版一样滚动同步。

**Comment by BlackHole1** [comment]
明白了。确实是vscode。很抱歉，没有在发issues时，把问题情况说清。

十分感谢您的解答。

**Comment by shd101wyy** [comment]
@BlackHole1 没事儿。
