### ISSUE TITLE
ParseError: KaTeX parse error

### ISSUE THREAD

**Issue by hyh19962008** [shd101wyy/markdown-preview-enhanced#878]
![2018-05-15 08-17-36](https://user-images.githubusercontent.com/23244369/40029766-d01c9e94-57d5-11e8-8302-81282e528d30.png)
- 在VSCODE中出现上面错误，ver 1.23.1

**Comment by shd101wyy** [comment]
哦你可以在插件设置中把 mathRenderingOption 设置为 None。现在是把 $$ 中的当成数学式了。

或者你可以写成 \$

**Comment by eromoe** [comment]
@shd101wyy 怎么配置插件啊?

说明看不懂啊
1. 
![image](https://user-images.githubusercontent.com/3938751/90355944-79ac6b80-e080-11ea-8481-b510c5e63301.png)
2. 
![image](https://user-images.githubusercontent.com/3938751/90355961-8b8e0e80-e080-11ea-8ee8-1ea7aa1a0831.png)
3.
![image](https://user-images.githubusercontent.com/3938751/90355992-a1033880-e080-11ea-9994-4d534a9a8aec.png)


说明只到第三步，但是第三步直接到了配置文件，也没说怎么配置，各项参数的意思
