### ISSUE TITLE
中文 TOC 無法保存

### ISSUE THREAD

**Issue by sappy5678** [shd101wyy/markdown-preview-enhanced#891]
關檔前
![](https://i.imgur.com/eHiZCMY.png)

一旦關掉檔案
![](https://i.imgur.com/ySaBIfI.png)

**Comment by shd101wyy** [comment]
我猜是插件冲突，不太清楚，因为我没有 githubCompatibility 这个设置。。

**Comment by sappy5678** [comment]
抱歉沒有看清楚，那個設定是其他插件的
感謝大大做出了如此好用的插件 ^^
