### ISSUE TITLE
[Feature Request] Rmarkdown document preview capability

### ISSUE THREAD

**Issue by sdrakulich** [shd101wyy/markdown-preview-enhanced#893]
Being able to preview Rmarkdown documents would be amazing. I'm too much of a novice to do even that, so I apologize.

This feature would really make my life so much better. Thanks so much!

**Comment by kachkaev** [comment]
Hi @sdrakulich, I'm afraid this feature is way too massive so is probably out of scope of this project. I'd suggest you to search for a Rmarkdown preview extension and share your findings here if you wish.
