### ISSUE TITLE
怎么取消自动超链接？

### ISSUE THREAD

**Issue by Espylapiza** [shd101wyy/markdown-preview-enhanced#897]
随便输入test.in自动转成超链接，怎么取消呢？

**Comment by shd101wyy** [comment]
这周末我看一下哈。可否贴个 markdown 文档在下面。多谢。

**Comment by Espylapiza** [comment]
test.in
一行就行了

**Comment by Espylapiza** [comment]
请问可以帮忙看下吗

**Comment by shd101wyy** [comment]
这应该是 markdown-it 这个包启动了 `linkify` 的缘故，我以后应该会添加一个设置允许你 disable 这个选项。你现在可以先这么写 
````
`test.int`
<span>test.in</span>
````
或者使用 pandoc，把 `usePandocParser` 这个选项打开
或者你可以给 [markdown-it](https://github.com/markdown-it/markdown-it/issues) 提个 issue。

**Comment by Espylapiza** [comment]
谢谢！
