### ISSUE TITLE
New Features Request

### ISSUE THREAD

**Issue by shd101wyy** [shd101wyy/markdown-preview-enhanced#9]
**If you are requesting new feature for this packages, please comment below with the description of the new feature that you want.**

**Comment by mistguy** [comment]
Is it possible to at table of contents support with `[TOC]`?

**Comment by shd101wyy** [comment]
@mistguy I will try to implement it when I have time ;) Thx

**Comment by nicofrand** [comment]
I am still wondering how to reduce the font size (for everything), maybe adding the possibility to modify it would be nice ?

I tried to modify the CSS preview but that did not work. I am using the Github.com style (but not the syntax theme because I prefer a black background for my code snippets).

**Comment by shd101wyy** [comment]
Hello @nicofrand , if you are trying to reduce the font size, you can use `Customize CSS` command then modify the `custom.less` file

![snip20160408_2](https://cloud.githubusercontent.com/assets/1908863/14379236/b2430c58-fd3e-11e5-8eae-35c2239bc686.png)

Then add
`
font-size: 0.8em !important; // any number you want
`

under `.markdown-katex-preview.custom` section. 

After saving the `custom.less` file you need to restart the atom editor to see the change.

However, there is a bug right now that the font size doesn't change in the generated pdf file and html file.
I will fix this bug in the future.

**Comment by nicofrand** [comment]
Ah, that's it, I did not restart atom… Thanks !

Does the bug concerns the font size only or everything ? (I have a different output in PDF than in the preview after modifying some margins).

**Comment by nicofrand** [comment]
@mistguy I am using markdown-toc package and this works fine with this package.

**Comment by mistguy** [comment]
@nicofrand Well, I am expecting something like hyberlinks. Markdown-toc does not handle that. I think this functionality is only possible to be implemented by previewer.

**Comment by nicofrand** [comment]
My bad, I did not check the HTML result, markdown-toc does generate a TOC with links pointing to the anchors, but the h1/h2/hx do not have a corresponding id attribute, so the links are indeed useless.

**Comment by shd101wyy** [comment]
@mistguy , Is this what you want? 

![toc](https://cloud.githubusercontent.com/assets/1908863/14397944/116927be-fda6-11e5-9d8c-e11c5f9e64bd.gif)

**Comment by shd101wyy** [comment]
@nicofrand I have fixed the custom css bug. 

Now you don't have to restart the atom to see the change.

**Comment by mistguy** [comment]
@shd101wyy yeah, but my atom doesn't work that way. Is that a development snapshot?

**Comment by nicofrand** [comment]
Both the custom CSS and the TOC work fine in the preview with the update, thanks. However, I wish that would work when I save as PDF too.

**Comment by shd101wyy** [comment]
hi @nicofrand , if you are talking about that links of TOC don't work in pdf. I think that is a bug from the electron. 

https://github.com/electron/electron/issues/4313

As the current atom editor is based on Chrome/45, the only way to bypass this issue is to open the html in browser and then print as pdf from that browser instead of printing directly from atom editor.

**Comment by nicofrand** [comment]
OK, thanks for the heads-up !

Another cool feature would be to open automatically the preview pane when I open a markdown file.
There is another atom package ([https://atom.io/packages/markdown-preview-opener]()) that does that for markdown-preview, and this is really handy.

**Comment by mistguy** [comment]
Is it possible that a `[TOC]` would generate table of contents automatically and update them automatically, like in http://classeur.io/.

**Comment by shd101wyy** [comment]
@mistguy the 0.5.2 version supports toc update automatically.
I rewrite toc by myself instead of using markdown-toc library as before.
So if the toc behaves buggy, please tell me.

Thanks ;)

**Comment by shd101wyy** [comment]
@nicofrand the preview will be opened automatically when you open a markdown file now.

You can disable the auto-open feature by unchecking it from the settings panel!

![screen shot 2016-04-17 at 5 14 28 am](https://cloud.githubusercontent.com/assets/1908863/14586365/5d646e4c-045b-11e6-8bdf-cf2f39985e73.png)

Cheers

**Comment by garipan** [comment]
There is some features I expecting,thanks for reading.

please makes all the css file of interface editable.only edit the styles.less file is not enough.for example,I want to change style of the <hr> tag to dashed ,but when I write down css code in styles.less , there disappears two lines.

**Comment by shd101wyy** [comment]
Hello @garipan , thanks for you reply.

If you are trying to change the style of `<hr`> to dashed, you can add following lines 
```less
  hr {
    background: transparent;
    border-bottom: 4px dotted #454545;
  }
```
to `.markdown-katex-preview-custom` section 

![screen shot 2016-04-18 at 1 30 15 pm](https://cloud.githubusercontent.com/assets/1908863/14615159/fac0558e-0569-11e6-95d0-57bb0f99f276.png)

**Comment by Ahoge1993** [comment]
希望加入流程图和序列图的功能

**Comment by Ahoge1993** [comment]
公式部分希望能加入语法高亮

**Comment by shd101wyy** [comment]
Hi @Ahoge1993 , **flowchart and sequence diagram are now supported** now in version `0.5.8`. 

You can go check [mermaid](https://knsv.github.io/mermaid/#sequence-diagrams) for more information about how to write the graph.
To write flowchart & sequence diagram, simple add `mermaid` after <code> ``` </code>.
For example 

<pre> 
```mermaid

graph LR 
A --> B

```
</pre>

However it is still in beta so there might be some bugs.

One bug I found so far is https://github.com/shd101wyy/atom-markdown-katex/issues/22 , which reopened the issue https://github.com/shd101wyy/atom-markdown-katex/issues/7

Please report any further issues that you find.

Thx

**Comment by mistguy** [comment]
With so many new features added to this package, maybe this package need a new name.

**Comment by shd101wyy** [comment]
@mistguy  Hahaha, yea I agree. Do you have any suggestions?

**Comment by mistguy** [comment]
@shd101wyy markdown-preview-enhanced.

**New feature request**: some hooks to configure mathjax.

For example, auto-numbering can be added this way:
http://docs.mathjax.org/en/latest/tex.html#automatic-equation-numbering

**Comment by shd101wyy** [comment]
@mistguy Thanks for your advice. I will change the package name in next release.
Thank you very much for your supports all the time!

**Comment by JBird608** [comment]
Heya @shd101wyy.

Loving the work you have done with this so far, I would agree it is the best markdown editor for Atom. I have a couple of suggestions that I think would really be great additions to the package. 
 
1. A 'task list' feature. 
2. Code Syntax Highlighting. 

![screen shot 2016-05-14 at 9 15 04 pm](https://cloud.githubusercontent.com/assets/1952494/15270467/3f2eb580-1a19-11e6-99bd-25aaed0f387a.png)

**Comment by shd101wyy** [comment]
Hello @JBird608 , thanks for your reply!

I think the syntax highlighting should be supported by default.
What **Syntax Theme** are you using right now for **Atom Editor**? I think it might be a bug for this package. 

I just tried **Monokai** and **Github Syntax Style**, it has the following rendering results.
![screen shot 2016-05-14 at 11 23 35 pm](https://cloud.githubusercontent.com/assets/1908863/15272009/2118dde8-1a2b-11e6-9e0f-3856bcbe130a.png)
![screen shot 2016-05-14 at 11 24 00 pm](https://cloud.githubusercontent.com/assets/1908863/15272010/2305cc1a-1a2b-11e6-9ee0-8adcaa3e04e9.png)

----
As for the "task list" feature, I will try to support it in the next release. 
Do you need to save the state of task? So the next you open the same file the box will be checked? 

Thank you very much ;)

**Comment by cdarlint** [comment]
would you please add emoji support
like this: :+1:

**Comment by shd101wyy** [comment]
hi @cdarlint , I think emoji is supported by default.

![screen shot 2016-05-19 at 9 31 23 am](https://cloud.githubusercontent.com/assets/1908863/15379984/a457b720-1da4-11e6-8156-13a1e16299c2.png)

It works on Mac. What operating system are you using?

**Comment by cdarlint** [comment]
@shd101wyy 
I'm using Windows
I've found a atom plug-in that transform string literal `:+1:` into :+1: and supports auto-completion
so I suppose your emoji is transformed into emoji Unicode by Mac
Please test if it works on plain text input

Thanks

**Comment by shd101wyy** [comment]
@cdarlint 
I found that [autocomplete-emojis](https://atom.io/packages/autocomplete-emojis) is a very nice plugin for displaying emoji and it works for all different kinds of files. So I would like to recommend you to use this plugin.

**Comment by shd101wyy** [comment]
Hi all, **atom-markdown-preview** has been renamed to **markdown-preview-enhanced**.
Please remove the old package and download the new one [markdown-preview-enhanced](https://atom.io/packages/markdown-preview-enhanced)

**Comment by shd101wyy** [comment]
Hi @JBird608 , the task list is now supported.

**Comment by JBird608** [comment]
That's awesome. Thank you very much.

I'll get it downloaded right away.
:D

On Friday, 20 May 2016, Yiyi Wang <notifications@github.com> wrote:

> Hi @JBird608 <https://github.com/JBird608> , the task list is now
> supported.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/shd101wyy/markdown-preview-enhanced/issues/9#issuecomment-220500493>
>


-- 
Thank You,
Joe Curran.

Web Designer & Developer.
Twitter: @JBird608
LinkedIn: in/joecurrancodes
Web: http://joecurran.codes

**Comment by jakemkc** [comment]
I found markdown-preview-enhanced is more powerful than Markdown Preview from the default Atom installation. Really appreciate for your nice work.

However, is it possible:

1) to render a newly created file without being saved first?
2) to render a saved file not restricted to *.md but also others, such as *.txt?

These 2 can be done with the Markdown Preview package.

Jake

**Comment by mistguy** [comment]
Is it possible that preview pane will switch to corresponding document automatically when switching documents in editor pane?

Thanks!

**Comment by shd101wyy** [comment]
Hi @jakemkc , sorry for my late reply.

There are several reasons why the markdown file is required to be saved first:

1. PDF and HTML file generation requires the file path in order to be generated under the same directory.
2. image relative path requires file path.  
for example  
```markdown
![test](../images/test.png)
```
etc  

Sorry for the trouble

**Comment by shd101wyy** [comment]
Hello @mistguy , after version `0.6.6` this package will only open one preview window. So when you switch markdown files, the preview window will only render the content that you are editing.

**Comment by NeedsAdjustment** [comment]
Page numbers or a customizable header/footer for exported .pdf files would be *amazing*. https://github.com/cakebake/markdown-themeable-pdf does this, but it's not as cool.

**Comment by noullove** [comment]
including plantuml rendering feature.
https://atom.io/packages/plantuml-viewer

**Comment by shd101wyy** [comment]
HI @noullove , thanks for your reply

I have finished implementing the support for plantuml 
![plantuml](http://ooo.0o0.ooo/2016/06/27/5770dffca93c1.gif)  
However, I am planning to add more features to this package. It will take me a few days.
I will notice you once I publish the new version.

Thanks

**Comment by shd101wyy** [comment]
Hi @NeedsAdjustment , I will try to upload a new version that supports the feature you required by the end of this week.

**Comment by noullove** [comment]
Thank you. I will wait for the next release.

나의 iPhone에서 보냄

2016. 6. 27. 오후 5:10 Yiyi Wang <notifications@github.com> 작성:

**Comment by shd101wyy** [comment]
Hi @noullove , the new version `0.7.2` supports PlantUML now. ;)

**Comment by cha2maru** [comment]
If possible , I want to set the argument at the time of mermaid.initilize run .
I have been using to remodel as follows md.coffee.
md.coffee line 17

```
mermaidAPI.initialize({
    startOnLoad: false,
    gantt:{
        axisFormatter: [
            ["%m/%d", ((d) -> return d.getDay()==1)],
            ["%y-%m",((d) -> return d.getDay())]
        ]
    }
})
```

**Comment by avasseur-pivotal** [comment]
I cannot find .markdown-katex-preview-custom section in my style.less.

Nothing happens when I ctrl+shift+p so I am not sure what I need to do to "run Markdown Katex Preview: Customize Css"  that then will create .markdown-katex-preview-custom
Can you explain?

**Comment by shd101wyy** [comment]
Hi @avasseur-pivotal 
The README.md says
![Screen Shot 2016-07-01 at 6.36.55 PM](http://ooo.0o0.ooo/2016/07/01/577649da8faa5.png)

You need to run 
![Screen Shot 2016-07-01 at 6.37.37 PM](http://ooo.0o0.ooo/2016/07/01/577649e18fdd5.png)

Then edit 
![Screen Shot 2016-07-01 at 6.37.58 PM](http://ooo.0o0.ooo/2016/07/01/577649ec6d859.png)

hope this helps

**Comment by avasseur-pivotal** [comment]
Thanks - I was missing the action to open the Menu "Package / Command Palette / Toggle"

**Comment by SudoMike** [comment]
Thanks for this great plugin. I'm using Atom with this as a replacement for OneNote! I have a few requests that I think would make this plugin go from amazing to ludicrous:

**Preview pane cursor indicator**: I would love it if there were an option to have the preview pane indicate where my cursor is in the editor window. I can think of a few ways - show a cursor, highlight the word that the editor is on, or highlight (with a slight background color offset) the line that the editor is on.

**Sync editor position to preview window**: If I click in the Markdown preview window, move the cursor in the editor window to that location. Alternatively, have a right-click option that would do this. This would really help because I always want to read my notes in Markdown, but then it can take some time to figure out where exactly the right code is in the editor window.

**Highlight searches in the preview window**: When I search for things in the editor window, they're highlighted over there but not in the preview window. Since I want to orient most of my reading in the preview window, it'd be nice if it could show the search matches there as well as in the editor window.

**Comment by shd101wyy** [comment]
Hi @SudoMike ,

Thanks for your reply. Your idea looks very hard haha, I will try to implement them when I have time.

Cheers.

**Comment by shd101wyy** [comment]
**From now on, please post feature request in a new issue.** 

Thank you ;)

**Comment by shd101wyy** [comment]
Hi @cha2maru 

You can now edit config of mermaid by running **Markdown Preview Enhanced: Config Mermaid** command. It will open the `mermaid_config.js` file located at `~/.atom/markdown-preview-enhanced/` folder. You may need to restart atom after you make changes.

Thanks

**Comment by cha2maru** [comment]
Thank you very much.
But , unfortunately , I wish the results could not be obtained .
That mermaid_config.js to mermaid.initize on the source code has been loaded I was confirmed , but the settings were not reflected .
( There is a problem and is generating the object as Promise from a file ?
When you pass the same as purely object with the previous post was not a problem . )

Please tell me if there is a place which is wrong in the following description method .

```javascript
'use strict'
// config mermaid init call
// http://knsv.github.io/mermaid/#configuration
//
// you can edit the 'config' variable below
// everytime you changed this file, you may need to restart atom.

let config = {
  startOnLoad: false,
  gantt:{
        axisFormatter: [
            ["%m/%d", function (d) {
                return d.getDay() == 1;
            }],
            ["%y-%m",function (d) {
                return d.getMonth();
            }]
        ]
    }
}

module.exports = config || {startOnLoad: false}
```

**Comment by shd101wyy** [comment]
Hi @cha2maru , should be fixed now in version `0.7.6`. Thanks

**Comment by cha2maru** [comment]
@shd101wyy , Thanks. Version 0.7.6 was working perfectly .

**Comment by Cphoenix** [comment]
Multi-line maths with KaTeX? Forgive me if I'm just being obtuse and missing it if it's already there, but it would be nice to use them along with environment settings to do stuff like aligning multiple lines of equations.

**Comment by shd101wyy** [comment]
Hi @Cphoenix , thanks for your reply.

I think the multi-line maths that you mentioned should already be supported by default. 
You can post issues if you meet problem.

Thanks.

**Comment by shd101wyy** [comment]
I am closing this post (**New Features Request**) out.
If you are requesting new features, please make a new post in **Issues**.

Thanks ;)

**Comment by Cphoenix** [comment]
@shd101wyy     You're right. I'm new to using LaTeX for maths so I was overlooking the `aligned` and `&` combination required when using KaTeX to get what I want. :flushed:

**Comment by eddy-ojb** [comment]
Hello, is there a way to preview a pdf on here? e.g. say if one were to include page breaks in mark down? I'd like to be able to produce long html and pdf documents!

Ed
