### ISSUE TITLE
is it support check box?

### ISSUE THREAD

**Issue by yushukk** [shd101wyy/markdown-preview-enhanced#90]
[x] or [ ]

**Comment by shd101wyy** [comment]
Hi @yushukk 

Yes it is supported in task list.  
You can create task list like this in your markdown file.

```markdown
* [ ] todo 1
* [x] todo 2
``` 

You can also click at the checkbox in preview to toggle task.  

Thanks

**Comment by yushukk** [comment]
- [x]todo -------------- It's unwork
- [x] todo --------------it  works

**Comment by yushukk** [comment]
My fault

**Comment by shd101wyy** [comment]
You are missing spaces.

**Comment by shd101wyy** [comment]
I will close this issue ;)
