### ISSUE TITLE
Cannot combine Super/Subscript with bold, emphasis, highlight

### ISSUE THREAD

**Issue by houghtonap** [shd101wyy/markdown-preview-enhanced#912]
When using superscript or subscript you cannot combine it with bold, emphasis or highlight.

Example issues:

`code*^2^*`
`code**^2^**`
`code==^2^==`

Expected the superscript 2 to be in emphasis, bold or highlighted, but instead the actual characters *, **, == are rendered around the superscript 2.

Note changing the above issues to the following which include the word `code` do not produce this issue and appear to combine fine however, that's not a solution to the issue at hand since I only want to apply them to only the super/subscript part.

`*code^2^*`
`**code^2^**`
`==code^2^==`

**Comment by kachkaev** [comment]
@houghtonap I'm afraid markdown only sees tokens like `*`, `**` and `==` when they are at the end of a word rather than in the middle of it. This should work I guess: `code **^2^**`. What you can also try is `code<b><sup>2</sup></b>`.

**Comment by houghtonap** [comment]
I'm adding this further comment for reference. I understand the limitation of markdown rules, but I have found another possible workaround rather than dropping into HTML, as you suggested, which will trigger markdown lint rule `MD033`.

1. It might be helpful to mention the markdown behavior, of only recognizing those characters at the beginning and ending of words, in the [Markdown Basics](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics) section.
1. Your second workaround, to separate the word code from the superscript one, will cause a space to occur between the word code and the superscript which may not be ideal in a person's situation. I have found a workaround to avoid the extra space without dropping down into HTML. You can use the markdown `code&zwj;**^1^**`. The `&zwj;` is a zero-width joiner in Unicode. Perhaps this should also be documented in the [Markdown Basics](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics) section too, including the fact that you can enter HTML named entities, such as `&nbsp;`, or XML style entities, such as `&#160;`.
