### ISSUE TITLE
[bug]can not bold string when there is any punctuation inside string

### ISSUE THREAD

**Issue by findNextStep** [shd101wyy/markdown-preview-enhanced#914]
看起来我无法加粗带有标点符号的字符串，尤其是字符串之后带有其他字符的时候

包括中文和英文标点

一个可以复现的样例形如
```markdown
**大佬:**的
```
下面是这种bug的截图
![image](https://user-images.githubusercontent.com/26270464/41981718-2c86187e-7a5c-11e8-91dd-30c136f42c2b.png)
我认为这个bug的产生可能和解析有关
但是似乎直接单行加粗并不会有这个问题

**Comment by kachkaev** [comment]
Hi @findNextStep!

I guess your issue has been discussed recently in https://github.com/shd101wyy/markdown-preview-enhanced/issues/912

I’m closing this one as we’re facing markdown limitations here, which I’m afraid we cannot overcome.

Does this work for you?

```
<b>大佬:</b>的
```
