### ISSUE TITLE
Enhancement to support {as=} option on import of documents

### ISSUE THREAD

**Issue by houghtonap** [shd101wyy/markdown-preview-enhanced#916]
I'm using a third party program that is used to generate a document in markdown format, but unfortunately the program can only produce documents with a `.txt` extension. I cannot change the program. While I do realize that I could copy or rename the resulting document, it would be nice if MPE supported the `{as=}` option when importing documents that are in markdown, but do not have the `.md` extension. I would like to be able to say:

`@import "abc.txt" {code_block=false as="markdown"}`

currently when this is done, the text file is produced in a code block rather than importing the document as if it were markdown code with a `.md` extension. I should be able to specify any document extension and have it imported as actual markdown, as if I said:

`@import "abc.md"`

**Comment by shd101wyy** [comment]
This feature is supported now. Thanks.
