### ISSUE TITLE
首行缩进不可用。。。

### ISSUE THREAD

**Issue by BeliefanX** [shd101wyy/markdown-preview-enhanced#92]
无论我是用全角输入空格还是半角，或者用Tab键，再或者用&nbsp，都不能实现首行缩进。。。

**Comment by shd101wyy** [comment]
你好，

能不能给张截图？

谢谢

**Comment by shd101wyy** [comment]
一般对于 markdown 首行，空格 Tab 本来的设计就是无用的。关于 `&nbsp;` 我刚才试了下，可以正常显示空格。  
可能是你没有加 `;` 在最后？

**Comment by sunshe35** [comment]
你妹，Markdown语法首行缩进本来就是不能用的。这个是使用markdown的常识。

**Comment by shd101wyy** [comment]
Hello @BeliefanX , 这个问题我先关闭了～
有问题再问，谢谢。
