### ISSUE TITLE
Config Remarkable Typographer

### ISSUE THREAD

**Issue by cha2maru** [shd101wyy/markdown-preview-enhanced#94]
I want to change settings from the GUI "Remarkable" of "Typepographer".

If possible , is happy if I get a added to the configuration in the same way as breakOnSingleNewline.

**Comment by shd101wyy** [comment]
Hi @cha2maru ,

Is it okay if I only add the config in `Settings` but not in commands?  
![Screen Shot 2016-08-05 at 11.28.54 AM](http://ooo.0o0.ooo/2016/08/04/57a40947a4b7b.png)

**Comment by shd101wyy** [comment]
Done! Thanks

**Comment by cha2maru** [comment]
Thanks!
