### ISSUE TITLE
plantuml Class Diagram not showing in Markdown Preview Enhanced

### ISSUE THREAD

**Issue by louagej** [shd101wyy/markdown-preview-enhanced#942]
Plantuml describes different exmaples in http://plantuml.com/class-diagram for generating a class diagram.
But in the preview this is not visible:
![2018_08_08_ 001](https://user-images.githubusercontent.com/7229592/43834543-b9e5c5de-9b0e-11e8-946a-ac8ffcac593d.png)

**Comment by shd101wyy** [comment]
Hi @louagej , you need to install Graphviz yourself and add it to your system path.  

https://www.graphviz.org/
https://shd101wyy.github.io/markdown-preview-enhanced/#/diagrams?id=plantuml

**Comment by louagej** [comment]
Hi,
Issue solved... thanks
![2018_08_09_ 000](https://user-images.githubusercontent.com/7229592/43883525-af778e20-9bb3-11e8-8bd5-24e987cbc5d0.png)
