### ISSUE TITLE
graphviz mode cannot change node color.

### ISSUE THREAD

**Issue by maplewizard** [shd101wyy/markdown-preview-enhanced#95]
Cannot change node color. When I use 

``` viz
digraph G {
        node [style=filled, fillcolor=green];
        b0 -> b1 -> b2 -> b3;
}
```

this code can work in  http://mdaines.github.io/viz.js/
![image](https://cloud.githubusercontent.com/assets/1419566/17460424/9a99c98e-5c98-11e6-92c7-5081b4a1b075.png)
but when I use it in atom, I just get:
![image](https://cloud.githubusercontent.com/assets/1419566/17460426/b61d1382-5c98-11e6-8db6-6aed94331ffa.png)

**Comment by shd101wyy** [comment]
Will be fixed in next release.

Thanks

**Comment by shd101wyy** [comment]
Fixed now.
Thanks

**Comment by maplewizard** [comment]
Thanks, but a new problem occure.
The default is like this color:
![image](https://cloud.githubusercontent.com/assets/1419566/17663974/4886a0ae-6323-11e6-8ddf-949c38bdee06.png)

but I got:
![image](https://cloud.githubusercontent.com/assets/1419566/17663974/4886a0ae-6323-11e6-8ddf-949c38bdee06.png)
![image](https://cloud.githubusercontent.com/assets/1419566/17663990/65fb076a-6323-11e6-81ed-24f588eb0afe.png)

**Comment by shd101wyy** [comment]
Actually the one on the right side should be the default color. The one on the left side was polluted by mermaid.css.

**Comment by shd101wyy** [comment]
So this time it's correct.

**Comment by maplewizard** [comment]
I see, thanks

**Comment by shd101wyy** [comment]
closing this issue out
