### ISSUE TITLE
State Diagram will not render.

### ISSUE THREAD

**Issue by cbuteau** [shd101wyy/markdown-preview-enhanced#957]
Hello,

I love plantuml and I love your atom plugin

However I am trying to draw a state engine and it is NOT working.

I am using a basic sample.

```plantuml
@startuml

[*] --> State1
State1 --> [*]
State1 : this is a string
State1 : this is another string

State1 -> State2
State2 --> [*]

@enduml
```

and what I see is the following.

Dot Executable: null
No dot executable found
Cannot find Graphviz. You should try
@startuml
testdot
@enduml
or
java -jar plantuml.jar -testdot

Please help.

**Comment by shd101wyy** [comment]
Check this: https://github.com/shd101wyy/markdown-preview-enhanced/issues/942

**Comment by cbuteau** [comment]
Ahhh Graphviz should maube be part of the postinstall?
