### ISSUE TITLE
无法正确渲染 KaTeX

### ISSUE THREAD

**Issue by liushilive** [shd101wyy/markdown-preview-enhanced#967]
公式：
```
\def\arraystretch{1.5}
   \begin{array}{c:c:c}
   a & b & c \\ \hline
   d & e & f \\
   \hdashline
   g & h & i
\end{array}
```

![image](https://user-images.githubusercontent.com/13434707/45472184-06986d00-b766-11e8-960f-2f72819fa578.png)

![image](https://user-images.githubusercontent.com/13434707/45472231-29c31c80-b766-11e8-96a3-4fc100f796e1.png)

**Comment by SanGoah** [comment]
在公式块中使用\\换行我这边也会提示“ParseError: KaTeX parse error: Expected 'EOF', got '\\' at position 40: …,B_{y-1})+\{t\}\̲\̲ Length(A_x,B_…”……

**Comment by shd101wyy** [comment]
Hi, @liushilive @SanGoah 现在应该好了。我刚刚更新了依赖。
谢谢
