### ISSUE TITLE
\oiint & \oiiint doesn't work

### ISSUE THREAD

**Issue by chiarld** [shd101wyy/markdown-preview-enhanced#969]
According to [KaTex documentation](https://katex.org/docs/supported.html), \oiint and \oiiint is supported but it doesn't seem to work for me.

Any ideas how I can fix this?

**Comment by shd101wyy** [comment]
The KaTeX that mpe is using is out of date. I am planning to update it this weekend. Thanks

**Comment by chiarld** [comment]
Awesome! Thanks a lot!

You might want to check out errors that show in the editor but render just fine in the preview too.

For example:

$$
\bigg |_{(2, -1, 0)}
$$

For context, this was an attempt to make an "evaluated at" sign. In the editor, it shows up as an error making that text (\bigg |_{(2, -1, 0)}) and the entire text after (until the next header) red. However, it renders just fine.

I'm just reporting this because having the entire text red colored is kind of annoying.

Btw, congrats on Markdown-Preview-Enhanced. I've used countless markdown preview editors and yours is **by far** the best.

**Comment by chiarld** [comment]
Hey @shd101wyy ! Thanks a lot for updating mpe's KaTex! Just tested for  `\oiint` and it works now!

Closing the issue (:
