### ISSUE TITLE
ERD help!

### ISSUE THREAD

**Issue by chiarld** [shd101wyy/markdown-preview-enhanced#977]
Oops! By mistake, I submitted this issue with an empty a description. Sorry about that!

In any case, I am posting this issue because no matter what I do I keep on getting 

`Error: spawn erd ENOENT`

To get it installed on my computer I've tried several things:

- Started reading your issue with baronTommy @ https://github.com/shd101wyy/markdown-preview-enhanced/issues/128.
- Tried doing `cabal install erd` and it failed (got the same error you did at the time).
- Tried cloning from the git repo like baronTommy recommended then configure and build cabal but that fails with no error message.
- Tried doing `cabal install --allow-newer erb` which I saw @ https://github.com/BurntSushi/erd/issues/24#issuecomment-314775206 which seems to work but I still can't use `erd` from Terminal.

Nothing has worked. I installed Haskell through the Haskell site and through brew. I installed cabal through brew as well. I have installed graphviz. Ghc looks fine too. 

I have really no idea what to try next.

I know this isn't much of an issue from Markdown Preview Enhanced but my ultimate goal is to use it in your software so I would really appreciate some help!

Thanks in advance!

**Comment by chiarld** [comment]
If there is no way to fix this, is there any way I can use a beta version of PlantUML with MPE? I know you use `node-plantuml` so I see this could be a problem.

**Comment by shd101wyy** [comment]
I assume you are using atom editor.
You can just copy the `plantuml.jar` file that you download from [plantuml](http://plantuml.com/download) website to 

```
~/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/dependencies/plantuml/plantuml.jar
```
. 

As for the `erd`, I would assume you didn't add `erd` command to your system path?
You should be able to invoke `erd` command directly from terminal.

```
$ erd --help
Usage: erd [flags]
  -i FILE  --input=FILE   When set, input will be read from the given file.
                          Otherwise, stdin will be used.
  -o FILE  --output=FILE  When set, output will be written to the given file.
                          Otherwise, stdout will be used.
                          If given and if --fmt is omitted, then the format will be
                          guessed from the file extension.
  -h       --help         Show this usage message.
  -f FMT   --fmt=FMT      Force the output format to one of:
                          bmp, dot, eps, gif, jpg, pdf, plain, png, ps, ps2, svg, tiff
```

Thank you

**Comment by chiarld** [comment]
Adding `plantuml.jar` to `~/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/dependencies/plantuml/plantuml.jar` worked perfectly. Thanks a lot!

About adding the edr to the system path, I did:

`sudo nano /etc/paths`

Then I tried adding both 
1. My erd installation from cloning the git repo as:
`/Users/chiarld/erd/dist/build/erd/erd`
2. My erd installation from `cabal install --allow-newer erd` as:
`/Users/chiarld/Library/Haskell/bin/erd`

None of them worked. Am I still doing something wrong?

**Comment by shd101wyy** [comment]
It seems that to me you need to add `Directory path` to `/etc/paths`, not `File path`,
So add `/Users/chiarld/Library/Haskell/bin/` to `/etc/paths`, then **restart** terminal to make sure `erd` exists in your path, then **restart** atom.

**Comment by chiarld** [comment]
That worked perfectly. Thanks a lot for helping out!

I hope one day I can repay you by doing some work for MPE. I really admire you and your software so keep it up! 😄
