### ISSUE TITLE
I'm curious!

### ISSUE THREAD

**Issue by chiarld** [shd101wyy/markdown-preview-enhanced#979]
Hey shd101wyy!

It's me again!

I was just wondering, how did you make your markdown preview look like:

![image](https://user-images.githubusercontent.com/39843321/46549837-27953f00-c888-11e8-91ae-f0492598ba1b.png)

It looks awesome and I would really enjoy something similar. 

Also, when you export to pdf will it maintain the style? 

Cheers!

(Ps. If you could also let me know what style UI you are using in this pic, that would be awesome too xD)

(Ps2. If there's anywhere else where you would prefer me to post these kind of questions, just let me know. I'm not too sure if you mind these not being really issues)

**Comment by shd101wyy** [comment]
I think that is a preview theme called `newsprint` which could be set from the package settings.

> Also, when you export to pdf will it maintain the style?

There is also an option called `Markdown-preview-enhanced: Print Background`. Enabling it will maintain the style when export to pdf.

**Comment by chiarld** [comment]
Ooh, I never looked that much into the themes offered inside of the package. Thanks a lot!

Also, what is the theme that you are using for your editor on the left side? I can't find any theme that recognizes KaTeX components inside $$...$$ and colors them.

Thanks in advance!

**Comment by shd101wyy** [comment]
* Theme: [atom material syntax](https://atom.io/themes/atom-material-syntax)
* Pakcage: [language markdown](https://atom.io/packages/language-markdown)

**Comment by chiarld** [comment]
So, it actually didn't work for me with language markdown but I downloaded your package for highlighting math and code chunks and it worked like a charm! Thanks!

**Comment by RobertAguilera712** [comment]
>     * Theme: [atom material syntax](https://atom.io/themes/atom-material-syntax)
> 
>     * Pakcage: [language markdown](https://atom.io/packages/language-markdown)

I installed the theme and the package, but I don't get the syntax highlighting for math equations
