### ISSUE TITLE
Feature Request: Github flavour markdown  support emoji

### ISSUE THREAD

**Issue by maplewizard** [shd101wyy/markdown-preview-enhanced#98]
Hi, I found that emoji didn't work. Could you please add this feature?

**Comment by shd101wyy** [comment]
I recommend you to try this plugin: [autocomplete-emojis](https://atom.io/packages/autocomplete-emojis)

Thanks

**Comment by maplewizard** [comment]
@shd101wyy is it difficult to render like github?

**Comment by shd101wyy** [comment]
what do you mean render like github? can you give me snippet or screenshot?

**Comment by maplewizard** [comment]
When I write `:smile:` in atom, and use markdown-preview-enhanced, it looks like didn't work:
![image](https://cloud.githubusercontent.com/assets/1419566/17541377/668f1594-5ef1-11e6-98e3-05e955226aba.png)
But on git hub if I write `:smile:`, it will show :smile:

**Comment by shd101wyy** [comment]
Please try [atomcomplete-emojis](https://atom.io/packages/autocomplete-emojis) plugin.

**Comment by shd101wyy** [comment]
I will there is no need to write something like `:smile:` since you can type emojis directly. 
Also github markdown behaves similarly like the [atomcomplete-emojis](https://atom.io/packages/autocomplete-emojis) plugin.

**Comment by shd101wyy** [comment]
@maplewizard Both emoji and font-awesome are supported now.  

You can disable it from the package settings.   
![screen shot 2017-09-30 at 9 32 11 pm](https://user-images.githubusercontent.com/1908863/31051176-d87e648e-a626-11e7-8e50-694bee25ff70.png)

Cheers :)
