### ISSUE TITLE
Exporting to PDF glitches

### ISSUE THREAD

**Issue by danbugs** [shd101wyy/markdown-preview-enhanced#980]
Hey! 

It's me again! :D

So, I have a couple of glitches to report regarding exporting markdown to pdf. 

1. Using Chrome (Puppeteer) I get an error saying:
```
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
```

2. Phantom JS, code chunks that are a bit long will get cut off with an illusion that they were, like:

<img width="419" alt="screen shot 2018-10-05 at 3 16 59 pm" src="https://user-images.githubusercontent.com/39843321/46562627-dac65e00-c8b1-11e8-9aae-9adc6ef1cc69.png">

☝️ Notice that there is a scroll to slide sideways and see the full code but it doesn't work.

Changing the style of the code chunk to something like coy.css changes the way Phantom JS handles it but, nonetheless, the code gets cut off.

<img width="426" alt="screen shot 2018-10-05 at 3 19 33 pm" src="https://user-images.githubusercontent.com/39843321/46562687-2ed14280-c8b2-11e8-80cb-e3d3a245ca4e.png">

3. PDF (prince) seems to not be able to handle some math stuff such as $\frac$ and we get:

<img width="364" alt="screen shot 2018-10-05 at 3 13 53 pm" src="https://user-images.githubusercontent.com/39843321/46562713-604a0e00-c8b2-11e8-8bd1-561ff6c8a1c5.png">

4. eBook PDF does the same thing as prince but for square roots:

<img width="403" alt="screen shot 2018-10-05 at 3 23 52 pm" src="https://user-images.githubusercontent.com/39843321/46562806-c33ba500-c8b2-11e8-94ad-5f13743ab555.png">

5. Pandoc is by far the best solution but I don't really like how it shows the alt text for my images such as:

<img width="361" alt="screen shot 2018-10-05 at 3 26 48 pm" src="https://user-images.githubusercontent.com/39843321/46562867-26c5d280-c8b3-11e8-9c5b-bf54a5424a13.png">

I use your software to take live notes during class at my university and I don't really have time to rename every single image alt. All I do is just drag and drop during class.

In any case, I love MPE and I thought that maybe I could contribute a tiny bit by showing you what I've noticed so far with PDF exports.

Hope I've been helpful!

**Comment by chiarld** [comment]
Actually, I just noticed a glitch from Pandoc that probably makes PhantomJS be better than it. 

I wrote some KaTeX code(?) that was supposed to look like: 

<img width="416" alt="screen shot 2018-10-05 at 3 37 08 pm" src="https://user-images.githubusercontent.com/39843321/46563129-a1432200-c8b4-11e8-8b86-5762104a37e6.png">

Pandoc makes it like:

<img width="275" alt="screen shot 2018-10-05 at 3 37 59 pm" src="https://user-images.githubusercontent.com/39843321/46563136-aa33f380-c8b4-11e8-8daa-c461f866a6e7.png">

Go PhantomJS! 😆

**Comment by chiarld** [comment]
Just checked, PhatomJS code doesn't get cut off with two css themes:

1. hopscoth
2. pojoaque

It looks like this:

<img width="678" alt="screen shot 2018-10-05 at 3 45 54 pm" src="https://user-images.githubusercontent.com/39843321/46563369-dc922080-c8b5-11e8-9cfc-a12c63d1b7d3.png">

**Comment by chiarld** [comment]
Also, I should add that hopscotch and pojoaque work like I mentioned above only with certain combinations of preview themes. 

I am currently using vue.js and hopscotch and exporting with PhantomJS works perfectly.
