### ISSUE TITLE
mermaid styles out of date

### ISSUE THREAD

**Issue by alechp** [shd101wyy/markdown-preview-enhanced#983]
![image](https://user-images.githubusercontent.com/3058939/46624402-84d9fc00-cae5-11e8-9d35-484bdefbd4fb.png)

**Comment by shd101wyy** [comment]
Go to your package settings, change the mermaid.theme to default.

**Comment by alechp** [comment]
That fixed it. Thank you @shd101wyy !


---

Nuance in case anyone else runs into this:

The theme was already set to default. However, when I clicked the theme dropdown and clicked default again, it fixed it. Afterwards, I wasn't able to go back to the black boxes (even with "dark" theme). 


These are all three options:

<img width="1792" alt="screen shot 2018-10-08 at 3 08 38 pm" src="https://user-images.githubusercontent.com/3058939/46636224-23795380-cb0c-11e8-85a8-57c319949bb8.png">
<img width="1792" alt="screen shot 2018-10-08 at 3 08 34 pm" src="https://user-images.githubusercontent.com/3058939/46636225-2411ea00-cb0c-11e8-959b-4a9fc56c20b9.png">
<img width="1792" alt="screen shot 2018-10-08 at 3 08 31 pm" src="https://user-images.githubusercontent.com/3058939/46636226-2411ea00-cb0c-11e8-92e3-19bf769c0424.png">
