### ISSUE TITLE
gantt  has a bad style

### ISSUE THREAD

**Issue by siriuscc** [shd101wyy/markdown-preview-enhanced#985]
I write code as ： 

(3`)mermaid

gantt

	dateFormat  YYYY-MM-DD
	title gantt diagram mermaid

	section A section
	Completed task            :done,    des1, 2014-01-06,2014-01-08
	Active task               :active,  des2, 2014-01-09, 3d
	Future task               :         des3, after des2, 5d
	Future task2              :         des4, after des3, 5d

	section Critical tasks
	Completed task in the critical line :crit, done, 2014-01-06,24h
	Implement parser and jison          :crit, done, after des1, 2d
	Create tests for parser             :crit, active, 3d
	Future task in critical line        :crit, 5d
	Create tests for renderer           :2d
	Add to mermaid                      :1d

	section Documentation
	Describe gantt syntax               :active, a1, after des1, 3d
	Add gantt diagram to demo page      :after a1  , 20h
	Add another diagram to demo page    :doc1, after a1  , 48h

	section Last section
	Describe gantt syntax               :after doc1, 3d
	Add gantt diagram to demo page      : 20h
	Add another diagram to demo page    : 48h

and then  preview：
![image](https://user-images.githubusercontent.com/16629888/46805999-04432600-cd99-11e8-81b8-0a024f94e7c7.png)

open in chrome, and select it :
![image](https://user-images.githubusercontent.com/16629888/46806038-22108b00-cd99-11e8-8287-dfaebc6d68e1.png)

How can I do?

**Comment by shd101wyy** [comment]
go to extension settings, then reset memaid.theme to default.
