### ISSUE TITLE
open in browser 失效了,  1.28版本

### ISSUE THREAD

**Issue by V0idk** [shd101wyy/markdown-preview-enhanced#989]
os: Ubuntu

**Comment by shd101wyy** [comment]
我刚试了下没问题呀，我用的是 vscode Version 1.28.1 (1.28.1)。
你重启下试试，或者我猜你打开的 preview 是错的？来张截图？

**Comment by V0idk** [comment]
@shd101wyy 
![peek 2018-10-16 01-17](https://user-images.githubusercontent.com/17514799/46966809-565db180-d0e1-11e8-997c-3d3bd6fdee42.gif)

**Comment by shd101wyy** [comment]
你试试小一点的文档会不会也有同样的问题？

**Comment by V0idk** [comment]
> 你试试小一点的文档会不会也有同样的问题？

一样打不开

**Comment by shd101wyy** [comment]
打开 vscode 的 javascript (developer) console 看看有没有报错的提示？

**Comment by samgang** [comment]
可以打开，但默认是IE，设置的默认浏览器没起作用

**Comment by V0idk** [comment]
@shd101wyy 没有错误, 我测试了一下. 最后可以打开的版本是code_1.27.2-1536736588_amd64.deb.

**Comment by V0idk** [comment]
@samgang 我用的chrome. 以前可以打开的
