### ISSUE TITLE
Support for mermaid Gantt diagrams

### ISSUE THREAD

**Issue by fieloss** [shd101wyy/markdown-preview-enhanced#99]
There is no support for this feature. I believe it's a very useful visualization and it would be nice to include it.
Here you can see [an example](https://github.com/knsv/mermaid/blob/master/test/gantt.html) or here on the [docs page](https://knsv.github.io/mermaid/).

**Comment by shd101wyy** [comment]
Hi @fieloss ,

I think Gantt diagram is supported by default. 
Can I see your code snippet? 

Thanks

**Comment by fieloss** [comment]
Wow, my fault sorry. I miss the gantt instruction:
```
# ```mermaid
# **gantt**
# ...
```
This is an amazing package

😄
