### ISSUE TITLE
Could you please update pandoc? 

### ISSUE THREAD

**Issue by chiarld** [shd101wyy/markdown-preview-enhanced#994]
Hey! 

I have been running into some issues where pandoc doesn't recognize $\Tau$, while weirdly working fine for $\tau$. 

Looking online, it seems like pandoc might need an update (as suggested here: https://github.com/jgm/pandoc/issues/2651). Would you mind checking it out?

Thanks!

**Comment by undergroundquizscene** [comment]
I could be wrong about this, but I believe $\Tau$ is incorrect TeX, as described in [this stackexchange answer](https://tex.stackexchange.com/a/111549) and in [The Not So Short Introduction to LaTeX](https://archive.org/details/lshort/page/n69), which it cites (p. 56, footnote 5):

> There is no uppercase Alpha, Beta etc. defined in LATEX2e because it looks the same as a normal roman A, B...

**Comment by chiarld** [comment]
Hey @undergroundquizscene , 

Thanks for your response. I ended up just using a normal T for that document 'cause, as you quoted, it looked similar enough to an uppercase tau.

I was looking for something similar to:

 ![uppercase tau](https://upload.wikimedia.org/wikipedia/commons/8/82/Greek_uc_tau.svg) 

where, as you can see, it has a stylized serif unlike the default sans-serif one:

![normal T](http://s3.amazonaws.com/static.graphemica.com/glyphs/i500s/000/002/000/original/0054-500x500.png?1275291786)

I'll close this issue now. Kinda forgot it was still here 😆

**Comment by undergroundquizscene** [comment]
Ah yeah, I get that! To be honest, I was quite surprised there wasn’t an uppercase tau, but I figured it’d be worth pointing out :)
