### ISSUE TITLE
PDF Export Specifications ⁉️

### ISSUE THREAD

**Issue by danbugs** [shd101wyy/markdown-preview-enhanced#997]
Hey!

So, is there a way to specify page breaks for when we PDF export? That is, specify that we want specific content on a page and other content on another page? 

That is, supposed I wanted to make a cover page. Is it possible?

Thanks in advance!

**Comment by shd101wyy** [comment]
Yes there is:

```
# Page1
this is page 1

<!-- pagebreak -->

# Page2
this is page 2
```

You just need to insert `<!-- pagebreak -->` comment to your markdown file.

I recommend to use puppeteer to export PDF.

Thank you.

**Comment by chiarld** [comment]
Hey @shd101wyy !

Thanks for the quick reply! I actually have never managed to properly setup puppeteer. It is the only one I couldn't get to work at all. 

I get:

`
Error: Puppeteer (Headless Chrome) is required to be installed globally. Please run npm install -g puppeteer in your terminal.
`

and I've installed puppeteer before. Any ideas how I could fix this?

**Comment by shd101wyy** [comment]
Hmmm I am not sure, which OS are you using?
After running `npm install -g puppeteer` you probably need to restart your editor.

**Comment by chiarld** [comment]
I am using MacOS Mojave.

After running `npm install -g puppeteer` I get:

`
> puppeteer@1.9.0 install /usr/local/lib/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r594312! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/puppeteer/.local-chromium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.9.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

I have tried installing it without Chromium but then I MPE gives me the `npm install -g puppeteer` error message again.

**Comment by shd101wyy** [comment]
Try `sudo npm install -g puppeteer`?

**Comment by chiarld** [comment]
That's what I used. Sorry, should have specified.

**Comment by chiarld** [comment]
Btw, is there no way to underline something in MPE?

**Comment by chiarld** [comment]
Managed to install puppeteer with `sudo npm install -g puppeteer --unsafe-perm=true`.
