### ISSUE TITLE
Unable to open 'MPE Preview': Cannot read property 'filter' of undefined.

### ISSUE THREAD

**Issue by lzlzlizi** [shd101wyy/markdown-preview-enhanced#999]
when I try to open preview, "Unable to open 'MPE Preview': Cannot read property 'filter' of undefined." shows up and failed to open it.

**Comment by shd101wyy** [comment]
Yeah it's a bug. I assumed the file you opened is not under the folder in workspace. You could click `Open Folder In Workspace` then open the folder that the files locates.

I will fix it tomorrow.

**Comment by shd101wyy** [comment]
Sorry, and thanks.

**Comment by lzlzlizi** [comment]
> Yeah it's a bug. I assumed the file you opened is not under the folder in workspace. You could click `Open Folder In Workspace` then open the folder that the files locates.
> 
> I will fix it tomorrow.

Thanks for your replay, it works now as i following your suggestion. Thanks a lot for this amazing tool, it really helps.

**Comment by shd101wyy** [comment]
The bug should be fixed now. Thanks.
